<?php
require __DIR__ . '/../backend/lib/bootstrap.php';
$me = require_login();

/* 🔒 Same practice gate as the Labs index — direct-URL users get the wall, too. */
$gateSolved = cf_solved_problems_count((int)$me['id']);
if ($gateSolved < cf_practice_gate()) {
    http_response_code(403);
    $page_title = 'Pro Labs';
    $active = 'labs';
    require __DIR__ . '/../backend/partials/head.php';
    require __DIR__ . '/../backend/partials/header.php';
    $gateIcon = '🧪'; $gateSection = 'Pro Labs';
    $gateTag = 'multi-file legacy codebases with planted bugs and published (readonly) APIs';
    $gateBackHref = 'labs.php'; $gateBackLabel = 'Pro Labs';
    require __DIR__ . '/../backend/partials/practice-gate.php';
    require __DIR__ . '/../backend/partials/footer.php';
    exit;
}

$slug = (string)($_GET['slug'] ?? '');
$lab = cf_get_lab($slug);
if (!$lab) {
    /* AI-built lab? Regenerate deterministically — private to its owner, and
     * only while that batch is unlocked (no guessing ahead to future sets). */
    if (preg_match('/^ail(\d+)b(\d+)-/', $slug, $m) && (int)$m[1] === (int)$me['id']) {
        [$maxB] = cf_ai_labs_unlock(db(), (int)$me['id']);
        if ((int)$m[2] <= $maxB) $lab = cf_ai_lab((int)$me['id'], $slug);
    }
}
if (!$lab) { http_response_code(404); require __DIR__ . '/../backend/partials/404.php'; exit; }
$isAiLab = (bool)preg_match('/^ail\d+b\d+-/', $lab['slug']);

$done = (bool)db_one('SELECT lab_slug FROM lab_progress WHERE user_id = ? AND lab_slug = ?', [(int)$me['id'], $lab['slug']]);

$page_title = $lab['title'];
$active = 'labs';
$page_scripts = ['assets/js/editor.js', 'assets/js/runner.js', 'assets/js/multiedit.js', 'assets/js/metrics.js', 'assets/js/reviewer.js', 'assets/js/lab.js'];

$payload = [
    'slug'  => $lab['slug'],
    'kind'  => $lab['kind'],
    'files' => array_map(function ($f) { return ['name' => $f['name'], 'readonly' => !empty($f['readonly']), 'content' => $f['content']]; }, $lab['files']),
    'tasks' => array_map(function ($t) { return ['text' => $t['text'], 'check' => $t['check']]; }, $lab['tasks']),
    'csrf'  => csrf_token(),
    'done'  => $done,
];

require __DIR__ . '/../backend/partials/head.php';
require __DIR__ . '/../backend/partials/header.php';
?>
<script id="labData" type="application/json"><?= json_encode($payload, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_UNESCAPED_SLASHES) ?></script>

<div class="container wide">
  <nav class="crumbs"><a href="labs.php">← Pro Labs</a></nav>

  <div class="split">
    <section class="pane pane-left">
      <div class="pane-scroll problem-desc">
        <div class="problem-title-row">
          <h1><?= e($lab['title']) ?></h1>
          <span class="solved-check" id="labStatus" <?= $done ? '' : 'hidden' ?>>✓ complete</span>
        </div>
        <div class="problem-meta-row">
          <span class="lab-kind lab-kind-<?= e($lab['kind']) ?>"><?= $lab['kind'] === 'debug' ? '🐞 legacy debug' : '🔌 API integration' ?></span>
          <span class="badge <?= difficulty_badge_class($lab['difficulty']) ?>"><?= e($lab['difficulty']) ?></span>
          <span class="muted">~<?= (int)$lab['minutes'] ?> min</span>
        </div>
        <div class="desc-body"><?= allow_html($lab['brief']) ?></div>

        <?php if ($isAiLab): ?>
        <div class="ai-hero"><span>🤖</span> This environment was generated by the Codeface AI for you — finish the whole set to unlock the next 10.</div>
        <?php endif; ?>

        <h4 class="tests-preview-title">Task checklist</h4>
        <ul class="task-list" id="labTasks"></ul>

        <div class="note-box">
          <strong>How it runs:</strong> every file executes in an isolated Web Worker in your browser —
          nothing runs on the server. Files load in tab order; readonly files simulate a vendor/published API you cannot change.
        </div>
      </div>
    </section>

    <section class="pane pane-right">
      <div class="editor-toolbar">
        <span class="toolbar-note">multi-file project · JavaScript</span>
        <span class="spacer"></span>
        <button class="btn btn-ghost btn-sm" id="btnLabReview" type="button">👨‍💻 Senior review</button>
        <button class="btn btn-ghost btn-sm" id="btnLabReset" type="button">Reset all</button>
        <button class="btn btn-primary btn-sm" id="btnLabRun" type="button">▶ Run checks</button>
      </div>
      <div id="editorHost" class="multi-editor"></div>
      <div class="results-panel">
        <div class="results-summary" id="labSummary">Run the checks to test the codebase.</div>
        <pre class="console-out" id="labConsole"></pre>
      </div>
      <div class="card review-panel" id="reviewPanel" hidden></div>
    </section>
  </div>
</div>
<?php require __DIR__ . '/../backend/partials/footer.php'; ?>
