<?php
require __DIR__ . '/../backend/lib/bootstrap.php';
$me = require_login();

/* 🔒 Same practice gate as the Gym index — direct-URL users get the wall, too. */
$gateSolved = cf_solved_problems_count((int)$me['id']);
if ($gateSolved < cf_practice_gate()) {
    http_response_code(403);
    $page_title = 'Refactor Gym';
    $active = 'refactor';
    require __DIR__ . '/../backend/partials/head.php';
    require __DIR__ . '/../backend/partials/header.php';
    $gateIcon = '🧹'; $gateSection = 'Refactor Gym';
    $gateTag = 'working-but-messy repos you must clean up without breaking behavior';
    $gateBackHref = 'refactor.php'; $gateBackLabel = 'Refactor Gym';
    require __DIR__ . '/../backend/partials/practice-gate.php';
    require __DIR__ . '/../backend/partials/footer.php';
    exit;
}

$slug = (string)($_GET['slug'] ?? '');
$chal = cf_get_refactor($slug);
$isAiChal = false;
if (!$chal) {
    /* AI-generated repo: private to its owner + gated to unlocked batches. */
    if (preg_match('/^air(\d+)b(\d+)-/', $slug, $m) && (int)$m[1] === (int)$me['id']) {
        [$maxB] = cf_ai_refactor_unlock(db(), (int)$me['id']);
        if ((int)$m[2] <= $maxB) {
            $chal = cf_ai_refactor((int)$me['id'], $slug);
            $isAiChal = (bool)$chal;
        }
    }
}
if (!$chal) { http_response_code(404); require __DIR__ . '/../backend/partials/404.php'; exit; }

$bestRow = db_one('SELECT MAX(score) AS b FROM refactor_runs WHERE user_id = ? AND challenge_slug = ?', [(int)$me['id'], $chal['slug']]);
$best = $bestRow && $bestRow['b'] !== null ? (int)$bestRow['b'] : null;

$page_title = $chal['title'] . ' — Refactor Gym';
$active = 'refactor';
$page_scripts = ['assets/js/editor.js', 'assets/js/runner.js', 'assets/js/multiedit.js', 'assets/js/metrics.js', 'assets/js/reviewer.js', 'assets/js/refactor.js'];

$payload = [
    'slug'   => $chal['slug'],
    'files'  => array_map(function ($f) { return ['name' => $f['name'], 'content' => $f['content']]; }, $chal['files']),
    'checks' => array_map(function ($c) { return ['text' => $c['text'], 'check' => $c['check']]; }, $chal['checks']),
    'base'   => $chal['base'],
    'csrf'   => csrf_token(),
];

require __DIR__ . '/../backend/partials/head.php';
require __DIR__ . '/../backend/partials/header.php';
?>
<script id="refactorData" type="application/json"><?= json_encode($payload, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_UNESCAPED_SLASHES) ?></script>

<div class="container wide">
  <nav class="crumbs"><a href="refactor.php">← Refactor Gym</a></nav>

  <div class="split">
    <section class="pane pane-left">
      <div class="pane-scroll problem-desc">
        <h1><?= e($chal['title']) ?></h1>
        <div class="problem-meta-row">
          <span class="lab-kind lab-kind-refactor">🧹 refactor</span>
          <span class="muted" id="rfBest"><?= $best !== null ? 'Best score: ' . $best . '/100' : 'Not attempted yet' ?></span>
        </div>
        <div class="desc-body">
          <p><?= e($chal['summary']) ?></p>
          <p><strong>Senior's brief:</strong> <?= e($chal['goal']) ?></p>
        </div>
        <?php if ($isAiChal): ?>
        <div class="ai-hero"><span>🤖</span> This messy repo was generated by the Codeface AI for you — get all 10 in the set green to unlock the next batch.</div>
        <?php endif; ?>

        <h4 class="tests-preview-title">Safety tests (must stay green)</h4>
        <ul class="task-list" id="rfChecks"></ul>

        <h4 class="tests-preview-title">Baseline vs your metrics</h4>
        <div id="rfMetrics"></div>

        <div class="note-box">
          <strong>Scoring:</strong> all tests passing = 55 pts minimum credit; up to +45 for cutting complexity and
          duplication vs the baseline. Behavior changes = fail. Run a <em>Senior review</em> for narrative feedback.
        </div>
      </div>
    </section>

    <section class="pane pane-right">
      <div class="editor-toolbar">
        <span class="toolbar-note">messy repo · JavaScript · behavior must not change</span>
        <span class="spacer"></span>
        <button class="btn btn-ghost btn-sm" id="btnRfReview" type="button">👨‍💻 Senior review</button>
        <button class="btn btn-ghost btn-sm" id="btnRfReset" type="button">Reset repo</button>
        <button class="btn btn-outline btn-sm" id="btnRfRun" type="button">▶ Run safety tests</button>
        <button class="btn btn-primary btn-sm" id="btnRfSubmit" type="button" disabled>Submit score</button>
      </div>
      <div id="editorHost" class="multi-editor"></div>
      <div class="results-panel">
        <div class="results-summary" id="rfSummary"></div>
        <pre class="console-out" id="rfConsole"></pre>
      </div>
      <div class="card review-panel" id="reviewPanel" hidden></div>
    </section>
  </div>
</div>
<?php require __DIR__ . '/../backend/partials/footer.php'; ?>
