<?php
// Category: arrays — scanning, transforming, in-place tricks
// Helpers t()/sig()/pdef() live in lib/emitters.php + lib/content_seed.php
return [
pdef('fizzbuzz', 'FizzBuzz', 'easy', 'fizzBuzz',
    sig(['n' => 'int'], 'str[]'),
    'Return a list of strings for numbers 1 to n: multiples of 3 become "Fizz", multiples of 5 become "Buzz", multiples of both become "FizzBuzz", everything else stays as the number in string form.',
    ['1 ≤ n ≤ 10⁴'],
    [t([3], ['1', '2', 'Fizz'], 1), t([5], ['1', '2', 'Fizz', '4', 'Buzz'], 1),
     t([15], ['1','2','Fizz','4','Buzz','Fizz','7','8','Fizz','Buzz','11','Fizz','13','14','FizzBuzz']), t([1], ['1'])],
    'function fizzBuzz(n){var o=[];for(var i=1;i<=n;i++){o.push(i%15===0?"FizzBuzz":i%3===0?"Fizz":i%5===0?"Buzz":String(i));}return o;}'),

pdef('array-range', 'Array Range', 'easy', 'arrayRange',
    sig(['nums' => 'int[]'], 'int'),
    'Return the difference between the largest and the smallest value in the array.',
    ['1 ≤ nums.length ≤ 10⁵', '-10⁹ ≤ nums[i] ≤ 10⁹'],
    [t([[3, 1, 9]], 8, 1), t([[5]], 0, 1), t([[-4, -1, -9]], 8), t([[7, 7, 7]], 0)],
    'function arrayRange(nums){var mn=nums[0],mx=nums[0];for(var i=1;i<nums.length;i++){mn=Math.min(mn,nums[i]);mx=Math.max(mx,nums[i]);}return mx-mn;}'),

pdef('sum-even', 'Sum of Even Numbers', 'easy', 'sumEven',
    sig(['nums' => 'int[]'], 'int'),
    'Return the sum of all even numbers in the array. Odd numbers contribute nothing.',
    ['0 ≤ nums.length ≤ 10⁵'],
    [t([[1, 2, 3, 4]], 6, 1), t([[1, 3, 5]], 0, 1), t([[-2, 2, 7]], 0), t([[]] , 0)],
    'function sumEven(nums){var s=0;for(var i=0;i<nums.length;i++){if(nums[i]%2===0)s+=nums[i];}return s;}'),

pdef('contains-duplicate', 'Contains Duplicate', 'easy', 'containsDuplicate',
    sig(['nums' => 'int[]'], 'bool'),
    'Return true if any value appears at least twice in the array, and false if every element is distinct.',
    ['1 ≤ nums.length ≤ 10⁵'],
    [t([[1, 2, 3, 1]], true, 1), t([[1, 2, 3, 4]], false, 1), t([[7]], false), t([[2, 2]], true)],
    'function containsDuplicate(nums){return new Set(nums).size!==nums.length;}',
    'Sorting first gives O(n log n) time but zero extra memory.'),

pdef('missing-number', 'Missing Number', 'easy', 'missingNumber',
    sig(['nums' => 'int[]'], 'int'),
    'The array contains n distinct numbers taken from the range 0 to n, so exactly one number from that range is missing. Return it.',
    ['1 ≤ n ≤ 10⁴', 'All numbers are unique'],
    [t([[3, 0, 1]], 2, 1), t([[0, 1]], 2, 1), t([[9, 6, 4, 2, 3, 5, 7, 0, 1]], 8), t([[0]], 1)],
    'function missingNumber(nums){var x=nums.length;for(var i=0;i<nums.length;i++){x^=i^nums[i];}return x;}',
    'Gauss would sum 0..n and subtract. XOR avoids overflow entirely.'),

pdef('rotate-array', 'Rotate Array', 'easy', 'rotateArray',
    sig(['nums' => 'int[]', 'k' => 'int'], 'int[]'),
    'Rotate the array to the right by k steps and return the result.',
    ['1 ≤ nums.length ≤ 10⁵', '0 ≤ k ≤ 10⁹'],
    [t([[1, 2, 3, 4, 5], 2], [4, 5, 1, 2, 3], 1), t([[1, 2], 3], [2, 1], 1), t([[1], 9], [1]), t([[1, 2, 3], 0], [1, 2, 3])],
    'function rotateArray(nums,k){k=k%nums.length;if(k===0)return nums.slice();return nums.slice(-k).concat(nums.slice(0,nums.length-k));}'),

pdef('product-except-self', 'Product of Array Except Self', 'medium', 'productExceptSelf',
    sig(['nums' => 'int[]'], 'int[]'),
    'Return an array where answer[i] equals the product of all the numbers in nums except nums[i]. Solve it without using division.',
    ['2 ≤ nums.length ≤ 10⁵', 'The product of any prefix or suffix fits in a 32-bit integer'],
    [t([[1, 2, 3, 4]], [24, 12, 8, 6], 1), t([[-1, 1, 0, -3, 3]], [0, 0, 9, 0, 0], 1), t([[2, 3]], [3, 2]), t([[5, 0]], [0, 5])],
    'function productExceptSelf(nums){var n=nums.length,out=new Array(n).fill(1),pre=1,post=1,i;for(i=0;i<n;i++){out[i]=pre;pre*=nums[i];}for(i=n-1;i>=0;i--){out[i]*=post;post*=nums[i];}return out;}'),

pdef('plus-one', 'Plus One', 'easy', 'plusOne',
    sig(['digits' => 'int[]'], 'int[]'),
    'The digits array represents a large integer, most significant digit first. Increment the integer by one and return the resulting digits.',
    ['1 ≤ digits.length ≤ 100', 'digits[i] is 0–9, no leading zero'],
    [t([[1, 2, 3]], [1, 2, 4], 1), t([[9]], [1, 0], 1), t([[9, 9]], [1, 0, 0]), t([[0]], [1])],
    'function plusOne(d){var a=d.slice(),i=a.length-1;while(i>=0){if(a[i]<9){a[i]++;return a;}a[i]=0;i--;}a.unshift(1);return a;}'),

pdef('third-max', 'Third Maximum Number', 'easy', 'thirdMax',
    sig(['nums' => 'int[]'], 'int'),
    'Return the third DISTINCT maximum number in the array. If fewer than three distinct values exist, return the overall maximum instead.',
    ['1 ≤ nums.length ≤ 10⁴'],
    [t([[3, 2, 1]], 1, 1), t([[1, 2]], 2, 1), t([[2, 2, 3, 1]], 1), t([[5, 4, 3, 2, 1]], 3)],
    'function thirdMax(nums){var s=Array.from(new Set(nums)).sort(function(a,b){return b-a;});return s.length>=3?s[2]:s[0];}'),

pdef('find-disappeared', 'Find All Numbers Disappeared', 'easy', 'findDisappeared',
    sig(['nums' => 'int[]'], 'int[]'),
    'The array contains numbers in the range 1 to n, where some appear twice and others are missing entirely. Return every missing number, sorted ascending.',
    ['1 ≤ n ≤ 10⁵'],
    [t([[4, 3, 2, 7, 8, 2, 3, 1]], [5, 6], 1), t([[1, 1]], [2], 1), t([[2, 2]], [1]), t([[1]], [])],
    'function findDisappeared(nums){var seen=new Set(nums),out=[];for(var i=1;i<=nums.length;i++){if(!seen.has(i))out.push(i);}return out;}'),

pdef('majority-element', 'Majority Element', 'easy', 'majorityElement',
    sig(['nums' => 'int[]'], 'int'),
    'Return the majority element — the value that appears more than n/2 times. It always exists.',
    ['1 ≤ nums.length ≤ 5·10⁴'],
    [t([[3, 2, 3]], 3, 1), t([[2, 2, 1, 1, 1, 2, 2]], 2, 1), t([[1]], 1), t([[6, 6, 6, 1]], 6)],
    'function majorityElement(nums){var c=0,m=null;for(var i=0;i<nums.length;i++){if(c===0)m=nums[i];c+=nums[i]===m?1:-1;}return m;}',
    'This is the Boyer–Moore voting algorithm: O(n) time, O(1) space.'),

pdef('array-intersection', 'Intersection of Two Arrays', 'easy', 'arrayIntersection',
    sig(['nums1' => 'int[]', 'nums2' => 'int[]'], 'int[]'),
    'Return the unique values present in BOTH arrays, sorted ascending.',
    ['1 ≤ each length ≤ 1000'],
    [t([[1, 2, 2, 1], [2, 2]], [2], 1), t([[4, 9, 5], [9, 4, 9, 8, 4]], [4, 9], 1), t([[1, 2], [3, 4]], []), t([[1, 3, 5], [5, 3, 1]], [1, 3, 5])],
    'function arrayIntersection(a,b){var s=new Set(b),out=new Set();for(var i=0;i<a.length;i++){if(s.has(a[i]))out.add(a[i]);}return Array.from(out).sort(function(x,y){return x-y;});}'),

pdef('student-sort', 'Rank Students by Score', 'easy', 'sortStudents',
    sig(['names' => 'str[]', 'scores' => 'int[]'], 'str[]'),
    'A gradebook stores names[i] with scores[i] at the same index. Return the names ordered by score, highest first. Ties keep their original order.',
    ['1 ≤ names.length ≤ 10⁴', 'Scores are 0–100'],
    [t([['amy', 'bob', 'cyd'], [50, 90, 70]], ['bob', 'cyd', 'amy'], 1), t([['ann'], [10]], ['ann'], 1),
     t([['a', 'b', 'c'], [5, 5, 5]], ['a', 'b', 'c']), t([['x', 'y'], [0, 100]], ['y', 'x'])],
    'function sortStudents(names,scores){return names.map(function(n,i){return {n:n,s:scores[i]};}).sort(function(a,b){return b.s-a.s;}).map(function(o){return o.n;});}'),

pdef('max-product-subarray', 'Maximum Product Subarray', 'medium', 'maxProduct',
    sig(['nums' => 'int[]'], 'int'),
    'Find the contiguous subarray with the largest product and return that product. Watch the signs: two negatives make a positive.',
    ['1 ≤ nums.length ≤ 2·10⁴', '-10 ≤ nums[i] ≤ 10'],
    [t([[2, 3, -2, 4]], 6, 1), t([[-2, 0, -1]], 0, 1), t([[-2]], -2), t([[0, 2]], 2)],
    'function maxProduct(nums){var best=nums[0],mx=1,mn=1;for(var i=0;i<nums.length;i++){var v=nums[i],a=mx*v,b=mn*v;mx=Math.max(v,a,b);mn=Math.min(v,a,b);best=Math.max(best,mx);}return best;}'),

pdef('running-sum', 'Running Sum of Array', 'easy', 'runningSum',
    sig(['nums' => 'int[]'], 'int[]'),
    'Return the running (prefix) sum: answer[i] is the sum of all elements up to and including i.',
    ['1 ≤ nums.length ≤ 1000', '-10⁶ ≤ nums[i] ≤ 10⁶'],
    [t([[1, 2, 3, 4]], [1, 3, 6, 10], 1), t([[1, 1, 1, 1, 1]], [1, 2, 3, 4, 5], 1),
     t([[3]], [3]), t([[3, 1, 2, 10, 1]], [3, 4, 6, 16, 17])],
    'function runningSum(nums){var s=0,a=[];for(var i=0;i<nums.length;i++){s+=nums[i];a.push(s);}return a;}'),

pdef('shuffle-array', 'Shuffle the Array', 'easy', 'shuffle',
    sig(['nums' => 'int[]', 'n' => 'int'], 'int[]'),
    'The array has 2n elements in the form [x1..xn, y1..yn]. Interleave them as [x1, y1, x2, y2, ...] and return that.',
    ['1 ≤ n ≤ 500', 'nums.length == 2n'],
    [t([[2, 5, 1, 3, 4, 7], 3], [2, 3, 5, 4, 1, 7], 1), t([[1, 2, 3, 4, 4, 3, 2, 1], 4], [1, 4, 2, 3, 3, 2, 4, 1], 1),
     t([[1, 1, 2, 2], 2], [1, 2, 1, 2])],
    'function shuffle(nums,n){var a=[];for(var i=0;i<n;i++){a.push(nums[i]);a.push(nums[i+n]);}return a;}'),

pdef('kids-with-candies', 'Kids With the Greatest Candies', 'easy', 'kidsWithCandies',
    sig(['candies' => 'int[]', 'extra' => 'int'], 'bool[]'),
    'Each kid has candies[i]. For each kid, return true if giving them ALL the extra candies puts them at or above the current maximum.',
    ['2 ≤ candies.length ≤ 100', '1 ≤ candies[i], extra ≤ 100'],
    [t([[2, 3, 5, 1, 3], 3], [true, true, true, false, true], 1), t([[4, 2, 1, 1, 2], 1], [true, false, false, false, false], 1),
     t([[12, 1, 12], 10], [true, false, true])],
    'function kidsWithCandies(candies,extra){var m=Math.max.apply(null,candies);return candies.map(function(c){return c+extra>=m;});}'),

pdef('num-good-pairs', 'Number of Good Pairs', 'easy', 'numIdenticalPairs',
    sig(['nums' => 'int[]'], 'int'),
    'Count pairs i < j where nums[i] equals nums[j].',
    ['1 ≤ nums.length ≤ 100', '1 ≤ nums[i] ≤ 100'],
    [t([[1, 2, 3, 1, 1, 3]], 4, 1), t([[1, 1, 1, 1]], 6, 1), t([[1, 2, 3]], 0)],
    'function numIdenticalPairs(nums){var c={},ans=0;for(var i=0;i<nums.length;i++){var k=nums[i];ans+=c[k]||0;c[k]=(c[k]||0)+1;}return ans;}'),

pdef('decompress-rle', 'Decompress Run-Length List', 'easy', 'decompressRLElist',
    sig(['nums' => 'int[]'], 'int[]'),
    'The list is pairs of [freq, value]: decompress it by emitting each value freq times, in order.',
    ['2 ≤ nums.length ≤ 100', 'nums.length is even', '1 ≤ nums[i] ≤ 100'],
    [t([[1, 2, 3, 4]], [2, 4, 4, 4], 1), t([[1, 1, 2, 3]], [1, 3, 3], 1),
     t([[2, 5]], [5, 5])],
    'function decompressRLElist(nums){var a=[];for(var i=0;i<nums.length;i+=2)for(var j=0;j<nums[i];j++)a.push(nums[i+1]);return a;}'),

pdef('array-partition-sum', 'Array Partition', 'easy', 'arrayPairSum',
    sig(['nums' => 'int[]'], 'int'),
    'Pair up the 2n numbers into n pairs to maximize the sum of each pair\'s minimum. Return that maximum sum.',
    ['1 ≤ n ≤ 10⁴', 'nums.length == 2n', '-10⁴ ≤ nums[i] ≤ 10⁴'],
    [t([[1, 4, 3, 2]], 4, 1), t([[6, 2, 6, 5, 1, 2]], 9, 1), t([[1, 1]], 1)],
    'function arrayPairSum(nums){nums.sort(function(a,b){return a-b;});var s=0;for(var i=0;i<nums.length;i+=2)s+=nums[i];return s;}'),

pdef('max-avg-subarray', 'Maximum Average Subarray', 'easy', 'findMaxAverage',
    sig(['nums' => 'num[]', 'k' => 'int'], 'num'),
    'Find the contiguous subarray of length k with the maximum average and return that average.',
    ['1 ≤ k ≤ nums.length ≤ 10⁵', '-10⁴ ≤ nums[i] ≤ 10⁴'],
    [t([[1, 12, -5, -6, 50, 3], 4], 12.75, 1), t([[5], 1], 5, 1),
     t([[0, 1, 1, 3, 3], 4], 2, 0), t([[4, 2, 1, 3, 3], 2], 3)],
    'function findMaxAverage(nums,k){var s=0;for(var i=0;i<k;i++)s+=nums[i];var b=s;for(var j=k;j<nums.length;j++){s+=nums[j]-nums[j-k];if(s>b)b=s;}return b/k;}'),

pdef('height-checker', 'Height Checker', 'easy', 'heightChecker',
    sig(['heights' => 'int[]'], 'int'),
    'A line sorted ascending is expected. Count how many positions differ from the sorted order.',
    ['1 ≤ heights.length ≤ 100', '1 ≤ heights[i] ≤ 100'],
    [t([[1, 1, 4, 2, 1, 3]], 3, 1), t([[5, 1, 2, 3, 4]], 5, 1), t([[1, 2, 3, 4, 5]], 0)],
    'function heightChecker(heights){var e=heights.slice().sort(function(a,b){return a-b;});var c=0;for(var i=0;i<heights.length;i++)if(heights[i]!==e[i])c++;return c;}'),

pdef('lucky-integer', 'Find Lucky Integer', 'easy', 'findLucky',
    sig(['arr' => 'int[]'], 'int'),
    'A lucky integer equals its own frequency in the array. Return the largest lucky integer, or -1 if none.',
    ['1 ≤ arr.length ≤ 500', '1 ≤ arr[i] ≤ 500'],
    [t([[2, 2, 3, 4]], 2, 1), t([[1, 2, 2, 3, 3, 3]], 3, 1), t([[2, 2, 2, 3, 3]], -1), t([[7, 7, 7, 7, 7, 7, 7]], 7)],
    'function findLucky(arr){var c={},best=-1;for(var i=0;i<arr.length;i++)c[arr[i]]=(c[arr[i]]||0)+1;for(var k in c)if(Number(k)===c[k])best=Math.max(best,c[k]);return best;}'),

pdef('monotonic-array', 'Monotonic Array', 'easy', 'isMonotonic',
    sig(['nums' => 'int[]'], 'bool'),
    'Return true if the array is monotonic (entirely non-increasing or non-decreasing).',
    ['1 ≤ nums.length ≤ 10⁵', '-10⁵ ≤ nums[i] ≤ 10⁵'],
    [t([[1, 2, 2, 3]], true, 1), t([[6, 5, 4, 4]], true, 1), t([[1, 3, 2]], false), t([[1]], true)],
    'function isMonotonic(nums){var inc=true,dec=true;for(var i=1;i<nums.length;i++){if(nums[i]>nums[i-1])dec=false;if(nums[i]<nums[i-1])inc=false;}return inc||dec;}'),

pdef('rank-transform', 'Rank Transform of an Array', 'easy', 'arrayRankTransform',
    sig(['arr' => 'int[]'], 'int[]'),
    'Replace each element by its rank: rank 1 = smallest distinct value, larger values get higher ranks. Equal values share a rank.',
    ['0 ≤ arr.length ≤ 10⁵', '-10⁹ ≤ arr[i] ≤ 10⁹'],
    [t([[40, 10, 20, 30]], [4, 1, 2, 3], 1), t([[100, 100, 100]], [1, 1, 1], 1), t([[37, 12, 28, 9, 100]], [4, 2, 3, 1, 5]), t([[]], [])],
    'function arrayRankTransform(arr){var u=Array.from(new Set(arr)).sort(function(a,b){return a-b;});var m={};u.forEach(function(v,i){m[v]=i+1;});return arr.map(function(v){return m[v];});}'),

pdef('relative-ranks', 'Relative Ranks', 'easy', 'findRelativeRanks',
    sig(['score' => 'int[]'], 'str[]'),
    'Rank a leaderboard: best score gets "Gold Medal", then "Silver Medal", "Bronze Medal", everyone else their 1-based place as a string.',
    ['1 ≤ score.length ≤ 10⁴', 'all scores distinct'],
    [t([[5, 4, 3, 2, 1]], ['Gold Medal', 'Silver Medal', 'Bronze Medal', '4', '5'], 1),
     t([[10, 3, 8, 9, 4]], ['Gold Medal', '5', 'Bronze Medal', 'Silver Medal', '4'], 1),
     t([[1]], ['Gold Medal'])],
    'function findRelativeRanks(score){var idx=score.map(function(v,i){return i;}).sort(function(a,b){return score[b]-score[a];});var out=new Array(score.length);idx.forEach(function(oi,rk){out[oi]=rk===0?"Gold Medal":rk===1?"Silver Medal":rk===2?"Bronze Medal":String(rk+1);});return out;}'),

pdef('avg-excluding-extremes', 'Average Excluding Min & Max', 'easy', 'average',
    sig(['salary' => 'num[]'], 'num'),
    'Return the average after excluding exactly one minimum and one maximum value.',
    ['3 ≤ salary.length ≤ 100', 'all values distinct'],
    [t([[4000, 3000, 1000, 2000]], 2500, 1), t([[1000, 2000, 3000]], 2000, 1),
     t([[6000, 5000, 4000, 3000, 2000, 1000]], 3500)],
    'function average(salary){var mn=Math.min.apply(null,salary),mx=Math.max.apply(null,salary),s=0;for(var i=0;i<salary.length;i++)s+=salary[i];return (s-mn-mx)/(salary.length-2);}'),

pdef('xor-operation', 'XOR Operation in an Array', 'easy', 'xorOperation',
    sig(['n' => 'int', 'start' => 'int'], 'int'),
    'Build nums[i] = start + 2i for i in 0..n-1 and return the XOR of the whole array.',
    ['1 ≤ n ≤ 1000', '0 ≤ start ≤ 1000'],
    [t([5, 3], 3, 1), t([4, 3], 8, 1), t([1, 7], 7), t([10, 5], 2)],
    'function xorOperation(n,start){var x=0;for(var i=0;i<n;i++)x^=start+2*i;return x;}'),

pdef('make-two-arrays-equal', 'Make Two Arrays Equal', 'easy', 'canBeEqual',
    sig(['target' => 'int[]', 'arr' => 'int[]'], 'bool'),
    'Return true if arr can be rearranged to equal target (same elements, same multiplicities).',
    ['1 ≤ target.length ≤ 1000', 'target.length == arr.length'],
    [t([[1, 2, 3, 4], [2, 4, 1, 3]], true, 1), t([[7], [7]], true, 1), t([[3, 7, 9], [3, 7, 11]], false)],
    'function canBeEqual(target,arr){if(target.length!==arr.length)return false;target.sort(function(a,b){return a-b;});arr.sort(function(a,b){return a-b;});for(var i=0;i<target.length;i++)if(target[i]!==arr[i])return false;return true;}'),

pdef('longest-ones-delete', 'Longest Subarray of 1s After Deleting One', 'medium', 'longestSubarray',
    sig(['nums' => 'int[]'], 'int'),
    'Delete exactly one element. Return the length of the longest all-ones subarray achievable.',
    ['1 ≤ nums.length ≤ 10⁵', 'nums[i] is 0 or 1'],
    [t([[1, 1, 0, 1]], 3, 1), t([[0, 1, 1, 1, 0, 1, 1, 0, 1]], 5, 1), t([[1, 1, 1]], 2), t([[0, 0, 0]], 0)],
    'function longestSubarray(nums){var l=0,z=0,b=0;for(var r=0;r<nums.length;r++){if(nums[r]===0)z++;while(z>1){if(nums[l]===0)z--;l++;}b=Math.max(b,r-l);}return b;}'),

pdef('busy-students', 'Students Doing Homework at Time T', 'easy', 'busyStudent',
    sig(['startTime' => 'int[]', 'endTime' => 'int[]', 't' => 'int'], 'int'),
    'The i-th student works from startTime[i] to endTime[i] inclusive. Count how many are working at time t.',
    ['1 ≤ startTime.length ≤ 100', 'startTime[i] ≤ endTime[i] ≤ 1000'],
    [t([[1, 2, 3], [3, 2, 7], 4], 1, 1), t([[4], [4], 4], 1, 1), t([[1, 1, 1, 1], [1, 3, 2, 4], 7], 0)],
    'function busyStudent(s,e,t){var c=0;for(var i=0;i<s.length;i++)if(s[i]<=t&&t<=e[i])c++;return c;}'),

pdef('min-start-value', 'Minimum Start Value', 'easy', 'minStartValue',
    sig(['nums' => 'int[]'], 'int'),
    'Choose a starting value so the running sum (start + prefix sums) never drops below 1. Return the minimum such start.',
    ['1 ≤ nums.length ≤ 100', '-100 ≤ nums[i] ≤ 100'],
    [t([[-3, 2, -3, 4, 2]], 5, 1), t([[1, 2]], 1, 1), t([[1, -2, -3]], 5)],
    'function minStartValue(nums){var s=0,mn=0;for(var i=0;i<nums.length;i++){s+=nums[i];mn=Math.min(mn,s);}return 1-mn;}'),

pdef('count-good-triplets', 'Count Good Triplets', 'easy', 'countGoodTriplets',
    sig(['arr' => 'int[]', 'a' => 'int', 'b' => 'int', 'c' => 'int'], 'int'),
    'Count triplets i < j < k with |arr[i]-arr[j]| ≤ a, |arr[j]-arr[k]| ≤ b, |arr[i]-arr[k]| ≤ c (|x| = absolute value).',
    ['3 ≤ arr.length ≤ 100', '0 ≤ arr[i], a, b, c ≤ 1000'],
    [t([[3, 0, 1, 1, 9, 7], 7, 2, 3], 4, 1), t([[1, 1, 2, 2, 3], 0, 0, 1], 0, 1),
     t([[1, 2, 3], 1, 1, 1], 0)],
    'function countGoodTriplets(arr,a,b,c){var n=arr.length,cnt=0;for(var i=0;i<n;i++)for(var j=i+1;j<n;j++)for(var k=j+1;k<n;k++)if(Math.abs(arr[i]-arr[j])<=a&&Math.abs(arr[j]-arr[k])<=b&&Math.abs(arr[i]-arr[k])<=c)cnt++;return cnt;}'),

pdef('remove-element', 'Remove Element', 'easy', 'removeElement',
    sig(['nums' => 'int[]', 'val' => 'int'], 'int'),
    'Remove all occurrences of val and return the new length (the kept elements may be in any order).',
    ['0 ≤ nums.length ≤ 100', '0 ≤ nums[i], val ≤ 50'],
    [t([[3, 2, 2, 3], 3], 2, 1), t([[0, 1, 2, 2, 3, 0, 4, 2], 2], 5, 1), t([[], 1], 0), t([[1, 1, 1], 1], 0)],
    'function removeElement(nums,val){var k=0;for(var i=0;i<nums.length;i++)if(nums[i]!==val)k++;return k;}'),

pdef('sum-odd-length-subarrays', 'Sum of All Odd-Length Subarrays', 'easy', 'sumOddLengthSubarrays',
    sig(['arr' => 'int[]'], 'int'),
    'Add up every contiguous subarray whose length is odd and return the grand total.',
    ['1 ≤ arr.length ≤ 100', '1 ≤ arr[i] ≤ 1000'],
    [t([[1, 4, 2, 5, 3]], 58, 1), t([[1, 2]], 3, 1), t([[10, 11, 12]], 66)],
    'function sumOddLengthSubarrays(arr){var n=arr.length,total=0;for(var len=1;len<=n;len+=2)for(var i=0;i+len<=n;i++)for(var j=0;j<len;j++)total+=arr[i+j];return total;}'),

pdef('max-consecutive-ones', 'Max Consecutive Ones', 'easy', 'findMaxConsecutiveOnes',
    sig(['nums' => 'int[]'], 'int'),
    'Return the length of the longest run of consecutive 1s.',
    ['1 ≤ nums.length ≤ 10⁵', 'nums[i] is 0 or 1'],
    [t([[1, 1, 0, 1, 1, 1]], 3, 1), t([[1, 0, 1, 1, 0, 1]], 2, 1), t([[0, 0]], 0), t([[1]], 1)],
    'function findMaxConsecutiveOnes(nums){var b=0,c=0;for(var i=0;i<nums.length;i++){c=nums[i]===1?c+1:0;b=Math.max(b,c);}return b;}'),

pdef('max-consecutive-ones-k-flips', 'Max Consecutive Ones III', 'medium', 'longestOnes',
    sig(['nums' => 'int[]', 'k' => 'int'], 'int'),
    'You may flip at most k zeros to ones. Return the longest all-ones stretch obtainable.',
    ['1 ≤ nums.length ≤ 10⁵', '0 ≤ k ≤ nums.length'],
    [t([[1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0], 2], 6, 1), t([[0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1], 3], 10, 1),
     t([[1, 1], 0], 2), t([[0, 0], 2], 2)],
    'function longestOnes(nums,k){var l=0,z=0,b=0;for(var r=0;r<nums.length;r++){if(nums[r]===0)z++;while(z>k){if(nums[l]===0)z--;l++;}b=Math.max(b,r-l+1);}return b;}'),

pdef('ascending-subarray-sum', 'Maximum Ascending Subarray Sum', 'easy', 'maxAscendingSum',
    sig(['nums' => 'int[]'], 'int'),
    'Find the strictly ascending contiguous run with the maximum sum and return that sum.',
    ['1 ≤ nums.length ≤ 100', '1 ≤ nums[i] ≤ 100'],
    [t([[10, 20, 30, 5, 10, 50]], 65, 1), t([[10, 20, 30, 40, 50]], 150, 1), t([[12, 17, 15, 13, 10, 11, 12]], 33)],
    'function maxAscendingSum(nums){var b=nums[0],c=nums[0];for(var i=1;i<nums.length;i++){c=nums[i]>nums[i-1]?c+nums[i]:nums[i];b=Math.max(b,c);}return b;}'),

pdef('sorted-rotated-check', 'Check if Sorted and Rotated', 'easy', 'check',
    sig(['nums' => 'int[]'], 'bool'),
    'Return true if the array can become non-decreasing sorted by some number of rotations (possibly zero).',
    ['1 ≤ nums.length ≤ 100', '1 ≤ nums[i] ≤ 100'],
    [t([[3, 4, 5, 1, 2]], true, 1), t([[2, 1, 3, 4]], false, 1), t([[1, 2, 3]], true), t([[1, 1, 1]], true)],
    'function check(nums){var d=0;for(var i=0;i<nums.length;i++)if(nums[i]>nums[(i+1)%nums.length])d++;return d<=1;}'),

pdef('poisoned-duration', 'Teemo Attacking', 'easy', 'findPoisonedDuration',
    sig(['timeSeries' => 'int[]', 'duration' => 'int'], 'int'),
    'Each attack at time t poisons for duration seconds ([t, t+duration)). Overlaps merge. Return total poisoned time.',
    ['1 ≤ timeSeries.length ≤ 10⁴', '0 ≤ timeSeries[i], duration ≤ 10⁷', 'timeSeries is sorted ascending'],
    [t([[1, 4], 2], 4, 1), t([[1, 2], 2], 3, 1), t([[1, 2, 3, 4, 5], 1], 5)],
    'function findPoisonedDuration(ts,dur){var tot=0;for(var i=1;i<ts.length;i++)tot+=Math.min(dur,ts[i]-ts[i-1]);return tot+dur;}'),

pdef('can-place-flowers', 'Can Place Flowers', 'easy', 'canPlaceFlowers',
    sig(['flowerbed' => 'int[]', 'n' => 'int'], 'bool'),
    'Plots with 1 are taken; no two new flowers may be adjacent. Return true if n new flowers can be planted.',
    ['1 ≤ flowerbed.length ≤ 2·10⁴', 'flowerbed has no adjacent 1s initially'],
    [t([[1, 0, 0, 0, 1], 1], true, 1), t([[1, 0, 0, 0, 1], 2], false, 1), t([[0, 0, 1, 0, 1], 1], true), t([[1, 0, 1, 0, 1, 0, 1], 0], true)],
    'function canPlaceFlowers(f,n){for(var i=0;i<f.length&&n>0;i++){if(f[i]===0&&(i===0||f[i-1]===0)&&(i===f.length-1||f[i+1]===0)){f[i]=1;n--;}}return n<=0;}'),

pdef('array-degree', 'Degree of an Array', 'easy', 'findShortestSubArray',
    sig(['nums' => 'int[]'], 'int'),
    'The degree is the max frequency of any value. Find the shortest contiguous subarray with that same degree and return its length.',
    ['1 ≤ nums.length ≤ 5·10⁴', '0 ≤ nums[i] ≤ 49999'],
    [t([[1, 2, 2, 3, 1]], 2, 1), t([[1, 2, 2, 3, 1, 4, 2]], 6, 1), t([[1]], 1)],
    'function findShortestSubArray(nums){var first={},last={},cnt={},deg=0;for(var i=0;i<nums.length;i++){var v=nums[i];if(first[v]===undefined)first[v]=i;last[v]=i;cnt[v]=(cnt[v]||0)+1;deg=Math.max(deg,cnt[v]);}var best=nums.length;for(var k in cnt)if(cnt[k]===deg)best=Math.min(best,last[k]-first[k]+1);return best;}'),

pdef('distribute-candies', 'Distribute Candies', 'easy', 'distributeCandies',
    sig(['candyType' => 'int[]'], 'int'),
    'n candies; one sibling may keep n/2. Return the maximum number of DIFFERENT types they can end up with.',
    ['2 ≤ n ≤ 10⁴', 'n is even', '-10⁵ ≤ candyType[i] ≤ 10⁵'],
    [t([[1, 1, 2, 2, 3, 3]], 3, 1), t([[1, 1, 2, 3]], 2, 1), t([[6, 6, 6, 6]], 1)],
    'function distributeCandies(c){return Math.min(c.length/2,new Set(c).size);}'),

pdef('lhs', 'Longest Harmonious Subsequence', 'easy', 'findLHS',
    sig(['nums' => 'int[]'], 'int'),
    'A harmonious subsequence has max-min = 1. Find the longest one (order does not matter) and return its length.',
    ['1 ≤ nums.length ≤ 2·10⁴', '-10⁹ ≤ nums[i] ≤ 10⁹'],
    [t([[1, 3, 2, 2, 5, 2, 3, 7]], 5, 1), t([[1, 2, 3, 4]], 2, 1), t([[1, 1, 1, 1]], 0), t([[1, 2, 2, 1]], 4)],
    'function findLHS(nums){var c={},b=0;for(var i=0;i<nums.length;i++)c[nums[i]]=(c[nums[i]]||0)+1;for(var k in c){var v=Number(k);if(c[v+1]!==undefined)b=Math.max(b,c[v]+c[v+1]);}return b;}'),

pdef('max-chunks', 'Max Chunks To Make Sorted', 'medium', 'maxChunksToSorted',
    sig(['arr' => 'int[]'], 'int'),
    'arr is a permutation of 0..n-1. Split it into the maximum number of chunks so that sorting each chunk yields a fully sorted array.',
    ['1 ≤ arr.length ≤ 10', 'arr is a permutation of 0..n-1'],
    [t([[1, 0, 2, 3, 4]], 4, 1), t([[4, 3, 2, 1, 0]], 1, 1), t([[0, 3, 2, 1, 4]], 3)],
    'function maxChunksToSorted(arr){var mx=0,c=0;for(var i=0;i<arr.length;i++){mx=Math.max(mx,arr[i]);if(mx===i)c++;}return c;}'),

pdef('array-nesting', 'Array Nesting', 'medium', 'arrayNesting',
    sig(['nums' => 'int[]'], 'int'),
    'nums is a permutation of 0..n-1. From each start k follow k, nums[k], nums[nums[k]], ... until you repeat. Return the longest such chain.',
    ['1 ≤ nums.length ≤ 10⁵', 'nums is a permutation of 0..n-1'],
    [t([[5, 4, 0, 3, 1, 6, 2]], 4, 1), t([[0, 1, 2]], 1, 1), t([[0, 2, 1]], 2)],
    'function arrayNesting(nums){var seen={},b=0;for(var i=0;i<nums.length;i++){if(seen[i])continue;var cur=i,len=0;while(!seen[cur]){seen[cur]=true;cur=nums[cur];len++;}b=Math.max(b,len);}return b;}'),

pdef('sum-abs-differences', 'Sum of Absolute Differences in Sorted Array', 'medium', 'getSumAbsoluteDifferences',
    sig(['nums' => 'int[]'], 'int[]'),
    'For each i, sum |nums[i] - nums[j]| over all j and return the array of totals.',
    ['2 ≤ nums.length ≤ 10⁵', 'nums is sorted non-decreasing'],
    [t([[2, 3, 5]], [4, 3, 5], 1), t([[1, 4, 6, 8, 10]], [24, 15, 13, 15, 21], 1), t([[1, 2]], [1, 1])],
    'function getSumAbsoluteDifferences(nums){var n=nums.length,pre=0,tot=0,out=[];for(var i=0;i<n;i++)tot+=nums[i];for(var j=0;j<n;j++){pre+=nums[j];var left=(j+1)*nums[j]-pre;var right=(tot-pre)-(n-j-1)*nums[j];out.push(left+right);}return out;}'),

pdef('triangular-sum', 'Find Triangular Sum of an Array', 'medium', 'triangularSum',
    sig(['nums' => 'int[]'], 'int'),
    'Repeatedly replace the array with pairwise sums mod 10 until one element remains; return it.',
    ['1 ≤ nums.length ≤ 1000', '0 ≤ nums[i] ≤ 9'],
    [t([[1, 2, 3, 4, 5]], 8, 1), t([[5]], 5, 1), t([[1, 1]], 2), t([[2, 6, 6, 5, 5, 3, 3, 8, 6, 4, 3, 3, 5, 1, 0, 1, 3, 6, 9]], 0)],
    'function triangularSum(nums){var a=nums.slice();while(a.length>1){var b=[];for(var i=0;i<a.length-1;i++)b.push((a[i]+a[i+1])%10);a=b;}return a[0];}'),

pdef('left-right-sum-diff', 'Left and Right Sum Differences', 'easy', 'leftRightDifference',
    sig(['nums' => 'int[]'], 'int[]'),
    'answer[i] = |sum(nums[0..i-1]) - sum(nums[i+1..end])|. Return the answer array.',
    ['1 ≤ nums.length ≤ 1000', '1 ≤ nums[i] ≤ 10⁵'],
    [t([[10, 4, 8, 3]], [15, 1, 11, 22], 1), t([[1]], [0], 1), t([[1, 2]], [2, 1])],
    'function leftRightDifference(nums){var tot=0,out=[],left=0;for(var i=0;i<nums.length;i++)tot+=nums[i];for(var j=0;j<nums.length;j++){var right=tot-left-nums[j];out.push(Math.abs(left-right));left+=nums[j];}return out;}'),

pdef('count-prefixes', 'Count Prefixes of a Given String', 'easy', 'countPrefixes',
    sig(['words' => 'str[]', 's' => 'str'], 'int'),
    'Count how many words are a prefix of s.',
    ['1 ≤ words.length ≤ 100', '1 ≤ words[i].length, s.length ≤ 10'],
    [t([['a', 'b', 'c', 'ab', 'bc', 'abc'], 'abc'], 3, 1), t([['a', 'a'], 'aa'], 2, 1), t([['x', 'yz'], 'w'], 0)],
    'function countPrefixes(words,s){return words.filter(function(w){return s.indexOf(w)===0;}).length;}'),

pdef('divide-pairs', 'Divide Array Into Equal Pairs', 'easy', 'divideArray',
    sig(['nums' => 'int[]'], 'bool'),
    'Return true if the array can be partitioned into pairs of equal values (every value occurs an even number of times).',
    ['2 ≤ nums.length ≤ 500', 'nums.length is even', '1 ≤ nums[i] ≤ 500'],
    [t([[3, 2, 3, 2, 2, 2]], true, 1), t([[1, 2, 3, 4]], false, 1), t([[5, 5]], true)],
    'function divideArray(nums){var c={};for(var i=0;i<nums.length;i++)c[nums[i]]=!c[nums[i]];for(var k in c)if(c[k])return false;return true;}'),

pdef('count-abs-diff-k', 'Count Number of Pairs With Absolute Difference K', 'easy', 'countKDifference',
    sig(['nums' => 'int[]', 'k' => 'int'], 'int'),
    'Count pairs i < j with |nums[i] - nums[j]| = k.',
    ['1 ≤ nums.length ≤ 200', '1 ≤ nums[i] ≤ 100', '1 ≤ k ≤ 99'],
    [t([[1, 2, 2, 1], 1], 4, 1), t([[1, 3], 3], 0, 1), t([[3, 2, 1, 5, 4], 2], 3)],
    'function countKDifference(nums,k){var c=0;for(var i=0;i<nums.length;i++)for(var j=i+1;j<nums.length;j++)if(Math.abs(nums[i]-nums[j])===k)c++;return c;}'),

pdef('min-common-value', 'Minimum Common Value', 'easy', 'getCommon',
    sig(['nums1' => 'int[]', 'nums2' => 'int[]'], 'int'),
    'Both arrays are sorted ascending. Return the smallest value present in both, or -1.',
    ['1 ≤ nums1.length, nums2.length ≤ 10⁵', '1 ≤ nums[i] ≤ 10⁹'],
    [t([[1, 2, 3], [2, 4]], 2, 1), t([[1, 2, 3, 6], [2, 3, 4, 5]], 2, 1), t([[1], [2]], -1)],
    'function getCommon(a,b){var i=0,j=0;while(i<a.length&&j<b.length){if(a[i]===b[j])return a[i];if(a[i]<b[j])i++;else j++;}return -1;}'),

pdef('separate-digits', 'Separate the Digits in an Array', 'easy', 'separateDigits',
    sig(['nums' => 'int[]'], 'int[]'),
    'Replace every number with its decimal digits in order and return the flattened array.',
    ['1 ≤ nums.length ≤ 1000', '1 ≤ nums[i] ≤ 10⁵'],
    [t([[13, 25, 83, 77]], [1, 3, 2, 5, 8, 3, 7, 7], 1), t([[7, 1, 3, 9]], [7, 1, 3, 9], 1), t([[10]], [1, 0])],
    'function separateDigits(nums){var out=[];for(var i=0;i<nums.length;i++){var s=String(nums[i]);for(var j=0;j<s.length;j++)out.push(Number(s[j]));}return out;}'),

pdef('count-equal-divisible', 'Count Equal and Divisible Pairs', 'easy', 'countPairs',
    sig(['nums' => 'int[]', 'k' => 'int'], 'int'),
    'Count pairs i < j where nums[i] === nums[j] and (i * j) is divisible by k.',
    ['1 ≤ nums.length ≤ 100', '1 ≤ nums[i], k ≤ 100'],
    [t([[3, 1, 2, 2, 2, 1, 3], 2], 4, 1), t([[1, 2, 3, 4], 1], 0, 1), t([[5, 5, 5], 2], 3)],
    'function countPairs(nums,k){var c=0;for(var i=0;i<nums.length;i++)for(var j=i+1;j<nums.length;j++)if(nums[i]===nums[j]&&(i*j)%k===0)c++;return c;}'),

pdef('count-beautiful-pairs', 'Count Beautiful Pairs', 'medium', 'countBeautifulPairs',
    sig(['nums' => 'int[]'], 'int'),
    'A pair i < j is beautiful if gcd(first digit of nums[i], last digit of nums[j]) = 1. Count them.',
    ['2 ≤ nums.length ≤ 100', '1 ≤ nums[i] ≤ 9999'],
    [t([[2, 5, 1, 4]], 5, 1), t([[11, 21, 12]], 2, 1), t([[31, 25, 72, 79, 74]], 7)],
    'function countBeautifulPairs(nums){function g(a,b){return b?g(b,a%b):a;}var c=0;for(var i=0;i<nums.length;i++){var fd=Number(String(nums[i])[0]);for(var j=i+1;j<nums.length;j++){if(g(fd,nums[j]%10)===1)c++;}}return c;}'),

pdef('ap-check', 'Can Make Arithmetic Progression', 'easy', 'canMakeArithmeticProgression',
    sig(['arr' => 'int[]'], 'bool'),
    'Return true if the array can be rearranged to form an arithmetic progression.',
    ['2 ≤ arr.length ≤ 1000', '-10⁶ ≤ arr[i] ≤ 10⁶'],
    [t([[3, 5, 1]], true, 1), t([[1, 2, 4]], false, 1), t([[0, 0, 0]], true), t([[1, 10, 7, 13, 4]], true)],
    'function canMakeArithmeticProgression(arr){arr.sort(function(a,b){return a-b;});var d=arr[1]-arr[0];for(var i=2;i<arr.length;i++)if(arr[i]-arr[i-1]!==d)return false;return true;}'),

pdef('bus-stop-distance', 'Distance Between Bus Stops', 'easy', 'distanceBetweenBusStops',
    sig(['distance' => 'int[]', 'start' => 'int', 'destination' => 'int'], 'int'),
    'Stops form a ring; distance[i] is the gap from stop i to i+1. Return the shortest distance between start and destination.',
    ['1 ≤ distance.length ≤ 10⁴', '0 ≤ start, destination < distance.length'],
    [t([[1, 2, 3, 4], 0, 3], 4, 1), t([[1, 2, 3, 4], 0, 2], 3, 1), t([[7, 10, 1, 12, 11, 14, 5, 0], 7, 2], 17)],
    'function distanceBetweenBusStops(d,s,e){if(s>e){var t=s;s=e;e=t;}var a=0,b=0;for(var i=0;i<d.length;i++){if(i>=s&&i<e)a+=d[i];else b+=d[i];}return Math.min(a,b);}'),

pdef('minimum-right-shifts', 'Minimum Right Shifts to Sort the Array', 'easy', 'minimumRightShifts',
    sig(['nums' => 'int[]'], 'int'),
    'One right shift moves the last element to the front. Return the minimum shifts to sort ascending, or -1 if impossible.',
    ['1 ≤ nums.length ≤ 100', 'all values distinct'],
    [t([[3, 4, 5, 1, 2]], 2, 1), t([[1, 3, 5]], 0, 1), t([[2, 1, 3]], -1), t([[5, 1, 2, 3, 4]], 4)],
    'function minimumRightShifts(nums){var n=nums.length,d=0,pos=-1;for(var i=0;i<n;i++)if(nums[i]>nums[(i+1)%n]){d++;pos=i;}if(d>1)return -1;if(d===0)return 0;return n-1-pos;}'),

pdef('max-pairs-up-to-limit', 'Count Pairs Whose Sum is Less than Target', 'easy', 'countPairsLT',
    sig(['nums' => 'int[]', 'target' => 'int'], 'int'),
    'Count pairs i < j where nums[i] + nums[j] < target.',
    ['1 ≤ nums.length ≤ 50', '-50 ≤ nums[i], target ≤ 50'],
    [t([[-1, 1, 2, 3, 1], 2], 3, 1), t([[-6, 2, 5, -2, -7, -1, 3], -2], 10, 1), t([[1, 2, 3], 100], 3)],
    'function countPairsLT(nums,target){var c=0;for(var i=0;i<nums.length;i++)for(var j=i+1;j<nums.length;j++)if(nums[i]+nums[j]<target)c++;return c;}'),

pdef('largest-element-after-merge', 'Largest Element in Array after Merge Operations', 'medium', 'maxArrayValue',
    sig(['nums' => 'int[]'], 'int'),
    'Scanning from the right, you may merge nums[i] into nums[i+1] whenever nums[i] ≤ nums[i+1] (adding them). Return the largest value reachable.',
    ['1 ≤ nums.length ≤ 10⁵', '1 ≤ nums[i] ≤ 10⁵'],
    [t([[2, 3, 7, 9, 3]], 21, 1), t([[5, 3, 3]], 11, 1), t([[1]], 1)],
    'function maxArrayValue(nums){var b=nums[nums.length-1];for(var i=nums.length-2;i>=0;i--){if(nums[i]<=b)b+=nums[i];else b=nums[i];}return b;}'),
];
