<?php
// Category: bits — XOR, masks, popcounts
return [
pdef('single-number', 'Single Number', 'easy', 'singleNumber',
    sig(['nums' => 'int[]'], 'int'),
    'Every element appears exactly twice except one. Find the one that appears once. Linear time, constant extra space — XOR makes this two lines.',
    ['1 ≤ nums.length ≤ 3·10⁴'],
    [t([[2, 2, 1]], 1, 1), t([[4, 1, 2, 1, 2]], 4, 1), t([[1]], 1), t([[-1, -1, -2]], -2)],
    'function singleNumber(nums){return nums.reduce(function(a,b){return a^b;},0);}'),

pdef('number-of-1-bits', 'Number of 1 Bits', 'easy', 'hammingWeight',
    sig(['n' => 'int'], 'int'),
    'Count the set bits (1s) in the 32-bit binary form of n. The n & (n−1) trick clears the lowest set bit per iteration.',
    ['0 ≤ n ≤ 2³² − 1'],
    [t([11], 3, 1), t([128], 1, 1), t([4294967293], 31), t([0], 0)],
    'function hammingWeight(n){n=n>>>0;var c=0;while(n){n&=n-1;c++;}return c;}'),

pdef('hamming-distance', 'Hamming Distance', 'easy', 'hammingDistance',
    sig(['x' => 'int', 'y' => 'int'], 'int'),
    'The Hamming distance is the number of bit positions where x and y differ.',
    ['0 ≤ x, y ≤ 2³¹ − 1'],
    [t([1, 4], 2, 1), t([3, 1], 1, 1), t([0, 0], 0), t([25, 30], 3)],
    'function hammingDistance(x,y){var n=(x^y)>>>0,c=0;while(n){n&=n-1;c++;}return c;}'),

pdef('reverse-bits', 'Reverse Bits', 'easy', 'reverseBits',
    sig(['n' => 'int'], 'int'),
    'Reverse the 32-bit binary representation of n and return the resulting unsigned integer.',
    ['0 ≤ n ≤ 2³² − 1'],
    [t([43261596], 964176192, 1), t([1], 2147483648, 1), t([0], 0), t([4294967295], 4294967295)],
    'function reverseBits(n){var r=0,i;for(i=0;i<32;i++){r=r*2+((n>>>i)&1);}return r;}'),

pdef('array-xor', 'XOR of All Elements', 'easy', 'xorAll',
    sig(['nums' => 'int[]'], 'int'),
    'Return the XOR of every element in the array (0 for an empty array). Useful warm-up for checksums and the XOR family.',
    ['0 ≤ nums.length ≤ 10⁴'],
    [t([[1, 2, 3]], 0, 1), t([[5]], 5, 1), t([[1, 1, 2, 2, 3]], 3), t([[]], 0)],
    'function xorAll(nums){var x=0,i;for(i=0;i<nums.length;i++){x^=nums[i];}return x;}'),

pdef('alternating-bits', 'Binary Number with Alternating Bits', 'easy', 'hasAlternatingBits',
    sig(['n' => 'int'], 'bool'),
    'Return true if the binary representation of n never has two adjacent equal bits (…1010 or …0101).',
    ['1 ≤ n ≤ 2³¹ − 1'],
    [t([5], true, 1), t([7], false, 1), t([10], true), t([3], false)],
    'function hasAlternatingBits(n){var x=(n^(n>>>1))>>>0;return (x&(x+1))===0&&x>0;}'),

pdef('binary-gap', 'Binary Gap', 'easy', 'binaryGap',
    sig(['n' => 'int'], 'int'),
    'Find the longest run of zeros strictly between two 1s in the binary form of n. If there is no such gap, return 0.',
    ['1 ≤ n ≤ 10⁹'],
    [t([529], 4, 1), t([9], 2, 1), t([15], 0), t([32], 0)],
    'function binaryGap(n){var best=0,cur=-1,i=0;while(n>0){if(n&1){if(cur>=0){best=Math.max(best,i-cur-1);}cur=i;}n>>>=1;i++;}return best;}'),

pdef('complement-base10', 'Complement of Base 10 Integer', 'easy', 'bitwiseComplement',
    sig(['n' => 'int'], 'int'),
    'Flip every bit in the binary form of n (with no leading zeros). For example 5 is 101, so the answer is 010 = 2. Complement of 0 is 1.',
    ['0 ≤ n ≤ 10⁹'],
    [t([5], 2, 1), t([10], 5, 1), t([0], 1), t([7], 0)],
    'function bitwiseComplement(n){if(n===0)return 1;var mask=0,x=n;while(x){mask=(mask<<1)|1;x>>>=1;}return (~n)>>>0&mask;}'),

pdef('convert-to-hex', 'Convert a Number to Hexadecimal', 'easy', 'toHex',
    sig(['num' => 'int'], 'str'),
    'Return the lowercase hexadecimal string of a 32-bit integer. Negative numbers print their two’s-complement 32-bit form.',
    ['-2³¹ ≤ num ≤ 2³¹ − 1'],
    [t([26], '1a', 1), t([-1], 'ffffffff', 1), t([255], 'ff'), t([0], '0')],
    'function toHex(n){return (n>>>0).toString(16);}'),

pdef('sum-two-integers', 'Sum of Two Integers (No +/−)', 'medium', 'getSum',
    sig(['a' => 'int', 'b' => 'int'], 'int'),
    'Add two integers WITHOUT using the + or − operators. XOR carries the sum bits; AND+(shift) carries the carry bits.',
    ['-1000 ≤ a, b ≤ 1000'],
    [t([1, 2], 3, 1), t([2, 3], 5, 1), t([-1, 1], 0), t([-12, -8], -20)],
    'function getSum(a,b){while(b!==0){var carry=(a&b)<<1;a=a^b;b=carry;}return a|0;}'),

pdef('power-of-four', 'Power of Four', 'easy', 'isPowerOfFour',
    sig(['n' => 'int'], 'bool'),
    'Return true if n is a power of four (1, 4, 16, 64, …). Bonus: do it without a loop — powers of four are powers of two whose single bit sits at an even position.',
    ['-2³¹ ≤ n ≤ 2³¹ − 1'],
    [t([16], true, 1), t([5], false, 1), t([1], true), t([8], false)],
    'function isPowerOfFour(n){return n>0&&(n&(n-1))===0&&(n&0x55555555)!==0;}'),

pdef('prime-set-bits', 'Prime Number of Set Bits in Range', 'medium', 'countPrimeSetBits',
    sig(['left' => 'int', 'right' => 'int'], 'int'),
    'Count the integers in the inclusive range [left, right] whose binary form has a PRIME number of set bits (popcount ∈ {2,3,5,7,11,13,17,19}).',
    ['1 ≤ left ≤ right ≤ 10⁶'],
    [t([6, 10], 4, 1), t([10, 15], 5, 1), t([1, 2], 0), t([3, 4], 1)],
    'function countPrimeSetBits(L,R){var primes={2:1,3:1,5:1,7:1,11:1,13:1,17:1,19:1},c=0,n,b;for(n=L;n<=R;n++){b=0;for(var x=n;x;x&=x-1)b++;if(primes[b])c++;}return c;}'),


pdef('find-kth-bit', 'Find Kth Bit in Nth Binary String', 'medium', 'findKthBit',
    sig(['n' => 'int', 'k' => 'int'], 'str'),
    'S1 = "0"; Si = S(i-1) + "1" + reverse(invert(S(i-1))). Return the kth character of Sn (1-based), as a 1-char string.',
    ['1 <= n <= 20'],
    [t([3, 1], '0', 1), t([4, 11], '1', 1), t([2, 3], '1'), t([1, 1], '0')],
    'function findKthBit(n,k){var s="0";for(var i=1;i<n;i++){var parts=s.split("").map(function(c){return c==="0"?"1":"0";}).reverse().join("");s=s+"1"+parts;}return s[k-1];}'),

pdef('max-xor-two', 'Maximum XOR of Two Numbers in an Array', 'medium', 'findMaximumXOR',
    sig(['nums' => 'int[]'], 'int'),
    'Return the maximum result of nums[i] XOR nums[j] over all pairs (i, j).',
    ['1 <= nums.length <= 2000'],
    [t([[3,10,5,25,2,8]], 28, 1), t([[14,70,53,83,49,91,36,80,92,51,66,70]], 127, 1), t([[0]], 0), t([[1,2]], 3)],
    'function findMaximumXOR(nums){var best=0;for(var i=0;i<nums.length;i++)for(var j=i;j<nums.length;j++)best=Math.max(best,nums[i]^nums[j]);return best;}'),

pdef('single-number-ii', 'Single Number II', 'medium', 'singleNumber2',
    sig(['nums' => 'int[]'], 'int'),
    'Every element appears three times except one, which appears once. Return it.',
    ['1 <= nums.length <= 30000'],
    [t([[2,2,3,2]], 3, 1), t([[0,1,0,1,0,1,99]], 99, 1), t([[5]], 5), t([[2,2,2,1]], 1)],
    'function singleNumber2(nums){var res=0;for(var bit=0;bit<32;bit++){var c=0;for(var n of nums)if(n&(1<<bit))c++;if(c%3)res|=1<<bit;}return res;}'),

pdef('single-number-iii', 'Single Number III', 'medium', 'singleNumber3',
    sig(['nums' => 'int[]'], 'int[]'),
    'Exactly two elements appear once; the rest appear twice. Return the two singletons ascending.',
    ['2 <= nums.length <= 30000'],
    [t([[1,2,1,3,2,5]], [3,5], 1), t([[-1,0]], [-1,0], 1), t([[0,1]], [0,1]), t([[5,7]], [5,7])],
    'function singleNumber3(nums){var x=0;for(var n of nums)x^=n;var bit=x&-x;var a=0,b=0;for(var n of nums){if(n&bit)a^=n;else b^=n;}return a<b?[a,b]:[b,a];}'),

pdef('subsets', 'Subsets', 'medium', 'subsets',
    sig(['nums' => 'int[]'], 'int[][]'),
    'Return all possible subsets (the power set), ordered by the standard bitmask enumeration 0, 1, ..., 2^n - 1.',
    ['1 <= nums.length <= 10'],
    [t([[1,2,3]], [[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]], 1), t([[0]], [[],[0]], 1), t([[1,2]], [[],[1],[2],[1,2]])],
    'function subsets(nums){var out=[];var n=nums.length;for(var mask=0;mask<1<<n;mask++){var s=[];for(var i=0;i<n;i++)if(mask&(1<<i))s.push(nums[i]);out.push(s);}return out;}'),

pdef('utf-8-validation', 'UTF-8 Validation', 'medium', 'validUtf8',
    sig(['data' => 'int[]'], 'bool'),
    'Each integer is a byte (0-255). Return true if the byte sequence is valid UTF-8.',
    ['1 <= data.length <= 20000'],
    [t([[197,130,1]], true, 1), t([[235,140,4]], false, 1), t([[255]], false), t([[10]], true)],
    'function validUtf8(data){var rem=0;for(var b of data){if(rem===0){if(b>=240&&b<=247)rem=3;else if(b>=224&&b<=239)rem=2;else if(b>=192&&b<=223)rem=1;else if(b>127)return false;}else{if(b<128||b>191)return false;rem--;}}return rem===0;}'),

pdef('total-hamming', 'Total Hamming Distance', 'medium', 'totalHammingDistance',
    sig(['nums' => 'int[]'], 'int'),
    'Return the sum of Hamming distances (differing bit positions) over every pair of values in the array.',
    ['1 <= nums.length <= 10000, values < 2^30'],
    [t([[4,14,2]], 6, 1), t([[4,14,4]], 4, 1), t([[1]], 0), t([[0,1]], 1)],
    'function totalHammingDistance(nums){var total=0;for(var bit=0;bit<31;bit++){var ones=0;for(var n of nums)if(n&(1<<bit))ones++;total+=ones*(nums.length-ones);}return total;}'),

pdef('min-flips-monotone', 'Flip String to Monotone Increasing', 'medium', 'minFlipsMonoIncr',
    sig(['s' => 'str'], 'int'),
    's is a binary string. Flip characters so it becomes all 0s followed by all 1s. Return the minimum flips.',
    ['1 <= s.length <= 100000'],
    [t(['00110'], 1, 1), t(['010110'], 2, 1), t(['00011000'], 2), t(['1'], 0)],
    'function minFlipsMonoIncr(s){var ones=0,flips=0;for(var c of s){if(c==="1")ones++;else flips=Math.min(flips+1,ones);}return flips;}'),

pdef('number-complement', 'Number Complement', 'easy', 'findComplement',
    sig(['num' => 'int'], 'int'),
    'Flip every bit in the binary representation of num (ignoring leading zeros). Return the result.',
    ['1 <= num <= 2^31'],
    [t([5], 2, 1), t([1], 0, 1), t([10], 5), t([7], 0)],
    'function findComplement(num){var mask=0,x=num;while(x>0){mask=(mask<<1)|1;x>>=1;}return num^mask;}'),

pdef('find-original-xor', 'Decode XORed Array', 'easy', 'findOriginalArray',
    sig(['encoded' => 'int[]', 'first' => 'int'], 'int[]'),
    'A hidden array arr was encoded as encoded[i] = arr[i] XOR arr[i+1]. Given encoded and arr[0] = first, recover arr.',
    ['encoded.length + 1 is the array length'],
    [t([[1,2,3], 1], [1,0,2,1], 1), t([[6], 4], [4,2], 1), t([[1], 1], [1,0])],
    'function findOriginalArray(encoded,first){var out=[first];for(var i=0;i<encoded.length;i++)out.push(out[i]^encoded[i]);return out;}'),

pdef('xor-pair-count', 'Count Pairs With XOR Equal to K', 'easy', 'xorPairCount',
    sig(['nums' => 'int[]', 'k' => 'int'], 'int'),
    'Count pairs of indices i < j with nums[i] XOR nums[j] === k.',
    ['1 <= nums.length <= 500'],
    [t([[1,2,3], 1], 1, 1), t([[1,1,1], 0], 3, 1), t([[5,4,1,3,7], 10], 0), t([[1,2,3,4], 0], 0)],
    'function xorPairCount(nums,k){var cnt=0;for(var i=0;i<nums.length;i++)for(var j=i+1;j<nums.length;j++)if((nums[i]^nums[j])===k)cnt++;return cnt;}'),

pdef('min-xor-pair', 'Minimum XOR of Any Pair', 'easy', 'minXORPair',
    sig(['nums' => 'int[]'], 'int'),
    'Return the smallest XOR value of any two elements in the array.',
    ['2 <= nums.length <= 500'],
    [t([[0,2,5,7]], 2, 1), t([[12,4,8,6]], 2, 1), t([[1,1]], 0), t([[3,7,3]], 0)],
    'function minXORPair(nums){var best=Infinity;for(var i=0;i<nums.length;i++)for(var j=i+1;j<nums.length;j++)best=Math.min(best,nums[i]^nums[j]);return best;}'),

pdef('swap-two-variables', 'Swap Two Values Without a Temp', 'easy', 'swapXor',
    sig(['a' => 'int', 'b' => 'int'], 'int[]'),
    'Swap a and b using only XOR operations (no temporary variable). Return [a, b] after the swap.',
    ['-1000 <= a, b <= 1000'],
    [t([5, 9], [9,5], 1), t([0, 7], [7,0], 1), t([4, 4], [4,4]), t([-3, 10], [10,-3])],
    'function swapXor(a,b){a=a^b;b=a^b;a=a^b;return [a,b];}'),

pdef('set-mismatch', 'Set Mismatch', 'easy', 'findErrorNums',
    sig(['nums' => 'int[]'], 'int[]'),
    'The array should hold 1..n but one value is duplicated, replacing another. Return [duplicated, missing].',
    ['2 <= nums.length <= 10000'],
    [t([[1,2,2,4]], [2,3], 1), t([[1,1]], [1,2], 1), t([[2,2]], [2,1]), t([[3,2,3,4,5]], [3,1])],
    'function findErrorNums(nums){var seen={},dup=-1;var sum=0;for(var n of nums){if(seen[n])dup=n;seen[n]=true;sum+=n;}var n2=nums.length;var expected=n2*(n2+1)/2;return [dup,expected-(sum-dup)];}'),

pdef('min-bit-flips', 'Minimum Bit Flips to Convert Number', 'easy', 'minBitFlips',
    sig(['start' => 'int', 'goal' => 'int'], 'int'),
    'Return the number of bit flips needed to convert start into goal.',
    ['0 <= start, goal <= 1000000000'],
    [t([10, 7], 3, 1), t([3, 4], 3, 1), t([1, 1], 0), t([82, 15], 5)],
    'function minBitFlips(start,goal){var x=start^goal,c=0;while(x){c+=x&1;x>>>=1;}return c;}'),

pdef('xor-range', 'XOR of a Range', 'easy', 'xorRange',
    sig(['a' => 'int', 'b' => 'int'], 'int'),
    'Return a XOR (a+1) XOR ... XOR b.',
    ['0 <= a <= b <= 1000000'],
    [t([3, 7], 3, 1), t([10, 12], 13, 1), t([5, 5], 5), t([0, 4], 4)],
    'function xorRange(a,b){function f(n){if(n<0)return 0;switch(n%4){case 0:return n;case 1:return 1;case 2:return n+1;default:return 0;}}return f(b)^f(a-1);}'),

pdef('gray-code', 'Gray Code', 'medium', 'grayCode',
    sig(['n' => 'int'], 'int[]'),
    'Return an n-bit gray code sequence (the canonical reflected form starting at 0).',
    ['0 <= n <= 16'],
    [t([2], [0,1,3,2], 1), t([1], [0,1], 1), t([0], [0]), t([3], [0,1,3,2,6,7,5,4])],
    'function grayCode(n){var out=[];for(var i=0;i<1<<n;i++)out.push(i^(i>>1));return out;}'),

pdef('even-odd-bits', 'Number of Even and Odd Bits', 'easy', 'evenOddBit',
    sig(['n' => 'int'], 'int[]'),
    'Count the set bits at even and odd indices (LSB is index 0) of n. Return [evenCount, oddCount].',
    ['0 <= n <= 1000'],
    [t([50], [1,2], 1), t([2], [0,1], 1), t([1], [1,0]), t([0], [0,0])],
    'function evenOddBit(n){var even=0,odd=0,i=0;while(n>0){if(n&1){if(i%2===0)even++;else odd++;}n>>=1;i++;}return [even,odd];}'),

pdef('apply-ops-double', 'Apply Operations to an Array', 'easy', 'applyOperations',
    sig(['nums' => 'int[]'], 'int[]'),
    'For i = 0..n-2: if nums[i] === nums[i+1], double nums[i] and zero nums[i+1]. Then shift all zeros to the end. Return the array.',
    ['2 <= nums.length <= 2000'],
    [t([[1,2,2,1,1,0]], [1,4,2,0,0,0], 1), t([[0,1]], [1,0], 1), t([[1]], [1]), t([[2,2]], [4,0])],
    'function applyOperations(nums){for(var i=0;i<nums.length-1;i++)if(nums[i]===nums[i+1]){nums[i]*=2;nums[i+1]=0;}var out=nums.filter(function(x){return x!==0;});while(out.length<nums.length)out.push(0);return out;}'),

pdef('sort-integers-bits', 'Sort Integers by The Number of 1 Bits', 'easy', 'sortByBits',
    sig(['arr' => 'int[]'], 'int[]'),
    'Sort ascending by the number of 1 bits, then by numeric value. Return the sorted array.',
    ['1 <= arr.length <= 500'],
    [t([[0,1,2,3,4,5,6,7,8]], [0,1,2,4,8,3,5,6,7], 1), t([[1024,512,256,128,64,32,16,8,4,2,1]], [1,2,4,8,16,32,64,128,256,512,1024], 1), t([[7,3,5]], [3,5,7]), t([[1]], [1])],
    'function sortByBits(arr){return arr.slice().sort(function(x,y){function p(v){var c=0;while(v){c+=v&1;v>>=1;}return c;}return p(x)-p(y)||x-y;});}'),

pdef('bitwise-and-range', 'Bitwise AND of Numbers Range', 'medium', 'rangeBitwiseAnd',
    sig(['m' => 'int', 'n' => 'int'], 'int'),
    'Return m AND (m+1) AND ... AND n.',
    ['0 <= m <= n <= 2^31 - 1'],
    [t([5, 7], 4, 1), t([0, 0], 0, 1), t([1, 2147483647], 0), t([6, 7], 6)],
    'function rangeBitwiseAnd(m,n){var shift=0;while(m<n){m>>=1;n>>=1;shift++;}return m<<shift;}'),

pdef('concatenation-binary', 'Concatenation of Consecutive Binary Numbers', 'medium', 'concatenatedBinary',
    sig(['n' => 'int'], 'int'),
    'Concatenate the binary strings of 1, 2, ..., n to form a big binary number. Return its value modulo 10^9 + 7.',
    ['1 <= n <= 100000'],
    [t([1], 1, 1), t([2], 6, 1), t([3], 27), t([12], 505379714)],
    'function concatenatedBinary(n){var M=1000000007;var res=0,len=0;for(var i=1;i<=n;i++){if((i&(i-1))===0)len++;res=(res*Math.pow(2,len)+i)%M;}return res;}'),

pdef('count-total-bits', 'Count Total Set Bits', 'easy', 'countTotalBits',
    sig(['n' => 'int'], 'int'),
    'Count the total number of set bits in the binary representations of every number from 0 to n.',
    ['0 <= n <= 10000'],
    [t([6], 9, 1), t([10], 17, 1), t([0], 0), t([3], 4)],
    'function countTotalBits(n){var total=0;for(var i=1;i<=n;i++){var x=i,c=0;while(x){c+=x&1;x>>=1;}total+=c;}return total;}'),

pdef('k-th-symbol-grammar', 'K-th Symbol in Grammar', 'medium', 'kthGrammar',
    sig(['n' => 'int', 'k' => 'int'], 'int'),
    'Row 1 is "0"; each 0 becomes 01 and each 1 becomes 10. Return the kth symbol (1-based) in row n.',
    ['1 <= k <= 2^(n-1)'],
    [t([1, 1], 0, 1), t([2, 1], 0, 1), t([2, 2], 1), t([4, 5], 1)],
    'function kthGrammar(n,k){if(n===1)return 0;var parent=kthGrammar(n-1,Math.ceil(k/2));return k%2===1?parent:1-parent;}'),

pdef('subset-xor-sum', 'Sum of All Subset XOR Totals', 'easy', 'subsetXORSum',
    sig(['nums' => 'int[]'], 'int'),
    'Compute the XOR total of every subset of nums and return the sum of those totals.',
    ['1 <= nums.length <= 12'],
    [t([[1,3]], 6, 1), t([[5,1,6]], 28, 1), t([[3,4,5,6,7,8]], 480), t([[1]], 1)],
    'function subsetXORSum(nums){var total=0;for(var n of nums)total|=n;return total<<(nums.length-1);}'),

];
