<?php
// Category: dp — memoization and bottom-up tables, from Fibonacci to edit distance
return [
pdef('climbing-stairs', 'Climbing Stairs', 'easy', 'climbStairs',
    sig(['n' => 'int'], 'int'),
    'You climb 1 or 2 steps at a time. In how many distinct ways can you reach step n?',
    ['1 ≤ n ≤ 45'],
    [t([2], 2, 1), t([3], 3, 1), t([5], 8), t([1], 1), t([10], 89), t([45], 1836311903)],
    'function climbStairs(n){var a=1,b=1,i;for(i=0;i<n;i++){var t=a+b;a=b;b=t;}return a;}'),

pdef('max-subarray', 'Maximum Subarray', 'medium', 'maxSubArray',
    sig(['nums' => 'int[]'], 'int'),
    'Find the contiguous subarray with the largest sum and return that sum. Kadane’s algorithm does it in one pass.',
    ['1 ≤ nums.length ≤ 10⁵'],
    [t([[-2, 1, -3, 4, -1, 2, 1, -5, 4]], 6, 1), t([[1]], 1, 1), t([[5, 4, -1, 7, 8]], 23), t([[-1, -2, -3]], -1)],
    'function maxSubArray(nums){var best=nums[0],cur=nums[0],i;for(i=1;i<nums.length;i++){cur=Math.max(nums[i],cur+nums[i]);best=Math.max(best,cur);}return best;}',
    'Once O(n) feels easy, try divide and conquer.'),

pdef('fibonacci', 'Fibonacci Number', 'easy', 'fib',
    sig(['n' => 'int'], 'int'),
    'Return the nth Fibonacci number: fib(0)=0, fib(1)=1, fib(n)=fib(n-1)+fib(n-2).',
    ['0 ≤ n ≤ 30'],
    [t([2], 1, 1), t([4], 3, 1), t([0], 0), t([10], 55)],
    'function fib(n){var a=0,b=1,i;for(i=0;i<n;i++){var t=a+b;a=b;b=t;}return a;}'),

pdef('tribonacci', 'N-th Tribonacci Number', 'easy', 'tribonacci',
    sig(['n' => 'int'], 'int'),
    'Tribonacci: T(0)=0, T(1)=1, T(2)=1, and T(n)=T(n-1)+T(n-2)+T(n-3). Return T(n).',
    ['0 ≤ n ≤ 37'],
    [t([4], 4, 1), t([25], 1389537, 1), t([0], 0), t([1], 1)],
    'function tribonacci(n){var a=0,b=1,c=1,i;if(n===0)return 0;for(i=3;i<=n;i++){var t=a+b+c;a=b;b=c;c=t;}return c;}'),

pdef('min-cost-stairs', 'Min Cost Climbing Stairs', 'easy', 'minCostClimbingStairs',
    sig(['cost' => 'int[]'], 'int'),
    'cost[i] is the toll for stepping on stair i. You may start at index 0 or 1 and climb 1 or 2 steps per move. Return the minimum cost to reach the top (beyond the last index).',
    ['2 ≤ cost.length ≤ 1000'],
    [t([[10, 15, 20]], 15, 1), t([[1, 100, 1, 1, 1, 100, 1, 1, 100, 1]], 6, 1), t([[0, 0, 0]], 0), t([[5, 5, 5]], 5)],
    'function minCostClimbingStairs(cost){var a=0,b=0,i;for(i=2;i<=cost.length;i++){var c=Math.min(a+cost[i-2],b+cost[i-1]);a=b;b=c;}return b;}'),

pdef('house-robber', 'House Robber', 'medium', 'rob',
    sig(['nums' => 'int[]'], 'int'),
    'You are a picky burglar: you cannot rob two ADJACENT houses without tripping the alarm. nums[i] is the loot in house i. Return the maximum you can steal.',
    ['0 ≤ nums.length ≤ 100'],
    [t([[1, 2, 3, 1]], 4, 1), t([[2, 7, 9, 3, 1]], 12, 1), t([[5]], 5), t([[]], 0)],
    'function rob(nums){var take=0,skip=0,i;for(i=0;i<nums.length;i++){var t=Math.max(skip+nums[i],take);skip=take;take=t;}return take;}'),

pdef('unique-paths', 'Unique Paths', 'medium', 'uniquePaths',
    sig(['m' => 'int', 'n' => 'int'], 'int'),
    'A robot on an m×n grid starts top-left and may move only RIGHT or DOWN. How many distinct paths reach the bottom-right corner?',
    ['1 ≤ m, n ≤ 100', 'answer ≤ 2·10⁹'],
    [t([3, 7], 28, 1), t([3, 2], 3, 1), t([1, 1], 1), t([1, 10], 1)],
    'function uniquePaths(m,n){var row=new Array(n).fill(1),i,j;for(i=1;i<m;i++){for(j=1;j<n;j++){row[j]+=row[j-1];}}return row[n-1];}'),

pdef('min-path-sum', 'Minimum Path Sum', 'medium', 'minPathSum',
    sig(['grid' => 'int[][]'], 'int'),
    'Move only right or down through a grid of non-negative costs, from top-left to bottom-right. Return the minimum total cost of any such path.',
    ['1 ≤ rows, cols ≤ 200'],
    [t([[[1, 3, 1], [1, 5, 1], [4, 2, 1]]], 7, 1), t([[[1, 2, 3], [4, 5, 6]]], 12, 1), t([[[5]]], 5), t([[[1, 2], [1, 1]]], 3)],
    'function minPathSum(g){var R=g.length,C=g[0].length,i,j;for(i=0;i<R;i++){for(j=0;j<C;j++){if(i===0&&j===0)continue;var up=i>0?g[i-1][j]:Infinity,left=j>0?g[i][j-1]:Infinity;g[i][j]+=Math.min(up,left);}}return g[R-1][C-1];}'),

pdef('coin-change', 'Coin Change', 'medium', 'coinChange',
    sig(['coins' => 'int[]', 'amount' => 'int'], 'int'),
    'Given coin denominations and an amount, return the FEWEST coins needed to make exactly that amount, or -1 if impossible. Coins are unlimited.',
    ['1 ≤ coins.length ≤ 12', '0 ≤ amount ≤ 10⁴'],
    [t([[1, 2, 5], 11], 3, 1), t([[2], 3], -1, 1), t([[1], 0], 0), t([[1, 2, 5, 10], 27], 4)],
    'function coinChange(coins,amount){var INF=amount+1,dp=new Array(INF).fill(INF),a,d;dp[0]=0;for(a=1;a<=amount;a++){for(d=0;d<coins.length;d++){if(coins[d]<=a)dp[a]=Math.min(dp[a],dp[a-coins[d]]+1);}}return dp[amount]>=INF?-1:dp[amount];}'),

pdef('lis', 'Longest Increasing Subsequence', 'medium', 'lengthOfLIS',
    sig(['nums' => 'int[]'], 'int'),
    'Return the length of the longest strictly increasing subsequence (elements keep their original order but need not be contiguous).',
    ['1 ≤ nums.length ≤ 2500'],
    [t([[10, 9, 2, 5, 3, 7, 101, 18]], 4, 1), t([[0, 1, 0, 3, 2, 3]], 4, 1), t([[7, 7, 7, 7]], 1), t([[1]], 1)],
    'function lengthOfLIS(nums){var tails=[],i,lo,hi,mid;for(i=0;i<nums.length;i++){lo=0;hi=tails.length;while(lo<hi){mid=(lo+hi)>>1;if(tails[mid]<nums[i])lo=mid+1;else hi=mid;}tails[lo]=nums[i];}return tails.length;}'),

pdef('word-break', 'Word Break', 'medium', 'wordBreak',
    sig(['s' => 'str', 'wordDict' => 'str[]'], 'bool'),
    'Return true if s can be segmented into space-free pieces that each appear in wordDict. Dictionary words may be reused.',
    ['1 ≤ s.length ≤ 300', 'dictionary words are non-empty'],
    [t(['leetcode', ['leet', 'code']], true, 1), t(['applepenapple', ['apple', 'pen']], true, 1),
     t(['catsandog', ['cats', 'dog', 'sand', 'and', 'cat']], false), t(['aaaaaaa', ['aaaa', 'aa']], false)],
    'function wordBreak(s,dict){var set=new Set(dict),ok=new Array(s.length+1).fill(false),i,j;ok[0]=true;for(i=1;i<=s.length;i++){for(j=0;j<i;j++){if(ok[j]&&set.has(s.slice(j,i))){ok[i]=true;break;}}}return ok[s.length];}'),

pdef('decode-ways', 'Decode Ways', 'medium', 'numDecodings',
    sig(['s' => 'str'], 'int'),
    'A=1, B=2, …, Z=26. Given a digit string, count how many ways it can be decoded into letters. Watch out for zeros: "06" is not valid.',
    ['1 ≤ s.length ≤ 100'],
    [t(['12'], 2, 1), t(['226'], 3, 1), t(['06'], 0), t(['10'], 1)],
    'function numDecodings(s){var prev2=1,prev1=s[0]==="0"?0:1,i;for(i=2;i<=s.length;i++){var cur=0,d=+s[i-1],dd=+s.slice(i-2,i);if(d>=1)cur+=prev1;if(dd>=10&&dd<=26)cur+=prev2;prev2=prev1;prev1=cur;}return prev1;}'),

pdef('edit-distance', 'Edit Distance', 'hard', 'minDistance',
    sig(['word1' => 'str', 'word2' => 'str'], 'int'),
    'Return the minimum number of single-character operations — insert, delete, replace — needed to turn word1 into word2. The DP classic.',
    ['0 ≤ word lengths ≤ 500'],
    [t(['horse', 'ros'], 3, 1), t(['intention', 'execution'], 5, 1), t(['', 'a'], 1), t(['abc', 'abc'], 0)],
    'function minDistance(a,b){var m=a.length,n=b.length,dp=[],i,j;for(i=0;i<=m;i++){dp[i]=new Array(n+1);dp[i][0]=i;}for(j=0;j<=n;j++)dp[0][j]=j;for(i=1;i<=m;i++){for(j=1;j<=n;j++){dp[i][j]=a[i-1]===b[j-1]?dp[i-1][j-1]:1+Math.min(dp[i-1][j],dp[i][j-1],dp[i-1][j-1]);}}return dp[m][n];}'),


pdef("pascal-triangle", "Pascal's Triangle", "easy", "pascalTriangle",
    sig(["numRows" => "int"], "int[][]"),
    "Return the first numRows rows of Pascal's triangle.",
    ["1 <= numRows <= 30"],
    [t([5], [[1],[1,1],[1,2,1],[1,3,3,1],[1,4,6,4,1]], 1), t([1], [[1]], 1), t([2], [[1],[1,1]]), t([4], [[1],[1,1],[1,2,1],[1,3,3,1]])],
    'function pascalTriangle(numRows){var r=[];for(var i=0;i<numRows;i++){var row=[1];for(var j=1;j<i;j++)row.push(r[i-1][j-1]+r[i-1][j]);if(i>0)row.push(1);r.push(row);}return r;}'),

pdef("pascal-row", "Pascal's Triangle Row", "easy", "pascalRow",
    sig(["rowIndex" => "int"], "int[]"),
    "Return the rowIndex-th (0-based) row of Pascal's triangle.",
    ["0 <= rowIndex <= 33"],
    [t([3], [1,3,3,1], 1), t([0], [1], 1), t([1], [1,1]), t([4], [1,4,6,4,1])],
    'function pascalRow(rowIndex){var row=[1];for(var i=1;i<=rowIndex;i++){var nx=[1];for(var j=1;j<i;j++)nx.push(row[j-1]+row[j]);nx.push(1);row=nx;}return row;}'),

pdef('divisor-game', 'Divisor Game', 'easy', 'divisorGame',
    sig(['n' => 'int'], 'bool'),
    'Two players alternate replacing n with n - x where x divides n and 0 < x < n. The player who cannot move loses. Alice starts; return true if she wins with optimal play.',
    ['1 <= n <= 1000'],
    [t([2], true, 1), t([3], false, 1), t([5], false), t([100], true)],
    'function divisorGame(n){return n%2===0;}'),

pdef('count-bits', 'Counting Bits', 'easy', 'countBits',
    sig(['n' => 'int'], 'int[]'),
    'Return an array where element i is the number of 1 bits in the binary form of i, for every 0 <= i <= n.',
    ['0 <= n <= 100000'],
    [t([2], [0,1,1], 1), t([5], [0,1,1,2,1,2], 1), t([0], [0]), t([8], [0,1,1,2,1,2,2,3,1])],
    'function countBits(n){var r=[0];for(var i=1;i<=n;i++)r.push(r[i>>1]+(i&1));return r;}'),

pdef('best-time-stock-cooldown', 'Best Time to Buy and Sell Stock with Cooldown', 'medium', 'maxProfitCooldown',
    sig(['prices' => 'int[]'], 'int'),
    'Unlimited transactions, but after you sell you must wait one day before buying again. Return the maximum profit.',
    ['1 <= prices.length <= 5000'],
    [t([[1,2,3,0,2]], 3, 1), t([[1]], 0, 1), t([[1,2]], 1), t([[2,1,4]], 3)],
    'function maxProfitCooldown(prices){var held=-Infinity,sold=0,rest=0;for(var p of prices){var ph=held,ps=sold;held=Math.max(ph,rest-p);sold=ph+p;rest=Math.max(rest,ps);}return Math.max(sold,rest);}'),

pdef('house-robber-ii', 'House Robber II', 'medium', 'houseRobber2',
    sig(['nums' => 'int[]'], 'int'),
    'Houses sit in a circle, so the first and last are adjacent. Rob non-adjacent houses for the maximum total.',
    ['1 <= nums.length <= 100'],
    [t([[2,3,2]], 3, 1), t([[1,2,3,1]], 4, 1), t([[1,2,3]], 3), t([[5]], 5)],
    'function houseRobber2(nums){function rob(a){var p=0,c=0;for(var x of a){var t=Math.max(c,p+x);p=c;c=t;}return c;}if(nums.length===1)return nums[0];return Math.max(rob(nums.slice(0,-1)),rob(nums.slice(1)));}'),

pdef('delete-and-earn', 'Delete and Earn', 'medium', 'deleteAndEarn',
    sig(['nums' => 'int[]'], 'int'),
    'Taking number x earns x points but deletes every x-1 and x+1 from the array. Return the maximum points.',
    ['1 <= nums.length <= 20000', '1 <= nums[i] <= 10000'],
    [t([[3,4,2]], 6, 1), t([[2,2,3,3,3,4]], 9, 1), t([[1]], 1), t([[1,3]], 4)],
    'function deleteAndEarn(nums){var pts={},mx=0;for(var n of nums){pts[n]=(pts[n]||0)+n;if(n>mx)mx=n;}var prev=0,cur=0;for(var k=1;k<=mx;k++){var t=Math.max(cur,prev+(pts[k]||0));prev=cur;cur=t;}return cur;}'),

pdef('longest-pal-subseq', 'Longest Palindromic Subsequence', 'medium', 'longestPalindromeSubseq',
    sig(['s' => 'str'], 'int'),
    'Return the length of the longest palindromic subsequence of s.',
    ['1 <= s.length <= 1000'],
    [t(['bbbab'], 4, 1), t(['cbbd'], 2, 1), t(['a'], 1), t(['abcdea'], 3)],
    'function longestPalindromeSubseq(s){var n=s.length;var dp=[];for(var i=0;i<n;i++){dp.push(new Array(n).fill(0));dp[i][i]=1;}for(var len=2;len<=n;len++)for(var a=0;a+len-1<n;a++){var b=a+len-1;dp[a][b]=s[a]===s[b]?dp[a+1][b-1]+2:Math.max(dp[a+1][b],dp[a][b-1]);}return dp[0][n-1];}'),

pdef('min-pal-cuts', 'Palindrome Partitioning II', 'hard', 'minCut',
    sig(['s' => 'str'], 'int'),
    'Return the minimum number of cuts needed so every piece of s is a palindrome.',
    ['1 <= s.length <= 2000'],
    [t(['aab'], 1, 1), t(['a'], 0, 1), t(['ab'], 1), t(['abba'], 0)],
    'function minCut(s){var n=s.length;var cut=[];for(var i=0;i<=n;i++)cut.push(i-1);for(var i=0;i<n;i++){for(var r=0;i-r>=0&&i+r<n&&s[i-r]===s[i+r];r++)cut[i+r+1]=Math.min(cut[i+r+1],cut[i-r]+1);for(var r2=0;i-r2>=0&&i+r2+1<n&&s[i-r2]===s[i+r2+1];r2++)cut[i+r2+2]=Math.min(cut[i+r2+2],cut[i-r2]+1);}return cut[n];}'),

pdef('unique-paths-ii', 'Unique Paths II', 'medium', 'uniquePathsWithObstacles',
    sig(['grid' => 'int[][]'], 'int'),
    'Move only right or down from the top-left to the bottom-right of a grid where 1 marks an obstacle. Count distinct paths.',
    ['1 <= rows, cols <= 100'],
    [t([[[0,0,0],[0,1,0],[0,0,0]]], 2, 1), t([[[0,1],[0,0]]], 1, 1), t([[[1]]], 0), t([[[0]]], 1)],
    'function uniquePathsWithObstacles(grid){var m=grid.length,n=grid[0].length;var dp=[];for(var i=0;i<m;i++){dp.push([]);for(var j=0;j<n;j++){if(grid[i][j]===1){dp[i].push(0);continue;}if(i===0&&j===0)dp[i].push(1);else dp[i].push((i>0?dp[i-1][j]:0)+(j>0?dp[i][j-1]:0));}}return dp[m-1][n-1];}'),

pdef('maximal-square', 'Maximal Square', 'medium', 'maximalSquare',
    sig(['matrix' => 'int[][]'], 'int'),
    'The matrix holds only 0 and 1. Return the area of the largest square containing only 1s.',
    ['1 <= rows, cols <= 300'],
    [t([[[1,0,1,0,0],[1,0,1,1,1],[1,1,1,1,1],[1,0,0,1,0]]], 4, 1), t([[[0,1],[1,0]]], 1, 1), t([[[0]]], 0), t([[[1,1],[1,1]]], 4)],
    'function maximalSquare(m){var rows=m.length,cols=m[0].length,best=0;var dp=[];for(var i=0;i<rows;i++){dp.push(new Array(cols).fill(0));for(var j=0;j<cols;j++){if(m[i][j]===1){dp[i][j]=1+Math.min(i>0?dp[i-1][j]:0,j>0?dp[i][j-1]:0,(i>0&&j>0)?dp[i-1][j-1]:0);if(dp[i][j]>best)best=dp[i][j];}}}return best*best;}'),

pdef('coin-change-2', 'Coin Change II', 'medium', 'change',
    sig(['amount' => 'int', 'coins' => 'int[]'], 'int'),
    'Count combinations of the given coins (unlimited supply) that total exactly amount. Order does not matter.',
    ['0 <= amount <= 5000', '1 <= coins.length <= 300'],
    [t([5, [1,2,5]], 4, 1), t([3, [2]], 0, 1), t([10, [10]], 1), t([10, [2,5,3,6]], 5)],
    'function change(amount,coins){var dp=new Array(amount+1).fill(0);dp[0]=1;for(var c of coins)for(var a=c;a<=amount;a++)dp[a]+=dp[a-c];return dp[amount];}'),

pdef('combination-sum-iv', 'Combination Sum IV', 'medium', 'combinationSum4',
    sig(['nums' => 'int[]', 'target' => 'int'], 'int'),
    'Using values from nums any number of times, count ordered sequences that sum to target.',
    ['1 <= nums.length <= 200', '1 <= target <= 1000'],
    [t([[1,2,3], 4], 7, 1), t([[9], 3], 0, 1), t([[1], 1], 1), t([[1,2], 3], 3)],
    'function combinationSum4(nums,target){var dp=new Array(target+1).fill(0);dp[0]=1;for(var t=1;t<=target;t++)for(var n of nums)if(t>=n)dp[t]+=dp[t-n];return dp[target];}'),

pdef('partition-equal-subset', 'Partition Equal Subset Sum', 'medium', 'canPartition',
    sig(['nums' => 'int[]'], 'bool'),
    'Return true if the array can be split into two subsets with equal sums.',
    ['1 <= nums.length <= 200', '1 <= nums[i] <= 100'],
    [t([[1,5,11,5]], true, 1), t([[1,2,3,5]], false, 1), t([[1,1]], true), t([[2]], false)],
    'function canPartition(nums){var s=0;for(var n of nums)s+=n;if(s%2)return false;var h=s/2,dp=new Array(h+1).fill(false);dp[0]=true;for(var n of nums)for(var v=h;v>=n;v--)if(dp[v-n])dp[v]=true;return dp[h];}'),

pdef('target-sum', 'Target Sum', 'medium', 'findTargetSumWays',
    sig(['nums' => 'int[]', 'target' => 'int'], 'int'),
    'Put + or - before every value so the expression equals target. Count ways.',
    ['1 <= nums.length <= 20'],
    [t([[1,1,1,1,1], 3], 5, 1), t([[1], 1], 1, 1), t([[0,1], 1], 2), t([[1,2,3], 0], 2)],
    'function findTargetSumWays(nums,target){var s=0;for(var n of nums)s+=n;if(Math.abs(target)>s||(s+target)%2!==0)return 0;var p=(s+target)/2;var dp=new Array(p+1).fill(0);dp[0]=1;for(var n of nums)for(var v=p;v>=n;v--)dp[v]+=dp[v-n];return dp[p];}'),

pdef('lcs', 'Longest Common Subsequence', 'medium', 'longestCommonSubsequence',
    sig(['a' => 'str', 'b' => 'str'], 'int'),
    'Return the length of the longest subsequence common to both strings.',
    ['1 <= a.length, b.length <= 1000'],
    [t(['abcde', 'ace'], 3, 1), t(['abc', 'abc'], 3, 1), t(['abc', 'def'], 0), t(['bl', 'yby'], 1)],
    'function longestCommonSubsequence(a,b){var m=a.length,n=b.length;var dp=[];for(var i=0;i<=m;i++)dp.push(new Array(n+1).fill(0));for(var i=1;i<=m;i++)for(var j=1;j<=n;j++)dp[i][j]=a[i-1]===b[j-1]?dp[i-1][j-1]+1:Math.max(dp[i-1][j],dp[i][j-1]);return dp[m][n];}'),

pdef('knapsack-01', '0/1 Knapsack', 'medium', 'knapsack',
    sig(['weights' => 'int[]', 'values' => 'int[]', 'capacity' => 'int'], 'int'),
    'Each item may be taken at most once. Return the maximum total value that fits in the capacity.',
    ['weights.length === values.length <= 100'],
    [t([[1,3,4,5], [1,4,5,7], 7], 9, 1), t([[1,2,3], [6,10,12], 5], 22, 1), t([[4], [2], 3], 0), t([[2,2], [3,3], 4], 6)],
    'function knapsack(weights,values,capacity){var dp=new Array(capacity+1).fill(0);for(var i=0;i<weights.length;i++)for(var v=capacity;v>=weights[i];v--)dp[v]=Math.max(dp[v],dp[v-weights[i]]+values[i]);return dp[capacity];}'),

pdef('longest-arithmetic-subseq', 'Longest Arithmetic Subsequence', 'medium', 'longestArithSeqLength',
    sig(['nums' => 'int[]'], 'int'),
    'Return the length of the longest subsequence whose consecutive differences are all equal.',
    ['2 <= nums.length <= 1000'],
    [t([[3,6,9,12]], 4, 1), t([[9,4,7,2,10]], 3, 1), t([[20,1,15,3,10,5,8]], 4), t([[2,2,2]], 3)],
    'function longestArithSeqLength(nums){var n=nums.length,best=2;var dp=[];for(var i=0;i<n;i++)dp.push({});for(var i=0;i<n;i++)for(var j=0;j<i;j++){var d=nums[i]-nums[j];dp[i][d]=(dp[j][d]||1)+1;if(dp[i][d]>best)best=dp[i][d];}return best;}'),

pdef('min-falling-path', 'Minimum Falling Path Sum', 'medium', 'minFallingPathSum',
    sig(['matrix' => 'int[][]'], 'int'),
    'A falling path picks one cell per row, moving at most one column sideways each step. Return the minimum path sum.',
    ['n x n matrix, 1 <= n <= 100'],
    [t([[[2,1,3],[6,5,4],[7,8,9]]], 13, 1), t([[[-19,57],[-40,-5]]], -59, 1), t([[[5]]], 5), t([[[1,2],[3,4]]], 4)],
    'function minFallingPathSum(m){var n=m.length;var prev=m[0].slice();for(var i=1;i<n;i++){var cur=[];for(var j=0;j<n;j++)cur.push(m[i][j]+Math.min(prev[j],j>0?prev[j-1]:Infinity,j<n-1?prev[j+1]:Infinity));prev=cur;}return Math.min.apply(null,prev);}'),

pdef('triangle-min-path', 'Triangle Minimum Path Sum', 'medium', 'minimumTotal',
    sig(['tri' => 'int[][]'], 'int'),
    'From top to bottom of the triangle, each step moves to an adjacent number on the row below. Return the minimum path sum.',
    ['1 <= tri.length <= 200'],
    [t([[[2],[3,4],[6,5,7],[4,1,8,3]]], 11, 1), t([[[-10]]], -10, 1), t([[[1],[2,3]]], 3), t([[[2],[3,4],[6,5,1]]], 7)],
    'function minimumTotal(tri){var prev=tri[tri.length-1].slice();for(var i=tri.length-2;i>=0;i--){var cur=[];for(var j=0;j<=i;j++)cur.push(tri[i][j]+Math.min(prev[j],prev[j+1]));prev=cur;}return prev[0];}'),

pdef('longest-turbulent', 'Longest Turbulent Subarray', 'medium', 'maxTurbulenceSize',
    sig(['arr' => 'int[]'], 'int'),
    'A subarray is turbulent when comparisons between neighbours strictly alternate direction. Return its maximum length.',
    ['1 <= arr.length <= 40000'],
    [t([[9,4,2,10,7,8,8,1,9]], 5, 1), t([[4,8,12,16]], 2, 1), t([[0,1,1,0,1,0,1,1,0,0]], 5), t([[100]], 1)],
    'function maxTurbulenceSize(a){var n=a.length;if(n===1)return 1;var best=1,cur=1;function cmp(x,y){return x<y?1:x>y?-1:0;}for(var i=1;i<n;i++){var c=cmp(a[i-1],a[i]);if(i>=2){var p=cmp(a[i-2],a[i-1]);cur=(c!==0&&p!==0&&c!==p)?cur+1:(c!==0?2:1);}else cur=c!==0?2:1;if(cur>best)best=cur;}return best;}'),

pdef('max-length-repeated-subarray', 'Maximum Length of Repeated Subarray', 'medium', 'findLength',
    sig(['a' => 'int[]', 'b' => 'int[]'], 'int'),
    'Return the maximum length of a subarray that appears in both arrays.',
    ['1 <= a.length, b.length <= 1000'],
    [t([[1,2,3,2,1], [3,2,1,4,7]], 3, 1), t([[0,0,0,0,0], [0,0,0,0,0]], 5, 1), t([[1,2,3], [4,5,6]], 0), t([[1,0,1,0,1], [1,0,1,0,1]], 5)],
    'function findLength(a,b){var m=a.length,n=b.length,best=0,prev=new Array(n+1).fill(0);for(var i=1;i<=m;i++){var cur=new Array(n+1).fill(0);for(var j=1;j<=n;j++)if(a[i-1]===b[j-1]){cur[j]=prev[j-1]+1;if(cur[j]>best)best=cur[j];}prev=cur;}return best;}'),

pdef('min-ascii-delete-sum', 'Minimum ASCII Delete Sum for Two Strings', 'medium', 'minimumDeleteSum',
    sig(['s1' => 'str', 's2' => 'str'], 'int'),
    'Delete characters from both strings to make them equal, minimizing the sum of ASCII codes deleted.',
    ['1 <= s1.length, s2.length <= 1000'],
    [t(['sea', 'eat'], 231, 1), t(['delete', 'leet'], 403, 1), t(['a', 'b'], 195), t(['abc', 'abc'], 0)],
    'function minimumDeleteSum(s1,s2){var m=s1.length,n=s2.length,dp=[],i,j;for(i=0;i<=m;i++)dp.push(new Array(n+1).fill(0));for(i=1;i<=m;i++)dp[i][0]=dp[i-1][0]+s1.charCodeAt(i-1);for(j=1;j<=n;j++)dp[0][j]=dp[0][j-1]+s2.charCodeAt(j-1);for(i=1;i<=m;i++)for(j=1;j<=n;j++)dp[i][j]=s1[i-1]===s2[j-1]?dp[i-1][j-1]:Math.min(dp[i-1][j]+s1.charCodeAt(i-1),dp[i][j-1]+s2.charCodeAt(j-1));return dp[m][n];}'),

pdef('predict-winner', 'Predict the Winner', 'medium', 'predictTheWinner',
    sig(['nums' => 'int[]'], 'bool'),
    'Two players alternate taking either end value; each plays to maximize their own total. Return true if the first player can score at least as much as the second.',
    ['1 <= nums.length <= 20'],
    [t([[1,5,2]], false, 1), t([[1,5,233,7]], true, 1), t([[1]], true), t([[1,2]], true)],
    'function predictTheWinner(nums){var n=nums.length,dp=nums.slice();for(var len=2;len<=n;len++)for(var i=0;i+len-1<n;i++)dp[i]=Math.max(nums[i]-dp[i+1],nums[i+len-1]-dp[i]);return dp[0]>=0;}'),

pdef('perfect-squares-num', 'Perfect Squares', 'medium', 'numSquares',
    sig(['n' => 'int'], 'int'),
    'Return the least number of perfect squares that sum to n.',
    ['1 <= n <= 10000'],
    [t([12], 3, 1), t([13], 2, 1), t([1], 1), t([48], 3)],
    'function numSquares(n){var dp=new Array(n+1).fill(Infinity);dp[0]=0;for(var i=1;i<=n;i++)for(var j=1;j*j<=i;j++)dp[i]=Math.min(dp[i],dp[i-j*j]+1);return dp[n];}'),

pdef('integer-break', 'Integer Break', 'medium', 'integerBreak',
    sig(['n' => 'int'], 'int'),
    'Break n into a sum of positive integers (at least two parts) maximizing the product of the parts.',
    ['2 <= n <= 58'],
    [t([2], 1, 1), t([10], 36, 1), t([3], 2), t([7], 12)],
    'function integerBreak(n){if(n<=3)return n-1;var r=1;while(n>4){r*=3;n-=3;}return r*n;}'),

pdef('count-unique-digits', 'Count Numbers with Unique Digits', 'medium', 'countNumbersWithUniqueDigits',
    sig(['n' => 'int'], 'int'),
    'Count all numbers x with 0 <= x < 10^n whose digits are all different.',
    ['0 <= n <= 8'],
    [t([2], 91, 1), t([0], 1, 1), t([1], 10), t([3], 739)],
    'function countNumbersWithUniqueDigits(n){if(n===0)return 1;var total=10,avail=9,cur=9;for(var k=2;k<=n;k++){cur*=avail;total+=cur;avail--;}return total;}'),

pdef('wiggle-subsequence', 'Wiggle Subsequence', 'medium', 'wiggleMaxLength',
    sig(['nums' => 'int[]'], 'int'),
    'A wiggle sequence strictly alternates up and down between consecutive elements. Return the length of the longest wiggle subsequence.',
    ['1 <= nums.length <= 1000'],
    [t([[1,7,4,9,2,5]], 6, 1), t([[1,17,5,10,13,15,10,5,16,8]], 7, 1), t([[1,2,3,4,5,6,7,8,9]], 2), t([[0,0]], 1)],
    'function wiggleMaxLength(nums){if(nums.length<2)return nums.length;var up=1,down=1;for(var i=1;i<nums.length;i++){if(nums[i]>nums[i-1])up=down+1;else if(nums[i]<nums[i-1])down=up+1;}return Math.max(up,down);}'),

pdef('arithmetic-slices', 'Arithmetic Slices', 'medium', 'numberOfArithmeticSlices',
    sig(['nums' => 'int[]'], 'int'),
    'Count contiguous subarrays of length at least 3 that form an arithmetic progression.',
    ['1 <= nums.length <= 5000'],
    [t([[1,2,3,4]], 3, 1), t([[1]], 0, 1), t([[1,2,3,4,5]], 6), t([[2,4,6,8,10]], 6)],
    'function numberOfArithmeticSlices(nums){var total=0,cur=0;for(var i=2;i<nums.length;i++){if(nums[i]-nums[i-1]===nums[i-1]-nums[i-2]){cur++;total+=cur;}else cur=0;}return total;}'),

pdef('dungeon-game', 'Dungeon Game', 'hard', 'calculateMinimumHP',
    sig(['g' => 'int[][]'], 'int'),
    'The knight enters top-left and must reach the princess bottom-right moving only right or down, health always > 0. Rooms add or subtract health. Return the minimum initial health.',
    ['1 <= rows, cols <= 200'],
    [t([[[-2,-3,3],[-5,-10,1],[10,30,-5]]], 7, 1), t([[[0]]], 1, 1), t([[[-3,5]]], 4), t([[[1,-3,3],[0,-2,0],[-3,-3,-3]]], 3)],
    'function calculateMinimumHP(g){var m=g.length,n=g[0].length;var need=[];for(var i=0;i<m;i++)need.push(new Array(n).fill(0));for(var i=m-1;i>=0;i--)for(var j=n-1;j>=0;j--){var req;if(i===m-1&&j===n-1)req=1;else if(i===m-1)req=need[i][j+1];else if(j===n-1)req=need[i+1][j];else req=Math.min(need[i+1][j],need[i][j+1]);need[i][j]=Math.max(1,req-g[i][j]);}return need[0][0];}'),

pdef('burst-balloons', 'Burst Balloons', 'hard', 'maxCoins',
    sig(['nums' => 'int[]'], 'int'),
    'Bursting balloon i earns nums[left] * nums[i] * nums[right] where left and right are the nearest unburst balloons (virtual 1s at the ends). Return the maximum coins.',
    ['1 <= nums.length <= 300'],
    [t([[3,1,5,8]], 167, 1), t([[1,5]], 10, 1), t([[9]], 9), t([[2]], 2)],
    'function maxCoins(nums){var a=[1].concat(nums,[1]),n=a.length;var dp=[];for(var i=0;i<n;i++)dp.push(new Array(n).fill(0));for(var len=3;len<=n;len++)for(var l=0;l+len-1<n;l++){var r=l+len-1;for(var k=l+1;k<r;k++)dp[l][r]=Math.max(dp[l][r],dp[l][k]+a[l]*a[k]*a[r]+dp[k][r]);}return dp[0][n-1];}'),

pdef('min-cost-tickets', 'Minimum Cost For Tickets', 'medium', 'mincostTickets',
    sig(['days' => 'int[]', 'costs' => 'int[]'], 'int'),
    'Travel happens on the given days. Passes cost costs[0] (1 day), costs[1] (7 days), costs[2] (30 days). Return the minimum spend to cover all travel days.',
    ['1 <= days.length <= 365'],
    [t([[1,4,6,7,8,20], [2,7,15]], 11, 1), t([[1,2,3,4,5,6,7,8,9,10,30,31], [2,7,15]], 17, 1), t([[1], [2,7,15]], 2), t([[2,5], [1,4,25]], 2)],
    'function mincostTickets(days,costs){var set=new Set(days);var last=days[days.length-1];var dp=new Array(last+1).fill(0);for(var d=1;d<=last;d++){if(!set.has(d))dp[d]=dp[d-1];else dp[d]=Math.min(dp[d-1]+costs[0],dp[Math.max(0,d-7)]+costs[1],dp[Math.max(0,d-30)]+costs[2]);}return dp[last];}'),

pdef('wildcard-matching', 'Wildcard Matching', 'hard', 'isWildcardMatch',
    sig(['s' => 'str', 'p' => 'str'], 'bool'),
    'Pattern p may contain ? (any single char) and * (any sequence, including empty). Return true if it matches the whole string s.',
    ['0 <= s.length, p.length <= 2000'],
    [t(['aa', '*'], true, 1), t(['aa', 'a'], false, 1), t(['cb', '?a'], false), t(['adceb', '*a*b'], true), t(['', '*'], true)],
    'function isWildcardMatch(s,p){var m=s.length,n=p.length;var dp=[];for(var i=0;i<=m;i++)dp.push(new Array(n+1).fill(false));dp[0][0]=true;for(var j=1;j<=n;j++)if(p[j-1]==="*")dp[0][j]=dp[0][j-1];for(var i=1;i<=m;i++)for(var j=1;j<=n;j++){var c=p[j-1];if(c==="*")dp[i][j]=dp[i][j-1]||dp[i-1][j];else dp[i][j]=(c==="?"||c===s[i-1])&&dp[i-1][j-1];}return dp[m][n];}'),

pdef('regex-matching', 'Regular Expression Matching', 'hard', 'isRegexMatch',
    sig(['s' => 'str', 'p' => 'str'], 'bool'),
    'Pattern p supports . (any char) and * (zero or more of the preceding element). Match must cover the whole string.',
    ['1 <= s.length <= 20', '1 <= p.length <= 20'],
    [t(['aa', 'a'], false, 1), t(['aa', 'a*'], true, 1), t(['ab', '.*'], true), t(['aab', 'c*a*b'], true), t(['mississippi', 'mis*is*p*.'], false)],
    'function isRegexMatch(s,p){var m=s.length,n=p.length;var dp=[];for(var i=0;i<=m;i++)dp.push(new Array(n+1).fill(false));dp[0][0]=true;for(var j=2;j<=n;j++)if(p[j-1]==="*")dp[0][j]=dp[0][j-2];for(var i=1;i<=m;i++)for(var j=1;j<=n;j++){if(j>=2&&p[j-1]==="*"){dp[i][j]=dp[i][j-2]||((p[j-2]==="."||p[j-2]===s[i-1])&&dp[i-1][j]);}else dp[i][j]=(p[j-1]==="."||p[j-1]===s[i-1])&&dp[i-1][j-1];}return dp[m][n];}'),

pdef('interleaving-string', 'Interleaving String', 'medium', 'isInterleave',
    sig(['a' => 'str', 'b' => 'str', 'c' => 'str'], 'bool'),
    'Return true if c is formed by interleaving a and b while preserving the order of each.',
    ['0 <= lengths <= 100'],
    [t(['aabcc', 'dbbca', 'aadbbcbcac'], true, 1), t(['aabcc', 'dbbca', 'aadbbbaccc'], false, 1), t(['', '', ''], true), t(['', '', 'a'], false)],
    'function isInterleave(a,b,c){if(a.length+b.length!==c.length)return false;var m=a.length,n=b.length;var dp=[];for(var i=0;i<=m;i++)dp.push(new Array(n+1).fill(false));for(var i=0;i<=m;i++)for(var j=0;j<=n;j++){if(i===0&&j===0)dp[i][j]=true;else if(i===0)dp[i][j]=dp[i][j-1]&&b[j-1]===c[i+j-1];else if(j===0)dp[i][j]=dp[i-1][j]&&a[i-1]===c[i+j-1];else dp[i][j]=(dp[i-1][j]&&a[i-1]===c[i+j-1])||(dp[i][j-1]&&b[j-1]===c[i+j-1]);}return dp[m][n];}'),

pdef('russian-doll', 'Russian Doll Envelopes', 'hard', 'maxEnvelopes',
    sig(['e' => 'int[][]'], 'int'),
    'Envelope [w,h] fits inside another only if both dimensions are strictly smaller. Return the maximum number you can nest.',
    ['1 <= e.length <= 100000'],
    [t([[[5,4],[6,4],[6,7],[2,3]]], 3, 1), t([[[1,1],[1,1],[1,1]]], 1, 1), t([[[2,3],[5,4],[6,7],[6,4]]], 3), t([[[1,3],[3,5],[6,7],[6,8],[8,4],[9,5]]], 3)],
    'function maxEnvelopes(e){e.sort(function(x,y){return x[0]===y[0]?y[1]-x[1]:x[0]-y[0];});var t=[];for(var i=0;i<e.length;i++){var h=e[i][1],lo=0,hi=t.length;while(lo<hi){var mid=(lo+hi)>>1;if(t[mid]<h)lo=mid+1;else hi=mid;}if(lo===t.length)t.push(h);else t[lo]=h;}return t.length;}'),

pdef('split-array-largest-sum', 'Split Array Largest Sum', 'hard', 'splitArray',
    sig(['nums' => 'int[]', 'k' => 'int'], 'int'),
    'Split the array into k non-empty contiguous parts minimizing the largest part sum. Return that minimum possible largest sum.',
    ['1 <= nums.length <= 1000', '1 <= k <= nums.length'],
    [t([[7,2,5,10,8], 2], 18, 1), t([[1,2,3,4,5], 2], 9, 1), t([[1,4,4], 3], 4), t([[1], 1], 1)],
    'function splitArray(nums,k){function ok(cap){var parts=1,cur=0;for(var n of nums){if(cur+n>cap){parts++;cur=0;}cur+=n;}return parts<=k;}var lo=0,hi=0;for(var n of nums){lo=Math.max(lo,n);hi+=n;}while(lo<hi){var mid=(lo+hi)>>1;if(ok(mid))hi=mid;else lo=mid+1;}return lo;}'),

pdef('paint-house', 'Paint House', 'medium', 'minCostPaint',
    sig(['costs' => 'int[][]'], 'int'),
    'costs[i] = [red, green, blue] to paint house i. Adjacent houses must differ in colour. Return the minimum total cost.',
    ['1 <= costs.length <= 100'],
    [t([[[17,2,17],[16,16,5],[14,3,19]]], 10, 1), t([[[7,6,2]]], 2, 1), t([[[1,5,3],[2,9,4]]], 5), t([[[3,5,3],[6,17,6],[7,13,18],[9,10,18]]], 26)],
    'function minCostPaint(costs){var r=0,g=0,b=0;for(var c of costs){var pr=r,pg=g,pb=b;r=c[0]+Math.min(pg,pb);g=c[1]+Math.min(pr,pb);b=c[2]+Math.min(pr,pg);}return Math.min(r,g,b);}'),

];
