<?php
// Category: greedy — take the locally best option and defend it
return [
pdef('best-time-stock', 'Best Time to Buy and Sell Stock', 'easy', 'maxProfit',
    sig(['prices' => 'int[]'], 'int'),
    'You may complete ONE transaction (buy one day, sell any later day). prices[i] is the price on day i. Return the maximum profit, or 0 if no profit is possible.',
    ['1 ≤ prices.length ≤ 10⁵'],
    [t([[7, 1, 5, 3, 6, 4]], 5, 1), t([[7, 6, 4, 3, 1]], 0, 1), t([[1]], 0), t([[2, 4, 1]], 2)],
    'function maxProfit(p){var mn=Infinity,best=0,i;for(i=0;i<p.length;i++){mn=Math.min(mn,p[i]);best=Math.max(best,p[i]-mn);}return best;}'),

pdef('best-time-stock-ii', 'Best Time to Buy and Sell Stock II', 'medium', 'maxProfit2',
    sig(['prices' => 'int[]'], 'int'),
    'Now you may complete as many transactions as you like (but must sell before buying again). Grab every upward step and the answer falls out.',
    ['1 ≤ prices.length ≤ 3·10⁴'],
    [t([[7, 1, 5, 3, 6, 4]], 7, 1), t([[1, 2, 3, 4, 5]], 4, 1), t([[7, 6, 4, 3, 1]], 0), t([[5, 4]], 0)],
    'function maxProfit2(p){var s=0,i;for(i=1;i<p.length;i++){if(p[i]>p[i-1])s+=p[i]-p[i-1];}return s;}'),

pdef('jump-game', 'Jump Game', 'medium', 'canJump',
    sig(['nums' => 'int[]'], 'bool'),
    'Each element is your maximum jump length from that position. Starting at index 0, can you reach the last index?',
    ['1 ≤ nums.length ≤ 10⁴'],
    [t([[2, 3, 1, 1, 4]], true, 1), t([[3, 2, 1, 0, 4]], false, 1), t([[0]], true), t([[1, 0]], true)],
    'function canJump(nums){var reach=0,i;for(i=0;i<nums.length;i++){if(i>reach)return false;reach=Math.max(reach,i+nums[i]);}return true;}'),

pdef('assign-cookies', 'Assign Cookies', 'easy', 'findContentChildren',
    sig(['g' => 'int[]', 's' => 'int[]'], 'int'),
    'Each child has a greed factor g[i] — the minimum cookie size that satisfies them. s[j] is a cookie size; each cookie feeds at most one child. Maximize content children.',
    ['1 ≤ g.length ≤ 3·10⁴', '0 ≤ s.length ≤ 3·10⁴'],
    [t([[1, 2, 3], [1, 1]], 1, 1), t([[1, 2], [1, 2, 3]], 2, 1), t([[1, 2, 3], [3]], 1), t([[1], [2]], 1)],
    'function findContentChildren(g,s){g.sort(function(a,b){return a-b;});s.sort(function(a,b){return a-b;});var i=0,j=0;while(i<g.length&&j<s.length){if(s[j]>=g[i]){i++;}j++;}return i;}'),

pdef('lemonade-change', 'Lemonade Change', 'easy', 'lemonadeChange',
    sig(['bills' => 'int[]'], 'bool'),
    'Lemonade costs $5. Customers pay with 5, 10 or 20 dollar bills in the given order. You start with no change. Return true if every customer gets correct change.',
    ['1 ≤ bills.length ≤ 10⁵'],
    [t([[5, 5, 5, 10, 20]], true, 1), t([[5, 5, 10, 10, 20]], false, 1), t([[10]], false), t([[5, 5, 5, 5]], true)],
    'function lemonadeChange(b){var f=0,t=0,i;for(i=0;i<b.length;i++){var x=b[i];if(x===5)f++;else if(x===10){if(!f)return false;f--;t++;}else{if(t&&f){t--;f--;}else if(f>=3){f-=3;}else return false;}}return true;}'),

pdef('max-69', 'Maximum 69 Number', 'easy', 'maximum69Number',
    sig(['num' => 'int'], 'int'),
    'The number consists only of digits 6 and 9. Flip at most ONE digit (6→9 or 9→6) to make the number as large as possible.',
    ['1 ≤ num ≤ 10⁴'],
    [t([9669], 9969, 1), t([9996], 9999, 1), t([9999], 9999), t([669], 969)],
    'function maximum69Number(n){return parseInt(String(n).replace("6","9"),10);}'),

pdef('min-seats-moves', 'Minimum Moves to Seat Everyone', 'easy', 'minMovesToSeat',
    sig(['seats' => 'int[]', 'students' => 'int[]'], 'int'),
    'seats[j] are chair positions, students[i] are student positions. One move shifts a student by ±1 position. Return the minimum total moves so every student sits on a distinct seat.',
    ['n = seats.length = students.length'],
    [t([[3, 1, 5], [2, 7, 4]], 4, 1), t([[4, 1, 5, 9], [1, 3, 2, 6]], 7, 1), t([[1], [1]], 0), t([[2, 2, 7], [3, 3, 8]], 3)],
    'function minMovesToSeat(a,b){a.sort(function(x,y){return x-y;});b.sort(function(x,y){return x-y;});var s=0,i;for(i=0;i<a.length;i++){s+=Math.abs(a[i]-b[i]);}return s;}'),

pdef('partition-labels', 'Partition Labels', 'medium', 'partitionLabels',
    sig(['s' => 'str'], 'int[]'),
    'Split s into as many parts as possible so that each letter appears in at most one part. Return the lengths of the parts in order.',
    ['1 ≤ s.length ≤ 500', 'lowercase letters'],
    [t(['ababcbacadefegdehijhklij'], [9, 7, 8], 1), t(['eccbbbbdec'], [10], 1), t(['abc'], [1, 1, 1]), t(['abac'], [3, 1])],
    'function partitionLabels(s){var last={},i;for(i=0;i<s.length;i++){last[s[i]]=i;}var out=[],start=0,end=0;for(i=0;i<s.length;i++){end=Math.max(end,last[s[i]]);if(i===end){out.push(end-start+1);start=i+1;}}return out;}'),

pdef('non-overlap-intervals', 'Non-overlapping Intervals', 'medium', 'eraseOverlapIntervals',
    sig(['intervals' => 'int[][]'], 'int'),
    'Return the minimum number of intervals you must remove so the rest do not overlap. Touching endpoints do NOT overlap.',
    ['1 ≤ intervals.length ≤ 10⁵'],
    [t([[[1, 2], [2, 3], [3, 4], [1, 3]]], 1, 1), t([[[1, 2], [1, 2], [1, 2]]], 2, 1), t([[[1, 2], [2, 3]]], 0), t([[[0, 10], [1, 2], [2, 3]]], 1)],
    'function eraseOverlapIntervals(iv){iv.sort(function(a,b){return a[1]-b[1];});var end=-Infinity,removed=0,i;for(i=0;i<iv.length;i++){if(iv[i][0]>=end){end=iv[i][1];}else{removed++;}}return removed;}'),

pdef('two-chocolates', 'Buy Two Chocolates', 'easy', 'buyChoco',
    sig(['prices' => 'int[]', 'money' => 'int'], 'int'),
    'You must buy exactly two chocolates. Return the money you have LEFT after picking the cheapest pair — or the original amount if the pair costs more than you have.',
    ['2 ≤ prices.length ≤ 50', '1 ≤ prices[i], money ≤ 100'],
    [t([[3, 1, 2], 5], 2, 1), t([[3, 2, 3], 3], 3, 1), t([[1, 1], 2], 0), t([[4, 5], 9], 0)],
    'function buyChoco(p,m){p.sort(function(a,b){return a-b;});var cost=p[0]+p[1];return cost>m?m:m-cost;}'),

pdef('largest-perimeter-triangle', 'Largest Perimeter Triangle', 'easy', 'largestPerimeter',
    sig(['nums' => 'int[]'], 'int'),
    'Pick three lengths that can form a non-degenerate triangle (sum of the two smaller > largest) and return the maximum perimeter, or 0.',
    ['3 ≤ nums.length ≤ 10⁴'],
    [t([[2, 1, 2]], 5, 1), t([[1, 2, 1, 10]], 0, 1), t([[3, 6, 2, 3]], 8), t([[1, 1, 1]], 3)],
    'function largestPerimeter(a){a.sort(function(x,y){return y-x;});for(var i=0;i<a.length-2;i++){if(a[i+1]+a[i+2]>a[i])return a[i]+a[i+1]+a[i+2];}return 0;}'),

pdef('max-units-truck', 'Maximum Units on a Truck', 'easy', 'maximumUnits',
    sig(['boxTypes' => 'int[][]', 'truckSize' => 'int'], 'int'),
    'boxTypes[i] = [count, unitsPerBox]. The truck fits truckSize boxes total. Choose boxes (up to their counts) maximizing total units carried.',
    ['1 ≤ boxTypes.length ≤ 1000', '1 ≤ truckSize ≤ 10⁶'],
    [t([[[1, 3], [2, 2], [3, 1]], 4], 8, 1), t([[[5, 10], [2, 5], [4, 7], [3, 9]], 10], 91, 1), t([[[1, 1]], 1], 1), t([[[2, 5], [4, 4]], 3], 14)],
    'function maximumUnits(bt,cap){bt.sort(function(a,b){return b[1]-a[1];});var s=0,i;for(i=0;i<bt.length&&cap>0;i++){var take=Math.min(cap,bt[i][0]);s+=take*bt[i][1];cap-=take;}return s;}'),


pdef('jump-game-ii', 'Jump Game II', 'medium', 'jump',
    sig(['nums' => 'int[]'], 'int'),
    'Each value is your maximum jump length from that index. Return the minimum number of jumps to reach the last index (always reachable).',
    ['1 <= nums.length <= 10000'],
    [t([[2,3,1,1,4]], 2, 1), t([[2,3,0,1,4]], 2, 1), t([[1]], 0), t([[1,1,1]], 2)],
    'function jump(nums){var jumps=0,end=0,far=0;for(var i=0;i<nums.length-1;i++){far=Math.max(far,i+nums[i]);if(i===end){jumps++;end=far;}}return jumps;}'),

pdef('gas-station', 'Gas Station', 'medium', 'canCompleteCircuit',
    sig(['gas' => 'int[]', 'cost' => 'int[]'], 'int'),
    'A circular route has stations i with gas[i] fuel and cost[i] to reach the next. Return the starting station index that completes the circuit, or -1.',
    ['1 <= gas.length <= 100000'],
    [t([[1,2,3,4,5], [3,4,5,1,2]], 3, 1), t([[2,3,4], [3,4,3]], -1, 1), t([[5,1,2,3,4], [4,4,1,5,1]], 4), t([[2], [2]], 0)],
    'function canCompleteCircuit(gas,cost){var total=0,tank=0,start=0;for(var i=0;i<gas.length;i++){var d=gas[i]-cost[i];total+=d;tank+=d;if(tank<0){start=i+1;tank=0;}}return total>=0?start:-1;}'),

pdef('candy', 'Candy', 'hard', 'candy',
    sig(['ratings' => 'int[]'], 'int'),
    'Every child gets at least one candy; a child with a higher rating than a neighbour must get more candies. Return the minimum total.',
    ['1 <= ratings.length <= 20000'],
    [t([[1,0,2]], 5, 1), t([[1,2,2]], 4, 1), t([[1]], 1), t([[1,2,3]], 6)],
    'function candy(r){var n=r.length,c=new Array(n).fill(1);for(var i=1;i<n;i++)if(r[i]>r[i-1])c[i]=c[i-1]+1;for(var i=n-2;i>=0;i--)if(r[i]>r[i+1])c[i]=Math.max(c[i],c[i+1]+1);var s=0;for(var x of c)s+=x;return s;}'),

pdef('queue-reconstruction', 'Queue Reconstruction by Height', 'medium', 'reconstructQueue',
    sig(['people' => 'int[][]'], 'int[][]'),
    'Each [h, k] means a person of height h with exactly k people of height >= h in front. Reconstruct the queue.',
    ['1 <= people.length <= 2000'],
    [t([[[7,0],[4,4],[7,1],[5,0],[6,1],[5,2]]], [[5,0],[7,0],[5,2],[6,1],[4,4],[7,1]], 1)],
    'function reconstructQueue(p){p.sort(function(a,b){return a[0]===b[0]?a[1]-b[1]:b[0]-a[0];});var out=[];for(var person of p)out.splice(person[1],0,person);return out;}'),

pdef('task-scheduler', 'Task Scheduler', 'medium', 'leastInterval',
    sig(['tasks' => 'str', 'n' => 'int'], 'int'),
    'tasks is a string of uppercase task names. Identical tasks must be at least n slots apart (idles allowed). Return the minimum total slots.',
    ['1 <= tasks.length <= 10000', '0 <= n <= 100'],
    [t(['AAABBB', 2], 8, 1), t(['AAAA', 2], 10, 1), t(['ABAB', 2], 5), t(['ABCDEF', 2], 6)],
    'function leastInterval(tasks,n){var f={};var mx=0;for(var c of tasks){f[c]=(f[c]||0)+1;if(f[c]>mx)mx=f[c];}var cnt=0;for(var k in f)if(f[k]===mx)cnt++;return Math.max(tasks.length,(n+1)*(mx-1)+cnt);}'),

pdef('us-coin-greedy', 'Fewest US Coins', 'easy', 'coinChangeGreedy',
    sig(['amount' => 'int'], 'int'),
    'Using US coins 25, 10, 5 and 1 cents (unlimited), return the fewest coins needed to make amount.',
    ['0 <= amount <= 100000'],
    [t([41], 4, 1), t([99], 9, 1), t([0], 0), t([6], 2)],
    'function coinChangeGreedy(amount){var coins=[25,10,5,1],cnt=0;for(var c of coins){while(amount>=c){amount-=c;cnt++;}}return cnt;}'),

pdef('min-arrows-balloons', 'Minimum Number of Arrows to Burst Balloons', 'medium', 'findMinArrowShots',
    sig(['points' => 'int[][]'], 'int'),
    'Balloon i spans [start, end]; one vertical arrow bursts every balloon covering that x. Return the minimum arrows.',
    ['1 <= points.length <= 100000'],
    [t([[[10,16],[2,8],[1,6],[7,12]]], 2, 1), t([[[1,2],[3,4],[5,6],[7,8]]], 4, 1), t([[[1,2]]], 1), t([[[1,10],[2,9],[3,8]]], 1)],
    'function findMinArrowShots(points){points.sort(function(a,b){return a[1]-b[1];});var arrows=0,end=null;for(var p of points){if(end===null||p[0]>end){arrows++;end=p[1];}}return arrows;}'),

pdef('monotone-digits', 'Monotone Increasing Digits', 'medium', 'monotoneIncreasingDigits',
    sig(['n' => 'int'], 'int'),
    'Return the largest number <= n whose digits are non-decreasing.',
    ['0 <= n <= 1000000000'],
    [t([10], 9, 1), t([1234], 1234, 1), t([332], 299), t([101], 99)],
    'function monotoneIncreasingDigits(n){var d=String(n).split("");var mark=d.length;for(var i=d.length-1;i>0;i--)if(d[i-1]>d[i]){mark=i-1;d[i-1]=String(Number(d[i-1])-1);}for(var i=mark+1;i<d.length;i++)d[i]="9";return Number(d.join(""));}'),

pdef('boats-save-people', 'Boats to Save People', 'medium', 'numRescueBoats',
    sig(['people' => 'int[]', 'limit' => 'int'], 'int'),
    'Each boat carries at most 2 people whose combined weight is at most limit. Return the minimum boats.',
    ['1 <= people.length <= 50000'],
    [t([[1,2], 3], 1, 1), t([[3,2,2,1], 3], 3, 1), t([[3,5,3,4], 5], 4), t([[1,1,1,1], 3], 2)],
    'function numRescueBoats(people,limit){people.sort(function(a,b){return a-b;});var l=0,r=people.length-1,boats=0;while(l<=r){if(people[l]+people[r]<=limit)l++;r--;boats++;}return boats;}'),

pdef('two-city-scheduling', 'Two City Scheduling', 'medium', 'twoCitySchedCost',
    sig(['costs' => 'int[][]'], 'int'),
    'costs[i] = [costA, costB] to fly person i to city A or B. Fly exactly half to each city; return the minimum total cost.',
    ['2 <= costs.length <= 200, even count'],
    [t([[[10,20],[30,200],[400,50],[30,20]]], 110, 1), t([[[259,770],[448,54],[926,667],[184,139],[840,118],[577,469]]], 1859, 1), t([[[1,100],[200,2],[3,200],[100,4]]], 10)],
    'function twoCitySchedCost(costs){costs.sort(function(a,b){return (a[0]-a[1])-(b[0]-b[1]);});var n=costs.length/2,s=0;for(var i=0;i<n;i++)s+=costs[i][0];for(var i=n;i<costs.length;i++)s+=costs[i][1];return s;}'),

pdef('split-balanced-string', 'Split a String in Balanced Strings', 'easy', 'balancedStringSplit',
    sig(['s' => 'str'], 'int'),
    'A balanced string has equal L and R counts. Split s (itself balanced) into the maximum number of balanced substrings and return that count.',
    ['2 <= s.length <= 1000'],
    [t(['RLRRLLRLRL'], 4, 1), t(['RLRRRLLRLL'], 2, 1), t(['LLLLRRRR'], 1), t(['RL'], 1)],
    'function balancedStringSplit(s){var bal=0,cnt=0;for(var c of s){bal+=c==="R"?1:-1;if(bal===0)cnt++;}return cnt;}'),

pdef('delete-columns-sorted', 'Delete Columns to Make Sorted', 'easy', 'minDeletionSize',
    sig(['strs' => 'str[]'], 'int'),
    'strs are equal-length strings forming rows. Return the number of columns that are NOT in sorted (non-decreasing) order top to bottom.',
    ['1 <= strs.length <= 100'],
    [t([['cba','daf','ghi']], 1, 1), t([['a','b']], 0, 1), t([['zyx','wvu','tsr']], 3), t([['abc','bce','cae']], 1)],
    'function minDeletionSize(strs){var cnt=0;for(var j=0;j<strs[0].length;j++)for(var i=1;i<strs.length;i++)if(strs[i][j]<strs[i-1][j]){cnt++;break;}return cnt;}'),

pdef('min-deletion-alternating', 'Deletions to Avoid Adjacent Duplicates', 'easy', 'minDeletion',
    sig(['s' => 'str'], 'int'),
    'Return the minimum deletions to make s a string where no two adjacent characters are equal.',
    ['1 <= s.length <= 100000'],
    [t(['aab'], 1, 1), t(['aaaa'], 3, 1), t(['abab'], 0), t(['aba'], 0)],
    'function minDeletion(s){var del=0,prev=-1;for(var i=0;i<s.length;i++){if(prev===-1||s[i]!==s[prev])prev=i;else del++;}return del;}'),

pdef('largest-number', 'Largest Number', 'medium', 'largestNumber',
    sig(['nums' => 'int[]'], 'str'),
    'Arrange the non-negative integers so their concatenation forms the largest possible number; return it as a string.',
    ['1 <= nums.length <= 100'],
    [t([[10,2]], '210', 1), t([[3,30,34,5,9]], '9534330', 1), t([[0,0]], '0'), t([[1]], '1')],
    'function largestNumber(nums){var strs=nums.map(String);strs.sort(function(a,b){var x=a+b,y=b+a;return x<y?1:x>y?-1:0;});var res=strs.join("");return res[0]==="0"?"0":res;}'),

pdef('smallest-subseq-distinct', 'Smallest Subsequence of Distinct Characters', 'medium', 'smallestSubsequence',
    sig(['s' => 'str'], 'str'),
    'Return the lexicographically smallest subsequence of s that contains every distinct character of s exactly once.',
    ['1 <= s.length <= 10000'],
    [t(['bcabc'], 'abc', 1), t(['cbacdcbc'], 'acdb', 1), t(['abcd'], 'abcd'), t(['leetcode'], 'letcod')],
    'function smallestSubsequence(s){var last={},seen={},st=[];for(var i=0;i<s.length;i++)last[s[i]]=i;for(var i=0;i<s.length;i++){var c=s[i];if(seen[c])continue;while(st.length&&st[st.length-1]>c&&last[st[st.length-1]]>i)seen[st.pop()]=false;st.push(c);seen[c]=true;}return st.join("");}'),

pdef('min-increment-unique', 'Minimum Increment to Make Array Unique', 'medium', 'minIncrementForUnique',
    sig(['nums' => 'int[]'], 'int'),
    'In one move you increment any value by 1. Return the minimum moves to make every value unique.',
    ['1 <= nums.length <= 100000'],
    [t([[1,2,2]], 1, 1), t([[3,2,1,2,1,7]], 6, 1), t([[1]], 0), t([[5,5,5]], 3)],
    'function minIncrementForUnique(nums){nums.sort(function(a,b){return a-b;});var moves=0;for(var i=1;i<nums.length;i++)if(nums[i]<=nums[i-1]){moves+=nums[i-1]+1-nums[i];nums[i]=nums[i-1]+1;}return moves;}'),

pdef('colorful-rope', 'Minimum Time to Make Rope Colorful', 'medium', 'minCost',
    sig(['colors' => 'str', 'neededTime' => 'int[]'], 'int'),
    'Remove balloons so no two adjacent balloons share a colour. neededTime[i] is the removal cost of balloon i. Return the minimum total time.',
    ['colors.length === neededTime.length'],
    [t(['abaac', [1,2,3,4,5]], 3, 1), t(['abc', [1,2,3]], 0, 1), t(['aabaa', [1,2,3,4,1]], 2), t(['aa', [5,4]], 4)],
    'function minCost(colors,t){var total=0,i=0;while(i<colors.length){var j=i,mx=t[i],sum=t[i];while(j+1<colors.length&&colors[j+1]===colors[i]){j++;sum+=t[j];if(t[j]>mx)mx=t[j];}total+=sum-mx;i=j+1;}return total;}'),

pdef('dish-satisfaction', 'Reducing Dishes', 'medium', 'maxSatisfaction',
    sig(['satisfaction' => 'int[]'], 'int'),
    'Cook a subset of dishes in some order; like-time coefficient of the k-th cooked dish is k * satisfaction. Return the maximum total.',
    ['1 <= satisfaction.length <= 500'],
    [t([[-1,-8,0,5,-9]], 14, 1), t([[4,3,2]], 20, 1), t([[-1,-4,-5]], 0), t([[-2,5,-1,0,3,-3]], 35)],
    'function maxSatisfaction(s){s.sort(function(a,b){return a-b;});var total=0,run=0,ans=0;for(var i=s.length-1;i>=0;i--){run+=s[i];total+=run;if(total>ans)ans=total;}return ans;}'),

pdef('broken-calculator', 'Broken Calculator', 'medium', 'brokenCalc',
    sig(['startValue' => 'int', 'target' => 'int'], 'int'),
    'The display can only double or subtract 1. Return the minimum operations to reach target from startValue.',
    ['1 <= startValue, target <= 1000000000'],
    [t([2, 3], 2, 1), t([5, 8], 2, 1), t([3, 10], 3), t([1024, 1], 1023)],
    'function brokenCalc(sv,target){var ops=0;while(target>sv){if(target%2)target++;else target/=2;ops++;}return ops+sv-target;}'),

pdef('hand-of-straights', 'Hand of Straights', 'medium', 'isNStraightHand',
    sig(['hand' => 'int[]', 'groupSize' => 'int'], 'bool'),
    'Return true if the hand can be rearranged into groups of groupSize consecutive numbers.',
    ['groupSize divides hand.length'],
    [t([[1,2,3,6,2,3,4,7,8], 3], true, 1), t([[1,2,3,4,5], 4], false, 1), t([[1,2,3], 1], true), t([[1,1,2,2,3,3], 2], false)],
    'function isNStraightHand(hand,g){if(hand.length%g)return false;var cnt={};for(var c of hand)cnt[c]=(cnt[c]||0)+1;var keys=Object.keys(cnt).map(Number).sort(function(a,b){return a-b;});for(var i=0;i<keys.length;i++){var k=keys[i];while(cnt[k]>0){for(var d=0;d<g;d++){if(!cnt[k+d])return false;cnt[k+d]--;}}}return true;}'),

pdef('max-ice-cream', 'Maximum Ice Cream Bars', 'medium', 'maxIceCream',
    sig(['costs' => 'int[]', 'coins' => 'int'], 'int'),
    'Return the maximum number of ice cream bars you can buy with coins (each bar bought at most once).',
    ['1 <= costs.length <= 100000'],
    [t([[1,3,2,4,1], 7], 4, 1), t([[10,6,8,7,7,8], 5], 0, 1), t([[1,6,3,1,2,5], 20], 6), t([[5], 5], 1)],
    'function maxIceCream(costs,coins){costs.sort(function(a,b){return a-b;});var cnt=0;for(var c of costs){if(c<=coins){coins-=c;cnt++;}else break;}return cnt;}'),

pdef('apple-redistribution', 'Apple Redistribution into Boxes', 'easy', 'minimumBoxes',
    sig(['apple' => 'int[]', 'capacity' => 'int[]'], 'int'),
    'Packs of apples must be redistributed into boxes (any split allowed). Return the minimum number of boxes needed.',
    ['Total apples fit in all boxes combined'],
    [t([[1,3,2], [4,3,1,5,2]], 2, 1), t([[5,8], [9,5]], 2, 1), t([[2,2,2], [1,2,3]], 3), t([[1], [2]], 1)],
    'function minimumBoxes(apple,capacity){var total=0;for(var a of apple)total+=a;capacity.sort(function(a,b){return b-a;});var used=0,need=0;while(need<total)need+=capacity[used++];return used;}'),

pdef('fraction-knapsack', 'Fractional Knapsack', 'medium', 'fractionKnapsack',
    sig(['weights' => 'int[]', 'values' => 'int[]', 'capacity' => 'int'], 'num'),
    'Unlike 0/1 knapsack you may take any fraction of an item. Return the maximum total value (fractions allowed).',
    ['weights.length === values.length <= 100'],
    [t([[10,20,30], [60,100,120], 50], 240, 1), t([[5], [10], 2], 4, 1), t([[10,40], [100,200], 30], 200)],
    'function fractionKnapsack(weights,values,cap){var items=[];for(var i=0;i<weights.length;i++)items.push([weights[i],values[i]]);items.sort(function(a,b){return b[1]/b[0]-a[1]/a[0];});var val=0;for(var it of items){if(cap<=0)break;if(it[0]<=cap){cap-=it[0];val+=it[1];}else{val+=it[1]/it[0]*cap;cap=0;}}return val;}'),

pdef('car-pooling', 'Car Pooling', 'medium', 'carPooling',
    sig(['trips' => 'int[][]', 'capacity' => 'int'], 'bool'),
    'Each trip is [passengers, from, to]. Return true if the car never exceeds capacity (passengers leave at their drop-off).',
    ['1 <= trips.length <= 1000'],
    [t([[[2,1,5],[3,3,7]], 4], false, 1), t([[[2,1,5],[3,3,7]], 5], true, 1), t([[[2,1,5],[3,5,7]], 3], true), t([[[9,3,6],[8,1,7]], 14], false)],
    'function carPooling(trips,capacity){var stops={};for(var t of trips){stops[t[1]]=(stops[t[1]]||0)+t[0];stops[t[2]]=(stops[t[2]]||0)-t[0];}var cur=0;var keys=Object.keys(stops).map(Number).sort(function(a,b){return a-b;});for(var k of keys){cur+=stops[k];if(cur>capacity)return false;}return true;}'),

pdef('flight-bookings', 'Corporate Flight Bookings', 'medium', 'corpFlightBookings',
    sig(['bookings' => 'int[][]', 'n' => 'int'], 'int[]'),
    'bookings[i] = [first, last, seats] reserves seats on flights first..last. Return the seats reserved on each of the n flights.',
    ['1 <= n <= 20000', '1 <= bookings.length <= 20000'],
    [t([[[1,2,10],[2,3,20],[2,5,25]], 5], [10,55,45,25,25], 1), t([[[1,2,10],[2,2,15]], 2], [10,25], 1)],
    'function corpFlightBookings(bookings,n){var diff=new Array(n+2).fill(0);for(var b of bookings){diff[b[0]]+=b[2];diff[b[1]+1]-=b[2];}var out=[],cur=0;for(var i=1;i<=n;i++){cur+=diff[i];out.push(cur);}return out;}'),

pdef('maximum-swap', 'Maximum Swap', 'medium', 'maximumSwap',
    sig(['num' => 'int'], 'int'),
    'You may swap two digits at most once. Return the maximum valued number achievable.',
    ['0 <= num <= 100000000'],
    [t([2736], 7236, 1), t([9973], 9973, 1), t([1993], 9913), t([98368], 98863), t([12], 21)],
    'function maximumSwap(num){var d=String(num).split("");var last={};for(var i=0;i<d.length;i++)last[d[i]]=i;for(var i=0;i<d.length;i++)for(var dg=9;dg>Number(d[i]);dg--){var sk=String(dg);if(last[sk]>i){var j=last[sk];var tmp=d[i];d[i]=d[j];d[j]=tmp;return Number(d.join(""));}}return num;}'),

pdef('min-taps-garden', 'Minimum Number of Taps to Open to Water a Garden', 'hard', 'minTaps',
    sig(['n' => 'int', 'ranges' => 'int[]'], 'int'),
    'Tap i at point i waters [i - ranges[i], i + ranges[i]]. The garden spans [0, n]. Return the minimum taps to cover it all, or -1.',
    ['0 <= n <= 10000', 'ranges.length === n + 1'],
    [t([5, [3,4,1,1,0,0]], 1, 1), t([3, [0,0,0,0]], -1, 1), t([7, [1,2,1,0,2,1,0,1]], 3), t([8, [4,0,0,0,0,0,0,0,4]], 2)],
    'function minTaps(n,ranges){var reach=new Array(n+1).fill(0);for(var i=0;i<=n;i++){var l=Math.max(0,i-ranges[i]);reach[l]=Math.max(reach[l],Math.min(n,i+ranges[i]));}var taps=0,end=0,far=0,i=0;while(end<n){while(i<=end){far=Math.max(far,reach[i]);i++;}if(far===end)return -1;end=far;taps++;}return taps;}'),

pdef('max-profit-assignment', 'Most Profit Assigning Work', 'medium', 'maxProfitAssignment',
    sig(['difficulty' => 'int[]', 'profit' => 'int[]', 'worker' => 'int[]'], 'int'),
    'Worker i can do any job with difficulty <= worker[i] at most once (any job can be done many times). Assign one job per worker for the maximum total profit.',
    ['difficulty.length === profit.length'],
    [t([[2,4,6,8,10], [10,20,30,40,50], [4,5,6,7]], 100, 1), t([[85,47,57], [24,66,99], [40,25,25]], 0, 1), t([[13,37,58], [4,90,96], [34,73,45]], 190)],
    'function maxProfitAssignment(difficulty,profit,worker){var jobs=[];for(var i=0;i<difficulty.length;i++)jobs.push([difficulty[i],profit[i]]);jobs.sort(function(a,b){return a[0]-b[0];});worker.sort(function(a,b){return a-b;});var total=0,i=0,best=0;for(var w of worker){while(i<jobs.length&&jobs[i][0]<=w){best=Math.max(best,jobs[i][1]);i++;}total+=best;}return total;}'),

];
