<?php
// Category: hashmap — the single most useful data structure in practice
return [
pdef('two-sum', 'Two Sum', 'easy', 'twoSum',
    sig(['nums' => 'int[]', 'target' => 'int'], 'int[]'),
    'Return the indices of the two numbers that add up to target. Each input has exactly one solution, you may not use the same element twice. Return the indices in ascending order.',
    ['2 ≤ nums.length ≤ 10⁴'],
    [t([[2, 7, 11, 15], 9], [0, 1], 1), t([[3, 2, 4], 6], [1, 2], 1), t([[3, 3], 6], [0, 1]), t([[1, 5, 9, 13], 18], [1, 3])],
    'function twoSum(nums,target){var seen=new Map();for(var i=0;i<nums.length;i++){var need=target-nums[i];if(seen.has(need))return [seen.get(need),i];seen.set(nums[i],i);}return [];}',
    'Can you do it in better than O(n²)? One pass with a hash map can.'),

pdef('group-anagrams', 'Group Anagrams', 'medium', 'groupAnagrams',
    sig(['strs' => 'str[]'], 'str[][]'),
    'Group the anagrams together. For a deterministic answer: sort the words inside each group alphabetically, then sort the groups by their first word.',
    ['1 ≤ strs.length ≤ 10⁴', 'lowercase letters'],
    [t([['eat', 'tea', 'tan', 'ate', 'nat', 'bat']], [['ate', 'eat', 'tea'], ['bat'], ['nat', 'tan']], 1), t([['']], [['']], 1),
     t([['a']], [['a']]), t([['cab', 'pug', 'gup', 'bac']], [['bac', 'cab'], ['gup', 'pug']])],
    'function groupAnagrams(strs){var m=new Map(),i;for(i=0;i<strs.length;i++){var k=strs[i].split("").sort().join("");if(!m.has(k))m.set(k,[]);m.get(k).push(strs[i]);}return Array.from(m.values()).map(function(g){return g.sort();}).sort(function(a,b){return a[0]<b[0]?-1:a[0]>b[0]?1:0;});}'),

pdef('first-recurring', 'First Recurring Character', 'easy', 'firstRecurring',
    sig(['s' => 'str'], 'str'),
    'Return the first character that appears twice as you scan left to right. If none repeats, return an empty string.',
    ['1 ≤ s.length ≤ 10⁵', 'lowercase letters'],
    [t(['abca'], 'a', 1), t(['abcab'], 'a', 1), t(['abcd'], ''), t(['zz'], 'z')],
    'function firstRecurring(s){var seen={};for(var i=0;i<s.length;i++){if(seen[s[i]])return s[i];seen[s[i]]=1;}return "";}'),

pdef('ransom-note', 'Ransom Note', 'easy', 'canConstruct',
    sig(['ransomNote' => 'str', 'magazine' => 'str'], 'bool'),
    'Return true if ransomNote can be constructed using letters from magazine. Each magazine letter may be used only once.',
    ['1 ≤ lengths ≤ 10⁵', 'lowercase letters'],
    [t(['a', 'b'], false, 1), t(['aa', 'aab'], true, 1), t(['aa', 'ab'], false), t(['abc', 'aabbcc'], true)],
    'function canConstruct(r,m){var need={},i,c;for(i=0;i<r.length;i++){c=r[i];need[c]=(need[c]||0)+1;}for(i=0;i<m.length;i++){c=m[i];if(need[c]>0)need[c]--;}for(c in need){if(need[c]>0)return false;}return true;}'),

pdef('jewels-stones', 'Jewels and Stones', 'easy', 'numJewelsInStones',
    sig(['jewels' => 'str', 'stones' => 'str'], 'int'),
    'Count how many characters of stones also appear in jewels. Characters in jewels are distinct; case matters.',
    ['1 ≤ lengths ≤ 50'],
    [t(['aA', 'aAAbbbb'], 3, 1), t(['z', 'ZZ'], 0, 1), t(['abc', 'abc'], 3)],
    'function numJewelsInStones(j,s){var set=new Set(j),c=0;for(var i=0;i<s.length;i++){if(set.has(s[i]))c++;}return c;}'),

pdef('unique-occurrences', 'Unique Number of Occurrences', 'easy', 'uniqueOccurrences',
    sig(['arr' => 'int[]'], 'bool'),
    'Return true if the number of times each value occurs in the array is unique for every value.',
    ['1 ≤ arr.length ≤ 1000'],
    [t([[1, 2, 2, 1, 1, 3]], true, 1), t([[1, 2]], false, 1), t([[-3, 0, 1, -3, 1, 1, 1, -3, 10, 0]], true), t([[1]], true)],
    'function uniqueOccurrences(arr){var m={},i;for(i=0;i<arr.length;i++){m[arr[i]]=(m[arr[i]]||0)+1;}var counts=Object.values(m);return new Set(counts).size===counts.length;}'),

pdef('word-pattern', 'Word Pattern', 'easy', 'wordPattern',
    sig(['pattern' => 'str', 's' => 'str'], 'bool'),
    'Return true if s follows the pattern: a bijection between pattern letters and whole space-separated words.',
    ['1 ≤ pattern.length ≤ 300', 's is lowercase words separated by single spaces'],
    [t(['abba', 'dog cat cat dog'], true, 1), t(['abba', 'dog cat cat fish'], false, 1), t(['aaaa', 'dog cat mouse bird'], false), t(['abc', 'b c a'], true)],
    'function wordPattern(p,s){var w=s.split(" ");if(w.length!==p.length)return false;var f={},g={},i;for(i=0;i<p.length;i++){var c=p[i],x=w[i];if(c in f&&f[c]!==x)return false;if(x in g&&g[x]!==c)return false;f[c]=x;g[x]=c;}return true;}'),

pdef('isomorphic-strings', 'Isomorphic Strings', 'easy', 'isIsomorphic',
    sig(['s' => 'str', 't2' => 'str'], 'bool'),
    'Two strings are isomorphic if characters of s can be replaced (consistently, one-to-one) to get t2. Return true if they are isomorphic.',
    ['1 ≤ s.length ≤ 5·10⁴', 't2 has the same length as s'],
    [t(['egg', 'add'], true, 1), t(['foo', 'bar'], false, 1), t(['paper', 'title'], true), t(['badc', 'baba'], false)],
    'function isIsomorphic(s,t){var f={},g={},i;for(i=0;i<s.length;i++){var a=s[i],b=t[i];if(a in f&&f[a]!==b)return false;if(b in g&&g[b]!==a)return false;f[a]=b;g[b]=a;}return true;}'),

pdef('find-common-chars', 'Find Common Characters', 'easy', 'commonChars',
    sig(['words' => 'str[]'], 'str[]'),
    'Return the characters common to ALL words, counting duplicates (a char that appears twice in every word appears twice in the answer). Sort the result alphabetically.',
    ['1 ≤ words.length ≤ 100', 'lowercase letters'],
    [t([['cool', 'lock', 'cook']], ['c', 'o'], 1), t([['bella', 'label', 'roller']], ['e', 'l', 'l'], 1), t([['a', 'a']], ['a']), t([['ab', 'ba']], ['a', 'b'])],
    'function commonChars(words){var cnt=words[0].split(""),w,i,j;for(i=1;i<words.length;i++){for(j=cnt.length-1;j>=0;j--){var idx=words[i].indexOf(cnt[j]);if(idx<0)cnt.splice(j,1);else{words[i]=words[i].slice(0,idx)+words[i].slice(idx+1);}}}return cnt.sort();}'),

pdef('most-frequent', 'Most Frequent Element', 'easy', 'mostFrequent',
    sig(['nums' => 'int[]'], 'int'),
    'Return the value that occurs most often. On a tie, return the numerically smallest of the tied values.',
    ['1 ≤ nums.length ≤ 10⁴'],
    [t([[1, 3, 2, 1, 4, 1]], 1, 1), t([[7]], 7, 1), t([[1, 2, 2, 3, 3]], 2), t([[5, 5, 9, 9]], 5)],
    'function mostFrequent(nums){var m={},i;for(i=0;i<nums.length;i++){m[nums[i]]=(m[nums[i]]||0)+1;}var best=Infinity,bc=0;for(var k in m){if(m[k]>bc||(m[k]===bc&&(+k)<best)){bc=m[k];best=+k;}}return best;}'),

pdef('tally-scores', 'Tally Scores', 'easy', 'tallyScores',
    sig(['names' => 'str[]', 'points' => 'int[]'], 'map'),
    'A scoreboard logs scoring events in parallel arrays: names[i] scored points[i] (points may be negative). Add everything up and return a {player: totalScore} object.',
    ['0 ≤ events ≤ 10⁴', 'names.length === points.length'],
    [t([['amy', 'bob', 'amy'], [10, 5, 7]], ['amy' => 17, 'bob' => 5], 1), t([[], []], new stdClass(), 1),
     t([['z'], [-3]], ['z' => -3]), t([['a', 'a'], [1, 1]], ['a' => 2])],
    'function tallyScores(names,points){var m={};for(var i=0;i<names.length;i++){m[names[i]]=(m[names[i]]||0)+points[i];}return m;}'),

pdef('inventory-merge', 'Merge Inventories', 'easy', 'mergeInventory',
    sig(['a' => 'map', 'b' => 'map'], 'map'),
    'Two stores keep inventory as {item: quantity} objects. Merge them: if an item exists in both, sum the quantities. Return the merged object.',
    ['0 ≤ items per store ≤ 10⁴', 'quantities ≥ 0'],
    [t([['apple' => 3, 'pear' => 2], ['apple' => 1, 'kiwi' => 4]], ['apple' => 4, 'kiwi' => 4, 'pear' => 2], 1),
     t([new stdClass(), ['x' => 1]], ['x' => 1], 1), t([['a' => 0], new stdClass()], ['a' => 0])],
    'function mergeInventory(a,b){var m={},k;for(k in a)m[k]=a[k];for(k in b)m[k]=(m[k]||0)+b[k];return m;}'),

pdef('longest-consecutive', 'Longest Consecutive Sequence', 'medium', 'longestConsecutive',
    sig(['nums' => 'int[]'], 'int'),
    'Return the length of the longest run of consecutive integers present anywhere in nums. Aim for O(n) — a hash set makes it possible.',
    ['0 ≤ nums.length ≤ 10⁵', '-10⁹ ≤ nums[i] ≤ 10⁹'],
    [t([[100, 4, 200, 1, 3, 2]], 4, 1), t([[0, 3, 7, 2, 5, 8, 4, 6, 0, 1]], 9, 1), t([[]], 0), t([[1, 2, 0, 1]], 3)],
    'function longestConsecutive(nums){var s=new Set(nums),best=0;for(var n of nums){if(!s.has(n-1)){var len=1;while(s.has(n+len))len++;best=Math.max(best,len);}}return best;}'),

pdef('two-out-of-three', 'Two Out of Three', 'easy', 'twoOutOfThree',
    sig(['nums1' => 'int[]', 'nums2' => 'int[]', 'nums3' => 'int[]'], 'int[]'),
    'Return every distinct value present in at least TWO of the three arrays, sorted ascending.',
    ['1 ≤ nums.length ≤ 100', '1 ≤ values ≤ 100'],
    [t([[1, 1, 3, 2], [2, 3], [3]], [2, 3], 1), t([[3, 1], [2, 3], [1, 2]], [1, 2, 3], 1), t([[1, 2, 2], [4, 3, 3], [5]], [])],
    'function twoOutOfThree(a,b,c){function S(x){return new Set(x);}var A=S(a),B=S(b),C=S(c),cnt={};[A,B,C].forEach(function(st){st.forEach(function(v){cnt[v]=(cnt[v]||0)+1;});});return Object.keys(cnt).filter(function(k){return cnt[k]>=2;}).map(Number).sort(function(x,y){return x-y;});}'),

pdef('equal-pairs-grid', 'Equal Row and Column Pairs', 'medium', 'equalPairs',
    sig(['grid' => 'int[][]'], 'int'),
    'Count pairs (row, column) in the n×n grid whose value sequences are identical.',
    ['1 ≤ n ≤ 200', '1 ≤ grid[i][j] ≤ 10⁵'],
    [t([[[3, 2, 1], [1, 7, 6], [2, 7, 7]]], 1, 1), t([[[3, 1, 2, 2], [1, 4, 4, 5], [2, 4, 2, 2], [2, 4, 2, 2]]], 3, 1), t([[[1]]], 1)],
    'function equalPairs(g){var n=g.length,ans=0;for(var r=0;r<n;r++)for(var c=0;c<n;c++){var ok=true;for(var k=0;k<n;k++)if(g[r][k]!==g[k][c]){ok=false;break;}if(ok)ans++;}return ans;}'),

pdef('similar-pairs', 'Count Pairs Of Similar Strings', 'easy', 'similarPairs',
    sig(['words' => 'str[]'], 'int'),
    'Two words are similar if they use the same SET of characters. Count similar pairs i < j.',
    ['1 ≤ words.length ≤ 100', 'lowercase letters only'],
    [t([['aba', 'aabb', 'abcd', 'bac', 'aabc']], 2, 1), t([['a', 'aa', 'aaa', 'aaaa']], 6, 1), t([['nba', 'cba', 'dba']], 0)],
    'function similarPairs(words){var mask=words.map(function(w){var s=new Set(w.split(""));return Array.from(s).sort().join("");});var c=0;for(var i=0;i<mask.length;i++)for(var j=i+1;j<mask.length;j++)if(mask[i]===mask[j])c++;return c;}'),

pdef('check-frequencies-equal', 'Equal Frequency After One Removal', 'easy', 'equalFrequency',
    sig(['word' => 'str'], 'bool'),
    'Return true if removing exactly ONE character can make every remaining letter occur the same number of times.',
    ['2 ≤ word.length ≤ 100 (lowercase)'],
    [t(['abcc'], true, 1), t(['aazz'], false, 1), t(['bac'], true), t(['ddaccb'], false)],
    'function equalFrequency(w){var c={};for(var i=0;i<w.length;i++)c[w[i]]=(c[w[i]]||0)+1;for(var k in c){c[k]--;var ok=true,seen=-1;for(var j in c){if(c[j]===0)continue;if(seen<0)seen=c[j];else if(c[j]!==seen){ok=false;break;}}c[k]++;if(ok)return true;}return false;}'),

pdef('smallest-index-equal', 'Smallest Index With Equal Value', 'easy', 'smallestEqual',
    sig(['nums' => 'int[]'], 'int'),
    'Return the smallest index i where i mod 10 equals nums[i], or -1.',
    ['1 ≤ nums.length ≤ 100', '0 ≤ nums[i] ≤ 9'],
    [t([[0, 1, 2]], 0, 1), t([[4, 3, 2, 1]], 2, 1), t([[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]], -1), t([[7, 8, 3, 5, 2, 6, 3, 1, 1, 4, 5]], -1)],
    'function smallestEqual(nums){for(var i=0;i<nums.length;i++)if(i%10===nums[i])return i;return -1;}'),

pdef('count-good-meals', 'Count Good Meals', 'medium', 'countPairs',
    sig(['deliciousness' => 'int[]'], 'int'),
    'A "good meal" is a pair i ≠ j whose sum is a power of two. Count good meals (i < j).',
    ['1 ≤ deliciousness.length ≤ 10⁵', '0 ≤ values ≤ 2²⁰'],
    [t([[1, 3, 5, 7, 9]], 4, 1), t([[1, 1, 1, 3, 3, 3, 7]], 15, 1), t([[2, 14]], 1)],
    'function countPairs(d){var c={},ans=0;for(var i=0;i<d.length;i++){for(var p=1;p<=2097152;p*=2){ans+=c[p-d[i]]||0;}c[d[i]]=(c[d[i]]||0)+1;}return ans;}'),

pdef('equivalent-dominoes', 'Number of Equivalent Domino Pairs', 'easy', 'numEquivDominoPairs',
    sig(['a' => 'int[]', 'b' => 'int[]'], 'int'),
    'Domino i is (a[i], b[i]); two dominoes are equivalent if they are equal up to rotation. Count equivalent pairs.',
    ['1 ≤ a.length ≤ 4·10⁴', 'a.length == b.length', '1 ≤ values ≤ 9'],
    [t([[1, 2, 3, 5], [2, 1, 4, 6]], 1, 1), t([[1, 2, 1, 2], [2, 1, 2, 1]], 6, 1), t([[1], [2]], 0)],
    'function numEquivDominoPairs(a,b){var c={},ans=0;for(var i=0;i<a.length;i++){var k=Math.min(a[i],b[i])+","+Math.max(a[i],b[i]);ans+=c[k]||0;c[k]=(c[k]||0)+1;}return ans;}'),

pdef('intersection-multiple', 'Intersection of Multiple Arrays', 'easy', 'intersection',
    sig(['nums' => 'int[][]'], 'int[]'),
    'Return the values present in EVERY array of the list, sorted ascending.',
    ['1 ≤ nums.length ≤ 1000', 'values within each array are distinct'],
    [t([[[3, 1, 2, 4, 5], [1, 2, 3, 4], [3, 4, 5, 6]]], [3, 4], 1), t([[[1, 2, 3], [4, 5, 6]]], [], 1), t([[[4, 2], [2, 4], [2]]], [2])],
    'function intersection(nums){var c={},n=nums.length,out=[];nums.forEach(function(a){a.forEach(function(v){c[v]=(c[v]||0)+1;});});for(var k in c)if(c[k]===n)out.push(Number(k));return out.sort(function(x,y){return x-y;});}'),

pdef('count-common-occurrence', 'Count Common Words With One Occurrence', 'easy', 'countWords',
    sig(['words1' => 'str[]', 'words2' => 'str[]'], 'int'),
    'Count words appearing exactly ONCE in each of the two lists (same word in both).',
    ['1 ≤ words.length ≤ 1000 (lowercase)'],
    [t([['leetcode', 'is', 'amazing', 'as', 'is'], ['amazing', 'leetcode', 'is']], 2, 1),
     t([['b', 'bb', 'bbb'], ['a', 'aa', 'aaa']], 0, 1), t([['a', 'ab'], ['a', 'a', 'b', 'ab']], 1)],
    'function countWords(w1,w2){function cnt(w){var c={};w.forEach(function(x){c[x]=(c[x]||0)+1;});return c;}var a=cnt(w1),b=cnt(w2),n=0;for(var k in a)if(a[k]===1&&b[k]===1)n++;return n;}'),

pdef('uncommon-sentences', 'Uncommon Words from Two Sentences', 'easy', 'uncommonFromSentences',
    sig(['s1' => 'str', 's2' => 'str'], 'str[]'),
    'A word is uncommon if it appears exactly once across BOTH sentences total. Return them (sorted).',
    ['1 ≤ s1.length, s2.length ≤ 200 (lowercase + single spaces)'],
    [t(['this apple is sweet', 'this apple is sour'], ['sour', 'sweet'], 1), t(['apple apple', 'banana'], ['banana'], 1), t(['a b c', 'a'], ['b', 'c'])],
    'function uncommonFromSentences(a,b){var c={};(a+" "+b).split(" ").forEach(function(w){c[w]=(c[w]||0)+1;});return Object.keys(c).filter(function(w){return c[w]===1;}).sort();}'),

pdef('fair-candy-swap', 'Fair Candy Swap', 'easy', 'fairCandySwap',
    sig(['aliceSizes' => 'int[]', 'bobSizes' => 'int[]'], 'int[]'),
    'Alice and Bob swap exactly one box each so their totals become equal. Return [aliceBox, bobBox] from the (unique) guaranteed answer.',
    ['1 ≤ both lengths ≤ 10⁴', 'an answer exists and is unique'],
    [t([[1, 1], [2, 2]], [1, 2], 1), t([[1, 2], [2, 3]], [1, 2], 1), t([[2], [1, 3]], [2, 3])],
    'function fairCandySwap(a,b){var sa=0,sb=0,i;a.forEach(function(v){sa+=v;});b.forEach(function(v){sb+=v;});var setB=new Set(b),target=(sb-sa)/2;for(i=0;i<a.length;i++){if(setB.has(a[i]+target))return [a[i],a[i]+target];}return [];}'),

pdef('min-index-sum', 'Minimum Index Sum of Two Lists', 'easy', 'findRestaurant',
    sig(['list1' => 'str[]', 'list2' => 'str[]'], 'str[]'),
    'Return all common strings with the minimum sum of positions across the two lists, in list1 order.',
    ['1 ≤ both lengths ≤ 1000', 'no duplicates within a list'],
    [t([['Shogun', 'Tapioca Express', 'Burger King', 'KFC'], ['Piatti', 'The Grill at Torrey Pines', 'Hungry Hunter Steakhouse', 'Shogun']], ['Shogun'], 1),
     t([['happy', 'sad', 'good'], ['sad', 'happy', 'good']], ['happy', 'sad'], 1), t([['a'], ['b']], [])],
    'function findRestaurant(l1,l2){var pos={};l2.forEach(function(w,i){pos[w]=i;});var best=1e9,out=[];l1.forEach(function(w,i){if(pos[w]===undefined)return;var s=i+pos[w];if(s<best){best=s;out=[w];}else if(s===best)out.push(w);});return out;}'),

pdef('max-balloons', 'Maximum Number of Balloons', 'easy', 'maxNumberOfBalloons',
    sig(['text' => 'str'], 'int'),
    'How many times can you form the word "balloon" from the letters of text?',
    ['1 ≤ text.length ≤ 10⁴ (lowercase)'],
    [t(['nlaebolko'], 1, 1), t(['loonbalxballpoon'], 2, 1), t(['leetcode'], 0), t(['balloon'], 1)],
    'function maxNumberOfBalloons(t){var c={};for(var i=0;i<t.length;i++)c[t[i]]=(c[t[i]]||0)+1;return Math.min(c.b||0,c.a||0,(c.l||0)>>1,(c.o||0)>>1,c.n||0);}'),

pdef('sort-chars-freq', 'Sort Characters By Frequency', 'medium', 'frequencySort',
    sig(['s' => 'str'], 'str'),
    'Sort the characters of s by decreasing frequency, keeping equal-frequency groups together with repeated characters.',
    ['1 ≤ s.length ≤ 5·10⁵', 'letters and digits'],
    [t(['treee'], 'eeetr', 1), t(['Aabb'], 'bbAa', 1), t(['cccaaaab'], 'aaaacccb')],
    'function frequencySort(s){var c={};for(var i=0;i<s.length;i++)c[s[i]]=(c[s[i]]||0)+1;return Object.keys(c).sort(function(a,b){return c[b]-c[a];}).map(function(k){return k.repeat(c[k]);}).join("");}'),

pdef('min-ops-distinct', 'Minimum Operations to Make Array Distinct (by Deletion)', 'easy', 'minimumOperations',
    sig(['nums' => 'int[]'], 'int'),
    'Repeatedly delete exactly three elements from the FRONT. How many such deletions until all remaining values are distinct?',
    ['0 ≤ nums.length ≤ 100', '1 ≤ nums[i] ≤ 100'],
    [t([[1, 2, 3, 4, 2, 3, 3, 5, 7]], 2, 1), t([[4, 5, 6, 4, 4]], 2, 1), t([[1, 2, 3]], 0), t([[6, 7, 8, 9]], 0)],
    'function minimumOperations(nums){for(var d=0;;d++){var a=nums.slice(d*3);if(new Set(a).size===a.length)return d;}}'),

pdef('count-special-quadruplets', 'Count Special Quadruplets', 'easy', 'countQuadruplets',
    sig(['nums' => 'int[]'], 'int'),
    'Count quadruplets a < b < c < d with nums[a] + nums[b] + nums[c] === nums[d].',
    ['4 ≤ nums.length ≤ 50', '1 ≤ nums[i] ≤ 100'],
    [t([[1, 2, 3, 6]], 1, 1), t([[3, 3, 6, 4, 5]], 0, 1), t([[1, 1, 1, 3, 5]], 4), t([[2, 16, 9, 27, 3, 39]], 2)],
    'function countQuadruplets(nums){var n=nums.length,c=0;for(var d=3;d<n;d++)for(var a=0;a<d-2;a++)for(var b=a+1;b<d-1;b++)for(var cc=b+1;cc<d;cc++)if(nums[a]+nums[b]+nums[cc]===nums[d])c++;return c;}'),

pdef('max-frequency-equal-ops', 'Frequency of the Most Frequent Element', 'medium', 'maxFrequency',
    sig(['nums' => 'int[]', 'k' => 'int'], 'int'),
    'In one "operation" you may increment any element by 1. After at most k operations, return the maximum frequency of any value.',
    ['1 ≤ nums.length ≤ 10⁵', '1 ≤ nums[i] ≤ 10⁵', '1 ≤ k ≤ 10⁵'],
    [t([[1, 2, 4], 5], 3, 1), t([[1, 4, 8, 13], 5], 2, 1), t([[3, 9, 6], 2], 1), t([[9930, 9923], 7], 2)],
    'function maxFrequency(nums,k){nums.sort(function(a,b){return a-b;});var l=0,s=0,b=1;for(var r=0;r<nums.length;r++){s+=nums[r];while((r-l+1)*nums[r]-s>k){s-=nums[l];l++;}b=Math.max(b,r-l+1);}return b;}'),

pdef('subarray-sum-k', 'Subarray Sum Equals K', 'medium', 'subarraySum',
    sig(['nums' => 'int[]', 'k' => 'int'], 'int'),
    'Count the contiguous subarrays whose elements sum to exactly k.',
    ['1 ≤ nums.length ≤ 2·10⁴', '-1000 ≤ nums[i] ≤ 1000'],
    [t([[1, 1, 1], 2], 2, 1), t([[1, 2, 3], 3], 2, 1), t([[1], 1], 1), t([[3, 4, 7, 2, -3, 1, 4, 2], 7], 4)],
    'function subarraySum(nums,k){var pre={0:1},s=0,ans=0;for(var i=0;i<nums.length;i++){s+=nums[i];ans+=pre[s-k]||0;pre[s]=(pre[s]||0)+1;}return ans;}'),

pdef('contiguous-array', 'Contiguous Array', 'medium', 'findMaxLength',
    sig(['nums' => 'int[]'], 'int'),
    'Find the longest contiguous subarray with an equal number of 0s and 1s; return its length.',
    ['1 ≤ nums.length ≤ 10⁵', 'nums[i] is 0 or 1'],
    [t([[0, 1]], 2, 1), t([[0, 1, 0]], 2, 1), t([[0, 1, 1, 1, 1, 1, 0, 0, 0]], 6), t([[0, 0, 1, 0, 0, 0, 1, 1]], 6)],
    'function findMaxLength(nums){var first={0:-1},s=0,b=0;for(var i=0;i<nums.length;i++){s+=nums[i]===1?1:-1;if(first[s]!==undefined)b=Math.max(b,i-first[s]);else first[s]=i;}return b;}'),

pdef('check-inclusion', 'Permutation in String', 'medium', 'checkInclusion',
    sig(['s1' => 'str', 's2' => 'str'], 'bool'),
    'Return true if any permutation of s1 is a substring of s2 (i.e. some window matches its letter counts).',
    ['1 ≤ s1.length ≤ 10⁴', '1 ≤ s2.length ≤ 10⁴ (lowercase)'],
    [t(['ab', 'eidbaooo'], true, 1), t(['ab', 'eidboaoo'], false, 1), t(['adc', 'dcda'], true), t(['abc', 'bbbca'], true)],
    'function checkInclusion(a,b){if(a.length>b.length)return false;var ca=new Array(26).fill(0),cb=new Array(26).fill(0);function ix(c){return c.charCodeAt(0)-97;}for(var i=0;i<a.length;i++){ca[ix(a[i])]++;cb[ix(b[i])]++;}function eq(){for(var k=0;k<26;k++)if(ca[k]!==cb[k])return false;return true;}if(eq())return true;for(var j=a.length;j<b.length;j++){cb[ix(b[j])]++;cb[ix(b[j-a.length])]--;if(eq())return true;}return false;}'),

pdef('min-window-substring', 'Minimum Window Substring', 'hard', 'minWindow',
    sig(['s' => 'str', 't' => 'str'], 'str'),
    'Return the smallest substring of s containing every character of t (with multiplicity). Guaranteed unique; "" if none.',
    ['1 ≤ s.length, t.length ≤ 10⁵'],
    [t(['ADOBECODEBANC', 'ABC'], 'BANC', 1), t(['a', 'a'], 'a', 1), t(['a', 'aa'], ''), t(['ab', 'b'], 'b')],
    'function minWindow(s,t){var need={},missing=t.length;for(var i=0;i<t.length;i++)need[t[i]]=(need[t[i]]||0)+1;var l=0,bl=0,blen=Infinity;for(var r=0;r<s.length;r++){var c=s[r];if(need[c]>0)missing--;need[c]=(need[c]||0)-1;while(missing===0){if(r-l+1<blen){blen=r-l+1;bl=l;}var lc=s[l];need[lc]++;if(need[lc]>0)missing++;l++;}}return blen===Infinity?"":s.slice(bl,bl+blen);}'),

pdef('longest-no-repeat', 'Longest Substring Without Repeating Characters', 'medium', 'lengthOfLongestSubstring',
    sig(['s' => 'str'], 'int'),
    'Return the length of the longest substring with all distinct characters.',
    ['0 ≤ s.length ≤ 5·10⁴'],
    [t(['abcabcbb'], 3, 1), t(['bbbbb'], 1, 1), t(['pwwkew'], 3), t([''], 0)],
    'function lengthOfLongestSubstring(s){var last={},l=0,b=0;for(var r=0;r<s.length;r++){var c=s[r];if(last[c]!==undefined&&last[c]>=l)l=last[c]+1;last[c]=r;b=Math.max(b,r-l+1);}return b;}'),

pdef('fruit-baskets', 'Fruit Into Baskets', 'medium', 'totalFruit',
    sig(['fruits' => 'int[]'], 'int'),
    'You have two "baskets" (one type each). Walking left to right without skipping, find the longest run using at most two fruit types.',
    ['1 ≤ fruits.length ≤ 10⁵', '0 ≤ fruits[i] < fruits.length'],
    [t([[1, 2, 1]], 3, 1), t([[0, 1, 2, 2]], 3, 1), t([[1, 2, 3, 2, 2]], 4), t([[3, 3, 3, 1, 2, 1, 1, 2, 3, 3, 4]], 5)],
    'function totalFruit(f){var last={},l=0,b=0;for(var r=0;r<f.length;r++){last[f[r]]=r;while(Object.keys(last).length>2){if(last[f[l]]===l)delete last[f[l]];l++;}b=Math.max(b,r-l+1);}return b;}'),

pdef('repeating-replacement', 'Longest Repeating Character Replacement', 'medium', 'characterReplacement',
    sig(['s' => 'str', 'k' => 'int'], 'int'),
    'You may change at most k characters anywhere. Return the longest possible run of one repeated character.',
    ['1 ≤ s.length ≤ 10⁵ (uppercase)', '0 ≤ k ≤ s.length'],
    [t(['ABAB', 2], 4, 1), t(['AABABBA', 1], 4, 1), t(['AAAA', 0], 4), t(['ABCDE', 1], 2)],
    'function characterReplacement(s,k){var c={},l=0,b=0,m=0;for(var r=0;r<s.length;r++){c[s[r]]=(c[s[r]]||0)+1;m=Math.max(m,c[s[r]]);while(r-l+1-m>k){c[s[l]]--;l++;}b=Math.max(b,r-l+1);}return b;}'),

pdef('min-deletions-freq', 'Minimum Deletions to Make Character Frequencies Unique', 'medium', 'minDeletions',
    sig(['s' => 'str'], 'int'),
    'Delete characters so no two distinct letters keep the same frequency. Return the minimum deletions.',
    ['1 ≤ s.length ≤ 10⁵ (lowercase)'],
    [t(['aab'], 0, 1), t(['aaabbbcc'], 2, 1), t(['ceabaacb'], 2), t(['abcabc'], 3)],
    'function minDeletions(s){var c={};for(var i=0;i<s.length;i++)c[s[i]]=(c[s[i]]||0)+1;var used=new Set(),d=0;for(var k in c){var f=c[k];while(f>0&&used.has(f))f--,d++;if(f>0)used.add(f);}return d;}'),

pdef('count-nice-pairs', 'Count Nice Pairs in an Array', 'medium', 'countNicePairs',
    sig(['nums' => 'int[]'], 'int'),
    'A pair i < j is nice if nums[i] + rev(nums[j]) === nums[j] + rev(nums[i]). Count them.',
    ['1 ≤ nums.length ≤ 10⁵', '1 ≤ nums[i] ≤ 10⁹'],
    [t([[42, 11, 1, 97]], 2, 1), t([[13, 10, 35, 24, 76]], 4, 1), t([[1, 2, 3]], 3)],
    'function countNicePairs(nums){function rev(x){return Number(String(x).split("").reverse().join(""));}var c={},ans=0;for(var i=0;i<nums.length;i++){var d=nums[i]-rev(nums[i]);ans+=c[d]||0;c[d]=(c[d]||0)+1;}return ans;}'),

pdef('max-erasure-value', 'Maximum Erasure Value', 'medium', 'maximumUniqueSubarray',
    sig(['nums' => 'int[]'], 'int'),
    'The score of a subarray is its sum; it is only valid if all elements are unique. Return the maximum valid score.',
    ['1 ≤ nums.length ≤ 10⁵', '1 ≤ nums[i] ≤ 10⁴'],
    [t([[4, 2, 4, 5, 6]], 17, 1), t([[5, 2, 1, 2, 5, 2, 1, 2, 5]], 8, 1), t([[1]], 1), t([[3, 3, 3]], 3)],
    'function maximumUniqueSubarray(nums){var l=0,s=0,b=0,seen=new Set();for(var r=0;r<nums.length;r++){while(seen.has(nums[r])){seen.delete(nums[l]);s-=nums[l];l++;}seen.add(nums[r]);s+=nums[r];b=Math.max(b,s);}return b;}'),

pdef('number-boomerangs', 'Number of Boomerangs', 'medium', 'numberOfBoomerangs',
    sig(['xs' => 'int[]', 'ys' => 'int[]'], 'int'),
    'Point i is (xs[i], ys[i]). A boomerang is an ordered triple (i, j, k) with equal distance from i to j and i to k, j ≠ k. Count them.',
    ['1 ≤ n ≤ 500', 'points are pairwise distinct'],
    [t([[0, 1, 2], [0, 0, 0]], 2, 1), t([[0, 1, 2], [0, 0, 1]], 0, 1), t([[1, 1, 2, 3], [1, 2, 2, 3]], 4)],
    'function numberOfBoomerangs(xs,ys){var ans=0;for(var i=0;i<xs.length;i++){var d={};for(var j=0;j<xs.length;j++){if(i===j)continue;var k=(xs[i]-xs[j])**2+(ys[i]-ys[j])**2;d[k]=(d[k]||0)+1;}for(var key in d)ans+=d[key]*(d[key]-1);}return ans;}'),

pdef('repeated-dna', 'Repeated DNA Sequences', 'medium', 'findRepeatedDnaSequences',
    sig(['s' => 'str'], 'str[]'),
    'Find every 10-letter sequence that occurs more than once in the DNA string (A,C,G,T). Return them sorted.',
    ['1 ≤ s.length ≤ 10⁵', 's contains only A,C,G,T'],
    [t(['AAAAACCCCCAAAAACCCCCCAAAAAGGGTTT'], ['AAAAACCCCC', 'CCCCCAAAAA'], 1), t(['AAAAAAAAAAAAA'], ['AAAAAAAAAA'], 1), t(['ACGTACGT'], [])],
    'function findRepeatedDnaSequences(s){var seen=new Set(),dup=new Set();for(var i=0;i+10<=s.length;i++){var sub=s.slice(i,i+10);if(seen.has(sub))dup.add(sub);seen.add(sub);}return Array.from(dup).sort();}'),

pdef('count-largest-group', 'Count Largest Group', 'easy', 'countLargestGroup',
    sig(['n' => 'int'], 'int'),
    'Group integers 1..n by their digit sum. Return how many groups tie for the largest size.',
    ['1 ≤ n ≤ 10⁴'],
    [t([13], 4, 1), t([2], 2, 1), t([15], 6), t([24], 5)],
    'function countLargestGroup(n){function ds(x){var s=0;while(x>0){s+=x%10;x=(x/10)|0;}return s;}var c={},mx=0;for(var i=1;i<=n;i++){var k=ds(i);c[k]=(c[k]||0)+1;mx=Math.max(mx,c[k]);}var ans=0;for(var key in c)if(c[key]===mx)ans++;return ans;}'),

pdef('max-sum-digit-pair', 'Max Pair Sum With Equal Digit Sum', 'medium', 'maximumSum',
    sig(['nums' => 'int[]'], 'int'),
    'Among pairs whose elements have the same digit sum, find the maximum pair sum; -1 if none.',
    ['1 ≤ nums.length ≤ 10⁵', '1 ≤ nums[i] ≤ 10⁹'],
    [t([[18, 43, 36, 13, 7]], 54, 1), t([[10, 12, 19, 14]], -1, 1), t([[51, 71, 17, 42]], 93)],
    'function maximumSum(nums){function ds(x){var s=0;while(x>0){s+=x%10;x=(x/10)|0;}return s;}var best={},ans=-1;for(var i=0;i<nums.length;i++){var k=ds(nums[i]);if(best[k]!==undefined){ans=Math.max(ans,best[k]+nums[i]);best[k]=Math.max(best[k],nums[i]);}else best[k]=nums[i];}return ans;}'),

pdef('min-penalty-shop', 'Minimum Penalty for a Shop', 'medium', 'bestClosingTime',
    sig(['customers' => 'str'], 'int'),
    'At each hour i, customers[i] is "Y" (visitors) or "N". Closing at hour j (0..n) costs: 1 per Y-hour after j (missed) plus 1 per N-hour before j (idle). Return the earliest hour minimizing the penalty.',
    ['1 ≤ customers.length ≤ 10⁵'],
    [t(['YYNY'], 2, 1), t(['NNNNN'], 0, 1), t(['YYYY'], 4)],
    'function bestClosingTime(c){var totalY=c.split("").filter(function(x){return x==="Y";}).length,best=totalY,bestH=0,pen=totalY;for(var j=1;j<=c.length;j++){pen+=c[j-1]==="Y"?-1:1;if(pen<best){best=pen;bestH=j;}}return bestH;}'),

pdef('valid-sudoku', 'Valid Sudoku', 'medium', 'isValidSudoku',
    sig(['board' => 'int[][]'], 'bool'),
    'A 9×9 board; blanks are -1. Return true if every row, column and 3×3 box contains no repeated digit.',
    ['9×9 board', 'digits 1..9 or -1'],
    [t([[[5,3,-1,-1,7,-1,-1,-1,-1],[6,-1,-1,1,9,5,-1,-1,-1],[-1,9,8,-1,-1,-1,-1,6,-1],[8,-1,-1,-1,6,-1,-1,-1,3],[4,-1,-1,8,-1,3,-1,-1,1],[7,-1,-1,-1,2,-1,-1,-1,6],[-1,6,-1,-1,-1,-1,2,8,-1],[-1,-1,-1,4,1,9,-1,-1,5],[-1,-1,-1,-1,8,-1,-1,7,9]]], true, 1),
     t([[[8,3,-1,-1,7,-1,-1,-1,-1],[6,-1,-1,1,9,5,-1,-1,-1],[-1,9,8,-1,-1,-1,-1,6,-1],[8,-1,-1,-1,6,-1,-1,-1,3],[4,-1,-1,8,-1,3,-1,-1,1],[7,-1,-1,-1,2,-1,-1,-1,6],[-1,6,-1,-1,-1,-1,2,8,-1],[-1,-1,-1,4,1,9,-1,-1,5],[-1,-1,-1,-1,8,-1,-1,7,9]]], false, 1)],
    'function isValidSudoku(b){var seen=new Set();for(var r=0;r<9;r++)for(var c=0;c<9;c++){var v=b[r][c];if(v<0)continue;var a="r"+r+v,d="c"+c+v,g="b"+((r/3|0)*3+(c/3|0))+v;if(seen.has(a)||seen.has(d)||seen.has(g))return false;seen.add(a);seen.add(d);seen.add(g);}return true;}'),

pdef('number-substrings-abc', 'Number of Substrings Containing All Three Characters', 'medium', 'numberOfSubstrings',
    sig(['s' => 'str'], 'int'),
    'Count substrings that contain at least one a, one b and one c.',
    ['3 ≤ s.length ≤ 5·10⁴', 'only letters a, b, c'],
    [t(['abcabc'], 10, 1), t(['aaacb'], 3, 1), t(['abc'], 1), t(['aabbcc'], 4)],
    'function numberOfSubstrings(s){var last={a:-1,b:-1,c:-1},ans=0;for(var i=0;i<s.length;i++){last[s[i]]=i;ans+=Math.min(last.a,last.b,last.c)+1;}return ans;}'),

pdef('count-substrings-only-ones', 'Number of Substrings With Only 1s', 'medium', 'numSub',
    sig(['s' => 'str'], 'int'),
    'Count substrings consisting only of "1". (For runs of length L there are L(L+1)/2.)',
    ['1 ≤ s.length ≤ 10⁵', 'only 0/1'],
    [t(['0110111'], 9, 1), t(['101'], 2, 1), t(['111111'], 21), t(['000'], 0)],
    'function numSub(s){var run=0,ans=0;for(var i=0;i<s.length;i++){run=s[i]==="1"?run+1:0;ans+=run;}return ans;}'),

pdef('count-subarrays-fixed-bounds', 'Count Subarrays With Fixed Bounds', 'hard', 'countSubarrays',
    sig(['nums' => 'int[]', 'minK' => 'int', 'maxK' => 'int'], 'int'),
    'Count subarrays whose minimum is exactly minK and maximum exactly maxK.',
    ['2 ≤ nums.length ≤ 10⁵', '1 ≤ nums[i], minK, maxK ≤ 10⁶'],
    [t([[1, 3, 5, 2, 7, 5], 1, 5], 2, 1), t([[1, 1, 1, 1], 1, 1], 10, 1), t([[3, 1], 1, 3], 1)],
    'function countSubarrays(nums,lo,hi){var ans=0,lastBad=-1,lastLo=-1,lastHi=-1;for(var i=0;i<nums.length;i++){var v=nums[i];if(v<lo||v>hi)lastBad=i;if(v===lo)lastLo=i;if(v===hi)lastHi=i;ans+=Math.max(0,Math.min(lastLo,lastHi)-lastBad);}return ans;}'),

pdef('arithmetic-subarrays', 'Arithmetic Subarrays', 'medium', 'checkArithmeticSubarrays',
    sig(['nums' => 'int[]', 'l' => 'int[]', 'r' => 'int[]'], 'bool[]'),
    'For each query i, consider nums[l[i]..r[i]]: can it be rearranged into an arithmetic progression? Answer every query.',
    ['2 ≤ nums.length ≤ 500', '0 ≤ l[i] < r[i] < nums.length'],
    [t([[4, 6, 5, 9, 3, 7], [0, 0, 2], [2, 3, 5]], [true, false, true], 1),
     t([[-12, -9, -3, -12, -6, 15, 20, -25, -20, -15, -10], [0, 1, 6, 4, 8, 7], [4, 4, 9, 7, 9, 10]], [false, true, false, false, true, true], 1)],
    'function checkArithmeticSubarrays(nums,l,r){return l.map(function(a,i){var b=nums.slice(a,r[i]+1).sort(function(x,y){return x-y;});var d=b[1]-b[0];for(var k=2;k<b.length;k++)if(b[k]-b[k-1]!==d)return false;return true;});}'),
];
