<?php
// Category: math — number sense, digit tricks, sieves
return [
pdef('palindrome-number', 'Palindrome Number', 'easy', 'isPalindrome',
    sig(['x' => 'int'], 'bool'),
    'Given an integer x, return true if x reads the same forward and backward. Negative numbers are not palindromes.',
    ['-2³¹ ≤ x ≤ 2³¹ − 1'],
    [t([121], true, 1), t([-121], false, 1), t([10], false), t([0], true), t([1221], true)],
    'function isPalindrome(x){if(x<0)return false;var o=x,r=0;while(o>0){r=r*10+o%10;o=Math.floor(o/10);}return r===x;}',
    'Solve it without converting the integer to a string.'),

pdef('sum-digits', 'Sum of Digits', 'easy', 'sumDigits',
    sig(['n' => 'int'], 'int'),
    'Return the sum of the digits of n. Negative input sums the digits of its absolute value.',
    ['|n| ≤ 10⁹'],
    [t([1234], 10, 1), t([0], 0, 1), t([999], 27), t([-123], 6)],
    'function sumDigits(n){n=Math.abs(n);var s=0;while(n>0){s+=n%10;n=Math.floor(n/10);}return s;}'),

pdef('add-digits', 'Add Digits (Digital Root)', 'easy', 'addDigits',
    sig(['num' => 'int'], 'int'),
    'Repeatedly add the digits of num until a single digit remains, and return that digital root.',
    ['0 ≤ num ≤ 2³¹ − 1'],
    [t([38], 2, 1), t([0], 0, 1), t([159], 6), t([9], 9)],
    'function addDigits(n){return n===0?0:1+(n-1)%9;}',
    'The loop version is fine — but the one-liner above explains why the pattern repeats every 9.'),

pdef('power-of-two', 'Power of Two', 'easy', 'isPowerOfTwo',
    sig(['n' => 'int'], 'bool'),
    'Return true if n is a power of two (1, 2, 4, 8, …).',
    ['-2³¹ ≤ n ≤ 2³¹ − 1'],
    [t([16], true, 1), t([18], false, 1), t([1], true), t([0], false), t([-16], false)],
    'function isPowerOfTwo(n){return n>0&&(n&(n-1))===0;}'),

pdef('power-of-three', 'Power of Three', 'easy', 'isPowerOfThree',
    sig(['n' => 'int'], 'bool'),
    'Return true if n is a power of three (1, 3, 9, 27, …).',
    ['-2³¹ ≤ n ≤ 2³¹ − 1'],
    [t([27], true, 1), t([0], false, 1), t([9], true), t([45], false)],
    'function isPowerOfThree(n){while(n>0&&n%3===0)n/=3;return n===1;}'),

pdef('happy-number', 'Happy Number', 'easy', 'isHappy',
    sig(['n' => 'int'], 'bool'),
    'Replace n by the sum of the squares of its digits, and repeat. If the process reaches 1, n is happy — return true. Loops that never reach 1 return false.',
    ['1 ≤ n ≤ 2³¹ − 1'],
    [t([19], true, 1), t([2], false, 1), t([1], true), t([7], true)],
    'function isHappy(n){var seen={};while(n!==1&&!seen[n]){seen[n]=1;var s=0;while(n>0){var d=n%10;s+=d*d;n=Math.floor(n/10);}n=s;}return n===1;}'),

pdef('count-primes', 'Count Primes (Sieve)', 'medium', 'countPrimes',
    sig(['n' => 'int'], 'int'),
    'Count the prime numbers strictly less than n. The Sieve of Eratosthenes is your friend here.',
    ['0 ≤ n ≤ 5·10⁶'],
    [t([10], 4, 1), t([0], 0, 1), t([2], 0), t([100], 25)],
    'function countPrimes(n){if(n<3)return 0;var comp=new Array(n).fill(0),c=0,i,j;for(i=2;i*i<n;i++){if(!comp[i]){for(j=i*i;j<n;j+=i)comp[j]=1;}}for(i=2;i<n;i++){if(!comp[i])c++;}return c;}'),

pdef('gcd', 'Greatest Common Divisor', 'easy', 'gcd',
    sig(['a' => 'int', 'b' => 'int'], 'int'),
    'Return the greatest common divisor of a and b using Euclid’s algorithm.',
    ['0 ≤ a, b ≤ 10⁹', 'at least one of them is positive'],
    [t([12, 18], 6, 1), t([7, 0], 7, 1), t([100, 75], 25), t([17, 13], 1)],
    'function gcd(a,b){while(b){var t=a%b;a=b;b=t;}return a;}'),

pdef('lcm', 'Least Common Multiple', 'easy', 'lcm',
    sig(['a' => 'int', 'b' => 'int'], 'int'),
    'Return the least common multiple of a and b. Hint: lcm(a,b) = a × b / gcd(a,b) — but divide first to avoid overflow.',
    ['1 ≤ a, b ≤ 10⁴'],
    [t([4, 6], 12, 1), t([3, 7], 21, 1), t([10, 5], 10), t([1, 100], 100)],
    'function lcm(a,b){var g=function(x,y){while(y){var t=x%y;x=y;y=t;}return x;};return a/g(a,b)*b;}'),

pdef('perfect-number', 'Perfect Number', 'easy', 'checkPerfectNumber',
    sig(['num' => 'int'], 'bool'),
    'A perfect number equals the sum of its proper divisors (divisors smaller than itself): 6 = 1+2+3. Return true if num is perfect.',
    ['1 ≤ num ≤ 10⁸'],
    [t([6], true, 1), t([28], true, 1), t([12], false), t([1], false)],
    'function checkPerfectNumber(n){if(n<=1)return false;var s=1,i;for(i=2;i*i<=n;i++){if(n%i===0){s+=i;if(i!==n/i)s+=n/i;}}return s===n;}'),

pdef('sqrt-newton', 'Square Root (Integer)', 'medium', 'mySqrt',
    sig(['x' => 'int'], 'int'),
    'Compute the square root of x rounded DOWN to the nearest integer, without calling any built-in square root function. Binary search or Newton iteration both work.',
    ['0 ≤ x ≤ 2³¹ − 1'],
    [t([8], 2, 1), t([4], 2, 1), t([1], 1), t([0], 0), t([1000000], 1000)],
    'function mySqrt(x){var lo=0,hi=x,ans=0;while(lo<=hi){var mid=(lo+hi)>>1,v=mid*mid;if(v===x)return mid;if(v<x){ans=mid;lo=mid+1;}else{hi=mid-1;}}return ans;}'),

pdef('roman-to-integer', 'Roman to Integer', 'medium', 'romanToInt',
    sig(['s' => 'str'], 'int'),
    'Convert a Roman numeral to an integer. Symbols are I V X L C D M; a smaller symbol before a larger one subtracts (IV=4, IX=9).',
    ['1 ≤ s.length ≤ 15', 'input is a valid Roman numeral in [1, 3999]'],
    [t(['III'], 3, 1), t(['LVIII'], 58, 1), t(['MCMXCIV'], 1994), t(['IX'], 9)],
    'function romanToInt(s){var v={I:1,V:5,X:10,L:50,C:100,D:500,M:1000},t=0,i;for(i=0;i<s.length;i++){var cur=v[s[i]],nxt=i+1<s.length?v[s[i+1]]:0;t+=cur<nxt?-cur:cur;}return t;}'),


pdef('subtract-product-sum', 'Subtract the Product and Sum of Digits', 'easy', 'subtractProductAndSum',
    sig(['n' => 'int'], 'int'),
    'Return (product of the digits of n) minus (sum of the digits of n).',
    ['1 ≤ n ≤ 10⁵'],
    [t([234], 15, 1), t([4421], 21, 1), t([10], -1), t([705], -12)],
    'function subtractProductAndSum(n){var p=1,s=0;while(n>0){p*=n%10;s+=n%10;n=(n/10)|0;}return p-s;}'),

pdef('count-matches-tournament', 'Count Matches in a Tournament', 'easy', 'numberOfMatches',
    sig(['n' => 'int'], 'int'),
    'Teams play a knockout: each round pairs teams (odd team advances). How many matches until one champion remains?',
    ['1 ≤ n ≤ 200'],
    [t([7], 6, 1), t([14], 13, 1), t([1], 0)],
    'function numberOfMatches(n){return n-1;}'),

pdef('number-of-steps', 'Number of Steps to Reduce to Zero', 'easy', 'numberOfSteps',
    sig(['num' => 'int'], 'int'),
    'Even numbers halve, odd numbers lose 1. Count steps to reach 0.',
    ['0 ≤ num ≤ 10⁶'],
    [t([14], 6, 1), t([8], 4, 1), t([123], 12), t([0], 0)],
    'function numberOfSteps(n){var s=0;while(n>0){n=n%2===0?n/2:n-1;s++;}return s;}'),

pdef('smallest-even-multiple', 'Smallest Even Multiple', 'easy', 'smallestEvenMultiple',
    sig(['n' => 'int'], 'int'),
    'Return the smallest positive integer divisible by both 2 and n.',
    ['1 ≤ n ≤ 150'],
    [t([5], 10, 1), t([6], 6, 1), t([1], 2), t([50], 50)],
    'function smallestEvenMultiple(n){return n%2===0?n:2*n;}'),

pdef('minimum-sum-digit', 'Minimum Sum of Four Digit Number After Splitting', 'easy', 'minimumSum',
    sig(['num' => 'int'], 'int'),
    'Split the four digits of num into two 2-digit numbers minimizing their sum. Return that sum.',
    ['1000 ≤ num ≤ 9999'],
    [t([2932], 52, 1), t([4009], 13, 1), t([1111], 22), t([4321], 37)],
    'function minimumSum(num){var d=String(num).split("").sort();return Number(d[0]+d[2])+Number(d[1]+d[3]);}'),

pdef('count-digits-divide', 'Count Digits That Divide a Number', 'easy', 'countDigits',
    sig(['num' => 'int'], 'int'),
    'Count the digits of num that divide num exactly (num has no zero digits... inputs may include zero digits — those never divide).',
    ['1 ≤ num ≤ 10⁹'],
    [t([7], 1, 1), t([121], 2, 1), t([1248], 4), t([1012], 3)],
    'function countDigits(n){var c=0,st=String(n);for(var i=0;i<st.length;i++){var d=Number(st[i]);if(d>0&&n%d===0)c++;}return c;}'),

pdef('valid-perfect-square', 'Valid Perfect Square', 'easy', 'isPerfectSquare',
    sig(['num' => 'int'], 'bool'),
    'Return true if num is a perfect square, without using a square-root function.',
    ['1 ≤ num ≤ 2³¹-1'],
    [t([16], true, 1), t([14], false, 1), t([1], true), t([808201], true)],
    'function isPerfectSquare(num){var lo=1,hi=num;while(lo<=hi){var mid=(lo+hi)>>1;var sq=mid*mid;if(sq===num)return true;if(sq<num)lo=mid+1;else hi=mid-1;}return false;}'),

pdef('armstrong-number', 'Armstrong Number', 'easy', 'isArmstrong',
    sig(['n' => 'int'], 'bool'),
    'An n-digit number is Armstrong if the sum of its digits each raised to the number of digits equals the number itself.',
    ['1 ≤ n ≤ 10⁸'],
    [t([153], true, 1), t([123], false, 1), t([1634], true), t([9], true)],
    'function isArmstrong(n){var s=String(n),d=s.length,sum=0;for(var i=0;i<d;i++)sum+=Math.pow(Number(s[i]),d);return sum===n;}'),

pdef('divide-integers', 'Divide Two Integers', 'medium', 'divide',
    sig(['dividend' => 'int', 'divisor' => 'int'], 'int'),
    'Integer division truncating toward zero, clamped to the signed 32-bit range (assume no / operator).',
    ['-2³¹ ≤ dividend, divisor ≤ 2³¹-1', 'divisor ≠ 0'],
    [t([10, 3], 3, 1), t([7, -3], -2, 1), t([-2147483648, -1], 2147483647), t([1, 2], 0)],
    'function divide(a,b){var q=Math.abs(Math.trunc(a/b));var s=(a<0)!==(b<0)?-1:1;var r=s*q;return r>2147483647?2147483647:r<-2147483648?-2147483648:r;}'),

pdef('pow-x-n', 'Pow(x, n)', 'medium', 'myPow',
    sig(['x' => 'num', 'n' => 'int'], 'num'),
    'Compute x raised to n (binary exponentiation; negative exponents allowed). Tests use exact-representable values.',
    ['-100 ≤ x ≤ 100', '-2³¹ ≤ n ≤ 2³¹-1'],
    [t([2, 10], 1024, 1), t([2, -2], 0.25, 1), t([3, 3], 27), t([7, 0], 1)],
    'function myPow(x,n){if(n<0){x=1/x;n=-n;}var r=1;while(n>0){if(n%2===1)r*=x;x*=x;n=(n/2)|0;}return r;}'),

pdef('reverse-integer', 'Reverse Integer', 'medium', 'reverse',
    sig(['x' => 'int'], 'int'),
    'Reverse the digits of a signed 32-bit integer; return 0 if the result overflows the 32-bit range.',
    ['-2³¹ ≤ x ≤ 2³¹-1'],
    [t([123], 321, 1), t([-123], -321, 1), t([120], 21), t([1534236469], 0)],
    'function reverse(x){var s=x<0?-1:1,r=0;x=Math.abs(x);while(x>0){r=r*10+x%10;x=(x/10)|0;}r*=s;return r>2147483647||r<-2147483648?0:r;}'),

pdef('atoi', 'String to Integer (atoi)', 'medium', 'myAtoi',
    sig(['s' => 'str'], 'int'),
    'Read an integer: skip whitespace, read optional sign, digits until non-digit, clamp to 32-bit signed range.',
    ['0 ≤ s.length ≤ 200'],
    [t(['42'], 42, 1), t([' -042'], -42, 1), t(['4193 with words'], 4193), t(['words and 987'], 0), t(['-91283472332'], -2147483648)],
    'function myAtoi(s){var m=/^\s*([+-]?\d+)/.exec(s);if(!m)return 0;var v=parseInt(m[1],10);return v>2147483647?2147483647:v<-2147483648?-2147483648:v;}'),

pdef('excel-column', 'Excel Sheet Column Title', 'easy', 'convertToTitle',
    sig(['columnNumber' => 'int'], 'str'),
    'Spreadsheet columns: 1 -> "A", 26 -> "Z", 27 -> "AA", 28 -> "AB". Convert the number to its title.',
    ['1 ≤ columnNumber ≤ 2³¹-1'],
    [t([1], 'A', 1), t([28], 'AB', 1), t([701], 'ZY'), t([27], 'AA'), t([52], 'AZ')],
    'function convertToTitle(n){var s="";while(n>0){n--;s=String.fromCharCode(65+n%26)+s;n=(n/26)|0;}return s;}'),

pdef('excel-column-number', 'Excel Sheet Column Number', 'easy', 'titleToNumber',
    sig(['columnTitle' => 'str'], 'int'),
    'Inverse of the title conversion: "A" -> 1, "AB" -> 28, "ZY" -> 701.',
    ['1 ≤ columnTitle.length ≤ 7 (uppercase A-Z)'],
    [t(['A'], 1, 1), t(['AB'], 28, 1), t(['ZY'], 701), t(['AAA'], 703)],
    'function titleToNumber(t){var n=0;for(var i=0;i<t.length;i++)n=n*26+(t.charCodeAt(i)-64);return n;}'),

pdef('integer-to-roman', 'Integer to Roman', 'medium', 'intToRoman',
    sig(['num' => 'int'], 'str'),
    'Convert 1..3999 to Roman numerals using standard subtractive notation.',
    ['1 ≤ num ≤ 3999'],
    [t([3749], 'MMMDCCXLIX', 1), t([58], 'LVIII', 1), t([1994], 'MCMXCIV'), t([9], 'IX')],
    'function intToRoman(num){var v=[[1000,"M"],[900,"CM"],[500,"D"],[400,"CD"],[100,"C"],[90,"XC"],[50,"L"],[40,"XL"],[10,"X"],[9,"IX"],[5,"V"],[4,"IV"],[1,"I"]],s="";for(var i=0;i<v.length;i++)while(num>=v[i][0]){s+=v[i][1];num-=v[i][0];}return s;}'),

pdef('count-common-factor', 'Number of Common Factors', 'easy', 'commonFactors',
    sig(['a' => 'int', 'b' => 'int'], 'int'),
    'Count positive integers dividing both a and b.',
    ['1 ≤ a, b ≤ 1000'],
    [t([12, 6], 4, 1), t([25, 30], 2, 1), t([7, 7], 2), t([885, 885], 8)],
    'function commonFactors(a,b){var c=0;for(var i=1;i<=Math.min(a,b);i++)if(a%i===0&&b%i===0)c++;return c;}'),

pdef('self-dividing', 'Self Dividing Numbers', 'easy', 'selfDividingNumbers',
    sig(['left' => 'int', 'right' => 'int'], 'int[]'),
    'A self-dividing number is divisible by every digit it contains (and has no zero digit). List them in [left, right].',
    ['1 ≤ left ≤ right ≤ 10⁴'],
    [t([1, 22], [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 15, 22], 1), t([47, 85], [48, 55, 66, 77], 1), t([1, 1], [1])],
    'function selfDividingNumbers(lo,hi){var out=[];for(var n=lo;n<=hi;n++){var s=String(n),ok=true;for(var i=0;i<s.length;i++){var d=Number(s[i]);if(d===0||n%d!==0){ok=false;break;}}if(ok)out.push(n);}return out;}'),

pdef('ugly-number', 'Ugly Number', 'easy', 'isUgly',
    sig(['n' => 'int'], 'bool'),
    'An ugly number has no prime factors other than 2, 3 and 5.',
    ['-2³¹ ≤ n ≤ 2³¹-1'],
    [t([6], true, 1), t([1], true, 1), t([14], false), t([8], true), t([0], false)],
    'function isUgly(n){if(n<=0)return false;[2,3,5].forEach(function(p){while(n%p===0)n/=p;});return n===1;}'),

pdef('nth-ugly-number', 'Ugly Number II', 'medium', 'nthUglyNumber',
    sig(['n' => 'int'], 'int'),
    'Return the n-th ugly number (prime factors only 2, 3, 5; sequence starts 1, 2, 3, 4, 5, 6, 8, 9, 10, 12, …).',
    ['1 ≤ n ≤ 1690'],
    [t([10], 12, 1), t([1], 1, 1), t([5], 5), t([1690], 2123366400)],
    'function nthUglyNumber(n){var u=[1],i2=0,i3=0,i5=0;while(u.length<n){var nx=Math.min(u[i2]*2,u[i3]*3,u[i5]*5);u.push(nx);if(nx===u[i2]*2)i2++;if(nx===u[i3]*3)i3++;if(nx===u[i5]*5)i5++;}return u[n-1];}'),

pdef('bulb-switcher', 'Bulb Switcher', 'medium', 'bulbSwitch',
    sig(['n' => 'int'], 'int'),
    'N bulbs toggle in rounds (round k flips multiples of k). After n rounds, how many are on?',
    ['0 ≤ n ≤ 10⁹'],
    [t([3], 1, 1), t([0], 0, 1), t([1], 1), t([1000000], 1000)],
    'function bulbSwitch(n){return Math.floor(Math.sqrt(n));}'),

pdef('nim-game', 'Nim Game', 'easy', 'canWinNim',
    sig(['n' => 'int'], 'bool'),
    'Nim with one heap; players take 1-3 stones, taker of the last stone wins, opponent plays optimally. Can the first player win?',
    ['1 ≤ n ≤ 2³¹-1'],
    [t([4], false, 1), t([1], true, 1), t([2], true), t([8], false)],
    'function canWinNim(n){return n%4!==0;}'),

pdef('water-jug', 'Water and Jug Problem', 'medium', 'canMeasureWater',
    sig(['x' => 'int', 'y' => 'int', 'target' => 'int'], 'bool'),
    'Jugs of capacity x and y; by filling, emptying and pouring, is any measurable amount exactly target possible?',
    ['1 ≤ x, y, target ≤ 10⁶'],
    [t([3, 5, 4], true, 1), t([2, 6, 5], false, 1), t([1, 2, 3], true)],
    'function canMeasureWater(x,y,z){function g(a,b){return b?g(b,a%b):a;}return z===0||(x+y>=z&&z%g(x,y)===0);}'),

pdef('next-greater-iii', 'Next Greater Element III (digits)', 'medium', 'nextGreaterElement',
    sig(['n' => 'int'], 'int'),
    'Rearrange the digits of n to form the smallest greater number, or -1 if none (must fit 32-bit int).',
    ['1 ≤ n ≤ 2³¹-1'],
    [t([12], 21, 1), t([21], -1, 1), t([122], 212), t([230241], 230412), t([1999999999], -1)],
    'function nextGreaterElement(n){var d=String(n).split("").map(Number),i=d.length-2;while(i>=0&&d[i]>=d[i+1])i--;if(i<0)return -1;var j=d.length-1;while(d[j]<=d[i])j--;var t=d[i];d[i]=d[j];d[j]=t;var tail=d.splice(i+1).sort(function(a,b){return a-b;});var v=Number(d.concat(tail).join(""));return v<=2147483647?v:-1;}'),

pdef('construct-rectangle', 'Construct the Rectangle', 'easy', 'constructRectangle',
    sig(['area' => 'int'], 'int[]'),
    'Return [L, W] with L*W = area, L ≥ W, minimizing L - W.',
    ['1 ≤ area ≤ 10⁷'],
    [t([4], [2, 2], 1), t([37], [37, 1], 1), t([6], [3, 2])],
    'function constructRectangle(a){for(var w=Math.floor(Math.sqrt(a));;w--)if(a%w===0)return [a/w,w];}'),

pdef('sum-of-squares', 'Sum of Square Numbers', 'medium', 'judgeSquareSum',
    sig(['c' => 'int'], 'bool'),
    'Decide whether c = a² + b² for some non-negative integers a, b.',
    ['0 ≤ c ≤ 2³¹-1'],
    [t([5], true, 1), t([3], false, 1), t([4], true), t([1], true), t([2147482647], false)],
    'function judgeSquareSum(c){for(var a=0;a*a<=c;a++){var b=Math.floor(Math.sqrt(c-a*a));if(b*b===c-a*a)return true;}return false;}'),

pdef('base-7', 'Base 7', 'easy', 'convertToBase7',
    sig(['num' => 'int'], 'str'),
    'Return the base-7 representation of the given integer.',
    ['-10⁷ ≤ num ≤ 10⁷'],
    [t([100], '202', 1), t([-7], '-10', 1), t([0], '0'), t([48], '66')],
    'function convertToBase7(n){if(n===0)return "0";var s=n<0?"-":"",t="";n=Math.abs(n);while(n>0){t=(n%7)+t;n=(n/7)|0;}return s+t;}'),

pdef('fraction-decimal', 'Fraction to Recurring Decimal', 'medium', 'fractionToDecimal',
    sig(['numerator' => 'int', 'denominator' => 'int'], 'str'),
    'Return the fraction as a decimal string, repeating parts in parentheses.',
    ['-2³¹ ≤ numerator, denominator ≤ 2³¹-1', 'denominator ≠ 0'],
    [t([1, 2], '0.5', 1), t([2, 1], '2', 1), t([4, 333], '0.(012)'), t([1, 6], '0.1(6)'), t([-50, 8], '-6.25')],
    'function fractionToDecimal(n,d){if(n===0)return "0";var s=(n<0)!==(d<0)?"-":"",out="";n=Math.abs(n);d=Math.abs(d);out+=(n/d|0)+"";n%=d;if(n===0)return s+out;out+=".";var seen={},pos=out.length;while(n>0){if(seen[n]!==undefined)return s+out.slice(0,seen[n])+"("+out.slice(seen[n])+")";seen[n]=pos++;n*=10;out+=(n/d|0);n%=d;}return s+out;}'),

pdef('continuous-int-sum', 'Consecutive Numbers Sum', 'medium', 'consecutiveNumbersSum',
    sig(['n' => 'int'], 'int'),
    'Count ways to write n as a sum of one or more consecutive positive integers.',
    ['1 ≤ n ≤ 10⁹'],
    [t([5], 2, 1), t([9], 3, 1), t([15], 4), t([1], 1), t([10], 2)],
    'function consecutiveNumbersSum(n){var ans=0;for(var k=1;k*(k+1)/2<=n;k++){if((n-k*(k+1)/2)%k===0)ans++;}return ans;}'),

pdef('reach-number', 'Reach a Number', 'medium', 'reachNumber',
    sig(['target' => 'int'], 'int'),
    'Start at 0; move i can be -i or +i. Return the minimum number of moves to land exactly on target.',
    ['-10⁹ ≤ target ≤ 10⁹', 'target ≠ 0'],
    [t([2], 3, 1), t([3], 2, 1), t([1], 1), t([-2], 3), t([11], 5)],
    'function reachNumber(t){t=Math.abs(t);var k=0,s=0;while(s<t||((s-t)%2)!==0){k++;s+=k;}return k;}'),

pdef('day-of-week', 'Day of the Week', 'easy', 'dayOfTheWeek',
    sig(['day' => 'int', 'month' => 'int', 'year' => 'int'], 'str'),
    'Return the weekday name for the given Gregorian date (1971-2100).',
    ['valid date between 1971 and 2100'],
    [t([31, 8, 2019], 'Saturday', 1), t([18, 7, 1999], 'Sunday', 1), t([15, 8, 1993], 'Sunday'), t([1, 1, 2000], 'Saturday')],
    'function dayOfTheWeek(d,m,y){var w=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];return w[new Date(Date.UTC(y,m-1,d)).getUTCDay()];}'),

pdef('day-of-year', 'Day of the Year', 'easy', 'dayOfYear',
    sig(['date' => 'str'], 'int'),
    'Given "YYYY-MM-DD", return its 1-based day number in that year.',
    ['date is valid, years 1900-2019'],
    [t(['2019-01-09'], 9, 1), t(['2019-02-10'], 41, 1), t(['2004-03-01'], 61), t(['1900-03-01'], 60)],
    'function dayOfYear(dt){var p=dt.split("-"),y=Number(p[0]),m=Number(p[1]),d=Number(p[2]);var leap=(y%4===0&&y%100!==0)||y%400===0,ml=[31,leap?29:28,31,30,31,30,31,31,30,31,30,31],n=d;for(var i=0;i<m-1;i++)n+=ml[i];return n;}'),

pdef('typewriter-time', 'Minimum Time to Type Word', 'easy', 'minTimeToType',
    sig(['word' => 'str'], 'int'),
    'A circular keyboard abcdef...z, pointer starts at "a". Moving between adjacent letters costs 1s (wraps), typing costs 1s. Total time for word?',
    ['1 ≤ word.length ≤ 100 (lowercase)'],
    [t(['abc'], 5, 1), t(['bza'], 7, 1), t(['zjpc'], 34), t(['a'], 1)],
    'function minTimeToType(w){var cur=97,sec=0;for(var i=0;i<w.length;i++){var d=Math.abs(w.charCodeAt(i)-cur);sec+=Math.min(d,26-d)+1;cur=w.charCodeAt(i);}return sec;}'),

pdef('count-operations-zero', 'Count Operations to Obtain Zero', 'easy', 'countOperations',
    sig(['num1' => 'int', 'num2' => 'int'], 'int'),
    'Repeatedly subtract the smaller number from the larger until one is zero. Count operations (if one is 0 at start, answer is 0).',
    ['0 ≤ num1, num2 ≤ 10⁵'],
    [t([2, 3], 3, 1), t([10, 10], 1, 1), t([5, 4], 5), t([0, 5], 0)],
    'function countOperations(a,b){var c=0;while(a>0&&b>0){if(a>=b)a-=b;else b-=a;c++;}return c;}'),

pdef('x-of-kind-deck', 'X of a Kind in a Deck of Cards', 'medium', 'hasGroupsSizeX',
    sig(['deck' => 'int[]'], 'bool'),
    'Can the deck be split into groups where every group has size X ≥ 2 and all cards in a group share a value?',
    ['1 ≤ deck.length ≤ 10⁴', '0 ≤ deck[i] < 10⁴'],
    [t([[1, 2, 3, 4, 4, 3, 2, 1]], true, 1), t([[1, 1, 1, 2, 2, 2, 3, 3]], false, 1), t([[1, 1]], true), t([[1]], false)],
    'function hasGroupsSizeX(deck){function g(a,b){return b?g(b,a%b):a;}function g(a,b){a=Math.abs(a);b=Math.abs(b);while(b){var t=b;b=a%b;a=t;}return a;}var c={};deck.forEach(function(v){c[v]=(c[v]||0)+1;});var G=0;for(var k in c)G=g(G,c[k]);return G>=2;}'),

pdef('three-divisors', 'Three Divisors', 'easy', 'isThree',
    sig(['n' => 'int'], 'bool'),
    'Return true if n has exactly three positive divisors.',
    ['1 ≤ n ≤ 10⁴'],
    [t([2], false, 1), t([4], true, 1), t([9], true), t([12], false), t([1], false)],
    'function isThree(n){var c=0;for(var i=1;i<=n;i++)if(n%i===0)c++;return c===3;}'),

pdef('count-vowel-strings', 'Count Sorted Vowel Strings', 'medium', 'countVowelStrings',
    sig(['n' => 'int'], 'int'),
    'Count strings of length n made from a,e,i,o,u that are lexicographically sorted (non-decreasing).',
    ['1 ≤ n ≤ 50'],
    [t([1], 5, 1), t([2], 15, 1), t([33], 66045)],
    'function countVowelStrings(n){return (n+4)*(n+3)*(n+2)*(n+1)/24;}'),

pdef('prime-arrangements', 'Prime Arrangements', 'medium', 'numPrimeArrangements',
    sig(['n' => 'int'], 'int'),
    'Permute 1..n so every prime sits at a prime index (1-based). Count arrangements mod 10⁹+7.',
    ['1 ≤ n ≤ 100'],
    [t([5], 12, 1), t([100], 682289015, 1), t([1], 1), t([2], 1)],
    'function numPrimeArrangements(n){var M=1000000007n;function prime(x){if(x<2)return false;for(var i=2;i*i<=x;i++)if(x%i===0)return false;return true;}function fact(k){var r=1n;for(var i=2;i<=k;i++)r=r*BigInt(i)%M;return r;}var p=0;for(var j=1;j<=n;j++)if(prime(j))p++;return Number(fact(p)*fact(n-p)%M);}'),

pdef('count-triplets-xor', 'Count Triplets That Can Form Two Arrays of Equal XOR', 'medium', 'countTriplets',
    sig(['arr' => 'int[]'], 'int'),
    'Count triplets (i, j, k), i < j ≤ k, where XOR(arr[i..j-1]) === XOR(arr[j..k]).',
    ['1 ≤ arr.length ≤ 300', '1 ≤ arr[i] ≤ 10⁸'],
    [t([[2, 3, 1, 6, 7]], 4, 1), t([[1, 1, 1, 1, 1]], 10, 1), t([[2, 3]], 0), t([[1, 3, 5, 7, 9]], 3)],
    'function countTriplets(arr){var n=arr.length,c=0;for(var i=0;i<n;i++){var x=arr[i];for(var k=i+1;k<n;k++){x^=arr[k];if(x===0)c+=k-i;}}return c;}'),

];
