<?php
// Category: search — binary search in all its disguises, plus sorting classics
return [
pdef('binary-search', 'Binary Search', 'easy', 'search',
    sig(['nums' => 'int[]', 'target' => 'int'], 'int'),
    'The array is sorted ascending with distinct values. Return the index of target, or -1 if absent. Must run in O(log n).',
    ['1 ≤ nums.length ≤ 10⁴'],
    [t([[-1, 0, 3, 5, 9, 12], 9], 4, 1), t([[-1, 0, 3, 5, 9, 12], 2], -1, 1), t([[5], 5], 0), t([[2, 5], 5], 1)],
    'function search(nums,target){var lo=0,hi=nums.length-1;while(lo<=hi){var mid=(lo+hi)>>1;if(nums[mid]===target)return mid;if(nums[mid]<target)lo=mid+1;else hi=mid-1;}return -1;}'),

pdef('search-insert', 'Search Insert Position', 'easy', 'searchInsert',
    sig(['nums' => 'int[]', 'target' => 'int'], 'int'),
    'The array is sorted ascending with distinct values. Return the index where target is found, or the index where it would be inserted to keep the array sorted.',
    ['1 ≤ nums.length ≤ 10⁴'],
    [t([[1, 3, 5, 6], 5], 2, 1), t([[1, 3, 5, 6], 2], 1, 1), t([[1, 3, 5, 6], 7], 4), t([[1], 0], 0)],
    'function searchInsert(nums,t){var lo=0,hi=nums.length;while(lo<hi){var mid=(lo+hi)>>1;if(nums[mid]<t)lo=mid+1;else hi=mid;}return lo;}'),

pdef('search-rotated', 'Search in Rotated Sorted Array', 'medium', 'searchRotated',
    sig(['nums' => 'int[]', 'target' => 'int'], 'int'),
    'A sorted array (distinct values) was rotated at some pivot: [0,1,2,4,5,6,7] might become [4,5,6,7,0,1,2]. Find target in O(log n) or return -1.',
    ['1 ≤ nums.length ≤ 5000'],
    [t([[4, 5, 6, 7, 0, 1, 2], 0], 4, 1), t([[4, 5, 6, 7, 0, 1, 2], 3], -1, 1), t([[1], 0], -1), t([[3, 1], 1], 1), t([[5, 1, 3], 5], 0)],
    'function searchRotated(nums,target){var l=0,r=nums.length-1;while(l<=r){var m=(l+r)>>1;if(nums[m]===target)return m;if(nums[l]<=nums[m]){if(target>=nums[l]&&target<nums[m])r=m-1;else l=m+1;}else{if(target>nums[m]&&target<=nums[r])l=m+1;else r=m-1;}}return -1;}'),

pdef('find-min-rotated', 'Find Minimum in Rotated Sorted Array', 'medium', 'findMin',
    sig(['nums' => 'int[]'], 'int'),
    'A sorted array (distinct values) was rotated 1..n times. Return its minimum element in O(log n).',
    ['1 ≤ nums.length ≤ 5000'],
    [t([[3, 4, 5, 1, 2]], 1, 1), t([[4, 5, 6, 7, 0, 1, 2]], 0, 1), t([[11, 13, 15, 17]], 11), t([[2, 1]], 1)],
    'function findMin(nums){var lo=0,hi=nums.length-1;while(lo<hi){var mid=(lo+hi)>>1;if(nums[mid]>nums[hi])lo=mid+1;else hi=mid;}return nums[lo];}'),

pdef('peak-index', 'Peak Index in a Mountain Array', 'medium', 'peakIndexInMountainArray',
    sig(['arr' => 'int[]'], 'int'),
    'The array climbs strictly up to one peak and then strictly descends (guaranteed mountain). Return the peak index in O(log n).',
    ['3 ≤ arr.length ≤ 10⁴'],
    [t([[0, 1, 0]], 1, 1), t([[0, 2, 1, 0]], 1, 1), t([[0, 10, 5, 2]], 1), t([[3, 5, 3]], 1)],
    'function peakIndexInMountainArray(a){var lo=0,hi=a.length-1;while(lo<hi){var mid=(lo+hi)>>1;if(a[mid]<a[mid+1])lo=mid+1;else hi=mid;}return lo;}'),

pdef('count-neg-matrix', 'Count Negatives in a Sorted Matrix', 'easy', 'countNegatives',
    sig(['grid' => 'int[][]'], 'int'),
    'Every row and every column of the matrix is sorted in non-increasing order. Count the negative numbers.',
    ['1 ≤ rows, cols ≤ 100'],
    [t([[[4, 3, 2, -1], [3, 2, 1, -1], [1, 1, -1, -2], [-1, -1, -2, -3]]], 8, 1), t([[[3, 2], [1, 0]]], 0, 1), t([[[-1]]], 1), t([[[5]]], 0)],
    'function countNegatives(g){var c=0,r;for(r=0;r<g.length;r++){for(var j=0;j<g[r].length;j++){if(g[r][j]<0)c++;}}return c;}'),

pdef('arrange-coins', 'Arranging Coins (Staircase)', 'easy', 'arrangeCoins',
    sig(['n' => 'int'], 'int'),
    'You stack coins into a staircase: row 1 has 1 coin, row 2 has 2, and so on. Given n coins, return how many COMPLETE rows you can build.',
    ['1 ≤ n ≤ 2³¹ − 1'],
    [t([5], 2, 1), t([8], 3, 1), t([1], 1), t([10], 4)],
    'function arrangeCoins(n){var lo=0,hi=n,ans=0;while(lo<=hi){var k=(lo+hi)>>1,need=k*(k+1)/2;if(need<=n){ans=k;lo=k+1;}else hi=k-1;}return ans;}'),

pdef('kth-missing-positive', 'Kth Missing Positive Number', 'easy', 'findKthPositive',
    sig(['arr' => 'int[]', 'k' => 'int'], 'int'),
    'The array holds distinct positive integers in ascending order. Return the kth positive integer that is MISSING from it.',
    ['1 ≤ arr.length ≤ 1000', '1 ≤ k ≤ 1000'],
    [t([[2, 3, 4, 7, 11], 5], 9, 1), t([[1, 2, 3, 4], 2], 6, 1), t([[5, 6, 7], 1], 1), t([[1, 3], 3], 5)],
    'function findKthPositive(arr,k){var prev=0,i;for(i=0;i<arr.length;i++){var gap=arr[i]-prev-1;if(gap>=k)return prev+k;k-=gap;prev=arr[i];}return arr[arr.length-1]+k;}'),

pdef('kth-largest', 'Kth Largest Element', 'medium', 'findKthLargest',
    sig(['nums' => 'int[]', 'k' => 'int'], 'int'),
    'Return the kth largest element — as if the array were sorted descending, index k-1. Sorting is acceptable here; a heap is the interview answer.',
    ['1 ≤ k ≤ nums.length ≤ 10⁵'],
    [t([[3, 2, 1, 5, 6, 4], 2], 5, 1), t([[3, 2, 3, 1, 2, 4, 5, 5, 6], 4], 4, 1), t([[1], 1], 1), t([[9, 9], 2], 9)],
    'function findKthLargest(nums,k){return nums.slice().sort(function(a,b){return b-a;})[k-1];}'),

pdef('top-k-frequent', 'Top K Frequent Elements', 'medium', 'topKFrequent',
    sig(['nums' => 'int[]', 'k' => 'int'], 'int[]'),
    'Return the k most frequent values. Order the answer by frequency (higher first); ties go to the numerically smaller value so the result is deterministic.',
    ['1 ≤ k ≤ number of distinct values'],
    [t([[1, 1, 1, 2, 2, 3], 2], [1, 2], 1), t([[1], 1], [1], 1), t([[4, 4, 6, 6, 2, 9, 9, 9], 2], [9, 4]), t([[5, 5, 3], 2], [5, 3])],
    'function topKFrequent(nums,k){var m={},i;for(i=0;i<nums.length;i++){m[nums[i]]=(m[nums[i]]||0)+1;}return Object.keys(m).map(Number).sort(function(a,b){return m[b]-m[a]||a-b;}).slice(0,k);}'),

pdef('first-last-pos', 'First and Last Position in Sorted Array', 'medium', 'searchRange',
    sig(['nums' => 'int[]', 'target' => 'int'], 'int[]'),
    'The array is sorted ascending (duplicates allowed). Return [firstIndex, lastIndex] of target, or [-1, -1] if absent. O(log n) with two binary searches.',
    ['0 ≤ nums.length ≤ 10⁵'],
    [t([[5, 7, 7, 8, 8, 10], 8], [3, 4], 1), t([[5, 7, 7, 8, 8, 10], 6], [-1, -1], 1), t([[], 0], [-1, -1]), t([[8, 8, 8], 8], [0, 2])],
    'function searchRange(nums,t){var find=function(left){var lo=0,hi=nums.length,ans=-1;while(lo<hi){var mid=(lo+hi)>>1;if(nums[mid]===t){ans=mid;if(left)hi=mid;else lo=mid+1;}else if(nums[mid]<t)lo=mid+1;else hi=mid;}return ans;};var f=find(true);if(f<0)return [-1,-1];return [f,find(false)];}'),

pdef('special-array', 'Special Array With X Elements ≥ X', 'easy', 'specialArray',
    sig(['nums' => 'int[]'], 'int'),
    'Find x ≥ 0 such that exactly x elements of the array are ≥ x, and return x. If no such x exists, return -1.',
    ['1 ≤ nums.length ≤ 100', '0 ≤ nums[i] ≤ 1000'],
    [t([[3, 5]], 2, 1), t([[0, 0]], -1, 1), t([[0, 4, 3, 0, 4]], 3), t([[7, 7, 7, 7, 7, 7, 7]], 7)],
    'function specialArray(nums){for(var x=0;x<=nums.length;x++){var c=0;for(var i=0;i<nums.length;i++){if(nums[i]>=x)c++;}if(c===x)return x;}return -1;}'),

pdef('smaller-than-current', 'Numbers Smaller Than the Current Number', 'easy', 'smallerNumbersThanCurrent',
    sig(['nums' => 'int[]'], 'int[]'),
    'For every element, count how many elements are strictly smaller than it. Counting sort over the 0..100 range makes this O(n).',
    ['2 ≤ nums.length ≤ 500', '0 ≤ nums[i] ≤ 100'],
    [t([[8, 1, 2, 2, 3]], [4, 0, 1, 1, 3], 1), t([[6, 5, 4, 8]], [2, 1, 0, 3], 1), t([[7, 7, 7]], [0, 0, 0]), t([[1]], [0])],
    'function smallerNumbersThanCurrent(nums){var sorted=nums.slice().sort(function(a,b){return a-b;}),first={},i;for(i=0;i<sorted.length;i++){if(!(sorted[i] in first))first[sorted[i]]=i;}return nums.map(function(n){return first[n];});}'),


pdef('sqrt-x', 'Sqrt(x)', 'easy', 'mySqrt',
    sig(['x' => 'int'], 'int'),
    'Return the square root of x rounded down to the nearest integer, without using a built-in sqrt.',
    ['0 <= x <= 2^31 - 1'],
    [t([4], 2, 1), t([8], 2, 1), t([1], 1), t([0], 0)],
    'function mySqrt(x){var lo=0,hi=x;while(lo<hi){var mid=(lo+hi+1)>>1;if(mid*mid<=x)lo=mid;else hi=mid-1;}return lo;}'),

pdef('guess-number', 'Guess Number Higher or Lower', 'easy', 'guessNumber',
    sig(['n' => 'int', 'pick' => 'int'], 'int'),
    'A number between 1 and n is secretly picked. Using plain binary search, how many guesses does it take to find pick?',
    ['1 <= pick <= n <= 2^31 - 1'],
    [t([10, 6], 3, 1), t([10, 1], 3, 1), t([100, 73], 6), t([1, 1], 1)],
    'function guessNumber(n,pick){var lo=1,hi=n,tries=0;while(true){var mid=(lo+hi)>>1;tries++;if(mid===pick)return tries;if(mid<pick)lo=mid+1;else hi=mid-1;}}'),

pdef('first-bad-version', 'First Bad Version', 'easy', 'firstBadVersion',
    sig(['n' => 'int', 'bad' => 'int'], 'int'),
    'Versions 1..n, and every version from bad onward is broken. An optimal binary search (isBad calls) locates bad; return how many calls it makes.',
    ['1 <= bad <= n <= 2^31 - 1'],
    [t([5, 4], 2, 1), t([1, 1], 0, 1), t([100, 67], 7), t([10, 9], 3)],
    'function firstBadVersion(n,bad){var lo=1,hi=n,calls=0;while(lo<hi){var mid=(lo+hi)>>1;calls++;if(mid>=bad)hi=mid;else lo=mid+1;}return calls;}'),

pdef('kth-smallest-matrix', 'Kth Smallest Element in a Sorted Matrix', 'medium', 'kthSmallest',
    sig(['matrix' => 'int[][]', 'k' => 'int'], 'int'),
    'Each row and column of the n x n matrix is sorted ascending. Return the kth smallest element overall.',
    ['1 <= n <= 300'],
    [t([[[1,5,9],[10,11,13],[12,13,15]], 8], 13, 1), t([[[-5]], 1], -5, 1), t([[[1,2],[1,3]], 2], 1), t([[[1,5,9],[10,11,13],[12,13,15]], 5], 11)],
    'function kthSmallest(matrix,k){var n=matrix.length,lo=matrix[0][0],hi=matrix[n-1][n-1];function countLe(x){var cnt=0,r=n-1,c=0;while(r>=0&&c<n){if(matrix[r][c]<=x){cnt+=r+1;c++;}else r--;}return cnt;}while(lo<hi){var mid=lo+((hi-lo)>>1);if(countLe(mid)>=k)hi=mid;else lo=mid+1;}return lo;}'),

pdef('find-duplicate', 'Find the Duplicate Number', 'medium', 'findDuplicate',
    sig(['nums' => 'int[]'], 'int'),
    'The array has n + 1 values, each in 1..n, with exactly one value repeated (maybe many times). Return the repeated value without modifying the array.',
    ['2 <= nums.length <= 100000'],
    [t([[1,3,4,2,2]], 2, 1), t([[3,1,3,4,2]], 3, 1), t([[3,3,3,3,3,3]], 3), t([[2,2,2,2]], 2)],
    'function findDuplicate(nums){var slow=nums[0],fast=nums[nums[0]];while(slow!==fast){slow=nums[slow];fast=nums[nums[fast]];}var s2=0;while(s2!==slow){s2=nums[s2];slow=nums[slow];}return s2;}'),

pdef('h-index-ii', 'H-Index II', 'medium', 'hIndex',
    sig(['citations' => 'int[]'], 'int'),
    'citations is sorted ascending. The h-index is the largest h such that at least h papers have >= h citations. Return it.',
    ['1 <= citations.length <= 100000'],
    [t([[0,1,3,5,6]], 3, 1), t([[1,2,100]], 2, 1), t([[0]], 0), t([[1]], 1)],
    'function hIndex(cit){var lo=0,hi=cit.length;while(lo<hi){var mid=(lo+hi+1)>>1;if(cit[cit.length-mid]>=mid)lo=mid;else hi=mid-1;}return lo;}'),

pdef('smallest-letter-gt', 'Find Smallest Letter Greater Than Target', 'easy', 'nextGreatestLetter',
    sig(['letters' => 'str[]', 'target' => 'str'], 'str'),
    'letters is sorted ascending. Return the smallest character greater than target; the list wraps around.',
    ['2 <= letters.length <= 10000'],
    [t([['c','f','j'], 'a'], 'c', 1), t([['c','f','j'], 'c'], 'f', 1), t([['x','x','y','y'], 'z'], 'x'), t([['c','f','j'], 'j'], 'c')],
    'function nextGreatestLetter(letters,target){var lo=0,hi=letters.length;while(lo<hi){var mid=(lo+hi)>>1;if(letters[mid]<=target)lo=mid+1;else hi=mid;}return letters[lo%letters.length];}'),

pdef('single-element-sorted', 'Single Element in a Sorted Array', 'medium', 'singleNonDuplicate',
    sig(['nums' => 'int[]'], 'int'),
    'Every element appears exactly twice except one; the array is sorted. Return the single element.',
    ['1 <= nums.length <= 100000, odd length'],
    [t([[1,1,2,3,3,4,4,8,8]], 2, 1), t([[3,3,7,7,10,11,11]], 10, 1), t([[1,1,2]], 2), t([[2]], 2)],
    'function singleNonDuplicate(nums){var lo=0,hi=nums.length-1;while(lo<hi){var mid=(lo+hi)>>1;if(mid%2)mid--;if(nums[mid]===nums[mid+1])lo=mid+2;else hi=mid;}return nums[lo];}'),

pdef('find-peak-element', 'Find Peak Element', 'medium', 'findPeakElement',
    sig(['nums' => 'int[]'], 'int'),
    'A peak is strictly greater than its neighbours (edges count as -infinity). Return the index of a peak; these tests have exactly one valid answer.',
    ['1 <= nums.length <= 1000'],
    [t([[1,2,3,1]], 2, 1), t([[1,2]], 1, 1), t([[2,1]], 0), t([[5,4,3,2,1]], 0)],
    'function findPeakElement(nums){var lo=0,hi=nums.length-1;while(lo<hi){var mid=(lo+hi)>>1;if(nums[mid]>nums[mid+1])hi=mid;else lo=mid+1;}return lo;}'),

pdef('min-speed-arrive', 'Minimum Speed to Arrive on Time', 'medium', 'minSpeedOnTime',
    sig(['dist' => 'int[]', 'hour' => 'num'], 'int'),
    'Trains run sequentially; each takes dist[i] / speed hours, and only the last may end mid-hour (others wait for the next full hour). Return the minimum integer speed to arrive within hour.',
    ['1 <= dist.length <= 100000'],
    [t([[1,3,2], 6], 1, 1), t([[1,3,2], 2.7], 3, 1), t([[1,1], 2], 1), t([[2], 1.5], 2)],
    'function minSpeedOnTime(dist,hour){function ok(sp){var t=0;for(var i=0;i<dist.length-1;i++)t+=Math.ceil(dist[i]/sp);t+=dist[dist.length-1]/sp;return t<=hour;}var lo=1,hi=10000000;while(lo<hi){var mid=(lo+hi)>>1;if(ok(mid))hi=mid;else lo=mid+1;}return lo;}'),

pdef('koko-bananas', 'Koko Eating Bananas', 'medium', 'minEatingSpeed',
    sig(['piles' => 'int[]', 'h' => 'int'], 'int'),
    'Each hour Koko eats up to speed bananas from one pile. Return the minimum integer speed to finish all piles within h hours.',
    ['1 <= piles.length <= h <= 1000000000'],
    [t([[3,6,7,11], 8], 4, 1), t([[30,11,23,4,20], 5], 30, 1), t([[30,11,23,4,20], 6], 23), t([[1], 1], 1)],
    'function minEatingSpeed(piles,h){function ok(sp){var t=0;for(var p of piles)t+=Math.ceil(p/sp);return t<=h;}var lo=1,hi=Math.max.apply(null,piles);while(lo<hi){var mid=(lo+hi)>>1;if(ok(mid))hi=mid;else lo=mid+1;}return lo;}'),

pdef('ship-packages', 'Capacity To Ship Packages Within D Days', 'medium', 'shipWithinDays',
    sig(['weights' => 'int[]', 'days' => 'int'], 'int'),
    'Packages ship in order, one ship per day with a weight capacity. Return the minimum capacity to ship everything within days.',
    ['1 <= days <= weights.length <= 50000'],
    [t([[1,2,3,4,5,6,7,8,9,10], 5], 15, 1), t([[3,2,2,4,1,4], 3], 6, 1), t([[1,2,3,1,1], 4], 3), t([[10], 2], 10)],
    'function shipWithinDays(weights,days){function ok(cap){var d=1,cur=0;for(var w of weights){if(cur+w>cap){d++;cur=0;}cur+=w;}return d<=days;}var lo=0,hi=0;for(var w of weights){lo=Math.max(lo,w);hi+=w;}while(lo<hi){var mid=(lo+hi)>>1;if(ok(mid))hi=mid;else lo=mid+1;}return lo;}'),

pdef('magnetic-balls', 'Magnetic Force Between Two Balls', 'medium', 'maxDistance',
    sig(['position' => 'int[]', 'm' => 'int'], 'int'),
    'Place m balls in baskets at the given positions to MAXIMIZE the minimum distance between any two balls. Return that force.',
    ['2 <= m <= position.length <= 100000'],
    [t([[1,2,3,4,7], 3], 3, 1), t([[5,4,3,2,1,1000000000], 2], 999999999, 1), t([[1,2,3], 2], 2), t([[4,3,2,1], 2], 3)],
    'function maxDistance(position,m){position.sort(function(a,b){return a-b;});function ok(d){var cnt=1,prev=position[0];for(var i=1;i<position.length;i++)if(position[i]-prev>=d){cnt++;prev=position[i];}return cnt>=m;}var lo=1,hi=position[position.length-1]-position[0];while(lo<hi){var mid=(lo+hi+1)>>1;if(ok(mid))lo=mid;else hi=mid-1;}return lo;}'),

pdef('divide-chocolate', 'Divide Chocolate', 'medium', 'maximizeSweetness',
    sig(['sweetness' => 'int[]', 'k' => 'int'], 'int'),
    'Cut the chocolate bar into k + 1 contiguous pieces; you take the piece with the minimum total sweetness. Maximize your piece and return its sweetness.',
    ['0 <= k < sweetness.length <= 100000'],
    [t([[1,2,3,4,5,6,7,8,9], 5], 6, 1), t([[5,6,7,8,9,1,2,3,4], 8], 1, 1), t([[1,2,2,1,2,2,1,2,2], 2], 5), t([[9], 0], 9)],
    'function maximizeSweetness(sweetness,k){function ok(v){var pieces=0,cur=0;for(var s of sweetness){cur+=s;if(cur>=v){pieces++;cur=0;}}return pieces>=k+1;}var total=0;for(var s of sweetness)total+=s;var lo=0,hi=total;while(lo<hi){var mid=(lo+hi+1)>>1;if(ok(mid))lo=mid;else hi=mid-1;}return lo;}'),

pdef('smallest-divisor', 'Find the Smallest Divisor Given a Threshold', 'medium', 'smallestDivisor',
    sig(['nums' => 'int[]', 'threshold' => 'int'], 'int'),
    'Dividing every element by d (rounding up each result) and summing must stay within threshold. Return the smallest such d.',
    ['1 <= nums.length <= 50000'],
    [t([[1,2,5,9], 6], 5, 1), t([[44,22,33,11,1], 5], 44, 1), t([[2,3,5,7,11], 11], 3), t([[1], 1], 1)],
    'function smallestDivisor(nums,threshold){function ok(d){var s=0;for(var x of nums)s+=Math.ceil(x/d);return s<=threshold;}var lo=1,hi=Math.max.apply(null,nums);while(lo<hi){var mid=(lo+hi)>>1;if(ok(mid))hi=mid;else lo=mid+1;}return lo;}'),

pdef('min-days-bouquets', 'Minimum Number of Days to Make m Bouquets', 'medium', 'minDays',
    sig(['bloomDay' => 'int[]', 'm' => 'int', 'k' => 'int'], 'int'),
    'Flower i blooms on bloomDay[i]. Each bouquet needs k adjacent bloomed flowers. Return the minimum day to make m bouquets, or -1.',
    ['1 <= m, k <= bloomDay.length'],
    [t([[1,10,3,10,2], 3, 1], 3, 1), t([[1,10,3,10,2], 3, 2], -1, 1), t([[7,7,7,7,12,7,7], 2, 3], 12), t([[1000000000,1000000000], 1, 1], 1000000000)],
    'function minDays(bloomDay,m,k){function ok(day){var bouquets=0,run=0;for(var d of bloomDay){if(d<=day){run++;if(run===k){bouquets++;run=0;}}else run=0;}return bouquets>=m;}if(m*k>bloomDay.length)return -1;var lo=Math.min.apply(null,bloomDay),hi=Math.max.apply(null,bloomDay);while(lo<hi){var mid=(lo+hi)>>1;if(ok(mid))hi=mid;else lo=mid+1;}return lo;}'),

pdef('nth-magical', 'Nth Magical Number', 'hard', 'nthMagicalNumber',
    sig(['n' => 'int', 'a' => 'int', 'b' => 'int'], 'int'),
    'A magical number is divisible by a or b. Return the nth magical number modulo 10^9 + 7.',
    ['1 <= n <= 1000000000', '2 <= a, b <= 40000'],
    [t([1, 2, 3], 2, 1), t([4, 2, 3], 6, 1), t([3, 6, 4], 8), t([2, 3, 5], 5)],
    'function nthMagicalNumber(n,a,b){var M=1000000007;function g(x,y){return y?g(y,x%y):x;}var lcm=a/g(a,b)*b;function count(x){return Math.floor(x/a)+Math.floor(x/b)-Math.floor(x/lcm);}var lo=Math.min(a,b),hi=n*Math.min(a,b);while(lo<hi){var mid=Math.floor((lo+hi)/2);if(count(mid)>=n)hi=mid;else lo=mid+1;}return lo%M;}'),

pdef('median-two-sorted', 'Median of Two Sorted Arrays', 'hard', 'findMedianSortedArrays',
    sig(['a' => 'int[]', 'b' => 'int[]'], 'num'),
    'Return the median of the two sorted arrays combined.',
    ['0 <= a.length, b.length, total >= 1'],
    [t([[1,3], [2]], 2, 1), t([[1,2], [3,4]], 2.5, 1), t([[0,0], [0,0]], 0), t([[1], []], 1)],
    'function findMedianSortedArrays(a,b){var m=[],i=0,j=0;while(i<a.length||j<b.length){if(j>=b.length||(i<a.length&&a[i]<=b[j]))m.push(a[i++]);else m.push(b[j++]);}var n=m.length;return n%2?m[(n-1)/2]:(m[n/2-1]+m[n/2])/2;}'),

pdef('find-k-closest', 'Find K Closest Elements', 'medium', 'findClosestElements',
    sig(['arr' => 'int[]', 'k' => 'int', 'x' => 'int'], 'int[]'),
    'arr is sorted. Return the k elements closest to x (ties prefer smaller values), sorted ascending.',
    ['1 <= k <= arr.length'],
    [t([[1,2,3,4,5], 4, 3], [1,2,3,4], 1), t([[1,2,3,4,5], 4, -1], [1,2,3,4], 1), t([[1,1,2,3,4,5], 4, -1], [1,1,2,3]), t([[0,1,2,3,4], 2, 2], [1,2])],
    'function findClosestElements(arr,k,x){var lo=0,hi=arr.length-k;while(lo<hi){var mid=(lo+hi)>>1;if(x-arr[mid]>arr[mid+k]-x)lo=mid+1;else hi=mid;}return arr.slice(lo,lo+k);}'),

pdef('count-smaller-after', 'Count of Smaller Numbers After Self', 'hard', 'countSmaller',
    sig(['nums' => 'int[]'], 'int[]'),
    'For each index count how many elements to its right are strictly smaller. Return the counts.',
    ['1 <= nums.length <= 100000'],
    [t([[5,2,6,1]], [2,1,1,0], 1), t([[-1]], [0], 1), t([[-1,-1]], [0,0]), t([[2,0,1]], [2,0,0])],
    'function countSmaller(nums){var idx=nums.map(function(_,i){return i;});var res=new Array(nums.length).fill(0);function ms(lo,hi){if(hi-lo<=1)return;var mid=(lo+hi)>>1;ms(lo,mid);ms(mid,hi);var tmp=[];var i=lo,j=mid;while(i<mid||j<hi){if(j>=hi||(i<mid&&nums[idx[i]]<=nums[idx[j]])){res[idx[i]]+=j-mid;tmp.push(idx[i++]);}else tmp.push(idx[j++]);}for(var t=0;t<tmp.length;t++)idx[lo+t]=tmp[t];}ms(0,nums.length);return res;}'),

pdef('search-suggestions', 'Search Suggestions System', 'medium', 'suggestedProducts',
    sig(['products' => 'str[]', 'searchWord' => 'str'], 'str[][]'),
    'After typing each character of searchWord, suggest up to 3 products (lexicographically smallest) starting with the typed prefix.',
    ['1 <= products.length <= 1000'],
    [t([['mobile','moneypot','monitor','mouse','mousepad'], 'mouse'], [['mobile','moneypot','monitor'],['mobile','moneypot','monitor'],['mouse','mousepad'],['mouse','mousepad'],['mouse','mousepad']], 1),
     t([['havana'], 'havana'], [['havana'],['havana'],['havana'],['havana'],['havana'],['havana']], 1),
     t([['apple','apps','banana'], 'app'], [['apple','apps'],['apple','apps'],['apple','apps']])],
    'function suggestedProducts(products,sw){products.sort();var out=[];var pre="";for(var i=0;i<sw.length;i++){pre+=sw[i];var row=[];var lo=0,hi=products.length;while(lo<hi){var mid=(lo+hi)>>1;if(products[mid]<pre)lo=mid+1;else hi=mid;}for(var k=lo;k<Math.min(lo+3,products.length);k++)if(products[k].startsWith(pre))row.push(products[k]);else break;out.push(row);}return out;}'),

pdef('longest-dup-substring', 'Longest Duplicate Substring', 'hard', 'longestDupSubstring',
    sig(['s' => 'str'], 'str'),
    'Return any longest substring appearing at least twice (the binary-search checker returns the first found).',
    ['2 <= s.length <= 30000'],
    [t(['banana'], 'ana', 1), t(['abcd'], '', 1), t(['aaaa'], 'aaa'), t(['abcabc'], 'abc')],
    'function longestDupSubstring(s){function has(L){var seen=new Set();for(var i=0;i+L<=s.length;i++){var sub=s.substring(i,i+L);if(seen.has(sub))return sub;seen.add(sub);}return null;}var lo=1,hi=s.length-1,ans="";while(lo<=hi){var mid=(lo+hi)>>1;var r=has(mid);if(r!==null){ans=r;lo=mid+1;}else hi=mid-1;}return ans;}'),

pdef('missing-element-sorted', 'Missing Element in Sorted Array', 'medium', 'missingElement',
    sig(['nums' => 'int[]', 'k' => 'int'], 'int'),
    'The sorted array originally had no duplicates but some values were removed; return the kth missing number.',
    ['nums strictly increasing'],
    [t([[4,7,9,10], 1], 5, 1), t([[4,7,9,10], 3], 8, 1), t([[1,2,4], 3], 6), t([[4,7,9,10], 5], 12)],
    'function missingElement(nums,k){for(var i=1;i<nums.length;i++){var gap=nums[i]-nums[i-1]-1;if(k<=gap)return nums[i-1]+k;k-=gap;}return nums[nums.length-1]+k;}'),

pdef('fixed-point', 'Fixed Point', 'easy', 'fixedPoint',
    sig(['arr' => 'int[]'], 'int'),
    'arr contains distinct sorted values. Return the smallest index i with arr[i] === i, or -1.',
    ['1 <= arr.length <= 10000'],
    [t([[-10,-5,0,3,7]], 3, 1), t([[0,2,5,8,17]], 0, 1), t([[-10,-5,3,4,7,9]], -1), t([[-10,-5,2]], 2)],
    'function fixedPoint(arr){var lo=0,hi=arr.length-1,ans=-1;while(lo<=hi){var mid=(lo+hi)>>1;if(arr[mid]===mid){ans=mid;hi=mid-1;}else if(arr[mid]<mid)lo=mid+1;else hi=mid-1;}return ans;}'),

pdef('matrix-median', 'Median in a Row-wise Sorted Matrix', 'medium', 'matrixMedian',
    sig(['m' => 'int[][]'], 'int'),
    'Every row is sorted and the matrix has an odd number of cells. Return the median of all values.',
    ['rows and cols are odd'],
    [t([[[1,3,5],[2,6,9],[3,6,9]]], 5, 1), t([[[1]]], 1, 1), t([[[1,3,8],[2,5,9],[3,6,9]]], 5), t([[[1,4,9],[2,5,6],[3,7,8]]], 5)],
    'function matrixMedian(m){var rows=m.length,cols=m[0].length;function countLe(x){var cnt=0;for(var r=0;r<rows;r++){var lo=0,hi=cols;while(lo<hi){var mid=(lo+hi)>>1;if(m[r][mid]<=x)lo=mid+1;else hi=mid;}cnt+=lo;}return cnt;}var lo=Infinity,hi=-Infinity;for(var r=0;r<rows;r++){lo=Math.min(lo,m[r][0]);hi=Math.max(hi,m[r][cols-1]);}var need=(rows*cols+1)/2;while(lo<hi){var mid=(lo+hi)>>1;if(countLe(mid)>=need)hi=mid;else lo=mid+1;}return lo;}'),

pdef('max-count-pos-neg', 'Maximum Count of Positive and Negative Integers', 'easy', 'maximumCount',
    sig(['nums' => 'int[]'], 'int'),
    'nums is sorted non-decreasing. Return max(count of positives, count of negatives).',
    ['1 <= nums.length <= 2000'],
    [t([[-2,-1,-1,1,2,3]], 3, 1), t([[-3,-2,-1,0,0,1,2]], 3, 1), t([[5,20,66,1314]], 4), t([[-1]], 1)],
    'function maximumCount(nums){function first(f){var lo=0,hi=nums.length;while(lo<hi){var mid=(lo+hi)>>1;if(f(nums[mid]))hi=mid;else lo=mid+1;}return lo;}var neg=first(function(x){return x>=0;});var pos=nums.length-first(function(x){return x>0;});return Math.max(neg,pos);}'),

pdef('two-sum-less-than-k', 'Two Sum Less Than K', 'easy', 'twoSumLessThanK',
    sig(['nums' => 'int[]', 'k' => 'int'], 'int'),
    'Return the maximum sum of any pair that is strictly less than k, or -1 if none.',
    ['1 <= nums.length <= 100'],
    [t([[34,23,1,24,75,33,54,8], 60], 58, 1), t([[10,20,30], 15], -1, 1), t([[1,2], 2], -1), t([[19], 50], -1)],
    'function twoSumLessThanK(nums,k){nums.sort(function(a,b){return a-b;});var best=-1,l=0,r=nums.length-1;while(l<r){var s=nums[l]+nums[r];if(s<k){best=Math.max(best,s);l++;}else r--;}return best;}'),

];
