<?php
// Category: stack — matching, undo, monotonic stacks
return [
pdef('valid-parentheses', 'Valid Parentheses', 'easy', 'isValid',
    sig(['s' => 'str'], 'bool'),
    'The string contains only ( ) [ ] { }. Return true if every opening bracket is closed by the same type in the correct order.',
    ['1 ≤ s.length ≤ 10⁴'],
    [t(['()[]{}'], true, 1), t(['(]'], false, 1), t(['([)]'], false), t(['{[]}'], true), t(['('], false)],
    'function isValid(s){var st=[],m={")":"(","]":"[","}":"{"},i;for(i=0;i<s.length;i++){var c=s[i];if(c==="("||c==="["||c==="{")st.push(c);else{if(st.pop()!==m[c])return false;}}return st.length===0;}'),

pdef('longest-valid-parentheses', 'Longest Valid Parentheses', 'hard', 'longestValidParentheses',
    sig(['s' => 'str'], 'int'),
    'Return the length of the longest valid (well-formed) parentheses substring. The string contains only ( and ).',
    ['0 ≤ s.length ≤ 3·10⁴'],
    [t(['(()'], 2, 1), t([')()())'], 4, 1), t([''], 0), t(['()(())'], 6), t(['()'], 2)],
    'function longestValidParentheses(s){var st=[-1],best=0,i;for(i=0;i<s.length;i++){if(s[i]==="(")st.push(i);else{st.pop();if(!st.length)st.push(i);else best=Math.max(best,i-st[st.length-1]);}}return best;}'),

pdef('baseball-game', 'Baseball Game', 'easy', 'calPoints',
    sig(['operations' => 'str[]'], 'int'),
    'Score a strange game from its op list: an integer adds that score; "+" adds the sum of the previous two scores; "D" doubles the previous score; "C" removes the previous score. Return the final total.',
    ['1 ≤ operations.length ≤ 1000', 'input always produces a valid history'],
    [t([['5', '2', 'C', 'D', '+']], 30, 1), t([['5', '-2', '4', 'C', 'D', '9', '+', '+']], 27, 1), t([['1']], 1), t([['1', 'C']], 0)],
    'function calPoints(ops){var st=[],i,o;for(i=0;i<ops.length;i++){o=ops[i];if(o==="C")st.pop();else if(o==="D")st.push(2*st[st.length-1]);else if(o==="+")st.push(st[st.length-1]+st[st.length-2]);else st.push(parseInt(o,10));}return st.reduce(function(a,b){return a+b;},0);}'),

pdef('remove-adjacent-dups', 'Remove All Adjacent Duplicates', 'easy', 'removeDuplicates2',
    sig(['s' => 'str'], 'str'),
    'Repeatedly remove adjacent duplicate PAIRS until none remain, and return the final string. A stack does this in one pass.',
    ['1 ≤ s.length ≤ 10⁵', 'lowercase letters'],
    [t(['abbaca'], 'ca', 1), t(['azxxzy'], 'ay', 1), t(['aab'], 'b'), t(['ab'], 'ab')],
    'function removeDuplicates2(s){var st=[],i;for(i=0;i<s.length;i++){if(st.length&&st[st.length-1]===s[i])st.pop();else st.push(s[i]);}return st.join("");}'),

pdef('daily-temperatures', 'Daily Temperatures', 'medium', 'dailyTemperatures',
    sig(['temperatures' => 'int[]'], 'int[]'),
    'For each day, return how many days you must wait for a warmer temperature, or 0 if no warmer day comes later. A monotonic stack gives O(n).',
    ['1 ≤ n ≤ 10⁵', '30 ≤ temperatures[i] ≤ 100'],
    [t([[73, 74, 75, 71, 69, 72, 76, 73]], [1, 1, 4, 2, 1, 1, 0, 0], 1), t([[30, 40, 50, 60]], [1, 1, 1, 0], 1), t([[90, 80]], [0, 0]), t([[50]], [0])],
    'function dailyTemperatures(T){var out=new Array(T.length).fill(0),st=[],i;for(i=0;i<T.length;i++){while(st.length&&T[i]>T[st[st.length-1]]){var p=st.pop();out[p]=i-p;}st.push(i);}return out;}'),

pdef('next-greater-element', 'Next Greater Element', 'medium', 'nextGreater',
    sig(['nums' => 'int[]'], 'int[]'),
    'For every element, return the first strictly greater element to its right, or -1 if none exists.',
    ['1 ≤ nums.length ≤ 10⁴'],
    [t([[2, 1, 2, 4, 3]], [4, 2, 4, -1, -1], 1), t([[1]], [-1], 1), t([[5, 4, 3, 2, 1]], [-1, -1, -1, -1, -1]), t([[1, 3, 2, 4]], [3, 4, 4, -1])],
    'function nextGreater(nums){var out=new Array(nums.length).fill(-1),st=[],i;for(i=0;i<nums.length;i++){while(st.length&&nums[i]>nums[st[st.length-1]]){out[st.pop()]=nums[i];}st.push(i);}return out;}'),

pdef('eval-rpn', 'Evaluate Reverse Polish Notation', 'medium', 'evalRPN',
    sig(['tokens' => 'str[]'], 'int'),
    'Evaluate an arithmetic expression in Reverse Polish Notation: numbers are operands, "+ - * /" pop two operands and apply. Division truncates toward zero.',
    ['1 ≤ tokens.length ≤ 10⁴', 'input is always a valid expression'],
    [t([['2', '1', '+', '3', '*']], 9, 1), t([['4', '13', '5', '/', '+']], 6, 1), t([['10', '6', '9', '3', '+', '-11', '*', '/', '*', '17', '+', '5', '+']], 22), t([['18']], 18)],
    'function evalRPN(tk){var st=[],i;for(i=0;i<tk.length;i++){var t=tk[i];if(t==="+"||t==="-"||t==="*"||t==="/"){var b=st.pop(),a=st.pop(),r=0;if(t==="+")r=a+b;else if(t==="-")r=a-b;else if(t==="*")r=a*b;else r=(a/b<0?Math.ceil(a/b):Math.floor(a/b));st.push(r);}else st.push(parseInt(t,10));}return st[0];}'),

pdef('score-of-parentheses', 'Score of Parentheses', 'medium', 'scoreOfParentheses',
    sig(['s' => 'str'], 'int'),
    'Every balanced parentheses string scores: "()" = 1; AB = score(A)+score(B); (A) = 2×score(A). Return the total.',
    ['1 ≤ s.length ≤ 50', 's is a balanced parentheses string'],
    [t(['()'], 1, 1), t(['(())'], 2, 1), t(['()()'], 2), t(['(()(()))'], 6)],
    'function scoreOfParentheses(s){var st=[0],i;for(i=0;i<s.length;i++){if(s[i]==="(")st.push(0);else{var v=st.pop();st[st.length-1]+=Math.max(2*v,1);}}return st[0];}'),

pdef('min-add-valid', 'Minimum Add to Make Valid', 'medium', 'minAddToMakeValid',
    sig(['s' => 'str'], 'int'),
    'A parentheses string is valid if brackets match in order. In one move you may insert a parenthesis anywhere. Return the minimum moves to make s valid.',
    ['1 ≤ s.length ≤ 1000', 'only ( and )'],
    [t(['())'], 1, 1), t(['((('], 3, 1), t(['()'], 0), t(['()))(('], 4)],
    'function minAddToMakeValid(s){var open=0,add=0,i;for(i=0;i<s.length;i++){if(s[i]==="(")open++;else{if(open>0)open--;else add++;}}return add+open;}'),

pdef('remove-stars', 'Removing Stars From a String', 'medium', 'removeStars',
    sig(['s' => 'str'], 'str'),
    'Each * deletes the closest non-star character to its left (and itself). Process left to right and return the resulting string.',
    ['1 ≤ s.length ≤ 10⁵', 'a deletable character always exists for every *'],
    [t(['leet**cod*e'], 'lecoe', 1), t(['erase*****'], '', 1), t(['ab*'], 'a'), t(['abc'], 'abc')],
    'function removeStars(s){var st=[],i;for(i=0;i<s.length;i++){if(s[i]==="*")st.pop();else st.push(s[i]);}return st.join("");}'),

pdef('simplify-path', 'Simplify Path', 'medium', 'simplifyPath',
    sig(['path' => 'str'], 'str'),
    'Simplify a Unix-style absolute path: "." means stay, ".." means go up one level (never above root), repeated slashes collapse. Return the canonical path starting with one slash, no trailing slash.',
    ['1 ≤ path.length ≤ 3000', 'path starts with /'],
    [t(['/home/'], '/home', 1), t(['/../'], '/', 1), t(['/home//foo/'], '/home/foo'), t(['/a/./b/../../c/'], '/c')],
    'function simplifyPath(p){var st=[],parts=p.split("/"),i;for(i=0;i<parts.length;i++){var x=parts[i];if(x===""||x===".")continue;if(x==="..")st.pop();else st.push(x);}return "/"+st.join("/");}'),

pdef('remove-kdigits', 'Remove K Digits', 'medium', 'removeKdigits',
    sig(['num' => 'str', 'k' => 'int'], 'str'),
    'Remove exactly k digits from the given number string so the remaining number is as small as possible. Strip leading zeroes; if nothing remains, return "0".',
    ['1 ≤ k ≤ num.length ≤ 10⁵', 'num contains only digits, no leading zeros'],
    [t(['1432219', 3], '1219', 1), t(['10200', 1], '200', 1), t(['10', 2], '0'), t(['9', 1], '0')],
    'function removeKdigits(num,k){var st=[],i;for(i=0;i<num.length;i++){while(k>0&&st.length&&st[st.length-1]>num[i]){st.pop();k--;}st.push(num[i]);}while(k>0){st.pop();k--;}var out=st.join("").replace(/^0+/,"");return out===""?"0":out;}'),


pdef('asteroid-collision', 'Asteroid Collision', 'medium', 'asteroidCollision',
    sig(['a' => 'int[]'], 'int[]'),
    'Asteroids move along a row: positive goes right, negative goes left. Equal sizes destroy each other on collision, else the smaller explodes. Return the surviving asteroids.',
    ['2 <= a.length <= 10000'],
    [t([[5,10,-5]], [5,10], 1), t([[8,-8]], [], 1), t([[10,2,-5]], [10]), t([[-2,-1,1,2]], [-2,-1,1,2])],
    'function asteroidCollision(a){var st=[];for(var x of a){var alive=true;while(alive&&x<0&&st.length&&st[st.length-1]>0){var t=st[st.length-1];if(t<-x)st.pop();else{if(t===-x)st.pop();alive=false;}}if(alive)st.push(x);}return st;}'),

pdef('crawler-log-folder', 'Crawler Log Folder', 'easy', 'minOperations',
    sig(['logs' => 'str[]'], 'int'),
    'Each log is "x/" (enter folder), "../" (go up) or "./" (stay). Starting at the main folder, return the minimum operations to get back to it after performing all logs (i.e. the final depth).',
    ['1 <= logs.length <= 100'],
    [t([['d1/','d2/','../','d21/','./']], 2, 1), t([['d1/','d2/','./','d3/','../','d31/']], 3, 1), t([['d1/','../','../','../']], 0)],
    'function minOperations(logs){var d=0;for(var op of logs){if(op==="../")d=Math.max(0,d-1);else if(op!=="./")d++;}return d;}'),

pdef('remove-outer-parens', 'Remove Outermost Parentheses', 'easy', 'removeOuterParentheses',
    sig(['s' => 'str'], 'str'),
    'A valid parentheses string is primitive if it cannot be split into two non-empty valid strings. Decompose s into primitives and remove the outermost parentheses of each.',
    ['1 <= s.length <= 100000'],
    [t(['(()())(())'], '()()()', 1), t(['(()())(())(()(()))'], '()()()()(())', 1), t(['()()'], ''), t(['(())'], '()')],
    'function removeOuterParentheses(s){var out="",d=0;for(var c of s){if(c==="("){if(d>0)out+=c;d++;}else{d--;if(d>0)out+=c;}}return out;}'),

pdef('final-prices-discount', 'Final Prices With a Special Discount', 'easy', 'finalPrices',
    sig(['prices' => 'int[]'], 'int[]'),
    'Item i gets a discount equal to prices[j] where j > i is the first index with prices[j] <= prices[i] (0 if none). Return the final prices.',
    ['1 <= prices.length <= 500'],
    [t([[8,4,6,2,3]], [4,2,4,2,3], 1), t([[1,2,3,4,5]], [1,2,3,4,5], 1), t([[10,1,1,6]], [9,0,1,6]), t([[5]], [5])],
    'function finalPrices(prices){var st=[],res=prices.slice();for(var i=0;i<prices.length;i++){while(st.length&&prices[i]<=prices[st[st.length-1]]){var j=st.pop();res[j]=prices[j]-prices[i];}st.push(i);}return res;}'),

pdef('next-greater-ii', 'Next Greater Element II', 'medium', 'nextGreaterElements',
    sig(['nums' => 'int[]'], 'int[]'),
    'The array is circular: element n-1 is followed by element 0. For each index return the next greater element, or -1.',
    ['1 <= nums.length <= 10000'],
    [t([[1,2,1]], [2,-1,2], 1), t([[1,2,3,4,3]], [2,3,4,-1,4], 1), t([[5,4,3,2,1]], [-1,5,5,5,5]), t([[1]], [-1])],
    'function nextGreaterElements(nums){var n=nums.length,res=new Array(n).fill(-1),st=[];for(var i=0;i<2*n;i++){var x=nums[i%n];while(st.length&&nums[st[st.length-1]]<x)res[st.pop()]=x;if(i<n)st.push(i);}return res;}'),

pdef('stock-span-array', 'Online Stock Span', 'medium', 'stockSpan',
    sig(['prices' => 'int[]'], 'int[]'),
    'prices[i] is the price on day i. The span of day i is the maximum consecutive days ending at i with price <= prices[i]. Return the span of every day.',
    ['1 <= prices.length <= 10000'],
    [t([[100,80,60,70,60,75,85]], [1,1,1,2,1,4,6], 1), t([[10,4,5,90,120,80]], [1,1,2,4,5,1], 1), t([[7]], [1]), t([[1,2]], [1,2])],
    'function stockSpan(prices){var res=[],st=[];for(var i=0;i<prices.length;i++){while(st.length&&prices[st[st.length-1]]<=prices[i])st.pop();res.push(st.length?i-st[st.length-1]:i+1);st.push(i);}return res;}'),

pdef('validate-stack-sequences', 'Validate Stack Sequences', 'medium', 'validateStackSequences',
    sig(['pushed' => 'int[]', 'popped' => 'int[]'], 'bool'),
    'Given the push order, return true if popped could result from some sequence of push and pop operations.',
    ['pushed and popped hold distinct values'],
    [t([[1,2,3,4,5], [4,5,3,2,1]], true, 1), t([[1,2,3,4,5], [4,3,5,1,2]], false, 1), t([[1,0], [1,0]], true), t([[2,1,0], [1,2,0]], true)],
    'function validateStackSequences(pushed,popped){var st=[],j=0;for(var x of pushed){st.push(x);while(st.length&&st[st.length-1]===popped[j]){st.pop();j++;}}return st.length===0;}'),

pdef('132-pattern', '132 Pattern', 'medium', 'find132pattern',
    sig(['nums' => 'int[]'], 'bool'),
    'Return true if there exist i < j < k with nums[i] < nums[k] < nums[j].',
    ['3 <= nums.length <= 200000'],
    [t([[1,2,3,4]], false, 1), t([[3,1,4,2]], true, 1), t([[-1,3,2,0]], true), t([[1,0,1]], false)],
    'function find132pattern(nums){var st=[],s3=-Infinity;for(var i=nums.length-1;i>=0;i--){if(nums[i]<s3)return true;while(st.length&&nums[i]>st[st.length-1])s3=st.pop();st.push(nums[i]);}return false;}'),

pdef('smallest-number-pattern', 'Construct Smallest Number From DI String', 'medium', 'smallestNumber',
    sig(['pattern' => 'str'], 'str'),
    'pattern holds I (increase) and D (decrease). Build the lexicographically smallest num using digits 1-9 (each at most once) whose consecutive comparisons match the pattern.',
    ['1 <= pattern.length <= 8'],
    [t(['IIIDIDDD'], '123549876', 1), t(['DDD'], '4321', 1), t(['ID'], '132'), t(['I'], '12')],
    'function smallestNumber(p){var res="",st=[];for(var i=0;i<=p.length;i++){st.push(String(i+1));if(i===p.length||p[i]==="I"){while(st.length)res+=st.pop();}}return res;}'),

pdef('min-remove-valid-parens', 'Minimum Remove to Make Valid Parentheses', 'medium', 'minRemoveToMakeValid',
    sig(['s' => 'str'], 'str'),
    'Remove the minimum number of parentheses so the result is a valid parentheses string. Return any valid result (the unique output of removing every unmatched bracket).',
    ['1 <= s.length <= 100000'],
    [t(['lee(t(c)o)de)'], 'lee(t(c)o)de', 1), t(['a)b(c)d'], 'ab(c)d', 1), t(['))(('], ''), t(['(a(b(c)d)'], 'a(b(c)d)')],
    'function minRemoveToMakeValid(s){var st=[],skip={};for(var i=0;i<s.length;i++){var c=s[i];if(c==="(")st.push(i);else if(c===")"){if(st.length)st.pop();else skip[i]=true;}}while(st.length)skip[st.pop()]=true;var out="";for(var i=0;i<s.length;i++)if(!skip[i])out+=s[i];return out;}'),

pdef('basic-calculator', 'Basic Calculator', 'hard', 'calculate',
    sig(['s' => 'str'], 'int'),
    'Evaluate an expression with non-negative integers, +, -, parentheses and spaces.',
    ['1 <= s.length <= 300000'],
    [t(['1 + 1'], 2, 1), t([' 2-1 + 2 '], 3, 1), t(['(1+(4+5+2)-3)+(6+8)'], 23), t(['-2+ 1'], -1)],
    'function calculate(s){var st=[],res=0,num=0,sign=1;for(var i=0;i<s.length;i++){var c=s[i];if(c>="0"&&c<="9")num=num*10+Number(c);else if(c==="+"||c==="-"){res+=sign*num;num=0;sign=c==="+"?1:-1;}else if(c==="("){st.push(res);st.push(sign);res=0;sign=1;}else if(c===")"){res+=sign*num;num=0;res=st.pop()*res+st.pop();}}return res+sign*num;}'),

pdef('basic-calculator-ii', 'Basic Calculator II', 'medium', 'calculate2',
    sig(['s' => 'str'], 'int'),
    'Evaluate an expression with non-negative integers, +, -, *, / and spaces. Integer division truncates toward zero. No parentheses.',
    ['1 <= s.length <= 300000'],
    [t(['3+2*2'], 7, 1), t([' 3/2 '], 1, 1), t([' 3+5 / 2 '], 5), t(['14-3/2'], 13)],
    'function calculate2(s){var st=[],num=0,op="+";for(var i=0;i<=s.length;i++){var c=s[i];if(i<s.length&&c===" ")continue;if(i<s.length&&c>="0"&&c<="9")num=num*10+Number(c);else{if(op==="+")st.push(num);else if(op==="-")st.push(-num);else if(op==="*")st.push(st.pop()*num);else st.push(Math.trunc(st.pop()/num));num=0;op=c;}}var res=0;for(var x of st)res+=x;return res;}'),

pdef('largest-rectangle', 'Largest Rectangle in Histogram', 'hard', 'largestRectangleArea',
    sig(['heights' => 'int[]'], 'int'),
    'Each bar has width 1 and the given height. Return the area of the largest rectangle inside the histogram.',
    ['1 <= heights.length <= 100000'],
    [t([[2,1,5,6,2,3]], 10, 1), t([[2,4]], 4, 1), t([[1]], 1), t([[6,2,5,4,5,1,6]], 12)],
    'function largestRectangleArea(h){var st=[],best=0;for(var i=0;i<=h.length;i++){var cur=i<h.length?h[i]:0;while(st.length&&h[st[st.length-1]]>=cur){var x=h[st.pop()];var left=st.length?st[st.length-1]+1:0;best=Math.max(best,x*(i-left));}st.push(i);}return best;}'),

pdef('maximal-rectangle', 'Maximal Rectangle', 'hard', 'maximalRectangle',
    sig(['matrix' => 'int[][]'], 'int'),
    'The matrix holds only 0 and 1. Return the area of the largest rectangle containing only 1s.',
    ['1 <= rows, cols <= 200'],
    [t([[[1,0,1,0,0],[1,0,1,1,1],[1,1,1,1,1],[1,0,0,1,0]]], 6, 1), t([[[0]]], 0, 1), t([[[1]]], 1), t([[[1,1],[1,1]]], 4)],
    'function maximalRectangle(m){var rows=m.length,cols=m[0].length,h=new Array(cols).fill(0),best=0;function largest(a){var st=[],mx=0;for(var i=0;i<=a.length;i++){var cur=i<a.length?a[i]:0;while(st.length&&a[st[st.length-1]]>=cur){var x=a[st.pop()];var left=st.length?st[st.length-1]+1:0;mx=Math.max(mx,x*(i-left));}st.push(i);}return mx;}for(var i=0;i<rows;i++){for(var j=0;j<cols;j++)h[j]=m[i][j]===1?h[j]+1:0;best=Math.max(best,largest(h));}return best;}'),

pdef('remove-dups-k', 'Remove All Adjacent Duplicates in String II', 'medium', 'removeDuplicatesK',
    sig(['s' => 'str', 'k' => 'int'], 'str'),
    'Repeatedly delete groups of k identical adjacent characters until none remain. Return the final string.',
    ['2 <= k <= 10000'],
    [t(['abcd', 2], 'abcd', 1), t(['deeedbbcccbdaa', 3], 'aa', 1), t(['pbbcggttciiippooaais', 2], 'ps'), t(['aabbb', 3], 'aa')],
    'function removeDuplicatesK(s,k){var st=[];for(var c of s){if(st.length&&st[st.length-1][0]===c)st[st.length-1][1]++;else st.push([c,1]);if(st[st.length-1][1]===k)st.pop();}var out="";for(var p of st)out+=p[0].repeat(p[1]);return out;}'),

pdef('make-good-string', 'Make The String Great', 'easy', 'makeGood',
    sig(['s' => 'str'], 'str'),
    'While two adjacent characters are the same letter in opposite cases (like "aA"), remove both. Return the final string.',
    ['1 <= s.length <= 100'],
    [t(['leEeetcode'], 'leetcode', 1), t(['abBAcC'], '', 1), t(['s'], 's'), t(['Pp'], '')],
    'function makeGood(s){var st=[];for(var c of s){var t=st.length?st[st.length-1]:"";if(t&&t!==c&&t.toLowerCase()===c.toLowerCase())st.pop();else st.push(c);}return st.join("");}'),

pdef('min-subarray-balance', 'Make Sum Divisible by P', 'medium', 'minSubarray',
    sig(['nums' => 'int[]', 'p' => 'int'], 'int'),
    'Remove the smallest contiguous subarray so the remaining sum is divisible by p. Return its length, or -1. You may not remove everything.',
    ['1 <= nums.length <= 100000'],
    [t([[3,1,4,2], 6], 1, 1), t([[6,3,5,2], 9], 2, 1), t([[1,2,3], 3], 0), t([[1,2,3], 7], -1)],
    'function minSubarray(nums,p){var total=0;for(var x of nums)total+=x;var rem=total%p;if(rem===0)return 0;var need={0:-1},cur=0,best=nums.length;for(var i=0;i<nums.length;i++){cur=(cur+nums[i])%p;need[cur]=i;var want=((cur-rem)%p+p)%p;if(need[want]!==undefined)best=Math.min(best,i-need[want]);}return best===nums.length?-1:best;}'),

pdef('sum-subarray-mins', 'Sum of Subarray Minimums', 'medium', 'sumSubarrayMins',
    sig(['arr' => 'int[]'], 'int'),
    'Return the sum of the minimum of every contiguous subarray, modulo 10^9 + 7.',
    ['1 <= arr.length <= 30000'],
    [t([[3,1,2,4]], 17, 1), t([[11,81,94,43,3]], 444, 1), t([[1,1]], 3), t([[2]], 2)],
    'function sumSubarrayMins(arr){var M=1000000007;var n=arr.length,left=new Array(n),right=new Array(n),st=[];for(var i=0;i<n;i++){while(st.length&&arr[st[st.length-1]]>arr[i]){var j=st.pop();right[j]=i-j;}left[i]=i-(st.length?st[st.length-1]:-1);st.push(i);}while(st.length){var j2=st.pop();right[j2]=n-j2;}var res=0;for(var i=0;i<n;i++)res=(res+arr[i]*left[i]*right[i])%M;return res;}'),

pdef('sum-subarray-ranges', 'Sum of Subarray Ranges', 'medium', 'subArrayRanges',
    sig(['nums' => 'int[]'], 'int'),
    'The range of a subarray is max minus min. Return the sum of ranges over all contiguous subarrays.',
    ['1 <= nums.length <= 1000'],
    [t([[1,2,3]], 4, 1), t([[1,3,3]], 4, 1), t([[4,-2,-3,4,1]], 59), t([[1]], 0)],
    'function subArrayRanges(nums){var total=0;for(var i=0;i<nums.length;i++){var mn=nums[i],mx=nums[i];for(var j=i+1;j<nums.length;j++){mn=Math.min(mn,nums[j]);mx=Math.max(mx,nums[j]);total+=mx-mn;}}return total;}'),

pdef('min-insertions-balance', 'Minimum Insertions to Balance a Parentheses String', 'medium', 'minInsertions',
    sig(['s' => 'str'], 'int'),
    'A string is balanced if every ( is matched by exactly )) after it (reads: one open needs two closes). Return the minimum insertions to balance s.',
    ['1 <= s.length <= 100000'],
    [t(['(()))'], 1, 1), t(['())'], 0, 1), t(['))())('], 3), t(['(((((('], 12), t([')(())'], 4)],
    'function minInsertions(s){var res=0,open=0,i=0;while(i<s.length){if(s[i]==="("){open++;i++;}else{if(i+1<s.length&&s[i+1]===")"){if(open>0)open--;else res++;i+=2;}else{res++;if(open>0)open--;else res++;i++;}}}return res+open*2;}'),

pdef('shortest-subarray-k', 'Shortest Subarray with Sum at Least K', 'hard', 'shortestSubarray',
    sig(['nums' => 'int[]', 'k' => 'int'], 'int'),
    'Return the length of the shortest non-empty subarray whose sum is at least k, or -1. Values may be negative.',
    ['1 <= nums.length <= 100000'],
    [t([[1], 1], 1, 1), t([[1,2], 4], -1, 1), t([[2,-1,2], 3], 3), t([[84,-37,32,40,95], 167], 3)],
    'function shortestSubarray(nums,k){var n=nums.length,pre=new Array(n+1).fill(0);for(var i=0;i<n;i++)pre[i+1]=pre[i]+nums[i];var dq=[],best=n+1;for(var i=0;i<=n;i++){while(dq.length&&pre[i]-pre[dq[0]]>=k)best=Math.min(best,i-dq.shift());while(dq.length&&pre[dq[dq.length-1]]>=pre[i])dq.pop();dq.push(i);}return best>n?-1:best;}'),

pdef('max-nesting-depth', 'Maximum Nesting Depth of the Parentheses', 'easy', 'maxDepth',
    sig(['s' => 'str'], 'int'),
    's is a valid parentheses expression. Return its maximum nesting depth.',
    ['1 <= s.length <= 100'],
    [t(['(1+(2*3)+((8)/4))+1'], 3, 1), t(['(1)+((2))+(((3)))'], 3, 1), t(['()'], 1), t(['1'], 0)],
    'function maxDepth(s){var d=0,best=0;for(var c of s){if(c==="(")d++;else if(c===")")d--;if(d>best)best=d;}return best;}'),

pdef('build-array-ops', 'Build an Array With Stack Operations', 'medium', 'buildArray',
    sig(['target' => 'int[]', 'n' => 'int'], 'str[]'),
    'With a stream of numbers 1..n and operations Push and Pop, produce the exact stack target (read bottom-up). Return the operation list.',
    ['target is strictly increasing, values <= n'],
    [t([[1,3], 3], ['Push','Push','Pop','Push'], 1), t([[1,2,3], 3], ['Push','Push','Push'], 1), t([[1,2], 4], ['Push','Push']), t([[2,3,4], 4], ['Push','Pop','Push','Push','Push'])],
    'function buildArray(target,n){var ops=[],cur=1;for(var t of target){while(cur<t){ops.push("Push");ops.push("Pop");cur++;}ops.push("Push");cur++;}return ops;}'),

pdef('reverse-parens-substr', 'Reverse Substrings Between Each Pair of Parentheses', 'medium', 'reverseParentheses',
    sig(['s' => 'str'], 'str'),
    'Reverse the substring inside every matching pair of parentheses, innermost first, and remove the parentheses.',
    ['0 <= s.length <= 2000'],
    [t(['(abcd)'], 'dcba', 1), t(['(u(love)i)'], 'iloveu', 1), t(['(ed(et(oc))el)'], 'leetcode'), t(['a(bcdefghijkl(mno)p)q'], 'apmnolkjihgfedcbq')],
    'function reverseParentheses(s){var st=[];var arr=s.split("");for(var i=0;i<arr.length;i++){if(arr[i]==="(")st.push(i);else if(arr[i]===")"){var l=st.pop()+1,r=i-1;while(l<r){var tmp=arr[l];arr[l]=arr[r];arr[r]=tmp;l++;r--;}}}return arr.filter(function(c){return c!=="("&&c!==")";}).join("");}'),

pdef('valid-abc-subs', 'Check If Word Is Valid After Substitutions', 'medium', 'isValid',
    sig(['s' => 'str'], 'bool'),
    'Starting from an empty string you may insert "abc" anywhere. Return true if s can be built this way.',
    ['1 <= s.length <= 20000'],
    [t(['aabcbc'], true, 1), t(['abcabcababcc'], true, 1), t(['abccba'], false), t(['cababc'], false)],
    'function isValid(s){var st=[];for(var c of s){if(c==="c"){var n=st.length;if(n<2||st[n-2]!=="a"||st[n-1]!=="b")return false;st.pop();st.pop();}else st.push(c);}return st.length===0;}'),

pdef('count-collisions-road', 'Count Collisions on a Road', 'medium', 'countCollisions',
    sig(['directions' => 'str'], 'int'),
    'Cars move Left, Right or Stay. Cars driving toward each other collide and stop; a moving car hitting a stopped car also stops. Return the total number of collisions involving moving cars.',
    ['1 <= directions.length <= 100000'],
    [t(['RLRSLL'], 5, 1), t(['LLRR'], 0, 1), t(['RLRLR'], 4), t(['SSRSSRLLRSLLRSRSSRLRRRRLLRRLSSRR'], 20)],
    'function countCollisions(dir){var a=dir.replace(/^L+/,"").replace(/R+$/,"");var cnt=0;for(var c of a)if(c!=="S")cnt++;return cnt;}'),

];
