<?php
// Category: matrix — rows, columns, diagonals, spirals
return [
pdef('richest-customer', 'Richest Customer Wealth', 'easy', 'maximumWealth',
    sig(['accounts' => 'int[][]'], 'int'),
    'accounts[i][j] is the balance of customer i in bank j. A customer\'s wealth is the row sum. Return the maximum wealth.',
    ['1 ≤ rows, cols ≤ 50'],
    [t([[[1, 2, 3], [3, 2, 1]]], 6, 1), t([[[1, 5], [7, 3], [3, 5]]], 10, 1), t([[[2, 8, 7], [7, 1, 3], [1, 9, 5]]], 17), t([[[0]]], 0)],
    'function maximumWealth(accs){var best=0,i;for(i=0;i<accs.length;i++){var s=accs[i].reduce(function(a,b){return a+b;},0);best=Math.max(best,s);}return best;}'),

pdef('transpose-matrix', 'Transpose Matrix', 'easy', 'transpose',
    sig(['matrix' => 'int[][]'], 'int[][]'),
    'Return the transpose: rows become columns and columns become rows.',
    ['1 ≤ rows, cols ≤ 1000'],
    [t([[[1, 2, 3], [4, 5, 6]]], [[1, 4], [2, 5], [3, 6]], 1), t([[[1], [2]]], [[1, 2]], 1), t([[[5]]], [[5]]), t([[[1, 2]]], [[1], [2]])],
    'function transpose(m){var out=[],r,c;for(c=0;c<m[0].length;c++){var row=[];for(r=0;r<m.length;r++){row.push(m[r][c]);}out.push(row);}return out;}'),

pdef('flip-invert-image', 'Flipping an Image', 'easy', 'flipAndInvertImage',
    sig(['image' => 'int[][]'], 'int[][]'),
    'First flip each row horizontally, then invert every bit (0↔1). Return the transformed image.',
    ['1 ≤ rows, cols ≤ 20', 'values are 0 or 1'],
    [t([[[1, 1, 0], [1, 0, 1], [0, 0, 0]]], [[1, 0, 0], [0, 1, 0], [1, 1, 1]], 1),
     t([[[1, 1, 0, 0], [1, 0, 0, 1], [0, 1, 1, 1], [1, 0, 1, 0]]], [[1, 1, 0, 0], [0, 1, 1, 0], [0, 0, 0, 1], [1, 0, 1, 0]], 1),
     t([[[0]]], [[1]]), t([[[1, 0]]], [[1, 0]])],
    'function flipAndInvertImage(img){return img.map(function(row){return row.reverse().map(function(b){return b^1;});});}'),

pdef('reshape-matrix', 'Reshape the Matrix', 'easy', 'matrixReshape',
    sig(['mat' => 'int[][]', 'r' => 'int', 'c' => 'int'], 'int[][]'),
    'Reshape the matrix into r rows × c columns, keeping the original row-major reading order. If the reshape is impossible (element counts differ), return the original matrix.',
    ['1 ≤ r·c ≤ 300'],
    [t([[[1, 2], [3, 4]], 1, 4], [[1, 2, 3, 4]], 1), t([[[1, 2], [3, 4]], 4, 1], [[1], [2], [3], [4]], 1),
     t([[[1, 2], [3, 4]], 2, 4], [[1, 2], [3, 4]]), t([[[1]], 1, 1], [[1]])],
    'function matrixReshape(m,r,c){var flat=[],i,j,R=m.length,C=m[0].length;if(R*C!==r*c)return m;for(i=0;i<R;i++){for(j=0;j<C;j++){flat.push(m[i][j]);}}var out=[],k=0;for(i=0;i<r;i++){out.push(flat.slice(k,k+c));k+=c;}return out;}'),

pdef('diagonal-sum', 'Matrix Diagonal Sum', 'easy', 'diagonalSum',
    sig(['mat' => 'int[][]'], 'int'),
    'Sum both diagonals of the square matrix; the center element of an odd-sized matrix counts only once.',
    ['1 ≤ n ≤ 100'],
    [t([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]], 25, 1), t([[[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]]], 8, 1), t([[[5]]], 5), t([[[1, 0], [0, 1]]], 2)],
    'function diagonalSum(m){var n=m.length,s=0,i;for(i=0;i<n;i++){s+=m[i][i]+m[i][n-1-i];}if(n%2===1){var mid=(n-1)/2;s-=m[mid][mid];}return s;}'),

pdef('lucky-numbers', 'Lucky Numbers in a Matrix', 'easy', 'luckyNumbers',
    sig(['matrix' => 'int[][]'], 'int[]'),
    'A lucky number is the minimum of its row AND the maximum of its column. Return all lucky numbers (at most one can exist), any order — tests use sorted output.',
    ['1 ≤ rows, cols ≤ 50', 'all elements distinct'],
    [t([[[3, 7, 8], [9, 11, 13], [15, 16, 17]]], [15], 1), t([[[1, 10, 4, 2], [9, 3, 8, 7], [15, 16, 17, 12]]], [12], 1),
     t([[[7, 8], [1, 2]]], [7]), t([[[3, 6], [5, 4]]], [])],
    'function luckyNumbers(m){var out=[],i,j;for(i=0;i<m.length;i++){var min=Math.min.apply(null,m[i]),j=m[i].indexOf(min),ok=true;for(var r=0;r<m.length;r++){if(m[r][j]>min){ok=false;break;}}if(ok)out.push(min);}return out;}'),

pdef('spiral-matrix', 'Spiral Matrix', 'medium', 'spiralOrder',
    sig(['matrix' => 'int[][]'], 'int[]'),
    'Return all elements of the matrix in clockwise spiral order, starting from the top-left.',
    ['1 ≤ rows, cols ≤ 10'],
    [t([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]], [1, 2, 3, 6, 9, 8, 7, 4, 5], 1),
     t([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]], [1, 2, 3, 4, 8, 12, 11, 10, 9, 5, 6, 7], 1),
     t([[[1]]], [1]), t([[[1, 2], [3, 4]]], [1, 2, 4, 3])],
    'function spiralOrder(m){var out=[],top=0,left=0,bottom=m.length-1,right=m[0].length-1,i;while(top<=bottom&&left<=right){for(i=left;i<=right;i++)out.push(m[top][i]);top++;for(i=top;i<=bottom;i++)out.push(m[i][right]);right--;if(top<=bottom){for(i=right;i>=left;i--)out.push(m[bottom][i]);bottom--;}if(left<=right){for(i=bottom;i>=top;i--)out.push(m[i][left]);left++;}}return out;}'),

pdef('rotate-image', 'Rotate Image', 'medium', 'rotateImage',
    sig(['matrix' => 'int[][]'], 'int[][]'),
    'Rotate the n×n image by 90 degrees clockwise and return the result (transpose, then reverse each row).',
    ['1 ≤ n ≤ 20'],
    [t([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]], [[7, 4, 1], [8, 5, 2], [9, 6, 3]], 1),
     t([[[5, 1, 9, 11], [2, 4, 8, 10], [13, 3, 6, 7], [15, 14, 12, 16]]], [[15, 13, 2, 5], [14, 3, 4, 1], [12, 6, 8, 9], [16, 7, 10, 11]], 1),
     t([[[1]]], [[1]]), t([[[1, 2], [3, 4]]], [[3, 1], [4, 2]])],
    'function rotateImage(m){var n=m.length,i,j;for(i=0;i<n;i++){for(j=i+1;j<n;j++){var t=m[i][j];m[i][j]=m[j][i];m[j][i]=t;}}for(i=0;i<n;i++){m[i].reverse();}return m;}'),

pdef('set-zeroes', 'Set Matrix Zeroes', 'medium', 'setZeroes',
    sig(['matrix' => 'int[][]'], 'int[][]'),
    'For every cell that is 0, zero out its ENTIRE row and column (cascades do not chain — base decisions on the original matrix). Return the updated matrix.',
    ['1 ≤ rows, cols ≤ 200'],
    [t([[[1, 1, 1], [1, 0, 1], [1, 1, 1]]], [[1, 0, 1], [0, 0, 0], [1, 0, 1]], 1),
     t([[[0, 1, 2, 0], [3, 4, 5, 2], [1, 3, 1, 5]]], [[0, 0, 0, 0], [0, 4, 5, 0], [0, 3, 1, 0]], 1),
     t([[[1]]], [[1]]), t([[[0, 1]]], [[0, 0]])],
    'function setZeroes(m){var rows=new Set(),cols=new Set(),i,j;for(i=0;i<m.length;i++){for(j=0;j<m[0].length;j++){if(m[i][j]===0){rows.add(i);cols.add(j);}}}for(i=0;i<m.length;i++){for(j=0;j<m[0].length;j++){if(rows.has(i)||cols.has(j))m[i][j]=0;}}return m;}'),

pdef('search-2d-matrix', 'Search a 2D Matrix', 'medium', 'searchMatrix',
    sig(['matrix' => 'int[][]', 'target' => 'int'], 'bool'),
    'Rows are sorted ascending, and each row starts after the previous row ends (reading order is one sorted list). Decide whether target exists. O(log(m·n)) by treating it as a virtual flat array.',
    ['1 ≤ rows, cols ≤ 100'],
    [t([[[1, 3, 5, 7], [10, 11, 16, 20], [23, 30, 34, 60]], 3], true, 1), t([[[1, 3, 5, 7], [10, 11, 16, 20], [23, 30, 34, 60]], 13], false, 1),
     t([[[1]], 1], true), t([[[1, 3]], 2], false)],
    'function searchMatrix(m,t){var R=m.length,C=m[0].length,lo=0,hi=R*C-1;while(lo<=hi){var mid=(lo+hi)>>1,v=m[(mid/C)|0][mid%C];if(v===t)return true;if(v<t)lo=mid+1;else hi=mid-1;}return false;}'),

pdef('island-count', 'Number of Islands', 'medium', 'numIslands',
    sig(['grid' => 'int[][]'], 'int'),
    '0 is water, 1 is land. An island is land connected horizontally or vertically. Count the islands.',
    ['1 ≤ rows, cols ≤ 300'],
    [t([[[1, 1, 0, 0], [1, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]], 3, 1), t([[[1, 0]]], 1, 1), t([[[0, 0], [0, 0]]], 0), t([[[1]]], 1)],
    'function numIslands(g){var R=g.length,C=g[0].length,count=0,dfs=function(r,c){if(r<0||c<0||r>=R||c>=C||g[r][c]!==1)return;g[r][c]=2;dfs(r+1,c);dfs(r-1,c);dfs(r,c+1);dfs(r,c-1);},i,j;for(i=0;i<R;i++){for(j=0;j<C;j++){if(g[i][j]===1){count++;dfs(i,j);}}}return count;}'),


pdef('spiral-matrix-ii', 'Spiral Matrix II', 'medium', 'generateMatrix',
    sig(['n' => 'int'], 'int[][]'),
    'Generate an n x n matrix filled with 1..n^2 in spiral (clockwise) order.',
    ['1 <= n <= 20'],
    [t([3], [[1,2,3],[8,9,4],[7,6,5]], 1), t([1], [[1]], 1), t([2], [[1,2],[4,3]]), t([4], [[1,2,3,4],[12,13,14,5],[11,16,15,6],[10,9,8,7]])],
    'function generateMatrix(n){var out=[];for(var i=0;i<n;i++)out.push(new Array(n).fill(0));var top=0,bot=n-1,left=0,right=n-1,v=1;while(top<=bot&&left<=right){for(var c=left;c<=right;c++)out[top][c]=v++;top++;for(var r=top;r<=bot;r++)out[r][right]=v++;right--;if(top<=bot){for(var c2=right;c2>=left;c2--)out[bot][c2]=v++;bot--;}if(left<=right){for(var r2=bot;r2>=top;r2--)out[r2][left]=v++;left++;}}return out;}'),

pdef('diagonal-traverse', 'Diagonal Traverse', 'medium', 'findDiagonalOrder',
    sig(['mat' => 'int[][]'], 'int[]'),
    'Return all elements in zig-zag diagonal order (up toward the top-right, then down, alternating).',
    ['1 <= rows, cols <= 10000'],
    [t([[[1,2,3],[4,5,6],[7,8,9]]], [1,2,4,7,5,3,6,8,9], 1), t([[[1,2],[3,4]]], [1,2,3,4], 1), t([[[5]]], [5])],
    'function findDiagonalOrder(m){var rows=m.length,cols=m[0].length;var out=[];for(var d=0;d<rows+cols-1;d++){var diag=[];for(var r=0;r<rows;r++){var c=d-r;if(c>=0&&c<cols)diag.push(m[r][c]);}if(d%2===0)diag.reverse();for(var x of diag)out.push(x);}return out;}'),

pdef('toeplitz-matrix', 'Toeplitz Matrix', 'easy', 'isToeplitzMatrix',
    sig(['m' => 'int[][]'], 'bool'),
    'Return true if every diagonal from top-left to bottom-right has the same value in all its cells.',
    ['1 <= rows, cols <= 20'],
    [t([[[1,2,3,4],[5,1,2,3],[9,5,1,2]]], true, 1), t([[[1,2],[2,2]]], false, 1), t([[[1]]], true), t([[[6,7],[8,6]]], true)],
    'function isToeplitzMatrix(m){for(var i=1;i<m.length;i++)for(var j=1;j<m[0].length;j++)if(m[i][j]!==m[i-1][j-1])return false;return true;}'),

pdef('projection-area', 'Projection Area of 3D Shapes', 'easy', 'projectionArea',
    sig(['grid' => 'int[][]'], 'int'),
    'grid[i][j] towers sit on an n x n grid. Return the total area of the three axis-aligned silhouettes (top, front, side).',
    ['n x n grid of non-negative heights'],
    [t([[[5]]], 11, 1), t([[[1,2],[3,4]]], 17, 1), t([[[1,0],[0,2]]], 8), t([[[2,2,2],[2,1,2],[2,2,2]]], 21)],
    'function projectionArea(g){var n=g.length,top=0,front=0,side=0;for(var i=0;i<n;i++){var mf=0,ms=0;for(var j=0;j<n;j++){if(g[i][j]>0)top++;mf=Math.max(mf,g[i][j]);ms=Math.max(ms,g[j][i]);}front+=mf;side+=ms;}return top+front+side;}'),

pdef('matrix-block-sum', 'Matrix Block Sum', 'medium', 'matrixBlockSum',
    sig(['mat' => 'int[][]', 'k' => 'int'], 'int[][]'),
    'For each cell, sum all elements within Manhattan-square distance k (rows and cols within k). Return the answer matrix.',
    ['1 <= rows, cols <= 100', '0 <= k'],
    [t([[[1,2,3],[4,5,6],[7,8,9]], 1], [[12,21,16],[27,45,33],[24,39,28]], 1), t([[[1,2],[3,4]], 0], [[1,2],[3,4]], 1), t([[[5]], 2], [[5]])],
    'function matrixBlockSum(mat,k){var rows=mat.length,cols=mat[0].length;var out=[];for(var i=0;i<rows;i++){out.push([]);for(var j=0;j<cols;j++){var s=0;for(var r=Math.max(0,i-k);r<=Math.min(rows-1,i+k);r++)for(var c=Math.max(0,j-k);c<=Math.min(cols-1,j+k);c++)s+=mat[r][c];out[i].push(s);}}return out;}'),

pdef('flood-fill', 'Flood Fill', 'easy', 'floodFill',
    sig(['image' => 'int[][]', 'sr' => 'int', 'sc' => 'int', 'color' => 'int'], 'int[][]'),
    'Starting at (sr, sc), recolor every 4-connected pixel sharing its colour. Return the new image.',
    ['1 <= rows, cols <= 50'],
    [t([[[1,1,1],[1,1,0],[1,0,1]], 1, 1, 2], [[2,2,2],[2,2,0],[2,0,1]], 1), t([[[0,0,0],[0,0,0]], 0, 0, 0], [[0,0,0],[0,0,0]], 1), t([[[0,0,0],[0,1,1]], 1, 1, 1], [[0,0,0],[0,1,1]])],
    'function floodFill(image,sr,sc,color){var orig=image[sr][sc];if(orig===color)return image;var rows=image.length,cols=image[0].length;var st=[[sr,sc]];while(st.length){var p=st.pop();var r=p[0],c=p[1];if(r<0||r>=rows||c<0||c>=cols||image[r][c]!==orig)continue;image[r][c]=color;st.push([r-1,c],[r+1,c],[r,c-1],[r,c+1]);}return image;}'),

pdef('odd-cells', 'Cells with Odd Values in a Matrix', 'easy', 'oddCells',
    sig(['m' => 'int', 'n' => 'int', 'indices' => 'int[][]'], 'int'),
    'Start with an m x n zero matrix. Each entry [ri, ci] increments row ri and column ci. Count cells ending with an odd value.',
    ['1 <= m, n <= 50'],
    [t([2, 3, [[0,1],[1,1]]], 6, 1), t([2, 2, [[1,1],[0,0]]], 0, 1), t([1, 1, [[0,0]]], 0), t([3, 3, []], 0)],
    'function oddCells(m,n,indices){var rows=new Array(m).fill(0),cols=new Array(n).fill(0);for(var p of indices){rows[p[0]]++;cols[p[1]]++;}var odd=0;for(var i=0;i<m;i++)for(var j=0;j<n;j++)if((rows[i]+cols[j])%2)odd++;return odd;}'),

pdef('shift-2d-grid', 'Shift 2D Grid', 'easy', 'shiftGrid',
    sig(['grid' => 'int[][]', 'k' => 'int'], 'int[][]'),
    'Flatten the grid row-major, shift right by k (wrapping), and reshape. Return the result.',
    ['1 <= rows, cols <= 50', '0 <= k <= 1000'],
    [t([[[1,2,3],[4,5,6],[7,8,9]], 1], [[9,1,2],[3,4,5],[6,7,8]], 1), t([[[3,8,1,9],[19,7,2,5],[4,6,11,10],[12,0,21,13]], 4], [[12,0,21,13],[3,8,1,9],[19,7,2,5],[4,6,11,10]], 1), t([[[1]], 10], [[1]])],
    'function shiftGrid(g,k){var m=g.length,n=g[0].length;var flat=[];for(var r of g)for(var x of r)flat.push(x);k%=flat.length;var rot=k===0?flat.slice():flat.slice(-k).concat(flat.slice(0,-k));var out=[];for(var i=0;i<m;i++)out.push(rot.slice(i*n,(i+1)*n));return out;}'),

pdef('image-smoother', 'Image Smoother', 'easy', 'imageSmoother',
    sig(['m' => 'int[][]'], 'int[][]'),
    'Each pixel becomes the floor of the average of itself and its (up to 8) neighbours. Return the smoothed image.',
    ['1 <= rows, cols <= 200'],
    [t([[[1,1,1],[1,0,1],[1,1,1]]], [[0,0,0],[0,0,0],[0,0,0]], 1), t([[[100,200,100],[200,50,200],[100,200,100]]], [[137,141,137],[141,138,141],[137,141,137]], 1), t([[[5]]], [[5]]), t([[[1,2],[3,4]]], [[2,2],[2,2]])],
    'function imageSmoother(m){var rows=m.length,cols=m[0].length;var out=[];for(var i=0;i<rows;i++){out.push([]);for(var j=0;j<cols;j++){var s=0,c=0;for(var di=-1;di<=1;di++)for(var dj=-1;dj<=1;dj++){var ni=i+di,nj=j+dj;if(ni>=0&&ni<rows&&nj>=0&&nj<cols){s+=m[ni][nj];c++;}}out[i].push(Math.floor(s/c));}}return out;}'),

pdef('range-addition', 'Range Addition', 'medium', 'getModifiedArray',
    sig(['length' => 'int', 'updates' => 'int[][]'], 'int[]'),
    'Start with a zero array of the given length. Each update [start, end, inc] adds inc to every element in [start, end]. Return the final array.',
    ['1 <= length <= 100000'],
    [t([5, [[1,3,2],[2,4,3],[0,2,-2]]], [-2,0,3,5,3], 1), t([3, [[2,2,5]]], [0,0,5], 1), t([1, [[0,0,7]]], [7])],
    'function getModifiedArray(length,updates){var diff=new Array(length+1).fill(0);for(var u of updates){diff[u[0]]+=u[2];diff[u[1]+1]-=u[2];}var out=[],cur=0;for(var i=0;i<length;i++){cur+=diff[i];out.push(cur);}return out;}'),

pdef('tic-tac-toe-winner', 'Find Winner on a Tic Tac Toe Game', 'easy', 'tictactoe',
    sig(['moves' => 'int[][]'], 'str'),
    'A and B alternate placing marks on a 3x3 board (A first) following the given moves. Return "A", "B", "Draw" or "Pending".',
    ['1 <= moves.length <= 9, no repeated square'],
    [t([[[0,0],[2,0],[1,1],[2,1],[2,2]]], 'A', 1), t([[[0,0],[1,1],[0,1],[0,2],[1,0],[2,0]]], 'B', 1), t([[[0,0],[0,1],[0,2],[1,2],[1,0],[2,0],[1,1],[2,2],[2,1]]], 'Draw'), t([[[0,0],[1,1]]], 'Pending')],
    'function tictactoe(moves){var g=[[0,0,0],[0,0,0],[0,0,0]];for(var i=0;i<moves.length;i++)g[moves[i][0]][moves[i][1]]=i%2===0?1:2;function win(p){for(var r=0;r<3;r++)if(g[r][0]===p&&g[r][1]===p&&g[r][2]===p)return true;for(var c=0;c<3;c++)if(g[0][c]===p&&g[1][c]===p&&g[2][c]===p)return true;return (g[0][0]===p&&g[1][1]===p&&g[2][2]===p)||(g[0][2]===p&&g[1][1]===p&&g[2][0]===p);}if(win(1))return "A";if(win(2))return "B";return moves.length===9?"Draw":"Pending";}'),

pdef('valid-boomerang', 'Valid Boomerang', 'easy', 'isBoomerang',
    sig(['points' => 'int[][]'], 'bool'),
    'A boomerang is three points that are not all on one straight line. Return true if the three points form one.',
    ['points.length === 3'],
    [t([[[1,1],[2,3],[3,2]]], true, 1), t([[[1,1],[2,2],[3,3]]], false, 1), t([[[0,1],[1,0],[2,1]]], true), t([[[0,0],[1,1],[2,2]]], false)],
    'function isBoomerang(p){var a=p[0],b=p[1],c=p[2];return (b[0]-a[0])*(c[1]-a[1])!==(b[1]-a[1])*(c[0]-a[0]);}'),

pdef('matrix-diagonal-sort', 'Sort the Matrix Diagonally', 'medium', 'diagonalSort',
    sig(['m' => 'int[][]'], 'int[][]'),
    'Sort each top-left to bottom-right diagonal ascending. Return the matrix.',
    ['1 <= rows, cols <= 100'],
    [t([[[3,3,1,1],[2,2,1,2],[1,1,1,2]]], [[1,1,1,1],[1,2,2,2],[1,2,3,3]], 1), t([[[5,2],[3,1]]], [[1,2],[3,5]], 1), t([[[1]]], [[1]])],
    'function diagonalSort(m){var rows=m.length,cols=m[0].length;var groups={};for(var i=0;i<rows;i++)for(var j=0;j<cols;j++){var d=i-j;if(!groups[d])groups[d]=[];groups[d].push(m[i][j]);}for(var d in groups)groups[d].sort(function(a,b){return b-a;});for(var i=0;i<rows;i++)for(var j=0;j<cols;j++)m[i][j]=groups[i-j].pop();return m;}'),

pdef('largest-local-values', 'Largest Local Values in a Matrix', 'easy', 'largestLocal',
    sig(['m' => 'int[][]'], 'int[][]'),
    'Build an (n-2) x (n-2) matrix where each cell is the maximum of the 3x3 neighbourhood centred there.',
    ['3 <= n <= 100'],
    [t([[[9,9,8,1],[5,6,2,6],[8,2,6,4],[6,2,2,2]]], [[9,9],[8,6]], 1), t([[[1,1,1,1,1],[1,1,1,1,1],[1,1,2,1,1],[1,1,1,1,1],[1,1,1,1,1]]], [[2,2,2],[2,2,2],[2,2,2]], 1), t([[[2,4,7],[1,9,2],[3,5,6]]], [[9]]), t([[[1,2,3],[4,5,6],[7,8,9]]], [[9]])],
    'function largestLocal(m){var n=m.length;var out=[];for(var i=0;i<n-2;i++){out.push([]);for(var j=0;j<n-2;j++){var mx=0;for(var di=0;di<3;di++)for(var dj=0;dj<3;dj++)mx=Math.max(mx,m[i+di][j+dj]);out[i].push(mx);}}return out;}'),

];
