<?php
// Category: realworld — parsing, aggregating, formatting: the stuff of actual jobs
return [
pdef('shopping-cart-total', 'Shopping Cart Total', 'easy', 'cartTotal',
    sig(['items' => 'str[][]', 'qtys' => 'int[]'], 'num'),
    'Each item is entered as ["name", "unit price as string"] and qtys[i] is its quantity — parallel arrays at the same index. Compute the grand total, rounded to 2 decimal places.',
    ['0 ≤ items ≤ 10⁴', 'prices have at most 2 decimals'],
    [t([[['apple', '0.50'], ['bread', '2.25']], [4, 1]], 4.25, 1), t([[], []], 0, 1), t([[['tea', '3.00']], [2]], 6), t([[['x', '1.05']], [3]], 3.15)],
    'function cartTotal(items,qtys){var s=0,i;for(i=0;i<items.length;i++){s+=parseFloat(items[i][1])*qtys[i];}return Math.round((s+Number.EPSILON)*100)/100;}'),

pdef('sales-summary', 'Sales Summary by Category', 'easy', 'summarizeSales',
    sig(['names' => 'str[]', 'amounts' => 'num[]'], 'map'),
    'A register logs sales in parallel arrays (names[i] is the category, amounts[i] the sale value — same index). Return a {category: total} object of today\'s takings.',
    ['0 ≤ records ≤ 10⁴', 'names.length === amounts.length'],
    [t([['milk', 'bread', 'milk'], [10, 5, 10]], ['bread' => 5, 'milk' => 20], 1), t([[], []], new stdClass(), 1),
     t([['a'], [1.5]], ['a' => 1.5])],
    'function summarizeSales(names,amounts){var m={},i;for(i=0;i<names.length;i++){m[names[i]]=Math.round(((m[names[i]]||0)+amounts[i])*100)/100;}return m;}'),

pdef('log-level-filter', 'Log Level Filter', 'easy', 'filterLogs',
    sig(['lines' => 'str[]', 'level' => 'str'], 'str[]'),
    'Every log line starts with its level and a colon, like "INFO: server started". Keep only the lines whose level matches exactly (case-sensitive), preserving order.',
    ['0 ≤ lines ≤ 10⁵'],
    [t([['INFO: boot', 'WARN: disk', 'INFO: net'], 'INFO'], ['INFO: boot', 'INFO: net'], 1),
     t([[], 'WARN'], [], 1), t([['ERR: x'], 'ERR'], ['ERR: x']), t([['info: lower'], 'INFO'], [])],
    'function filterLogs(lines,level){var prefix=level+":";return lines.filter(function(l){return l.indexOf(prefix)===0;});}'),

pdef('dedupe-notifications', 'Dedupe Notifications', 'easy', 'dedupeKeepOrder',
    sig(['events' => 'str[]'], 'str[]'),
    'A noisy pipeline emits the same notification id over and over. Keep each id only the FIRST time it appears, preserving order.',
    ['0 ≤ events ≤ 10⁵'],
    [t([['a', 'b', 'a', 'c', 'b']], ['a', 'b', 'c'], 1), t([[]], [], 1), t([['x', 'x']], ['x']), t([['a', 'a', 'a']], ['a'])],
    'function dedupeKeepOrder(events){var seen=new Set(),out=[],i;for(i=0;i<events.length;i++){if(!seen.has(events[i])){seen.add(events[i]);out.push(events[i]);}}return out;}'),

pdef('username-gen', 'Username Generator', 'easy', 'makeUsernames',
    sig(['names' => 'str[]'], 'str[]'),
    'Generate usernames from display names: first initial + last word, all lowercase. "Ada Lovelace" becomes "alovelace". Single names lowercase as-is.',
    ['0 ≤ names ≤ 10⁴', 'names are letters and single spaces'],
    [t([['Ada Lovelace']], ['alovelace'], 1), t([['Grace Hopper', 'Alan Turing']], ['ghopper', 'aturing'], 1),
     t([['Cher']], ['cher']), t([['Jean Van Damme']], ['jvandamme'])],
    'function makeUsernames(names){return names.map(function(n){var w=n.split(" ");return w.length===1?w[0].toLowerCase():(w[0][0]+w.slice(1).join("")).toLowerCase();});}'),

pdef('meeting-overlap', 'Meeting Overlap Check', 'easy', 'meetingsOverlap',
    sig(['times' => 'str[][]'], 'bool'),
    'A calendar stores busy slots as [start, end] strings like ["09:30", "10:30"] (24h, end exclusive). Return true if any two slots overlap.',
    ['0 ≤ slots ≤ 10⁴', 'start < end within the same day'],
    [t([[['09:00', '10:00'], ['10:00', '11:00']]], false, 1), t([[['09:00', '10:00'], ['09:30', '11:00']]], true, 1),
     t([[]], false), t([[['13:00', '14:00'], ['12:00', '13:30'], ['14:00', '15:00']]], true)],
    'function meetingsOverlap(times){var toMin=function(s){var p=s.split(":");return p[0]*60+(+p[1]);};var n=times.length,iv=times.map(function(t){return [toMin(t[0]),toMin(t[1])];}).sort(function(a,b){return a[0]-b[0];});for(var i=1;i<n;i++){if(iv[i][0]<iv[i-1][1])return true;}return false;}'),

pdef('parking-fee', 'Parking Fee Calculator', 'easy', 'calcParking',
    sig(['minutes' => 'int', 'ratePerHour' => 'int', 'dailyCap' => 'int'], 'int'),
    'Parking charges ratePerHour for every STARTED hour (partial hours count full), capped at dailyCap. Return the fee.',
    ['0 ≤ minutes ≤ 10⁶', '1 ≤ rate ≤ cap'],
    [t([30, 2, 10], 2, 1), t([300, 2, 10], 10, 1), t([0, 5, 50], 0), t([61, 1, 5], 2)],
    'function calcParking(minutes,ratePerHour,cap){if(minutes<=0)return 0;var hours=Math.ceil(minutes/60);return Math.min(hours*ratePerHour,cap);}'),

pdef('temp-batch', 'Batch Celsius → Fahrenheit', 'easy', 'toFahrenheit',
    sig(['celsius' => 'num[]'], 'num[]'),
    'Convert a batch of Celsius readings to Fahrenheit (°F = °C × 9/5 + 32), each rounded to 1 decimal place.',
    ['0 ≤ readings ≤ 10⁵'],
    [t([[0, 100]], [32, 212], 1), t([[-40]], [-40], 1), t([[36.6, 37]], [97.9, 98.6]), t([[]], [])],
    'function toFahrenheit(cs){return cs.map(function(c){return Math.round((c*9/5+32)*10)/10;});}'),

pdef('csv-sum-column', 'Sum a CSV Column', 'easy', 'sumCsvColumn',
    sig(['lines' => 'str[]', 'colIndex' => 'int'], 'int'),
    'You receive exported spreadsheet rows as CSV strings (commas, no quotes or spaces). The first line is a header. Sum the integer values in the column at colIndex, skipping the header.',
    ['1 ≤ lines ≤ 10⁴', 'the column in data rows always holds integers'],
    [t([['name,score', 'ana,10', 'bo,20'], 1], 30, 1), t([['a,b', '1,2', '3,4'], 0], 4, 1), t([['h1,h2', '5,6'], 1], 6), t([['only'] , 0], 0)],
    'function sumCsvColumn(lines,col){var s=0,i;for(i=1;i<lines.length;i++){s+=parseInt(lines[i].split(",")[col],10)||0;}return s;}'),

pdef('playlist-length', 'Playlist Total Length', 'easy', 'playlistTotal',
    sig(['tracks' => 'str[]'], 'int'),
    'Track durations come as "mm:ss" strings. Return the playlist\'s total length in seconds.',
    ['0 ≤ tracks ≤ 10⁵', '0 ≤ mm ≤ 999, 0 ≤ ss ≤ 59'],
    [t([['3:30', '2:30']], 360, 1), t([['10:00']], 600, 1), t([[]], 0), t([['0:45', '0:15']], 60)],
    'function playlistTotal(tracks){var s=0,i;for(i=0;i<tracks.length;i++){var p=tracks[i].split(":");s+=(+p[0])*60+(+p[1]);}return s;}'),

pdef('restock-alerts', 'Restock Alerts', 'easy', 'restockAlerts',
    sig(['names' => 'str[]', 'qtys' => 'int[]', 'threshold' => 'int'], 'str[]'),
    'names[i] has qtys[i] units in stock (parallel arrays). Return the names of items STRICTLY below the reorder threshold, sorted alphabetically.',
    ['0 ≤ items ≤ 10⁴', 'names.length === qtys.length'],
    [t([['pens', 'pads', 'cups'], [4, 2, 9], 5], ['pads', 'pens'], 1), t([[], [], 3], [], 1),
     t([['x'], [3], 3], []), t([['a', 'b'], [0, 1], 2], ['a', 'b'])],
    'function restockAlerts(names,qtys,t){var out=[],i;for(i=0;i<names.length;i++){if(qtys[i]<t)out.push(names[i]);}return out.sort();}'),

pdef('streak-days', 'Longest Practice Streak', 'easy', 'longestStreak',
    sig(['days' => 'str'], 'int'),
    'A habit log is a string of 1s (practiced) and 0s (skipped), one char per day. Return the length of the longest run of 1s.',
    ['0 ≤ days.length ≤ 10⁵', 'only characters 0 and 1'],
    [t(['1101110'], 3, 1), t(['0'], 0, 1), t(['1111'], 4), t([''], 0), t(['10101'], 1)],
    'function longestStreak(days){var best=0,cur=0,i;for(i=0;i<days.length;i++){if(days[i]==="1"){cur++;best=Math.max(best,cur);}else{cur=0;}}return best;}'),

pdef('invoice-total-tax', 'Invoice Total With Tax', 'easy', 'totalWithTax',
    sig(['names' => 'str[]', 'prices' => 'num[]', 'taxPct' => 'int'], 'num'),
    'names[i] is a line item priced at prices[i] (parallel arrays). Return the subtotal plus taxPct percent tax, rounded to 2 decimals.',
    ['0 ≤ items ≤ 10⁴', '0 ≤ taxPct ≤ 60'],
    [t([['book', 'pen'], [10, 2], 10], 13.2, 1), t([[], [], 20], 0, 1), t([['a'], [99.99], 0], 99.99), t([['x', 'y'], [2.5, 2.5], 20], 6)],
    'function totalWithTax(names,prices,tax){var s=0,i;for(i=0;i<prices.length;i++){s+=prices[i];}return Math.round((s*(1+tax/100)+Number.EPSILON)*100)/100;}'),


pdef('coupon-discount', 'Apply Coupon to Cart', 'easy', 'applyCoupon',
    sig(['prices' => 'int[]', 'pct' => 'int', 'cap' => 'int'], 'num'),
    'A coupon takes pct percent off the cart total, but the discount is capped at cap. Return the final payable amount.',
    ['0 <= pct <= 100'],
    [t([[120,80], 10, 30], 180, 1), t([[50,50], 20, 15], 85, 1), t([[200], 25, 100], 150), t([[99], 10, 9], 90)],
    'function applyCoupon(prices,pct,cap){var total=0;for(var p of prices)total+=p;var off=Math.min(total*pct/100,cap);return Math.max(0,total-off);}'),

pdef('sku-subtotals', 'Order Subtotals by SKU', 'easy', 'skuSubtotals',
    sig(['items' => 'str[]'], 'map'),
    'Each item is "SKU:price:qty". Return a map of SKU -> total price (price x qty), summing repeated SKUs.',
    ['1 <= items.length <= 1000'],
    [t([['LATTE:4.50:2','CAPPU:5:1']], ['LATTE' => 9, 'CAPPU' => 5], 1), t([['A:2:3','A:1:2','B:10:1']], ['A' => 8, 'B' => 10], 1)],
    'function skuSubtotals(items){var out={};for(var line of items){var parts=line.split(":");var sku=parts[0],price=Number(parts[1]),qty=Number(parts[2]);out[sku]=(out[sku]||0)+price*qty;}return out;}'),

pdef('email-domain-counter', 'Email Domain Counter', 'easy', 'domainCounts',
    sig(['emails' => 'str[]'], 'map'),
    'Count how many sign-ups came from each email domain (the part after @).',
    ['1 <= emails.length <= 10000'],
    [t([['a@gmail.com','b@yahoo.com','c@gmail.com']], ['gmail.com' => 2, 'yahoo.com' => 1], 1), t([['x@in.io']], ['in.io' => 1], 1)],
    'function domainCounts(emails){var out={};for(var e of emails){var d=e.split("@")[1];out[d]=(out[d]||0)+1;}return out;}'),

pdef('phone-normalizer', 'Phone Number Normalizer', 'easy', 'normalizePhone',
    sig(['s' => 'str'], 'str'),
    'Strip all non-digit characters; if 10 digits remain, prepend country code 1. Return the digit string.',
    ['input has 10 or 11 digits'],
    [t(['(415) 555-2671'], '14155552671', 1), t(['+1 (415) 555-2671'], '14155552671', 1), t(['4155552671'], '14155552671'), t(['14155552671'], '14155552671')],
    'function normalizePhone(s){var d=s.replace(/\\D/g,"");if(d.length===10)d="1"+d;return d;}'),

pdef('password-strength-score', 'Password Strength Score', 'easy', 'passwordScore',
    sig(['pw' => 'str'], 'int'),
    'Score 0-5: one point each for length >= 8, an uppercase letter, a lowercase letter, a digit, and a non-alphanumeric symbol.',
    ['1 <= pw.length <= 100'],
    [t(['Hello123!'], 5, 1), t(['hello'], 1, 1), t(['HELLO'], 1), t(['Hello1'], 3)],
    'function passwordScore(pw){var score=0;if(pw.length>=8)score++;if(/[A-Z]/.test(pw))score++;if(/[a-z]/.test(pw))score++;if(/\\d/.test(pw))score++;if(/[^A-Za-z0-9]/.test(pw))score++;return score;}'),

pdef('slugify-title', 'Slugify a Title', 'easy', 'slugify',
    sig(['t' => 'str'], 'str'),
    'Convert a title into a URL slug: lowercase, letters and digits kept, any run of other characters becomes one hyphen, and no leading or trailing hyphens.',
    ['1 <= t.length <= 200'],
    [t(['Hello World!'], 'hello-world', 1), t(['  Multiple   Spaces  '], 'multiple-spaces', 1), t(['Rust, PHP & JS'], 'rust-php-js'), t(['A--B'], 'a-b')],
    'function slugify(t){return t.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");}'),

pdef('truncate-words', 'Truncate on Word Boundary', 'easy', 'truncateWords',
    sig(['s' => 'str', 'maxChars' => 'int'], 'str'),
    'If s is longer than maxChars, cut it at the last space inside the limit and append "...". Otherwise return s unchanged.',
    ['1 <= maxChars <= s.length <= 500'],
    [t(['The quick brown fox', 10], 'The quick...', 1), t(['hello', 20], 'hello', 1), t(['hello world', 6], 'hello...'), t(['hi', 2], 'hi')],
    'function truncateWords(s,maxChars){if(s.length<=maxChars)return s;var cut=s.substring(0,maxChars);var sp=cut.lastIndexOf(" ");if(sp>0)cut=cut.substring(0,sp);return cut+"...";}'),

pdef('round-robin-assign', 'Round Robin Job Assignment', 'easy', 'roundRobin',
    sig(['jobs' => 'int', 'servers' => 'int'], 'int[]'),
    'Assign jobs 1..jobs to servers 0..servers-1 round robin. Return the server index of each job in order.',
    ['1 <= jobs <= 10000', '1 <= servers <= 1000'],
    [t([5, 2], [0,1,0,1,0], 1), t([3, 3], [0,1,2], 1), t([4, 1], [0,0,0,0]), t([2, 5], [0,1])],
    'function roundRobin(jobs,servers){var out=[];for(var j=1;j<=jobs;j++)out.push((j-1)%servers);return out;}'),

pdef('rate-allow', 'Sliding Window Rate Limiter', 'medium', 'rateAllow',
    sig(['timestamps' => 'int[]', 'window' => 'int', 'limit' => 'int'], 'int'),
    'Attempts arrive at the given timestamps. An attempt is allowed only if, counting itself, no more than limit attempts happened within the trailing window seconds. Return the number allowed.',
    ['timestamps are ascending', 'every attempt counts, allowed or not'],
    [t([[1,2,3,4], 3, 2], 2, 1), t([[1,2,3], 2, 5], 3, 1), t([[5,5,5], 1, 1], 1), t([[10,30,40], 15, 2], 3)],
    'function rateAllow(timestamps,window,limit){var allowed=0;for(var i=0;i<timestamps.length;i++){var cnt=0;for(var j=0;j<=i;j++)if(timestamps[j]>timestamps[i]-window)cnt++;if(cnt<=limit)allowed++;}return allowed;}'),

pdef('cache-key-build', 'Build a Cache Key', 'easy', 'cacheKey',
    sig(['url' => 'str', 'params' => 'map'], 'str'),
    'Build a deterministic HTTP cache key: url plus query string with params sorted alphabetically, k=v joined by &.',
    ['values are strings or numbers'],
    [t(['/api/users', ['b' => 2, 'a' => 1]], '/api/users?a=1&b=2', 1), t(['/search', ['q' => 'rust', 'page' => '2']], '/search?page=2&q=rust', 1), t(['/home', []], '/home'), t(['/x', ['z' => 'z', 'm' => 'm']], '/x?m=m&z=z')],
    'function cacheKey(url,params){var keys=Object.keys(params).sort();if(!keys.length)return url;var qs=[];for(var k of keys)qs.push(k+"="+params[k]);return url+"?"+qs.join("&");}'),

pdef('money-format', 'Format Money for Display', 'easy', 'moneyFormat',
    sig(['cents' => 'int', 'currency' => 'str'], 'str'),
    'Format a cents amount with a currency symbol ($, EUR sign, INR sign), thousands separators and two decimals.',
    ['currency is USD, EUR or INR', '0 <= cents'],
    [t([123456, 'USD'], '$1,234.56', 1), t([999, 'INR'], "₹9.99", 1), t([100000000, 'EUR'], "€1,000,000.00"), t([7, 'USD'], '$0.07')],
    'function moneyFormat(cents,currency){var sym={"USD":"$","EUR":"€","INR":"₹"}[currency];var s=(cents/100).toFixed(2);var parts=s.split(".");var intp=parts[0];var out="";while(intp.length>3){out=","+intp.slice(-3)+out;intp=intp.slice(0,-3);}return sym+intp+out+"."+parts[1];}'),

pdef('csv-row-build', 'Build a CSV Row', 'easy', 'csvRow',
    sig(['fields' => 'str[]'], 'str'),
    'Serialize fields as one CSV row: quote fields containing a comma, quote or newline, and double any inner quotes.',
    ['0 <= fields.length <= 100'],
    [t([['a','b','c']], 'a,b,c', 1), t([['he said "hi"','x']], '"he said ""hi""",x', 1), t([['a,b','c']], '"a,b",c'), t([['','x']], ',x')],
    'function csvRow(fields){var out=[];for(var f of fields){if(/[",\\n]/.test(f))out.push(String.fromCharCode(34)+f.replace(/"/g,String.fromCharCode(34)+String.fromCharCode(34))+String.fromCharCode(34));else out.push(f);}return out.join(",");}'),

pdef('log-rotate-names', 'Log Rotation Filenames', 'easy', 'logRotateNames',
    sig(['base' => 'str', 'count' => 'int'], 'str[]'),
    'List the log files kept for base: base.log, then base.1.log, ... up to count files.',
    ['1 <= count <= 100'],
    [t(['app', 3], ['app.log','app.1.log','app.2.log'], 1), t(['db', 1], ['db.log'], 1), t(['x', 2], ['x.log','x.1.log'])],
    'function logRotateNames(base,count){var out=[base+".log"];for(var i=1;i<count;i++)out.push(base+"."+i+".log");return out;}'),

pdef('semver-compare', 'Compare Semantic Versions', 'easy', 'semverCompare',
    sig(['a' => 'str', 'b' => 'str'], 'int'),
    'Compare two semver strings (missing parts are 0). Return -1, 0 or 1.',
    ['parts are non-negative integers'],
    [t(['1.2.3', '1.2.10'], -1, 1), t(['2.0', '2.0.0'], 0, 1), t(['1.0.1', '1.0.0'], 1), t(['0.9', '1.0'], -1)],
    'function semverCompare(a,b){var x=a.split(".").map(Number),y=b.split(".").map(Number);for(var i=0;i<3;i++){var p=x[i]||0,q=y[i]||0;if(p<q)return -1;if(p>q)return 1;}return 0;}'),

pdef('cart-merge-dups', 'Merge Duplicate Cart Lines', 'easy', 'mergeCart',
    sig(['items' => 'str[]', 'qtys' => 'int[]'], 'map'),
    'items[i] was added qtys[i] times. Merge duplicates into one map of item -> total quantity.',
    ['items.length === qtys.length'],
    [t([['a','b','a'], [1,2,3]], ['a' => 4, 'b' => 2], 1), t([['sku'], [5]], ['sku' => 5], 1)],
    'function mergeCart(items,qtys){var out={};for(var i=0;i<items.length;i++)out[items[i]]=(out[items[i]]||0)+qtys[i];return out;}'),

pdef('pager-window', 'Pagination Window', 'medium', 'pageWindow',
    sig(['current' => 'int', 'total' => 'int', 'window' => 'int'], 'int[]'),
    'Show up to window page numbers centred on the current page, clamped to 1..total. Return them ascending.',
    ['1 <= current <= total', '1 <= window'],
    [t([1, 10, 5], [1,2,3,4,5], 1), t([6, 10, 3], [5,6,7], 1), t([9, 10, 3], [8,9,10]), t([2, 3, 5], [1,2,3])],
    'function pageWindow(current,total,window){var half=Math.floor(window/2);var start=Math.max(1,current-half);var end=Math.min(total,start+window-1);start=Math.max(1,end-window+1);var out=[];for(var p=start;p<=end;p++)out.push(p);return out;}'),

pdef('temp-convert-batch', 'Convert Celsius Batch to Fahrenheit', 'easy', 'cToF',
    sig(['ctemps' => 'num[]'], 'num[]'),
    'Convert each Celsius temperature to Fahrenheit.',
    ['-100 <= ctemps[i] <= 100'],
    [t([[0,100,37]], [32,212,98.6], 1), t([[-40]], [-40], 1)],
    'function cToF(ctemps){return ctemps.map(function(c){return c*9/5+32;});}'),

pdef('lru-sequence', 'LRU Cache Final State', 'medium', 'lruSequence',
    sig(['capacity' => 'int', 'ops' => 'str[]'], 'str[]'),
    'Simulate an LRU cache that receives the given keys. A hit refreshes; a miss inserts and evicts the least recently used. Return the cache, most-recent first.',
    ['1 <= capacity <= 100', '0 <= ops.length <= 1000'],
    [t([3, ['a','b','c','a','d']], ['d','a','c'], 1), t([2, ['x','y','x','z']], ['z','x'], 1), t([1, ['a','b']], ['b']), t([4, ['a','b','c']], ['c','b','a'])],
    'function lruSequence(cap,ops){var cache=[];for(var k of ops){var i=cache.indexOf(k);if(i>=0)cache.splice(i,1);else if(cache.length>=cap)cache.pop();cache.unshift(k);}return cache;}'),

pdef('jwt-payload-decode', 'Decode a JWT Payload', 'medium', 'jwtPayload',
    sig(['token' => 'str'], 'map'),
    'A JWT is header.payload.signature with base64url parts. Decode and return the payload JSON as a map. Do not verify the signature.',
    ['payload JSON is an object'],
    [t(['aaa.eyJzdWIiOiI0MiJ9.ccc'], ['sub' => '42'], 1), t(['aaa.eyJuYW1lIjoieCIsInJvbGVzIjpbImEiLCJiIl19.ccc'], ['name' => 'x', 'roles' => ['a','b']], 1)],
    'function jwtPayload(token){var parts=token.split(".");var b=parts[1].replace(/-/g,"+").replace(/_/g,"/");while(b.length%4)b+="=";return JSON.parse(atob(b));}'),

pdef('http-status-label', 'HTTP Status Code Label', 'easy', 'statusLabel',
    sig(['code' => 'int'], 'str'),
    'Return the standard reason phrase for common HTTP status codes.',
    ['code is one of 200, 201, 204, 301, 302, 400, 401, 403, 404, 500, 503'],
    [t([200], 'OK', 1), t([404], 'Not Found', 1), t([500], 'Internal Server Error'), t([302], 'Found'), t([201], 'Created')],
    'function statusLabel(code){var map={200:"OK",201:"Created",204:"No Content",301:"Moved Permanently",302:"Found",400:"Bad Request",401:"Unauthorized",403:"Forbidden",404:"Not Found",500:"Internal Server Error",503:"Service Unavailable"};return map[code];}'),

pdef('diff-line-stats', 'Diff Line Statistics', 'easy', 'diffStats',
    sig(['before' => 'str[]', 'after' => 'str[]'], 'map'),
    'Compare two lists of unique lines (like a simple diff). Return a map with added, removed and kept counts.',
    ['each list has unique lines'],
    [t([['a','b','c'], ['b','c','d']], ['added' => 1, 'removed' => 1, 'kept' => 2], 1), t([['x'], ['y']], ['added' => 1, 'removed' => 1, 'kept' => 0], 1), t([[], ['a']], ['added' => 1, 'removed' => 0, 'kept' => 0])],
    'function diffStats(before,after){var b=new Set(before),a=new Set(after);var added=0,removed=0,kept=0;for(var x of a){if(b.has(x))kept++;else added++;}removed=b.size-kept;return {added:added,removed:removed,kept:kept};}'),

pdef('flatten-json-paths', 'Flatten JSON to Dot Paths', 'medium', 'flattenPaths',
    sig(['obj' => 'map'], 'map'),
    'Flatten a nested JSON-style object into dot-path keys. Empty objects contribute nothing; leaf values stay as-is.',
    ['nested values are maps or scalars'],
    [t([['a' => ['b' => 1, 'c' => ['d' => 2]], 'e' => 3]], ['a.b' => 1, 'a.c.d' => 2, 'e' => 3], 1), t([['x' => 1]], ['x' => 1], 1), t([new stdClass()], new stdClass())],
    'function flattenPaths(obj){var out={};function walk(o,prefix){for(var k of Object.keys(o)){var v=o[k];var path=prefix?prefix+"."+k:k;if(v&&typeof v==="object"&&!Array.isArray(v)&&Object.keys(v).length)walk(v,path);else out[path]=v;}}walk(obj,"");return out;}'),

pdef('retry-backoff-schedule', 'Exponential Backoff Schedule', 'easy', 'retryDelays',
    sig(['base' => 'int', 'factor' => 'int', 'retries' => 'int'], 'int[]'),
    'Return the backoff delays before each retry: base, base x factor, base x factor^2, ...',
    ['1 <= retries <= 10'],
    [t([100, 2, 4], [100,200,400,800], 1), t([50, 3, 3], [50,150,450], 1), t([200, 2, 1], [200])],
    'function retryDelays(base,factor,retries){var out=[],d=base;for(var i=0;i<retries;i++){out.push(d);d*=factor;}return out;}'),

pdef('markdown-headings', 'Extract Markdown Headings', 'easy', 'extractHeadings',
    sig(['lines' => 'str[]'], 'str[][]'),
    'From Markdown lines, extract ATX headings (# to ###### followed by a space) as [text, level] pairs.',
    ['0 <= lines.length <= 1000'],
    [t([['# A','## B','plain','# C']], [['A',1],['B',2],['C',1]], 1), t([['no headings']], [], 1)],
    'function extractHeadings(lines){var out=[];for(var line of lines){var m=line.match(/^(#{1,6}) (.+)$/);if(m)out.push([m[2],m[1].length]);}return out;}'),

pdef('discount-tier', 'Loyalty Discount Tier', 'easy', 'discountTier',
    sig(['spend' => 'num'], 'int'),
    'Loyalty tiers: spend < 50 earns 0%, < 100 earns 5%, < 250 earns 10%, otherwise 15%. Return the percent.',
    ['0 <= spend'],
    [t([30], 0, 1), t([75], 5, 1), t([200], 10), t([300], 15)],
    'function discountTier(spend){if(spend>=250)return 15;if(spend>=100)return 10;if(spend>=50)return 5;return 0;}'),

pdef('pick-route-distance', 'Warehouse Pick Route Distance', 'easy', 'pickRoute',
    sig(['aisles' => 'int[]', 'start' => 'int'], 'int'),
    'The picker starts at position start and visits each aisle position in the given order. Return the total walking distance.',
    ['0 <= aisles.length <= 1000'],
    [t([[3,-1,4], 0], 12, 1), t([[0], 0], 0, 1), t([[2,5,3], 0], 7), t([[-2,-5], 0], 5)],
    'function pickRoute(aisles,start){var dist=0,cur=start;for(var a of aisles){dist+=Math.abs(a-cur);cur=a;}return dist;}'),

pdef('pluralize-label', 'Pluralize a Label', 'easy', 'pluralize',
    sig(['count' => 'int', 'noun' => 'str'], 'str'),
    'Return "count noun", pluralizing the noun when count is not 1 (y -> ies; s, x, ch endings -> es; otherwise -> s).',
    ['0 <= count <= 1000'],
    [t([1, 'ticket'], '1 ticket', 1), t([3, 'ticket'], '3 tickets', 1), t([0, 'city'], '0 cities'), t([2, 'box'], '2 boxes'), t([5, 'class'], '5 classes')],
    'function pluralize(count,noun){var w=noun;if(count!==1){if(/(s|x|ch)$/.test(noun))w=noun+"es";else if(/y$/.test(noun))w=noun.slice(0,-1)+"ies";else w=noun+"s";}return count+" "+w;}'),

pdef('anchor-slugs', 'Generate Unique Anchor Slugs', 'medium', 'anchorSlugs',
    sig(['headings' => 'str[]'], 'str[]'),
    'Generate GitHub-style anchor slugs: lowercase slug per heading, and a repeated slug gets -1, -2, ... suffixes.',
    ['0 <= headings.length <= 100'],
    [t([['Intro','Intro','Setup']], ['intro','intro-1','setup'], 1), t([['A B','a-b']], ['a-b','a-b-1'], 1), t([['X']], ['x']), t([['One','one']], ['one','one-1'])],
    'function anchorSlugs(headings){var seen={},out=[];for(var h of headings){var s=h.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");if(seen[s]===undefined)seen[s]=0;else seen[s]++;out.push(seen[s]?s+"-"+seen[s]:s);}return out;}'),

];
