<?php
// Category: strings — parsing, scanning, building
return [
pdef('reverse-string', 'Reverse String', 'easy', 'reverseString',
    sig(['s' => 'str'], 'str'),
    'Given a string s, return it reversed.',
    ['1 ≤ s.length ≤ 10⁵'],
    [t(['hello'], 'olleh', 1), t(['Codeface'], 'ecafedoC', 1), t([''], ''), t(['ab'], 'ba'), t(['racecar'], 'racecar')],
    'function reverseString(s){var o="";for(var i=s.length-1;i>=0;i--)o+=s[i];return o;}',
    'Do it without the built-in reverse() method.'),

pdef('count-vowels', 'Count Vowels', 'easy', 'countVowels',
    sig(['s' => 'str'], 'int'),
    'Count the vowels (a, e, i, o, u — lowercase input) in the string.',
    ['0 ≤ s.length ≤ 10⁵', 's is lowercase letters and spaces'],
    [t(['hello'], 2, 1), t(['xyz'], 0, 1), t(['aeiou'], 5), t(['a b c'], 1)],
    'function countVowels(s){var v={},c=0;"aeiou".split("").forEach(function(x){v[x]=1;});for(var i=0;i<s.length;i++){if(v[s[i]])c++;}return c;}'),

pdef('reverse-words', 'Reverse Words in a String', 'easy', 'reverseWords',
    sig(['s' => 'str'], 'str'),
    'Reverse the order of the words. A word is a run of non-space characters; extra whitespace anywhere should collapse to single spaces in the result.',
    ['1 ≤ s.length ≤ 10⁴'],
    [t(['the sky is blue'], 'blue is sky the', 1), t(['  hello world  '], 'world hello', 1), t(['a'], 'a'), t(['bob likes dogs'], 'dogs likes bob')],
    'function reverseWords(s){return s.trim().split(/\s+/).reverse().join(" ");}'),

pdef('first-unique-char', 'First Unique Character', 'easy', 'firstUniqChar',
    sig(['s' => 'str'], 'int'),
    'Return the index of the first non-repeating character in s, or -1 if there is none.',
    ['1 ≤ s.length ≤ 10⁵', 'lowercase letters'],
    [t(['leetcode'], 0, 1), t(['loveleetcode'], 2, 1), t(['aabb'], -1), t(['z'], 0)],
    'function firstUniqChar(s){var m={};for(var i=0;i<s.length;i++){m[s[i]]=(m[s[i]]||0)+1;}for(var j=0;j<s.length;j++){if(m[s[j]]===1)return j;}return -1;}'),

pdef('valid-anagram', 'Valid Anagram', 'easy', 'isAnagram',
    sig(['s' => 'str', 't2' => 'str'], 'bool'),
    'Return true if t2 is an anagram of s — same letters, same counts, any order.',
    ['1 ≤ lengths ≤ 5·10⁴', 'lowercase letters'],
    [t(['anagram', 'nagaram'], true, 1), t(['rat', 'car'], false, 1), t(['ab', 'a'], false), t(['listen', 'silent'], true)],
    'function isAnagram(a,b){if(a.length!==b.length)return false;var s=a.split("").sort().join(""),t=b.split("").sort().join("");return s===t;}'),

pdef('is-subsequence', 'Is Subsequence', 'easy', 'isSubsequence',
    sig(['s' => 'str', 't' => 'str'], 'bool'),
    'Return true if s is a subsequence of t — its characters appear in t in the same relative order (not necessarily contiguous).',
    ['0 ≤ s.length ≤ 100', '0 ≤ t.length ≤ 10⁴'],
    [t(['abc', 'ahbgdc'], true, 1), t(['axc', 'ahbgdc'], false, 1), t(['', 'abc'], true), t(['abc', ''], false)],
    'function isSubsequence(s,t){var i=0;for(var j=0;j<t.length&&i<s.length;j++){if(t[j]===s[i])i++;}return i===s.length;}'),

pdef('count-segments', 'Count Segments', 'easy', 'countSegments',
    sig(['s' => 'str'], 'int'),
    'Count the number of segments in the string, where a segment is a contiguous run of non-space characters.',
    ['0 ≤ s.length ≤ 300'],
    [t(['Hello, my name is John'], 5, 1), t([''], 0, 1), t(['  spaced  out '], 2), t(['one'], 1)],
    'function countSegments(s){var t=s.trim();return t===""?0:t.split(/\s+/).length;}'),

pdef('truncate-sentence', 'Truncate Sentence', 'easy', 'truncateSentence',
    sig(['s' => 'str', 'k' => 'int'], 'str'),
    'Return the sentence truncated to its first k words, joined by single spaces.',
    ['1 ≤ k ≤ number of words ≤ 100', 'words are space-separated, single spaces'],
    [t(['Hello how are you Contestant', 4], 'Hello how are you', 1), t(['What is the solution to this problem', 4], 'What is the solution', 1), t(['Hi', 1], 'Hi'), t(['a b c', 5], 'a b c')],
    'function truncateSentence(s,k){return s.split(" ").slice(0,k).join(" ");}'),

pdef('detect-capital', 'Detect Capital', 'easy', 'detectCapital',
    sig(['word' => 'str'], 'bool'),
    'Capital usage is correct when (1) all letters are capitals, (2) all letters are lowercase, or (3) only the first letter is a capital. Return true if the word uses capitals correctly.',
    ['1 ≤ word.length ≤ 100', 'English letters only'],
    [t(['USA'], true, 1), t(['FlaG'], false, 1), t(['leetcode'], true), t(['g'], true), t(['mL'], false)],
    'function detectCapital(w){return w===w.toUpperCase()||w===w.toLowerCase()||w===w[0].toUpperCase()+w.slice(1).toLowerCase();}'),

pdef('string-rle', 'Run-Length Encode', 'easy', 'runLengthEncode',
    sig(['s' => 'str'], 'str'),
    'Compress the string by replacing each run of a repeated character with the character followed by the run length. Case matters.',
    ['0 ≤ s.length ≤ 10⁴', 'letters only'],
    [t(['aabbc'], 'a2b2c1', 1), t(['xyz'], 'x1y1z1', 1), t([''], ''), t(['aaaB'], 'a3B1')],
    'function runLengthEncode(s){var out="",i=0;while(i<s.length){var j=i;while(j<s.length&&s[j]===s[i])j++;out+=s[i]+String(j-i);i=j;}return out;}'),

pdef('common-prefix', 'Longest Common Prefix', 'easy', 'longestCommonPrefix',
    sig(['strs' => 'str[]'], 'str'),
    'Return the longest common prefix string amongst an array of strings. If there is none, return an empty string.',
    ['1 ≤ strs.length ≤ 200', 'lowercase or empty strings'],
    [t([['flower', 'flow', 'flight']], 'fl', 1), t([['dog', 'racecar', 'car']], '', 1), t([['abc']], 'abc'), t([['', '']], '')],
    'function longestCommonPrefix(a){if(!a.length)return "";var p=a[0];for(var i=1;i<a.length;i++){while(a[i].indexOf(p)!==0){p=p.slice(0,-1);if(!p)return "";}}return p;}'),

pdef('decode-string', 'Decode String', 'medium', 'decodeString',
    sig(['s' => 'str'], 'str'),
    'Given an encoded string where k[substring] means the substring repeated k times (nesting allowed), return the decoded string.',
    ['1 ≤ s.length ≤ 30', 'output is guaranteed valid'],
    [t(['3[a]2[bc]'], 'aaabcbc', 1), t(['3[a2[c]]'], 'accaccacc', 1), t(['2[abc]3[cd]ef'], 'abcabccdcdcdef'), t(['abc'], 'abc')],
    'function decodeString(s){var st=[],cur="",num=0,i;for(i=0;i<s.length;i++){var ch=s[i];if(ch>="0"&&ch<="9"){num=num*10+(ch|0);}else if(ch==="["){st.push([cur,num]);cur="";num=0;}else if(ch==="]"){var p=st.pop();cur=p[0]+cur.repeat(p[1]);}else{cur+=ch;}}return cur;}'),

pdef('find-anagram-indices', 'Find All Anagrams', 'medium', 'findAnagrams',
    sig(['s' => 'str', 'p' => 'str'], 'int[]'),
    'Return the start indices of every substring of s that is an anagram of p, in ascending order.',
    ['1 ≤ s.length, p.length ≤ 3·10⁴', 'lowercase letters'],
    [t(['cbaebabacd', 'abc'], [0, 6], 1), t(['abab', 'ab'], [0, 1, 2], 1), t(['a', 'b'], []), t(['baa', 'aa'], [1])],
    'function findAnagrams(s,p){var out=[],need={},i,c;if(p.length>s.length)return out;for(i=0;i<p.length;i++){c=p[i];need[c]=(need[c]||0)+1;}var miss=Object.keys(need).length;for(i=0;i<s.length;i++){c=s[i];if(c in need){need[c]--;if(need[c]===0)miss--;}if(i>=p.length){c=s[i-p.length];if(c in need){if(need[c]===0)miss++;need[c]++;}}if(miss===0)out.push(i-p.length+1);}return out;}'),

pdef('defang-ip', 'Defanging an IP Address', 'easy', 'defangIPaddr',
    sig(['address' => 'str'], 'str'),
    'Replace every "." in the IP address with "[.]" and return the modified string.',
    ['the given address is a valid IPv4'],
    [t(['1.1.1.1'], '1[.]1[.]1[.]1', 1), t(['255.100.50.0'], '255[.]100[.]50[.]0', 1)],
    'function defangIPaddr(address){return address.split(".").join("[.]");}'),

pdef('goal-parser', 'Goal Parser Interpretation', 'easy', 'interpret',
    sig(['command' => 'str'], 'str'),
    'A command language: "G" -> "G", "()" -> "o", "(al)" -> "al". Interpret the whole string.',
    ['1 ≤ command.length ≤ 100', 'only G, (, ), a, l appear'],
    [t(['G()(al)'], 'Goal', 1), t(['G()()()()(al)'], 'Gooooal', 1), t(['(al)G(al)()()G'], 'alGalooG')],
    'function interpret(c){return c.split("").reduce(function(o,s,i){if(s==="G")return o+"G";if(s===")")return o+(c[i-1]==="("?"o":"al");return o;},"");}'),

pdef('final-value-x', 'Final Value After Operations', 'easy', 'finalValueAfterOperations',
    sig(['operations' => 'str[]'], 'int'),
    'X starts at 0. Each operation is "X++"/"++X" (+1) or "X--"/"--X" (-1). Return the final value.',
    ['1 ≤ operations.length ≤ 100'],
    [t([['--X', 'X++', 'X++']], 1, 1), t([['++X', '++X', 'X++']], 3, 1), t([['X++', '++X', '--X', 'X--']], 0)],
    'function finalValueAfterOperations(ops){var x=0;for(var i=0;i<ops.length;i++)x+=ops[i][1]==="+"?1:-1;return x;}'),

pdef('max-words-sentence', 'Maximum Number of Words in a Sentence', 'easy', 'mostWordsFound',
    sig(['sentences' => 'str[]'], 'int'),
    'A "sentence" is words separated by single spaces (no leading/trailing). Return the maximum word count.',
    ['1 ≤ sentences.length ≤ 100'],
    [t([['alice and bob love leetcode', 'i think so too', 'this is great thanks very much']], 6, 1),
     t([['please wait', 'continue to fight', 'continue to win']], 3, 1), t([['one']], 1)],
    'function mostWordsFound(s){return Math.max.apply(null,s.map(function(x){return x.split(" ").length;}));}'),

pdef('count-asterisks', 'Count Asterisks Between Pipes', 'easy', 'countAsterisks',
    sig(['s' => 'str'], 'int'),
    'Count "*" characters that lie OUTSIDE every pair of "|" delimiters (segments between pipes are "hidden").',
    ['1 ≤ s.length ≤ 1000', 's has an even number of |'],
    [t(['l|*e*et|c**o|*de|'], 2, 1), t(['iamprogrammer'], 0, 1), t(['yo|uar|e**|b|e***au|tifu|l'], 5)],
    'function countAsterisks(s){var c=0,inside=false;for(var i=0;i<s.length;i++){if(s[i]==="|")inside=!inside;else if(s[i]==="*"&&!inside)c++;}return c;}'),

pdef('shuffle-string', 'Shuffle String', 'easy', 'restoreString',
    sig(['s' => 'str', 'indices' => 'int[]'], 'str'),
    'indices[i] says where s[i] belongs. Rebuild the shuffled string.',
    ['s.length == indices.length', 'indices is a permutation'],
    [t(['codeleet', [4, 5, 6, 7, 0, 2, 1, 3]], 'leetcode', 1), t(['abc', [0, 1, 2]], 'abc', 1), t(['aiohn', [3, 1, 4, 2, 0]], 'nihao')],
    'function restoreString(s,idx){var o=new Array(s.length);for(var i=0;i<s.length;i++)o[idx[i]]=s[i];return o.join("");}'),

pdef('sort-sentence', 'Sorting the Sentence', 'easy', 'sortSentence',
    sig(['s' => 'str'], 'str'),
    'Each word ends with a digit 1-9 marking its position in the original sentence. Rebuild it without the digits.',
    ['2 ≤ number of words ≤ 9', 'positions are unique 1..n'],
    [t(['is2 sentence4 This1 a3'], 'This is a sentence', 1), t(['Myself2 Me1 I4 and3'], 'Me Myself and I', 1)],
    'function sortSentence(s){var w=s.split(" "),o=new Array(w.length);w.forEach(function(x){o[x[x.length-1]-1]=x.slice(0,-1);});return o.join(" ");}'),

pdef('prefix-sentence', 'Check If String Is a Prefix of a Sentence', 'easy', 'isPrefixOfSentence',
    sig(['sentence' => 'str', 'searchWord' => 'str'], 'int'),
    'Return the 1-based index of the first word in sentence that starts with searchWord, or -1.',
    ['1 ≤ sentence.length ≤ 100 (single spaces, lowercase)'],
    [t(['i love eating burger', 'burg'], 4, 1), t(['this problem is an easy problem', 'pro'], 2, 1), t(['i am tired', 'you'], -1)],
    'function isPrefixOfSentence(s,w){var a=s.split(" ");for(var i=0;i<a.length;i++)if(a[i].indexOf(w)===0)return i+1;return -1;}'),

pdef('equal-string-arrays', 'Check If Two String Arrays are Equivalent', 'easy', 'arrayStringsAreEqual',
    sig(['word1' => 'str[]', 'word2' => 'str[]'], 'bool'),
    'Concatenate each array\'s strings; return true if both concatenations are equal.',
    ['1 ≤ word1.length, word2.length ≤ 10³'],
    [t([['ab', 'c'], ['a', 'bc']], true, 1), t([['a', 'cb'], ['ab', 'c']], false, 1), t([['abc', 'd', 'defg'], ['abcddefg']], true)],
    'function arrayStringsAreEqual(a,b){return a.join("")===b.join("");}'),

pdef('halves-alike', 'Determine if String Halves Are Alike', 'easy', 'halvesAreAlike',
    sig(['s' => 'str'], 'bool'),
    'Split the even-length string in half; return true if both halves contain the same number of vowels (a,e,i,o,u, any case).',
    ['2 ≤ s.length ≤ 1000', 's.length is even'],
    [t(['book'], true, 1), t(['textbook'], false, 1), t(['AbCdEfGh'], true)],
    'function halvesAreAlike(s){var v="aeiouAEIOU",n=s.length/2,c=0;for(var i=0;i<n;i++){if(v.indexOf(s[i])>=0)c++;if(v.indexOf(s[i+n])>=0)c--;}return c===0;}'),

pdef('destination-city', 'Destination City', 'easy', 'destCity',
    sig(['from' => 'str[]', 'to' => 'str[]'], 'str'),
    'Travel legs go from[i] -> to[i]. Find the city with no outgoing leg (the destination).',
    ['1 ≤ from.length ≤ 100', 'the legs form one continuous route with no loops'],
    [t([['London', 'New York'], ['New York', 'Lima']], 'Lima', 1), t([['B', 'C'], ['C', 'D']], 'D', 1), t([['A'], ['Z']], 'Z')],
    'function destCity(from,to){var s=new Set(from);for(var i=0;i<to.length;i++)if(!s.has(to[i]))return to[i];return to[to.length-1];}'),

pdef('percentage-letter', 'Percentage of Letter in String', 'easy', 'percentageLetter',
    sig(['s' => 'str', 'letter' => 'str'], 'int'),
    'Return the percentage (floored) of occurrences of letter in s.',
    ['1 ≤ s.length ≤ 100', 'letter is a single lowercase character'],
    [t(['abc', 'a'], 33, 1), t(['foobar', 'o'], 33, 1), t(['jjjj', 'k'], 0), t(['sgawtb', 's'], 16)],
    'function percentageLetter(s,l){var c=0;for(var i=0;i<s.length;i++)if(s[i]===l)c++;return Math.floor(100*c/s.length);}'),

pdef('remove-trailing-zeros', 'Remove Trailing Zeros From a String', 'easy', 'removeTrailingZeros',
    sig(['num' => 'str'], 'str'),
    'Return the given positive integer string without trailing zeros.',
    ['1 ≤ num.length ≤ 1000', 'only digits, no leading zeros'],
    [t(['51230100'], '512301', 1), t(['123'], '123', 1), t(['1000'], '1')],
    'function removeTrailingZeros(n){return n.replace(/0+$/,"");}'),

pdef('capitalize-title', 'Capitalize the Title', 'easy', 'capitalizeTitle',
    sig(['title' => 'str'], 'str'),
    'Words of length ≤ 2 become all-lowercase; longer words get a capital first letter, rest lowercase.',
    ['1 ≤ title.length ≤ 100', 'words are single-space separated, no leading/trailing spaces'],
    [t(['capiTalIze tHe titLe'], 'Capitalize The Title', 1), t(['First leTTeR of EACH Word'], 'First Letter of Each Word', 1), t(['i lOve leetcode'], 'i Love Leetcode')],
    'function capitalizeTitle(t){return t.split(" ").map(function(w){w=w.toLowerCase();return w.length>2?w[0].toUpperCase()+w.slice(1):w;}).join(" ");}'),

pdef('longest-palindrome', 'Longest Palindrome', 'easy', 'longestPalindrome',
    sig(['s' => 'str'], 'int'),
    'Build the longest palindrome possible from the letters of s (case-sensitive counts). Return its maximum length.',
    ['1 ≤ s.length ≤ 2000', 'only a-z and A-Z'],
    [t(['abccccdd'], 7, 1), t(['a'], 1, 1), t(['bb'], 2), t(['Aa'], 1)],
    'function longestPalindrome(s){var c={},odd=0;for(var i=0;i<s.length;i++){c[s[i]]=(c[s[i]]||0)+1;if(c[s[i]]%2===1)odd++;else odd--;}return s.length-odd+(odd>0?1:0);}'),

pdef('reverse-prefix', 'Reverse Prefix of Word', 'easy', 'reversePrefix',
    sig(['word' => 'str', 'ch' => 'str'], 'str'),
    'Reverse the segment from index 0 up to and including the FIRST occurrence of ch; if ch is missing, return word unchanged.',
    ['1 ≤ word.length ≤ 250 (lowercase)'],
    [t(['abcdefd', 'd'], 'dcbaefd', 1), t(['xyxzxe', 'z'], 'zxyxxe', 1), t(['abcd', 'z'], 'abcd')],
    'function reversePrefix(w,ch){var i=w.indexOf(ch);if(i<0)return w;return w.slice(0,i+1).split("").reverse().join("")+w.slice(i+1);}'),

pdef('greatest-letter', 'Greatest English Letter in Cases', 'easy', 'greatestLetter',
    sig(['s' => 'str'], 'str'),
    'Return the greatest letter (by alphabet order) that appears in BOTH upper and lower case, uppercased — or "" if none.',
    ['1 ≤ s.length ≤ 1000', 'only letters'],
    [t(['lEeTcOdE'], 'E', 1), t(['arRAzFif'], 'R', 1), t(['AbCdEfGhIjK'], ''), t(['aAbBcC'], 'C')],
    'function greatestLetter(s){var lo={},up={};for(var i=0;i<s.length;i++){var c=s[i];if(c>="a"&&c<="z")lo[c]=1;else if(c>="A"&&c<="Z")up[c]=1;}var best="";for(var L in up)if(lo[L.toLowerCase()]&&L>best)best=L;return best;}'),

pdef('digit-count', 'Check if Number Has Equal Digit Count and Digit Value', 'easy', 'digitCount',
    sig(['num' => 'str'], 'bool'),
    'For every index i, num[i] (the digit) must equal how many times the value i occurs in num. Return whether that holds.',
    ['1 ≤ num.length ≤ 10', 'digits only'],
    [t(['1210'], true, 1), t(['030'], false, 1), t(['2020'], true)],
    'function digitCount(n){for(var i=0;i<n.length;i++){var c=0;for(var j=0;j<n.length;j++)if(Number(n[j])===i)c++;if(c!==Number(n[i]))return false;}return true;}'),

pdef('most-common-word', 'Most Common Word', 'easy', 'mostCommonWord',
    sig(['paragraph' => 'str', 'banned' => 'str[]'], 'str'),
    'Return the most frequent lowercase word that is not banned. Words split on any non-letter; answer is unique.',
    ['1 ≤ paragraph.length ≤ 1000', 'answer exists and is unique'],
    [t(['Bob hit a ball, the hit BALL flew far after it was hit.', ['hit']], 'ball', 1),
     t(['a, a, a, a, b,b,b,b, c, c', ['a']], 'b', 1), t(['Bob! Bob is here', ['is']], 'bob')],
    'function mostCommonWord(p,banned){var ban=new Set(banned),w=p.toLowerCase().split(/[^a-z]+/),c={};for(var i=0;i<w.length;i++){var x=w[i];if(x&&!ban.has(x))c[x]=(c[x]||0)+1;}var best="",bn=0;for(var k in c)if(c[k]>bn){bn=c[k];best=k;}return best;}'),

pdef('strong-password-ii', 'Strong Password Checker II', 'easy', 'strongPasswordCheckerII',
    sig(['password' => 'str'], 'bool'),
    'Strong = ≥8 chars, has lower+upper+digit+special from "!@#$%^&*()-+", and no two equal adjacent characters.',
    ['1 ≤ password.length ≤ 100'],
    [t(['IloveLe3tcode!'], true, 1), t(['Me+You--IsMyDream'], false, 1), t(['Aa1!bB2#'], true)],
    'function strongPasswordCheckerII(p){if(p.length<8)return false;var lo=false,up=false,dg=false,sp=false;for(var i=0;i<p.length;i++){var c=p[i];if(i>0&&c===p[i-1])return false;if(c>="a"&&c<="z")lo=true;else if(c>="A"&&c<="Z")up=true;else if(c>="0"&&c<="9")dg=true;else if("!@#$%^&*()-+".indexOf(c)>=0)sp=true;}return lo&&up&&dg&&sp;}'),

pdef('good-three-substrings', 'Substrings of Size Three with Distinct Characters', 'easy', 'countGoodSubstrings',
    sig(['s' => 'str'], 'int'),
    'Count length-3 substrings where all three characters are distinct.',
    ['1 ≤ s.length ≤ 100 (lowercase)'],
    [t(['xyzzaz'], 1, 1), t(['aababcabc'], 4, 1), t(['abc'], 1)],
    'function countGoodSubstrings(s){var c=0;for(var i=0;i+2<s.length;i++)if(s[i]!==s[i+1]&&s[i+1]!==s[i+2]&&s[i]!==s[i+2])c++;return c;}'),

pdef('vowel-substrings', 'Count Vowel Substrings of a String', 'easy', 'countVowelSubstrings',
    sig(['word' => 'str'], 'int'),
    'Count substrings that contain ONLY vowels and include each of a, e, i, o, u at least once.',
    ['1 ≤ word.length ≤ 100 (lowercase)'],
    [t(['aeiouu'], 2, 1), t(['unicornarihan'], 0, 1), t(['cuaieuouac'], 7)],
    'function countVowelSubstrings(w){var v="aeiou",c=0;for(var i=0;i<w.length;i++){if(v.indexOf(w[i])<0)continue;var seen={};for(var j=i;j<w.length;j++){if(v.indexOf(w[j])<0)break;seen[w[j]]=1;if(Object.keys(seen).length===5)c++;}}return c;}'),

pdef('divide-string-groups', 'Divide a String Into Groups of Size k', 'easy', 'divideString',
    sig(['s' => 'str', 'k' => 'int', 'fill' => 'str'], 'str[]'),
    'Split s into groups of size k, padding the final group with the fill character. Return the groups.',
    ['1 ≤ s.length ≤ 1000', 'fill is a single character'],
    [t(['abcdefghi', 3, 'x'], ['abc', 'def', 'ghi'], 1), t(['abcdefghij', 3, 'x'], ['abc', 'def', 'ghi', 'jxx'], 1), t(['ab', 1, 'z'], ['a', 'b'])],
    'function divideString(s,k,f){var o=[];for(var i=0;i<s.length;i+=k){var g=s.slice(i,i+k);while(g.length<k)g+=f;o.push(g);}return o;}'),

pdef('square-white', 'Color of Chessboard Square', 'easy', 'squareIsWhite',
    sig(['coordinates' => 'str'], 'bool'),
    'Chess squares: a1 is black. Return true if the given square (e.g. "c3") is white.',
    ['coordinates is a letter a-h followed by a digit 1-8'],
    [t(['a1'], false, 1), t(['h3'], true, 1), t(['c7'], false)],
    'function squareIsWhite(c){return ((c.charCodeAt(0)-97)+(c.charCodeAt(1)-49))%2===1;}'),

pdef('circular-sentence', 'Circular Sentence', 'easy', 'isCircularSentence',
    sig(['sentence' => 'str'], 'bool'),
    'Circular = last char of each word equals the first char of the next word (and last word feeds back to the first).',
    ['1 ≤ sentence.length ≤ 100', 'lowercase + single spaces, no leading/trailing space'],
    [t(['leetcode exercises sound delightful'], true, 1), t(['eetcode'], true, 1), t(['Leetcode is cool'], false)],
    'function isCircularSentence(s){var w=s.split(" ");for(var i=0;i<w.length;i++){var nx=w[(i+1)%w.length];if(w[i][w[i].length-1]!==nx[0])return false;}return true;}'),

pdef('count-binary-substrings', 'Count Binary Substrings', 'easy', 'countBinarySubstrings',
    sig(['s' => 'str'], 'int'),
    'Count substrings with equal numbers of 0s and 1s, all 0s and 1s grouped consecutively (e.g. "0011", "01", "1100").',
    ['1 ≤ s.length ≤ 10⁵', 'only 0/1'],
    [t(['00110011'], 6, 1), t(['10101'], 4, 1), t(['00110'], 3)],
    'function countBinarySubstrings(s){var prev=0,cur=1,ans=0;for(var i=1;i<=s.length;i++){if(i<s.length&&s[i]===s[i-1])cur++;else{ans+=Math.min(prev,cur);prev=cur;cur=1;}}return ans;}'),

pdef('rotate-string', 'Rotate String', 'easy', 'rotateString',
    sig(['s' => 'str', 'goal' => 'str'], 'bool'),
    'Return true if any left-rotation of s equals goal.',
    ['1 ≤ s.length, goal.length ≤ 100 (lowercase)'],
    [t(['abcde', 'cdeab'], true, 1), t(['abcde', 'abced'], false, 1), t(['aa', 'a'], false)],
    'function rotateString(s,g){return s.length===g.length&&((s+s).indexOf(g)>=0);}'),

pdef('buddy-strings', 'Buddy Strings', 'easy', 'buddyStrings',
    sig(['s' => 'str', 'goal' => 'str'], 'bool'),
    'Return true if swapping exactly two letters of s can produce goal.',
    ['1 ≤ s.length, goal.length ≤ 2·10⁴ (lowercase)'],
    [t(['ab', 'ba'], true, 1), t(['ab', 'ab'], false, 1), t(['aa', 'aa'], true), t(['abcaa', 'abcbb'], false)],
    'function buddyStrings(s,g){if(s.length!==g.length)return false;if(s===g){return new Set(s.split("")).size<s.length;}var d=[];for(var i=0;i<s.length;i++)if(s[i]!==g[i])d.push(i);return d.length===2&&s[d[0]]===g[d[1]]&&s[d[1]]===g[d[0]];}'),

pdef('to-lower-case', 'To Lower Case', 'easy', 'toLowerCase',
    sig(['s' => 'str'], 'str'),
    'Convert the string to lowercase WITHOUT using a built-in lowercase function.',
    ['1 ≤ s.length ≤ 1000 (ASCII)'],
    [t(['Hello'], 'hello', 1), t(['LOVELY'], 'lovely', 1), t(['al&phaBET'], 'al&phabet')],
    'function toLowerCase(s){return s.split("").map(function(c){var x=c.charCodeAt(0);return x>=65&&x<=90?String.fromCharCode(x+32):c;}).join("");}'),

pdef('reverse-only-letters', 'Reverse Only Letters', 'easy', 'reverseOnlyLetters',
    sig(['s' => 'str'], 'str'),
    'Reverse only the letters; non-letters keep their positions.',
    ['1 ≤ s.length ≤ 100'],
    [t(['ab-cd'], 'dc-ba', 1), t(['a-bC-dEf-ghIj'], 'j-Ih-gfE-dCba', 1), t(['Test1ng-Leet=code-Q!'], 'Qedo1ct-eeLg=ntse-T!')],
    'function reverseOnlyLetters(s){function isL(c){return /[A-Za-z]/.test(c);}var a=s.split(""),i=0,j=a.length-1;while(i<j){if(!isL(a[i])){i++;continue;}if(!isL(a[j])){j--;continue;}var t=a[i];a[i]=a[j];a[j]=t;i++;j--;}return a.join("");}'),

pdef('goat-latin', 'Goat Latin', 'easy', 'toGoatLatin',
    sig(['sentence' => 'str'], 'str'),
    'Each word: if it starts with a vowel add "ma", else move the first letter to the end and add "ma"; then append i+1 copies of "a" (1-based).',
    ['1 ≤ sentence.length ≤ 150 (words of letters, single spaces)'],
    [t(['I speak Goat Latin'], 'Imaa peaksmaaa oatGmaaaa atinLmaaaaa', 1),
     t(['The quick brown fox'], 'heTmaa uickqmaaa rownbmaaaa oxfmaaaaa', 1)],
    'function toGoatLatin(s){var v="aeiouAEIOU";return s.split(" ").map(function(w,i){if(v.indexOf(w[0])<0)w=w.slice(1)+w[0];w+="ma";for(var k=0;k<=i;k++)w+="a";return w;}).join(" ");}'),

pdef('unique-morse', 'Unique Morse Code Words', 'easy', 'uniqueMorseRepresentations',
    sig(['words' => 'str[]'], 'int'),
    'Map each word to Morse code (a-z fixed) and count distinct transformations.',
    ['1 ≤ words.length ≤ 100', '1 ≤ words[i].length ≤ 12 (lowercase)'],
    [t([['gin', 'zen', 'gig', 'msg']], 2, 1), t([['a']], 1, 1), t([['rwjje', 'aittjje', 'auyyn', 'lqtktn', 'lmjwn']], 1)],
    'function uniqueMorseRepresentations(words){var mor=[".-","-...","-.-.","-..",".","..-.","--.","....","..",".---","-.-",".-..","--","-.","---",".--.","--.-",".-.","...","-","..-","...-",".--","-..-","-.--","--.."];var st=new Set(words.map(function(w){return w.split("").map(function(c){return mor[c.charCodeAt(0)-97];}).join("");}));return st.size;}'),

pdef('keyboard-row', 'Keyboard Row', 'easy', 'findWords',
    sig(['words' => 'str[]'], 'str[]'),
    'QWERTY rows: "qwertyuiop", "asdfghjkl", "zxcvbnm". Keep words typeable on ONE row (case-insensitive); keep original order.',
    ['1 ≤ words.length ≤ 20', '1 ≤ words[i].length ≤ 100 (letters only)'],
    [t([['Hello', 'Alaska', 'Dad', 'Peace']], ['Alaska', 'Dad'], 1), t([['omk']], [], 1), t([['adsdf', 'sfd']], ['adsdf', 'sfd'])],
    'function findWords(words){var r=["qwertyuiop","asdfghjkl","zxcvbnm"];return words.filter(function(w){w=w.toLowerCase();for(var i=0;i<3;i++){var ok=true;for(var j=0;j<w.length;j++)if(r[i].indexOf(w[j])<0){ok=false;break;}if(ok)return true;}return false;});}'),

pdef('shortest-to-char', 'Shortest Distance to a Character', 'easy', 'shortestToChar',
    sig(['s' => 'str', 'c' => 'str'], 'int[]'),
    'For each index i, return the distance to the closest occurrence of c in s.',
    ['1 ≤ s.length ≤ 10⁴ (lowercase)', 'c occurs in s'],
    [t(['loveleetcode', 'e'], [3, 2, 1, 0, 1, 0, 0, 1, 2, 2, 1, 0], 1), t(['aaab', 'b'], [3, 2, 1, 0], 1), t(['baaa', 'a'], [1, 0, 0, 0])],
    'function shortestToChar(s,c){var n=s.length,ans=new Array(n).fill(n),d=n;for(var i=0;i<n;i++){if(s[i]===c)d=0;ans[i]=Math.min(ans[i],d++);}d=n;for(var j=n-1;j>=0;j--){if(s[j]===c)d=0;ans[j]=Math.min(ans[j],d++);}return ans;}'),

pdef('license-key', 'License Key Formatting', 'easy', 'licenseKeyFormatting',
    sig(['s' => 'str', 'k' => 'int'], 'str'),
    'Reformat the key: regroup alphanumerics into groups of k (first group may be shorter), uppercase letters, separated by "-".',
    ['1 ≤ s.length ≤ 10⁵', '1 ≤ k ≤ 10⁴'],
    [t(['5F3Z-2e-9-w', 4], '5F3Z-2E9W', 1), t(['2-5g-3-J', 2], '2-5G-3J', 1), t(['a-a-a-a-', 3], 'A-AAA')],
    'function licenseKeyFormatting(s,k){var t=s.replace(/-/g,"").toUpperCase();var f=t.length%k,o=[];if(f)o.push(t.slice(0,f));for(var i=f;i<t.length;i+=k)o.push(t.slice(i,i+k));return o.join("-");}'),

pdef('add-strings', 'Add Strings', 'easy', 'addStrings',
    sig(['num1' => 'str', 'num2' => 'str'], 'str'),
    'Add two non-negative integers given as decimal strings, WITHOUT converting the whole string to an integer (simulate digit addition).',
    ['1 ≤ num1.length, num2.length ≤ 10⁴', 'no leading zeros except "0" itself'],
    [t(['11', '123'], '134', 1), t(['456', '77'], '533', 1), t(['0', '0'], '0'), t(['3876620623801494171', '6529364523802684779'], '10405985147604178950')],
    'function addStrings(a,b){var i=a.length-1,j=b.length-1,c=0,o="";while(i>=0||j>=0||c){var d=(i>=0?Number(a[i--]):0)+(j>=0?Number(b[j--]):0)+c;o=(d%10)+o;c=(d/10)|0;}return o;}'),

pdef('consistent-strings', 'Count Strings Consistent with Allowed Letters', 'easy', 'countConsistentStrings',
    sig(['allowed' => 'str', 'words' => 'str[]'], 'int'),
    'A word is consistent if every letter appears in allowed. Count them.',
    ['1 ≤ words.length ≤ 10⁴', 'allowed has distinct lowercase letters'],
    [t(['ab', ['ad', 'bd', 'aaab', 'baa', 'badab']], 2, 1), t(['abc', ['a', 'b', 'c', 'ab', 'ac', 'bc', 'abc']], 7, 1), t(['cad', ['cc', 'acd', 'b', 'ba', 'bac', 'bad', 'ac', 'd']], 4)],
    'function countConsistentStrings(al,words){var st=new Set(al.split(""));return words.filter(function(w){for(var i=0;i<w.length;i++)if(!st.has(w[i]))return false;return true;}).length;}'),

pdef('repeated-substring', 'Repeated Substring Pattern', 'easy', 'repeatedSubstringPattern',
    sig(['s' => 'str'], 'bool'),
    'Return true if s equals some non-empty substring repeated 2+ times.',
    ['1 ≤ s.length ≤ 10⁴ (lowercase)'],
    [t(['abab'], true, 1), t(['aba'], false, 1), t(['abcabcabcabc'], true), t(['abaababaab'], true)],
    'function repeatedSubstringPattern(s){return (s+s).slice(1,-1).indexOf(s)>=0;}'),

pdef('valid-palindrome-ii', 'Valid Palindrome II', 'easy', 'validPalindrome',
    sig(['s' => 'str'], 'bool'),
    'Return true if s can become a palindrome by deleting AT MOST one character.',
    ['1 ≤ s.length ≤ 10⁵ (lowercase)'],
    [t(['aba'], true, 1), t(['abca'], true, 1), t(['abc'], false), t(['deeee'], true)],
    'function validPalindrome(s){function pal(a,i,j){while(i<j){if(a[i]!==a[j])return false;i++;j--;}return true;}var i=0,j=s.length-1;while(i<j){if(s[i]!==s[j])return pal(s,i+1,j)||pal(s,i,j-1);i++;j--;}return true;}'),

pdef('merge-alternately', 'Merge Strings Alternately', 'easy', 'mergeAlternately',
    sig(['word1' => 'str', 'word2' => 'str'], 'str'),
    'Merge the two strings by adding letters in alternating order (word1 first), appending any remainder.',
    ['1 ≤ word1.length, word2.length ≤ 100 (lowercase)'],
    [t(['abc', 'pqr'], 'apbqcr', 1), t(['ab', 'pqrs'], 'apbqrs', 1), t(['abcd', 'pq'], 'apbqcd')],
    'function mergeAlternately(a,b){var o="",n=Math.max(a.length,b.length);for(var i=0;i<n;i++){if(i<a.length)o+=a[i];if(i<b.length)o+=b[i];}return o;}'),

pdef('jewels-shortest-word', 'Find Minimum Length Word Missing From List', 'easy', 'shortestCompletingWord',
    sig(['licensePlate' => 'str', 'words' => 'str[]'], 'str'),
    'Ignore digits/spaces/case in licensePlate; call its letters "required". Return the shortest word containing all required letters (with multiplicity); answer is unique.',
    ['1 ≤ licensePlate.length ≤ 7', '1 ≤ words.length ≤ 1000'],
    [t(['1s3 PSt', ['step', 'steps', 'stripe', 'stepple']], 'steps', 1),
     t(['1s3 456', ['looks', 'pest', 'stew', 'show']], 'pest', 1), t(['Ah71752', ['suggest', 'letter', 'of', 'husband', 'easy', 'education', 'in', 'jj', 'his']], 'husband')],
    'function shortestCompletingWord(lp,words){var need={};var L=lp.toLowerCase();for(var i=0;i<L.length;i++){var c=L[i];if(c>="a"&&c<="z")need[c]=(need[c]||0)+1;}var best=null;words.forEach(function(w){if(best&&w.length>=best.length)return;var have={};for(var j=0;j<w.length;j++)have[w[j]]=(have[w[j]]||0)+1;var ok=true;for(var k in need)if((have[k]||0)<need[k])ok=false;if(ok)best=w;});return best;}'),

pdef('first-letter-twice', 'First Letter to Appear Twice', 'easy', 'repeatedCharacter',
    sig(['s' => 'str'], 'str'),
    'Return the first letter whose SECOND occurrence appears earliest while scanning left to right.',
    ['1 ≤ s.length ≤ 100 (lowercase)', 'at least one letter repeats'],
    [t(['abccbaacz'], 'c', 1), t(['abcdd'], 'd', 1), t(['aab'], 'a'), t(['jkgnaozxmykcdhd'], 'k')],
    'function repeatedCharacter(s){var seen=new Set();for(var i=0;i<s.length;i++){if(seen.has(s[i]))return s[i];seen.add(s[i]);}return "";}'),

pdef('alternating-digit-string-sum', 'Alternating Digit Sum', 'easy', 'alternateDigitSum',
    sig(['n' => 'int'], 'int'),
    'Sum the digits of n with alternating signs (+ - + - ...) starting positive from the leftmost (most significant) digit.',
    ['1 ≤ n ≤ 10⁹'],
    [t([521], 4, 1), t([111], 1, 1), t([886996], 0), t([10], 1)],
    'function alternateDigitSum(n){var s=String(n),sum=0,sign=1;for(var i=0;i<s.length;i++){sum+=sign*Number(s[i]);sign=-sign;}return sum;}'),
];
