<?php
// Category: twoptr — two pointers, sliding windows, read/write cursors
return [
pdef('move-zeroes', 'Move Zeroes', 'easy', 'moveZeroes',
    sig(['nums' => 'int[]'], 'int[]'),
    'Move all the zeroes to the end of the array while keeping the relative order of the non-zero elements. Return the resulting array.',
    ['1 ≤ nums.length ≤ 10⁴'],
    [t([[0, 1, 0, 3, 12]], [1, 3, 12, 0, 0], 1), t([[0]], [0], 1), t([[1, 2, 3]], [1, 2, 3]), t([[4, 0, 5, 0, 1]], [4, 5, 1, 0, 0])],
    'function moveZeroes(nums){var w=0,r;for(r=0;r<nums.length;r++){if(nums[r]!==0){var tmp=nums[w];nums[w]=nums[r];nums[r]=tmp;w++;}}return nums;}'),

pdef('container-with-most-water', 'Container With Most Water', 'medium', 'maxArea',
    sig(['height' => 'int[]'], 'int'),
    'height[i] is the height of a vertical line at position i. Pick two lines that, with the x-axis, hold the most water and return that maximum area.',
    ['2 ≤ n ≤ 10⁵', '0 ≤ height[i] ≤ 10⁴'],
    [t([[1, 8, 6, 2, 5, 4, 8, 3, 7]], 49, 1), t([[1, 1]], 1, 1), t([[4, 3, 2, 1, 4]], 16), t([[1, 2, 1]], 2)],
    'function maxArea(h){var l=0,r=h.length-1,best=0;while(l<r){best=Math.max(best,Math.min(h[l],h[r])*(r-l));if(h[l]<h[r])l++;else r--;}return best;}'),

pdef('trapping-rain-water', 'Trapping Rain Water', 'hard', 'trap',
    sig(['height' => 'int[]'], 'int'),
    'Given an elevation map of bar heights (each bar 1 wide), compute how much rain water the terrain can trap after raining.',
    ['0 ≤ n ≤ 2·10⁴', '0 ≤ height[i] ≤ 10⁵'],
    [t([[0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]], 6, 1), t([[4, 2, 0, 3, 2, 5]], 9, 1), t([[]], 0), t([[2, 0, 2]], 2)],
    'function trap(h){var l=0,r=h.length-1,lm=0,rm=0,w=0;while(l<r){if(h[l]<h[r]){lm=Math.max(lm,h[l]);w+=lm-h[l];l++;}else{rm=Math.max(rm,h[r]);w+=rm-h[r];r--;}}return w;}'),

pdef('valid-palindrome', 'Valid Palindrome', 'easy', 'isPalindromeStr',
    sig(['s' => 'str'], 'bool'),
    'After removing every non-alphanumeric character and lowercasing, does the phrase read the same forward and backward? Return true if it is a palindrome.',
    ['1 ≤ s.length ≤ 2·10⁵'],
    [t(['A man, a plan, a canal: Panama'], true, 1), t(['race a car'], false, 1), t([' '], true), t(['0P'], false)],
    'function isPalindromeStr(s){s=s.toLowerCase().replace(/[^a-z0-9]/g,"");var i=0,j=s.length-1;while(i<j){if(s[i]!==s[j])return false;i++;j--;}return true;}'),

pdef('reverse-vowels', 'Reverse Vowels of a String', 'easy', 'reverseVowels',
    sig(['s' => 'str'], 'str'),
    'Reverse only the vowels of the string; every other character keeps its exact position. Vowels are a,e,i,o,u in either case.',
    ['1 ≤ s.length ≤ 3·10⁵'],
    [t(['hello'], 'holle', 1), t(['leetcode'], 'leotcede', 1), t(['aA'], 'Aa'), t(['xyz'], 'xyz')],
    'function reverseVowels(s){var a=s.split(""),v="aeiouAEIOU",i=0,j=a.length-1;while(i<j){while(i<j&&v.indexOf(a[i])<0)i++;while(i<j&&v.indexOf(a[j])<0)j--;var t=a[i];a[i]=a[j];a[j]=t;i++;j--;}return a.join("");}'),

pdef('squares-sorted', 'Squares of a Sorted Array', 'easy', 'sortedSquares',
    sig(['nums' => 'int[]'], 'int[]'),
    'The array is sorted in non-decreasing order (negatives allowed). Return the squares of each number, also sorted. Aim for O(n) with two pointers from both ends.',
    ['1 ≤ nums.length ≤ 10⁴'],
    [t([[-4, -1, 0, 3, 10]], [0, 1, 9, 16, 100], 1), t([[-7, -3, 2, 3, 11]], [4, 9, 9, 49, 121], 1), t([[-5]], [25]), t([[-3, -2, -1]], [1, 4, 9])],
    'function sortedSquares(nums){var n=nums.length,out=new Array(n),i=0,j=n-1,k=n-1;while(i<=j){var a=nums[i]*nums[i],b=nums[j]*nums[j];if(a>b){out[k--]=a;i++;}else{out[k--]=b;j--;}}return out;}'),

pdef('remove-duplicates-sorted', 'Remove Duplicates from Sorted Array', 'easy', 'removeDuplicates',
    sig(['nums' => 'int[]'], 'int[]'),
    'The array is sorted. Remove the duplicates in-place style so each value appears once, and return the deduplicated array in the same order.',
    ['0 ≤ nums.length ≤ 3·10⁴'],
    [t([[1, 1, 2]], [1, 2], 1), t([[0, 0, 1, 1, 1, 2, 2, 3, 3, 4]], [0, 1, 2, 3, 4], 1), t([[]], []), t([[1, 1, 1]], [1])],
    'function removeDuplicates(nums){if(!nums.length)return [];var w=1,r;for(r=1;r<nums.length;r++){if(nums[r]!==nums[w-1]){nums[w]=nums[r];w++;}}return nums.slice(0,w);}'),

pdef('two-sum-sorted', 'Two Sum II (Sorted Input)', 'easy', 'twoSumSorted',
    sig(['numbers' => 'int[]', 'target' => 'int'], 'int[]'),
    'The array is sorted ascending. Find the two numbers that sum to target and return their 1-BASED indices ascending. There is exactly one solution.',
    ['2 ≤ numbers.length ≤ 3·10⁴'],
    [t([[2, 7, 11, 15], 9], [1, 2], 1), t([[2, 3, 4], 6], [1, 3], 1), t([[-1, 0], -1], [1, 2]), t([[1, 2, 5, 7], 8], [1, 4])],
    'function twoSumSorted(a,t){var i=0,j=a.length-1;while(i<j){var s=a[i]+a[j];if(s===t)return [i+1,j+1];if(s<t)i++;else j--;}return [];}'),

pdef('backspace-compare', 'Backspace String Compare', 'easy', 'backspaceCompare',
    sig(['s' => 'str', 't2' => 'str'], 'bool'),
    'In both strings, # means a backspace (deleting the previous character if any). Return true if the two strings end up equal after every backspace is processed.',
    ['1 ≤ lengths ≤ 200'],
    [t(['ab#c', 'ad#c'], true, 1), t(['ab##', 'c#d#'], true, 1), t(['a#c', 'b'], false), t(['##ab', 'ab'], true)],
    'function backspaceCompare(s,t){var build=function(x){var st=[],i;for(i=0;i<x.length;i++){if(x[i]==="#")st.pop();else st.push(x[i]);}return st.join("");};return build(s)===build(t);}'),

pdef('merge-sorted-arrays', 'Merge Two Sorted Arrays', 'easy', 'mergeSorted',
    sig(['a' => 'int[]', 'b' => 'int[]'], 'int[]'),
    'Merge two ascending-sorted arrays into one ascending-sorted array and return it.',
    ['0 ≤ lengths ≤ 10⁵'],
    [t([[1, 3, 5], [2, 4, 6]], [1, 2, 3, 4, 5, 6], 1), t([[], [1]], [1], 1), t([[1, 1], [2]], [1, 1, 2]), t([[-3, 0], [0, 3]], [-3, 0, 0, 3])],
    'function mergeSorted(a,b){var out=[],i=0,j=0;while(i<a.length||j<b.length){if(j>=b.length||(i<a.length&&a[i]<=b[j]))out.push(a[i++]);else out.push(b[j++]);}return out;}'),

pdef('sort-parity', 'Sort Array By Parity', 'easy', 'sortByParity',
    sig(['nums' => 'int[]'], 'int[]'),
    'Return the array with all even numbers first (ascending), followed by all odd numbers (ascending).',
    ['1 ≤ nums.length ≤ 5000'],
    [t([[3, 1, 2, 4]], [2, 4, 1, 3], 1), t([[0]], [0], 1), t([[5, 7, 9]], [5, 7, 9]), t([[8, 2, 6, 1]], [2, 6, 8, 1])],
    'function sortByParity(nums){var evens=nums.filter(function(x){return x%2===0;}).sort(function(a,b){return a-b;});var odds=nums.filter(function(x){return Math.abs(x%2)===1;}).sort(function(a,b){return a-b;});return evens.concat(odds);}'),

pdef('count-pairs-less', 'Count Pairs With Sum Less Than Target', 'easy', 'countPairsLess',
    sig(['nums' => 'int[]', 'target' => 'int'], 'int'),
    'Count the pairs (i, j) with i < j whose values sum to LESS than target.',
    ['1 ≤ nums.length ≤ 50', '-50 ≤ nums[i], target ≤ 50'],
    [t([[-1, 1, 2, 3, 1], 2], 3, 1), t([[1, 2, 3], 2], 0, 1), t([[1, -2, 3], 1], 1), t([[0, 0, 0], 1], 3)],
    'function countPairsLess(nums,target){var c=0,i,j;for(i=0;i<nums.length;i++){for(j=i+1;j<nums.length;j++){if(nums[i]+nums[j]<target)c++;}}return c;}'),

pdef('three-sum', '3Sum', 'medium', 'threeSum',
    sig(['nums' => 'int[]'], 'int[][]'),
    'Find every unique triplet that sums to zero. Keep each triplet sorted ascending, and sort the list of triplets lexicographically so the answer is deterministic.',
    ['3 ≤ nums.length ≤ 3000'],
    [t([[-1, 0, 1, 2, -1, -4]], [[-1, -1, 2], [-1, 0, 1]], 1), t([[0, 1, 1]], [], 1), t([[0, 0, 0]], [[0, 0, 0]]), t([[-2, 0, 1, 1, 2]], [[-2, 0, 2], [-2, 1, 1]])],
    'function threeSum(nums){nums.sort(function(a,b){return a-b;});var out=[],i,l,r;for(i=0;i<nums.length;i++){if(i>0&&nums[i]===nums[i-1])continue;l=i+1;r=nums.length-1;while(l<r){var s=nums[i]+nums[l]+nums[r];if(s===0){out.push([nums[i],nums[l],nums[r]]);while(l<r&&nums[l]===nums[l+1])l++;while(l<r&&nums[r]===nums[r-1])r--;l++;r--;}else if(s<0)l++;else r--;}}return out;}'),


pdef('three-sum-closest', '3Sum Closest', 'medium', 'threeSumClosest',
    sig(['nums' => 'int[]', 'target' => 'int'], 'int'),
    'Find three integers whose sum is closest to target. Return that sum.',
    ['3 <= nums.length <= 1000'],
    [t([[-1,2,1,-4], 1], 2, 1), t([[0,0,0], 1], 0, 1), t([[1,1,1,0], -100], 2), t([[0,1,2], 0], 3)],
    'function threeSumClosest(nums,target){nums.sort(function(a,b){return a-b;});var best=nums[0]+nums[1]+nums[2];for(var i=0;i<nums.length-2;i++){var l=i+1,r=nums.length-1;while(l<r){var s=nums[i]+nums[l]+nums[r];if(Math.abs(s-target)<Math.abs(best-target))best=s;if(s<target)l++;else if(s>target)r--;else return s;}}return best;}'),

pdef('four-sum', '4Sum', 'medium', 'fourSum',
    sig(['nums' => 'int[]', 'target' => 'int'], 'int[][]'),
    'Return all unique quadruplets [a, b, c, d] (ascending) whose sum equals target.',
    ['1 <= nums.length <= 200'],
    [t([[1,0,-1,0,-2,2], 0], [[-2,-1,1,2],[-2,0,0,2],[-1,0,0,1]], 1), t([[2,2,2,2,2], 8], [[2,2,2,2]], 1), t([[1], 1], []), t([[2,2,2,2], 8], [[2,2,2,2]])],
    'function fourSum(nums,target){nums.sort(function(a,b){return a-b;});var out=[];var n=nums.length;for(var i=0;i<n-3;i++){if(i>0&&nums[i]===nums[i-1])continue;for(var j=i+1;j<n-2;j++){if(j>i+1&&nums[j]===nums[j-1])continue;var l=j+1,r=n-1;while(l<r){var s=nums[i]+nums[j]+nums[l]+nums[r];if(s===target){out.push([nums[i],nums[j],nums[l],nums[r]]);l++;r--;while(l<r&&nums[l]===nums[l-1])l++;while(l<r&&nums[r]===nums[r+1])r--;}else if(s<target)l++;else r--;}}}return out;}'),

pdef('three-sum-smaller', '3Sum Smaller', 'medium', 'threeSumSmaller',
    sig(['nums' => 'int[]', 'target' => 'int'], 'int'),
    'Count triples of indices i < j < k whose values sum to strictly less than target.',
    ['0 <= nums.length <= 3500'],
    [t([[-2,0,1,3], 2], 2, 1), t([[0], 0], 0, 1), t([[1,1,-2], 1], 1), t([[2,0,0,2], 3], 2)],
    'function threeSumSmaller(nums,target){nums.sort(function(a,b){return a-b;});var cnt=0;for(var i=0;i<nums.length-2;i++){var l=i+1,r=nums.length-1;while(l<r){if(nums[i]+nums[l]+nums[r]<target){cnt+=r-l;l++;}else r--;}}return cnt;}'),

pdef('reverse-words-iii', 'Reverse Words in a String III', 'easy', 'reverseWords',
    sig(['s' => 'str'], 'str'),
    'Reverse each word in place, keeping the word order and single spaces.',
    ['1 <= s.length <= 50000'],
    [t(["Let's take LeetCode contest"], "s'teL ekat edoCteeL tsetnoc", 1), t(['Mr Ding'], 'rM gniD', 1), t(['hello'], 'olleh'), t(['hi there'], 'ih ereht')],
    'function reverseWords(s){return s.split(" ").map(function(w){return w.split("").reverse().join("");}).join(" ");}'),

pdef('intersection-two-ii', 'Intersection of Two Arrays II', 'easy', 'intersect',
    sig(['a' => 'int[]', 'b' => 'int[]'], 'int[]'),
    'Return the intersection keeping duplicates (each value appears as many times as it shows in both). Result is ascending.',
    ['1 <= a.length, b.length <= 1000'],
    [t([[1,2,2,1], [2,2]], [2,2], 1), t([[4,9,5], [9,4,9,8,4]], [4,9], 1), t([[1,2], [1,1]], [1]), t([[1,2,3], [2]], [2])],
    'function intersect(a,b){a.sort(function(x,y){return x-y;});b.sort(function(x,y){return x-y;});var out=[],i=0,j=0;while(i<a.length&&j<b.length){if(a[i]===b[j]){out.push(a[i]);i++;j++;}else if(a[i]<b[j])i++;else j++;}return out;}'),

pdef('longest-mountain', 'Longest Mountain in Array', 'medium', 'longestMountain',
    sig(['arr' => 'int[]'], 'int'),
    'A mountain strictly increases to a peak then strictly decreases, length >= 3. Return the longest mountain subarray length.',
    ['1 <= arr.length <= 10000'],
    [t([[2,1,4,7,3,2,5]], 5, 1), t([[2,2,2]], 0, 1), t([[0,1,2,3,4,5,4,3,2,1,0]], 11), t([[1,2,3]], 0)],
    'function longestMountain(a){var n=a.length,best=0,i=1;while(i<n){if(a[i]>a[i-1]){var start=i-1;while(i<n&&a[i]>a[i-1])i++;if(i<n&&a[i]<a[i-1]){while(i<n&&a[i]<a[i-1])i++;best=Math.max(best,i-start);}}else i++;}return best;}'),

pdef('subarray-product-lt-k', 'Subarray Product Less Than K', 'medium', 'numSubarrayProductLessThanK',
    sig(['nums' => 'int[]', 'k' => 'int'], 'int'),
    'Count contiguous subarrays whose product of all elements is strictly less than k. All values are positive.',
    ['1 <= nums.length <= 30000'],
    [t([[10,5,2,6], 100], 8, 1), t([[1,2,3], 0], 0, 1), t([[1,1,1], 1], 0), t([[10,9,10,4,3,8,3,3,6,2,10,10,9,3], 19], 18)],
    'function numSubarrayProductLessThanK(nums,k){if(k<=1)return 0;var count=0,prod=1,l=0;for(var r=0;r<nums.length;r++){prod*=nums[r];while(prod>=k)prod/=nums[l++];count+=r-l+1;}return count;}'),

pdef('sort-colors', 'Sort Colors', 'medium', 'sortColors',
    sig(['nums' => 'int[]'], 'int[]'),
    'The array holds only 0 (red), 1 (white) and 2 (blue). Sort it in one pass and return it.',
    ['1 <= nums.length <= 300'],
    [t([[2,0,2,1,1,0]], [0,0,1,1,2,2], 1), t([[2,0,1]], [0,1,2], 1), t([[0]], [0]), t([[1]], [1])],
    'function sortColors(nums){var lo=0,hi=nums.length-1,i=0;while(i<=hi){if(nums[i]===0){var t=nums[lo];nums[lo]=0;nums[i]=t;lo++;i++;}else if(nums[i]===2){var t2=nums[hi];nums[hi]=2;nums[i]=t2;hi--;}else i++;}return nums;}'),

pdef('min-max-pair-sum', 'Minimize Maximum Pair Sum in Array', 'medium', 'minPairSum',
    sig(['nums' => 'int[]'], 'int'),
    'Pair up the even-length array so the largest pair sum is as small as possible. Return that sum.',
    ['2 <= nums.length <= 100000, even'],
    [t([[3,5,2,3]], 7, 1), t([[3,5,4,2,4,6]], 8, 1), t([[1,1]], 2), t([[1,100000]], 100001)],
    'function minPairSum(nums){nums.sort(function(a,b){return a-b;});var best=0;for(var i=0;i<nums.length/2;i++)best=Math.max(best,nums[i]+nums[nums.length-1-i]);return best;}'),

pdef('next-permutation', 'Next Permutation', 'medium', 'nextPermutation',
    sig(['nums' => 'int[]'], 'int[]'),
    "Rearrange into the lexicographically next permutation; if it is the last one, wrap to the first. Return the rearranged array.",
    ['1 <= nums.length <= 100'],
    [t([[1,2,3]], [1,3,2], 1), t([[3,2,1]], [1,2,3], 1), t([[1,1,5]], [1,5,1]), t([[1]], [1])],
    'function nextPermutation(nums){var i=nums.length-2;while(i>=0&&nums[i]>=nums[i+1])i--;if(i>=0){var j=nums.length-1;while(nums[j]<=nums[i])j--;var t=nums[i];nums[i]=nums[j];nums[j]=t;}var l=i+1,r=nums.length-1;while(l<r){var t2=nums[l];nums[l]=nums[r];nums[r]=t2;l++;r--;}return nums;}'),

pdef('max-erase-value', 'Maximum Erasure Value', 'medium', 'maxErasureValue',
    sig(['nums' => 'int[]'], 'int'),
    'Erase one subarray of unique elements to score its sum. Return the maximum score.',
    ['1 <= nums.length <= 100000'],
    [t([[4,2,4,5,6]], 17, 1), t([[1,2,3,4,5]], 15, 1), t([[5,2,1,2,5,2,1,2,5]], 8), t([[1]], 1)],
    'function maxErasureValue(nums){var seen={},l=0,sum=0,best=0;for(var r=0;r<nums.length;r++){while(seen[nums[r]]){delete seen[nums[l]];sum-=nums[l];l++;}seen[nums[r]]=true;sum+=nums[r];best=Math.max(best,sum);}return best;}'),

pdef('replace-balanced', 'Replace the Substring for Balanced String', 'medium', 'balancedString',
    sig(['s' => 'str'], 'int'),
    's contains only Q, W, E, R. In one move replace any characters inside one chosen substring. Return the smallest substring length that makes all four counts equal.',
    ['s.length is divisible by 4'],
    [t(['QWER'], 0, 1), t(['QQWE'], 1, 1), t(['QQQW'], 2), t(['QQQQ'], 3)],
    'function balancedString(s){var total={Q:0,W:0,E:0,R:0};for(var c of s)total[c]++;var k=s.length/4;var need={};for(var c2 in total)if(total[c2]>k)need[c2]=total[c2]-k;var keys=Object.keys(need);if(!keys.length)return 0;var have={},l=0,best=s.length;for(var r=0;r<s.length;r++){var ch=s[r];if(need[ch])have[ch]=(have[ch]||0)+1;while(keys.every(function(c){return (have[c]||0)>=need[c];})){best=Math.min(best,r-l+1);var cl=s[l++];if(need[cl])have[cl]--;}}return best;}'),

pdef('shortest-unsorted', 'Shortest Unsorted Continuous Subarray', 'medium', 'findUnsortedSubarray',
    sig(['nums' => 'int[]'], 'int'),
    'Return the length of the shortest subarray that, when sorted, makes the whole array ascending. 0 if already sorted.',
    ['1 <= nums.length <= 10000'],
    [t([[2,6,4,8,10,9,15]], 5, 1), t([[1,2,3,4]], 0, 1), t([[1]], 0), t([[1,3,2,2,2]], 4)],
    'function findUnsortedSubarray(nums){var n=nums.length,end=-1,start=0;for(var i=0,mx=-Infinity;i<n;i++){if(nums[i]<mx)end=i;mx=Math.max(mx,nums[i]);}for(var j=n-1,mn=Infinity;j>=0;j--){if(nums[j]>mn)start=j;mn=Math.min(mn,nums[j]);}return end-start+1;}'),

pdef('longest-repeating-replacement', 'Longest Repeating Character Replacement', 'medium', 'characterReplacement',
    sig(['s' => 'str', 'k' => 'int'], 'int'),
    'You may change at most k characters to any letter. Return the longest run of one repeating letter achievable.',
    ['1 <= s.length <= 100000, uppercase A-Z'],
    [t(['ABAB', 2], 4, 1), t(['AABABBA', 1], 4, 1), t(['AAAA', 0], 4), t(['ABBB', 2], 4)],
    'function characterReplacement(s,k){var cnt={},l=0,best=0,mx=0;for(var r=0;r<s.length;r++){cnt[s[r]]=(cnt[s[r]]||0)+1;mx=Math.max(mx,cnt[s[r]]);while(r-l+1-mx>k){cnt[s[l]]--;l++;}best=Math.max(best,r-l+1);}return best;}'),

pdef('non-decreasing-array', 'Non-decreasing Array', 'medium', 'checkPossibility',
    sig(['nums' => 'int[]'], 'bool'),
    'Return true if the array can become non-decreasing by modifying at most one element.',
    ['1 <= nums.length <= 10000'],
    [t([[4,2,3]], true, 1), t([[4,2,1]], false, 1), t([[3,4,2,3]], false), t([[1,2,3]], true)],
    'function checkPossibility(nums){var fixed=0;for(var i=1;i<nums.length;i++){if(nums[i]<nums[i-1]){if(fixed)return false;fixed++;if(i>=2&&nums[i]<nums[i-2])nums[i]=nums[i-1];}}return true;}'),

pdef('circular-array-loop', 'Circular Array Loop', 'medium', 'circularArrayLoop',
    sig(['nums' => 'int[]'], 'bool'),
    'From index i you jump nums[i] steps (positive forward, negative backward). Return true if some cycle exists with length > 1 that never changes direction.',
    ['1 <= nums.length <= 5000'],
    [t([[2,-1,1,2,2]], true, 1), t([[-1,-2,-3,-4,-5,6]], false, 1), t([[1,-1,5,1,4]], true), t([[2,2,2,2]], true)],
    'function circularArrayLoop(nums){var n=nums.length;function nx(i){return ((i+nums[i])%n+n)%n;}for(var i=0;i<n;i++){if(nums[i]===0)continue;var slow=i,fast=i;while(true){slow=nx(slow);fast=nx(nx(fast));if(nums[fast]===0||nums[nx(fast)]===0)break;if(nums[slow]*nums[i]<0||nums[fast]*nums[i]<0)break;if(slow===fast){if(slow===nx(slow))break;return true;}}var j=i,d=nums[i];while(nums[j]*d>0){var nxt=nx(j);nums[j]=0;j=nxt;}}return false;}'),

pdef('remove-palindromic-subseq', 'Remove Palindromic Subsequences', 'easy', 'removePalindromeSub',
    sig(['s' => 'str'], 'int'),
    'In one move you delete any palindromic subsequence (not substring). s contains only a and b. Return the minimum moves to empty it.',
    ['0 <= s.length <= 1000'],
    [t(['ababa'], 1, 1), t(['abb'], 2, 1), t(['baabb'], 2), t([''], 0)],
    'function removePalindromeSub(s){if(!s.length)return 0;var t=s.split("").reverse().join("");return s===t?1:2;}'),

pdef('sentence-similarity-iii', 'Sentence Similarity III', 'medium', 'areSentencesSimilar',
    sig(['a' => 'str', 'b' => 'str'], 'bool'),
    'Return true if one sentence can be turned into the other by inserting one sentence (a run of words) into it.',
    ['1 <= lengths <= 100 words each'],
    [t(['My name is Haley', 'My Haley'], true, 1), t(['of', 'A lot of words'], false, 1), t(['Eating right now', 'Eating'], true), t(['Luky', 'Lucccky'], false)],
    'function areSentencesSimilar(a,b){var x=a.split(" "),y=b.split(" ");while(x.length&&y.length&&x[0]===y[0]){x.shift();y.shift();}while(x.length&&y.length&&x[x.length-1]===y[y.length-1]){x.pop();y.pop();}return !x.length||!y.length;}'),

pdef('strobogrammatic', 'Strobogrammatic Number', 'easy', 'isStrobogrammatic',
    sig(['num' => 'str'], 'bool'),
    'A strobogrammatic number looks the same rotated 180 degrees. Return true if num is one.',
    ['1 <= num.length <= 50'],
    [t(['69'], true, 1), t(['88'], true, 1), t(['962'], false), t(['1'], true)],
    'function isStrobogrammatic(num){var m={"0":"0","1":"1","6":"9","8":"8","9":"6"};var out="";for(var c of num){if(m[c]===undefined)return false;out=m[c]+out;}return out===num;}'),

pdef('push-dominoes', 'Push Dominoes', 'medium', 'pushDominoes',
    sig(['dominoes' => 'str'], 'str'),
    'R falls right, L falls left, . stands. Every second, a force reaches the immediate neighbour; opposing forces cancel. Return the final state.',
    ['1 <= dominoes.length <= 100000'],
    [t(['RR.L'], 'RR.L', 1), t(['.L.R...LR..L..'], 'LL.RR.LLRRLL..', 1), t(['R.R.L'], 'RRR.L'), t(['L'], 'L')],
    'function pushDominoes(dom){var n=dom.length,f=new Array(n).fill(0);var force=0;for(var i=0;i<n;i++){if(dom[i]==="R")force=n;else if(dom[i]==="L")force=0;else force=Math.max(0,force-1);f[i]+=force;}for(var j=n-1;j>=0;j--){if(dom[j]==="L")force=n;else if(dom[j]==="R")force=0;else force=Math.max(0,force-1);f[j]-=force;}var out="";for(var v of f)out+=v>0?"R":v<0?"L":".";return out;}'),

pdef('valid-number', 'Valid Number', 'hard', 'isNumber',
    sig(['s' => 'str'], 'bool'),
    'Return true if s (after trimming spaces) is a valid decimal number: optional sign, digits with optional fractional part, optional exponent.',
    ['1 <= s.length <= 20'],
    [t([' 0.1 '], true, 1), t(['abc'], false, 1), t(['2e10'], true), t(['.1'], true), t(['.'], false), t(['e3'], false)],
    'function isNumber(s){return /^[+-]?(\\d+(\\.\\d*)?|\\.\\d+)([eE][+-]?\\d+)?$/.test(s.trim());}'),

pdef('long-pressed-name', 'Long Pressed Name', 'easy', 'isLongPressedName',
    sig(['name' => 'str', 'typed' => 'str'], 'bool'),
    'Long-pressing a key types a character multiple times. Return true if typed could have come from name this way.',
    ['1 <= name.length, typed.length <= 1000'],
    [t(['alex', 'aaleex'], true, 1), t(['saeed', 'ssaaedd'], false, 1), t(['leelee', 'lleeelee'], true), t(['vtkgn', 'vttkgnn'], true)],
    'function isLongPressedName(name,typed){var i=0,j=0;while(j<typed.length){if(i<name.length&&name[i]===typed[j]){i++;j++;}else if(j>0&&typed[j]===typed[j-1])j++;else return false;}return i===name.length;}'),

pdef('expressive-words', 'Expressive Words', 'medium', 'expressiveWords',
    sig(['s' => 'str', 'words' => 'str[]'], 'int'),
    'A group of 3+ equal chars in s is stretchy: a word with a shorter matching group stretches into it. Count words that stretch into s.',
    ['1 <= words.length <= 100'],
    [t(['heeellooo', ['hello','hi','helo']], 1, 1), t(['zzzzzyyyyy', ['zzyy','zy','zyy']], 3, 1), t(['aaaa', ['a','aa','aaa']], 3), t(['abcd', ['abc']], 0)],
    'function expressiveWords(s,words){function groups(w){var g=[];for(var i=0;i<w.length;){var j=i;while(j<w.length&&w[j]===w[i])j++;g.push([w[i],j-i]);i=j;}return g;}var gs=groups(s);var cnt=0;for(var w of words){var gw=groups(w);if(gw.length!==gs.length)continue;var ok=true;for(var k=0;k<gs.length;k++){if(gw[k][0]!==gs[k][0]){ok=false;break;}if(gw[k][1]>gs[k][1]||(gs[k][1]<3&&gw[k][1]!==gs[k][1])){ok=false;break;}}if(ok)cnt++;}return cnt;}'),

pdef('bag-of-tokens', 'Bag of Tokens', 'medium', 'bagOfTokensScore',
    sig(['tokens' => 'int[]', 'power' => 'int'], 'int'),
    'Face up: spend tokens[i] power for +1 score. Face down: gain tokens[i] power for -1 score. Play each token once; return the maximum score.',
    ['0 <= tokens.length <= 1000'],
    [t([[100], 50], 0, 1), t([[200,100], 150], 1, 1), t([[100,200,300,400], 200], 2), t([[100,200], 150], 1)],
    'function bagOfTokensScore(tokens,power){tokens.sort(function(a,b){return a-b;});var l=0,r=tokens.length-1,score=0,best=0;while(l<=r){if(power>=tokens[l]){power-=tokens[l++];score++;best=Math.max(best,score);}else if(score>0){power+=tokens[r--];score--;}else break;}return best;}'),

];
